import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

test('agent session UI keeps explicit local runtime thread recovery contracts', () => {
  const panelSource = readFileSync(resolve('src/components/layout/AIAgentPanel.tsx'), 'utf8')
  const builtinChatShellSource = readFileSync(resolve('src/components/agent/AgentBuiltinChatShell.tsx'), 'utf8')
  const chatViewSource = readFileSync(resolve('src/components/agent/AgentChatView.tsx'), 'utf8')
  const chatViewControllerSource = readFileSync(resolve('src/components/agent/useAgentChatViewController.ts'), 'utf8')
  const clientSource = readFileSync(resolve('src/lib/localAgentClient.ts'), 'utf8')
  const sessionStoreSource = readFileSync(resolve('src/store/agentSessionStore.ts'), 'utf8')
  const agentStoreSource = readFileSync(resolve('src/store/agentStore.ts'), 'utf8')
  const runtimeHydrationHookSource = readFileSync(resolve('src/components/agent/useAgentRuntimeThreadHydration.ts'), 'utf8')
  const conversationHydrationSource = readFileSync(resolve('src/lib/agentRuntimeThreadConversationHydration.ts'), 'utf8')
  const agentConversationSource = readFileSync(resolve('../../packages/conversation/src/index.ts'), 'utf8')
  const protocolSource = readFileSync(resolve('../../packages/protocol/src/index.ts'), 'utf8')
  const sendActivitySource = readFileSync(resolve('src/lib/agentSendActivity.ts'), 'utf8')
  const sendCompletionSource = readFileSync(resolve('src/lib/agentSendCompletion.ts'), 'utf8')
  const sendCommitSource = readFileSync(resolve('src/lib/agentSendCommit.ts'), 'utf8')
  const runtimeRestoreSource = readFileSync(resolve('src/lib/agentRuntimeThreadRestore.ts'), 'utf8')
  const builtinChatControllerSource = readFileSync(resolve('src/components/agent/useAgentBuiltinChatController.ts'), 'utf8')
  const interactionControllerSource = readFileSync(resolve('src/components/agent/useAgentChatInteractionController.ts'), 'utf8')
  const interactionInputsSource = readFileSync(resolve('src/components/agent/agentChatInteractionInputs.ts'), 'utf8')
  const actionInputsSource = readFileSync(resolve('src/components/agent/agentChatActionInputs.ts'), 'utf8')
  const sendPipelineInputsSource = readFileSync(resolve('src/components/agent/agentChatSendPipelineInputs.ts'), 'utf8')
  const sendPipelineSource = readFileSync(resolve('src/components/agent/useAgentChatSendPipeline.ts'), 'utf8')
  const commitSendHookSource = readFileSync(resolve('src/components/agent/useAgentCommitSendDraft.ts'), 'utf8')
  const conversationTabsSource = readFileSync(resolve('src/components/agent/AgentConversationTabs.tsx'), 'utf8')
  const conversationTabRuntimeLightsSource = readFileSync(resolve('src/components/agent/useAgentConversationTabRuntimeStatusLights.ts'), 'utf8')

  assert.doesNotMatch(clientSource, /getThreadOrCreate/)
  assert.match(clientSource, /RunMessageResult/)
  assert.match(protocolSource, /export interface RunMessageResult[\s\S]*threadResolution: AgentThreadResolution/)
  assert.match(clientSource, /if \(!isLocalAgentNotFoundError\(error\)\) throw error/)
  assert.match(clientSource, /runMessageStream[\s\S]*threadResolution: resolvedThread\.resolution/)

  assert.doesNotMatch(sessionStoreSource, /conversationIdForLocalThread/)
  assert.match(agentConversationSource, /export function conversationIdForRuntimeThread/)
  assert.match(agentStoreSource, /export type Conversation = AgentConversation/)
  assert.match(protocolSource, /runtimeThreadId\?: string/)
  assert.match(agentStoreSource, /setConversationRuntimeThreadId/)
  assert.match(agentConversationSource, /conversation\.runtimeThreadId === threadId/)
  assert.match(chatViewSource, /useAgentChatViewController\(props\)/)
  assert.match(chatViewControllerSource, /useAgentChatInteractionController\(buildAgentChatInteractionControllerInput\(\{/)
  assert.match(interactionControllerSource, /useAgentChatSendPipeline\(\{/)
  assert.match(interactionInputsSource, /actionBindings: buildAgentChatActionBindingsInput\(options\)/)
  assert.match(interactionInputsSource, /sendPipeline: buildAgentChatSendPipelineInput\(options\)/)
  assert.match(actionInputsSource, /runResultActions: \{/)
  assert.match(actionInputsSource, /messageStore: \{[\s\S]*upsertMessage: store\.messageStore\.upsertMessage/)
  assert.match(actionInputsSource, /workflowActions: \{/)
  assert.match(actionInputsSource, /planActions: \{/)
  assert.match(actionInputsSource, /stopAction: \{/)
  assert.match(sendPipelineInputsSource, /draftBuilder: \{/)
  assert.match(sendPipelineInputsSource, /commitDraft: \{/)
  assert.match(sendPipelineInputsSource, /runtimeThreadHydration: \{/)
  assert.match(sendPipelineInputsSource, /sendActions: \{/)
  assert.match(sendPipelineSource, /useAgentRuntimeThreadHydration\(runtimeThreadHydration\)/)
  assert.match(conversationTabsSource, /runtimeStatusLights/)
  assert.match(conversationTabsSource, /data-runtime-state/)
  assert.match(conversationTabRuntimeLightsSource, /localAgentClient\.getThreadRuntime/)
  assert.match(conversationTabRuntimeLightsSource, /localAgentClient\.streamThread/)
  assert.match(conversationTabRuntimeLightsSource, /localThreadIdsByConversation/)
  assert.match(runtimeHydrationHookSource, /hydratedRuntimeThreadKeysRef/)
  assert.match(conversationHydrationSource, /runtimeThreadHydrationKey\(input\.conversationId, threadId\)/)
  assert.match(runtimeHydrationHookSource, /const controller = new AbortController\(\)/)
  assert.match(runtimeHydrationHookSource, /signal: controller\.signal/)
  assert.match(runtimeHydrationHookSource, /controller\.abort\(\)/)
  assert.match(runtimeHydrationHookSource, /loadRuntimeThreadProjection\(\{[\s\S]*threadId/)
  assert.match(conversationHydrationSource, /deps\.messageStore\.setConversationMessages\([\s\S]*mergeRuntimeThreadProjectionMessages\(input\.existingMessages, projection\)/)
  assert.match(agentConversationSource, /markRuntimeMessagesRestored\(projection\.messages, deps\.restoredLabel\)/)
  assert.match(agentConversationSource, /deps\.messageStore\.upsertMessage/)
  assert.match(agentConversationSource, /conversationIdForRuntimeThread\(\{[\s\S]*localThreadIdsByConversation[\s\S]*conversationRuntimes/)
  assert.match(agentConversationSource, /deps\.setActiveConversation\(deps\.userId, existingConversationId\)[\s\S]*return/)
  assert.match(panelSource, /<AgentBuiltinChatShell/)
  assert.match(builtinChatShellSource, /useAgentBuiltinChatController\(\{/)
  assert.match(builtinChatShellSource, /<AgentChatView/)
  assert.match(builtinChatControllerSource, /restoreRuntimeThreadConversation\(threadId, \{/)
  assert.match(builtinChatControllerSource, /consumeQueuedPanelDrafts\(consumeAgentPanelDraft/)
  assert.match(builtinChatControllerSource, /activateConversationForPanelDraft\(detail, \{/)

  assert.match(sendActivitySource, /function threadResolutionActivityEvent/)
  assert.match(sendActivitySource, /本地线程不存在，已创建新线程/)
  assert.match(agentConversationSource, /completeRuntimeSendRunResult/)
  assert.match(agentConversationSource, /appendAssistantRunResult\(run, thread, liveEvents\)/)
  assert.match(agentConversationSource, /mergeRuntimeThreadProjectionMessages\(existingMessages, projection\)/)
  assert.match(sendCompletionSource, /completeRuntimeSendRunResult/)
  assert.match(sendCompletionSource, /threadResolutionActivityEvent/)
  assert.match(sendCompletionSource, /loadRuntimeThreadProjection: \(projectionInput\) => loadRuntimeThreadProjection/)
  assert.match(sendPipelineSource, /useAgentCommitSendDraft\(\{/)
  assert.match(sendPipelineInputsSource, /messageStore: \{/)
  assert.match(commitSendHookSource, /commitAgentSendDraft\(draft, \{/)
  assert.match(commitSendHookSource, /messageStore,/)
  assert.match(agentConversationSource, /interface AgentConversationMessageStore/)
  assert.match(conversationHydrationSource, /messageStore: Pick<AgentConversationMessageStore<ChatMessage, ChatMessageMeta>, 'setConversationMessages'>/)
  assert.match(sendCommitSource, /messageStore: AgentConversationMessageStore<ChatMessage, ChatMessageMeta>/)
  assert.match(sendCommitSource, /completeSendRunResult\(\{/)
})

test('agent session UI keeps worker trace drilldown contracts', () => {
  const planOverviewSource = readFileSync(resolve('src/components/agent/AgentPlanOverviewPanel.tsx'), 'utf8')

  assert.match(planOverviewSource, /const \[traceSummaries, setTraceSummaries\]/)
  assert.match(planOverviewSource, /const \[traceEventsByRunId, setTraceEventsByRunId\]/)
  assert.match(planOverviewSource, /localAgentClient\.getRunTraceSummary\(runId\)/)
  assert.match(planOverviewSource, /localAgentClient\.getRunTraceEvents\(runId, \{ limit: 8/)
  assert.match(planOverviewSource, /traceEventHasMoreByRunId/)
  assert.match(planOverviewSource, /traceEventKindFilters/)
  assert.match(planOverviewSource, /轨迹统计/)
  assert.match(planOverviewSource, /运行事件/)
  assert.match(planOverviewSource, /加载更多/)
})

test('agent session UI pins live task, plan, and subagent status at top of the thread', () => {
  const threadSectionSource = readFileSync(resolve('src/components/agent/AgentConversationThreadSection.tsx'), 'utf8')
  const layoutPropsSource = readFileSync(resolve('src/components/agent/agentChatViewLayoutProps.ts'), 'utf8')
  const conversationPresentationSource = readFileSync(resolve('src/lib/agentConversationPresentation.ts'), 'utf8')
  const pinnedStatusShelfSource = readFileSync(resolve('src/components/agent/AgentPinnedStatusShelf.tsx'), 'utf8')
  const derivedStateSource = readFileSync(resolve('src/components/agent/useAgentChatDerivedState.ts'), 'utf8')

  assert.match(threadSectionSource, /<AgentPinnedStatusShelf/)
  assert.match(layoutPropsSource, /generationProgressStates: presentation\.generationProgressStates/)
  assert.match(derivedStateSource, /generationProgressStatesForPinnedStatus/)
  assert.match(conversationPresentationSource, /showLiveRunActivity/)
  assert.doesNotMatch(conversationPresentationSource, /blocks\.push\(\.\.\.generationProgressStates/)
  assert.match(pinnedStatusShelfSource, /data-testid="agent-pinned-status-shelf"/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.tabs\.generation/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.tabs\.worker/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.workersCount/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.tabs\.plan/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.viewPlanDetails/)
  assert.match(pinnedStatusShelfSource, /const \[collapsed, setCollapsed\] = useState\(false\)/)
  assert.match(pinnedStatusShelfSource, /aria-expanded=\{!collapsed\}/)
  assert.match(pinnedStatusShelfSource, /aria-controls="agent-pinned-status-shelf-body"/)
  assert.match(pinnedStatusShelfSource, /event\.target !== event\.currentTarget/)
  assert.match(pinnedStatusShelfSource, /!collapsed && activeCount > 0/)
  assert.match(pinnedStatusShelfSource, /h-28 overflow-y-auto overscroll-contain/)
})

test('agent session UI routes pending input answers before starting a new run', () => {
  const chatViewSource = readFileSync(resolve('src/components/agent/AgentChatView.tsx'), 'utf8')
  const chatViewControllerSource = readFileSync(resolve('src/components/agent/useAgentChatViewController.ts'), 'utf8')
  const chatViewLayoutSource = readFileSync(resolve('src/components/agent/AgentChatViewLayout.tsx'), 'utf8')
  const interactionControllerSource = readFileSync(resolve('src/components/agent/useAgentChatInteractionController.ts'), 'utf8')
  const derivedStateSource = readFileSync(resolve('src/components/agent/useAgentChatDerivedState.ts'), 'utf8')
  const workflowStateSource = readFileSync(resolve('src/components/agent/useAgentChatWorkflowState.ts'), 'utf8')
  const composerSource = readFileSync(resolve('src/components/agent/AgentComposerSection.tsx'), 'utf8')
  const threadSectionSource = readFileSync(resolve('src/components/agent/AgentConversationThreadSection.tsx'), 'utf8')
  const threadItemsSource = readFileSync(resolve('src/lib/agentConversationThreadItems.ts'), 'utf8')
  const chatActionBindingsSource = readFileSync(resolve('src/components/agent/useAgentChatActionBindings.ts'), 'utf8')
  const sendActionsSource = readFileSync(resolve('src/components/agent/useAgentSendActions.ts'), 'utf8')
  const workflowBindingsSource = readFileSync(resolve('src/components/agent/useAgentWorkflowActionBindings.ts'), 'utf8')
  const workflowActionsSource = readFileSync(resolve('src/lib/agentWorkflowActions.ts'), 'utf8')
  const runPageSource = readFileSync(resolve('src/pages/agent/AIAgentRunPage.tsx'), 'utf8')

  assert.match(derivedStateSource, /useAgentChatWorkflowState\(\{/)
  assert.match(workflowStateSource, /const activePendingInputRequest = firstPendingInputRequest\(actionableLocalRun\)/)
  assert.match(workflowStateSource, /const answeringPendingInput = !!activePendingInputRequest/)
  assert.match(chatViewSource, /useAgentChatViewController\(props\)/)
  assert.match(chatViewControllerSource, /useAgentChatInteractionController\(buildAgentChatInteractionControllerInput\(\{/)
  assert.match(interactionControllerSource, /useAgentChatActionBindings\(actionBindings\)/)
  assert.match(chatActionBindingsSource, /useAgentWorkflowActionBindings\(\{/)
  assert.match(workflowBindingsSource, /answerWorkflowRunInputAction\(\{/)
  assert.match(workflowActionsSource, /sourceMessageId: localMessageId/)
  assert.match(workflowActionsSource, /answerRunInput\(run\.id, \{[\s\S]*requestId,[\s\S]*\.\.\.answer,[\s\S]*sourceMessageId/)
  assert.match(workflowActionsSource, /optimisticInputAnswerRun\(run, requestId, answer\)/)
  assert.match(workflowStateSource, /workflowAnswerEchoesForMessages\(messages, workflowRuns\)/)
  assert.match(chatViewSource, /<AgentChatViewLayout/)
  assert.match(chatViewLayoutSource, /<AgentConversationThreadSection/)
  assert.match(threadSectionSource, /buildAgentConversationThreadItems\(\{/)
  assert.match(threadSectionSource, /<LocalAgentWorkflowBubble/)
  assert.match(threadItemsSource, /isWorkflowAnswerEchoMessage\(message, workflowAnswerEchoes\)/)
  assert.match(threadItemsSource, /workflowRunFromActivity\(message\.meta\?\.localRunActivity\)/)
  assert.match(chatViewLayoutSource, /<AgentComposerSection/)
  assert.match(composerSource, /answeringPendingInput \? '回答' : debugBeforeSend/)
  assert.match(composerSource, /buildingSendDraft \|\| \(answeringPendingInput && !canAnswerPendingInputWithText\)/)
  assert.match(sendActionsSource, /answerActiveLocalRunInput\(activePendingInputRequest\.id, \{ text \}\)/)
  assert.match(sendActionsSource, /if \(canSendActiveRunRuntimeInput\)/)
  assert.match(sendActionsSource, /sendActiveRunRuntimeInput\(\{ content, attachments \}\)/)

  const pendingBranch = sendActionsSource.indexOf('if (answeringPendingInput && activePendingInputRequest)')
  const runtimeInputPath = sendActionsSource.indexOf('if (canSendActiveRunRuntimeInput)')
  const newRunPath = sendActionsSource.indexOf('const draft = await buildSendDraft')
  assert.ok(pendingBranch > 0, 'pending input answer branch must exist in send()')
  assert.ok(newRunPath > pendingBranch, 'pending input must be handled before building a new send draft')
  assert.ok(runtimeInputPath > pendingBranch, 'active run runtime input branch must run after pending input answers')
  assert.ok(newRunPath > runtimeInputPath, 'active run messages must be routed as runtime input before building a new send draft')

  assert.match(runPageSource, /import \{ LocalAgentInputRequestCard \}/)
  assert.match(runPageSource, /<LocalAgentInputRequestCard/)
  assert.doesNotMatch(runPageSource, /inputDrafts/)
})

test('agent session UI renders generation job approvals as summary cards', () => {
  const workflowBubbleSource = readFileSync(resolve('src/components/agent/AgentWorkflowBubble.tsx'), 'utf8')

  assert.match(workflowBubbleSource, /GenerationJobApprovalDetails/)
  assert.match(workflowBubbleSource, /generationJobApprovalView\(approval\)/)
  assert.match(workflowBubbleSource, /approval\.toolName === 'core_work_start' && kind === 'generation_job'/)
  assert.match(workflowBubbleSource, /approval\.toolName !== 'generation_job_create'/)
  assert.match(workflowBubbleSource, /view\.targetLabel/)
  assert.match(workflowBubbleSource, /view\.prompt/)
  assert.match(workflowBubbleSource, /referenceResourceIds/)
  assert.match(workflowBubbleSource, /ApprovalResourceThumbnail resourceId=\{previewResourceId\}/)
  assert.match(workflowBubbleSource, /resourceFileUrl\(resourceId\)/)
  assert.match(workflowBubbleSource, /safeJSONStringify\(approval\.args\)/)
})

test('agent session UI renders asset slot candidate approvals as summary cards', () => {
  const workflowBubbleSource = readFileSync(resolve('src/components/agent/AgentWorkflowBubble.tsx'), 'utf8')

  assert.match(workflowBubbleSource, /AssetSlotCandidateApprovalDetails/)
  assert.match(workflowBubbleSource, /assetSlotCandidateApprovalView\(approval\)/)
  assert.match(workflowBubbleSource, /approval\.toolName !== 'candidate_asset_slot_attach'/)
  assert.match(workflowBubbleSource, /素材槽 #/)
  assert.match(workflowBubbleSource, /只加入候选集，不会锁定、采纳或替换当前素材。/)
  assert.match(workflowBubbleSource, /output_resource_id/)
  assert.match(workflowBubbleSource, /resource_id/)
  assert.match(workflowBubbleSource, /AuthedImage/)
})

test('agent panel keeps recent resources as mention candidates, not automatic context labels', () => {
  const chatViewSource = readFileSync(resolve('src/components/agent/AgentChatView.tsx'), 'utf8')
  const composerStateSource = readFileSync(resolve('src/components/agent/useAgentChatComposerState.ts'), 'utf8')
  const composerControllerSource = readFileSync(resolve('src/components/agent/useAgentComposerController.ts'), 'utf8')
  const sendDraftSource = readFileSync(resolve('src/lib/agentSendDraft.ts'), 'utf8')

  assert.doesNotMatch(chatViewSource, /recentResourcesCount/)
  assert.doesNotMatch(composerStateSource, /recentResourcesCount/)
  assert.match(composerStateSource, /recentResources,\s*fileRef,\s*inputRef/)
  assert.match(composerControllerSource, /for \(const resource of recentResources\)[\s\S]*attachmentFromResource\(resource\)/)
  assert.match(composerControllerSource, /input\.matchAll\(RESOURCE_MENTION_RE\)/)
  assert.match(sendDraftSource, /recentResources: \[\]/)
})

test('agent panel no longer renders the context card surface', () => {
  const chatViewSource = readFileSync(resolve('src/components/agent/AgentChatView.tsx'), 'utf8')
  const chatViewControllerSource = readFileSync(resolve('src/components/agent/useAgentChatViewController.ts'), 'utf8')
  const chatViewLayoutSource = readFileSync(resolve('src/components/agent/AgentChatViewLayout.tsx'), 'utf8')
  const contextStateSource = readFileSync(resolve('src/components/agent/useAgentChatContextState.ts'), 'utf8')

  assert.match(chatViewSource, /useAgentChatViewController\(props\)/)
  assert.match(chatViewControllerSource, /useAgentChatContextState\(\{/)
  assert.match(contextStateSource, /useAgentContextSummary\(\{/)
  assert.match(chatViewSource, /<AgentChatViewLayout/)
  assert.doesNotMatch(chatViewLayoutSource, /AgentContextSection/)
  assert.doesNotMatch(chatViewLayoutSource, /context:/)
  assert.doesNotMatch(contextStateSource, /useAgentContextPaneController/)
})
