import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('content workbench keeps stable production workspace hooks', () => {
  const source = readFileSync(resolve('src/pages/workbench/WorkbenchPage.tsx'), 'utf8')
  const contentWorkbenchSource = source.slice(source.indexOf('function ContentGenerationWorkbench'))

  assert.match(source, /data-testid="content-workbench-command-center"/)
  assert.match(source, /data-testid="content-workbench-command-brief"/)
  assert.match(contentWorkbenchSource, /flex flex-wrap items-stretch overflow-hidden rounded-md border border-border bg-background" data-testid="content-workbench-command-brief"/)
  assert.doesNotMatch(contentWorkbenchSource, /grid gap-1\.5 md:grid-cols-4" data-testid="content-workbench-command-brief"/)
  assert.match(source, /buildContentWorkbenchPipeline/)
  assert.match(source, /data-testid="content-workbench-production-pipeline"/)
  assert.match(contentWorkbenchSource, /production-workbench space-y-3/)
  assert.match(source, /w-\[126px\] rounded-md border px-2\.5 py-2/)
  assert.doesNotMatch(contentWorkbenchSource, /情节生产队列|min-w-\[240px\]|w-\[150px\] rounded-md border px-3 py-2/)
  assert.match(source, /selectedPreviewItemCount/)
  assert.match(source, /selectedDeliveryVersionCount/)
  assert.match(source, /preview_delivery: Film/)
  assert.match(source, /searchParams\.get\('scene_moment_id'\)/)
  assert.match(source, /searchParams\.get\('content_unit_id'\)/)
  assert.match(source, /searchParams\.get\('productionId'\)/)
  assert.match(source, /setProductionFilter\(target\)/)
  assert.match(source, /function selectProductionFilter/)
  assert.match(source, /next\.set\('productionId', value\)/)
  assert.match(source, /next\.delete\('scene_moment_id'\)/)
  assert.match(source, /next\.delete\('content_unit_id'\)/)
  assert.match(source, /onValueChange=\{selectProductionFilter\}/)
  assert.match(source, /function selectSegmentFilter/)
  assert.match(source, /onValueChange=\{selectSegmentFilter\}/)
  assert.match(source, /function selectSceneMoment/)
  assert.match(source, /next\.set\('scene_moment_id'/)
  assert.match(source, /function selectContentUnit/)
  assert.match(source, /next\.set\('content_unit_id'/)
  assert.match(source, /pickContentWorkbenchUploadTarget/)
  assert.match(source, /pickContentWorkbenchFirstUsableUnit/)
  assert.match(source, /pickContentWorkbenchFocusAfterIgnoredCandidate/)
  assert.match(source, /setCandidateUploadTargetSlot\(uploadTargetSlot\)/)
  assert.match(source, /if \(!file\) \{\s+setCandidateUploadTargetSlot\(null\)/)
  assert.match(source, /uploadCandidate\.mutate\(\{ file, slot \}\)/)
  assert.match(source, /if \(variables\.next === 'confirmed'\) \{\s+selectContentUnit\(variables\.unitId\)/)
  assert.match(source, /else if \(selectedUnit\?\.ID === variables\.unitId\)/)
  assert.match(source, /buildContentWorkbenchCommandBrief/)
  assert.match(source, /commandBriefIcons/)
  assert.doesNotMatch(source, /commandStageRows/)
  assert.match(source, /筛选与定位/)
  assert.match(contentWorkbenchSource, /<div className="space-y-2">\s+<div className="flex items-center gap-2 text-xs font-medium text-muted-foreground">\s+<Settings2 size=\{14\} \/>/)
  assert.doesNotMatch(contentWorkbenchSource, /<div className="rounded-md border border-border bg-background p-3">\s+<div className="flex items-center gap-2 text-xs font-medium text-muted-foreground">\s+<Settings2 size=\{14\} \/>/)
  assert.doesNotMatch(contentWorkbenchSource, /SelectTrigger className="mt-[23] h-9"/)
  assert.doesNotMatch(source, /入口、筛选与动作/)
  assert.doesNotMatch(contentWorkbenchSource, /当前写入目标/)
  assert.doesNotMatch(source, /onClick=\{openAiSuggest\}/)
  assert.doesNotMatch(source, /onClick=\{\(\) => setCreatingUnit\(true\)\}/)
  assert.doesNotMatch(source, /onClick=\{openSelectedUnitCanvas\}/)
  assert.doesNotMatch(source, /const onClick = item\.actionKey \? nextActionHandlers/)
  assert.doesNotMatch(source, /key=\{item\.key\}\s+type="button"/)
  assert.match(source, /data-testid="content-workbench-production-grid"/)
  assert.doesNotMatch(source, /title="制作项列表"/)
  assert.doesNotMatch(contentWorkbenchSource, /<p className="text-xs text-muted-foreground">当前情节<\/p>/)
  assert.doesNotMatch(contentWorkbenchSource, /准备度 \{selected\.progress\}%/)
  assert.match(source, /data-testid="content-workbench-next-actions"/)
  assert.match(source, /function NextActionsPanel/)
  assert.match(source, /const primaryAction = actions\[0\]/)
  assert.match(source, /const secondaryActions = actions\.slice\(1\)/)
  assert.match(source, /data-testid="content-workbench-secondary-actions"/)
  assert.doesNotMatch(source, /nextActions\.map\(\(action, index\)/)
  assert.match(source, /data-testid="content-workbench-review-queue"/)
  assert.match(source, /data-testid="content-workbench-readiness-summary"/)
  assert.match(source, /data-testid="content-workbench-delivery-brief"/)
  assert.match(source, /mt-2 flex flex-wrap overflow-hidden rounded-md border border-border bg-card/)
  assert.doesNotMatch(source, /mt-2 grid grid-cols-2 gap-1\.5 sm:grid-cols-4/)
  assert.match(source, /<DeliveryBriefCard brief=\{deliveryBrief\} \/>/)
  assert.doesNotMatch(source, /deliveryPrimaryAction/)
  assert.doesNotMatch(source, /DeliveryBriefCard\(\{\s+brief,\s+primaryActionLabel/)
  assert.doesNotMatch(source, /primaryActionLabel=\{deliveryPrimaryAction/)
  assert.match(source, /data-testid="content-workbench-generation-context-detail"/)
  assert.match(source, /data-testid="content-workbench-gate-detail"/)
  assert.match(source, /<WorkbenchPanel[\s\S]{0,120}title="生成检查"/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="上下文 Inspector"/)
  assert.match(source, /<span className="truncate">当前上下文<\/span>/)
  assert.doesNotMatch(source, /<WorkbenchPanel[\s\S]{0,120}title="生成门禁"/)
  assert.doesNotMatch(source, /<WorkbenchPanel[\s\S]{0,120}title="当前制作项"/)
  assert.match(source, /<WorkbenchPanel title="执行与交付" icon=\{PackageCheck\}>/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="生成上下文详情"/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="生成交付包"/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="生产活动流"/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="素材与生成上下文"/)
  assert.doesNotMatch(source, /素材候选上传|上传素材候选|CandidateComparison|production-candidate-row/)
  assert.match(source, /data-testid="content-workbench-activity-feed"/)
  assert.match(source, /data-testid="content-workbench-activity-overflow"/)
  assert.match(source, /const primaryItems = feed\.items\.slice\(0, 1\)/)
  assert.match(source, /const secondaryItems = feed\.items\.slice\(1\)/)
  assert.match(source, /<ActivityFeedCard feed=\{activityFeed\} \/>/)
  assert.doesNotMatch(source, /ActivityFeedCard feed=\{activityFeed\} actionIcons/)
  assert.doesNotMatch(source, /item\.actionLabel \?\? '处理'/)
  assert.match(source, /data-testid="content-workbench-unit-track"/)
  assert.match(source, /data-testid="content-workbench-candidate-queue"/)
  assert.match(source, /action=\{unitCandidates\.length > 0 \? <Badge variant="secondary">\{unitCandidates\.length\} 条待确认<\/Badge> : undefined\}/)
  assert.doesNotMatch(source, /variant=\{unitCandidates\.length > 0 \? 'secondary' : 'outline'\}/)
  assert.match(source, /overflow-hidden rounded-md border border-border bg-card">\s+\{unitCandidates\.map/)
  assert.doesNotMatch(source, /unitCandidates\.map[\s\S]{0,220}rounded-md border border-border bg-card p-3/)
  assert.doesNotMatch(source, /当前情节没有待确认的候选制作项/)
  assert.doesNotMatch(source, /选择情节后查看候选制作项/)
  assert.match(source, /data-testid="content-workbench-keyframe-continuity"/)
  assert.match(source, /const showMomentKeyframeContinuity = selectedKeyframeSequence\.length > 0/)
  assert.match(source, /showMomentKeyframeContinuity \? \(\s+<KeyframeContinuityStrip[\s\S]{0,120}sequence=\{selectedKeyframeSequence\}/)
  assert.doesNotMatch(source, /<KeyframeContinuityStrip[\s\S]{0,160}onCreateKeyframe/)
  assert.doesNotMatch(source, /连续关键帧总览/)
  assert.doesNotMatch(source, /给当前制作项补开头帧、结尾帧后，这里会形成一条可扫读的连续性检查带。/)
  assert.match(source, /w-\[168px\] shrink-0 overflow-hidden rounded-md border border-border bg-card/)
  assert.match(source, /aria-label="上传关键帧图片"/)
  assert.match(source, /aria-label="从资源库选择关键帧素材"/)
  assert.match(source, /data-testid="content-workbench-current-unit-panel"/)
  assert.match(source, /buildContentWorkbenchUnitHealth/)
  assert.match(source, /data-testid="content-workbench-unit-health"/)
  assert.match(source, /flex items-center justify-between gap-2 rounded-md border px-2\.5 py-1\.5/)
  assert.doesNotMatch(source, /UnitHealthCard[\s\S]{0,1800}<Progress value=\{health\.score\}/)
  assert.doesNotMatch(source, /visibleChecks/)
  assert.match(source, /data-action-key=\{action\.key\}/)
  assert.match(source, /buildContentWorkbenchNextActions/)
  assert.match(source, /function selectFirstSceneMoment/)
  assert.match(source, /function selectFirstContentUnit/)
  assert.match(source, /select_scene_moment: selectFirstSceneMoment/)
  assert.match(source, /select_unit: selectFirstContentUnit/)
  assert.match(source, /open_preview_workspace: Film/)
  assert.match(source, /open_delivery_workspace: PackageCheck/)
  assert.match(source, /open_preview_workspace: \(\) => navigate\(withRouteParams\(ROUTES\.project\.contentUnitWorkbench/)
  assert.match(source, /data-testid="content-workbench-preview-mount"/)
  assert.match(source, /const firstGap = gaps\[0\]/)
  assert.match(source, /优先缺口：\{firstGap\.name\}/)
  assert.doesNotMatch(source, /gaps\.slice\(0, 2\)\.map/)
  assert.doesNotMatch(source, /onOpenAssets=\{/)
  assert.doesNotMatch(source, /onOpenDelivery=\{/)
  assert.doesNotMatch(source, /function ProductionPreviewWorkspace/)
  assert.doesNotMatch(source, /loadProductionPreviewData/)
  assert.match(source, /open_delivery_workspace: \(\) => navigate\(withRouteParams\(ROUTES\.project\.deliveryWorkbench/)
  assert.match(source, /buildContentWorkbenchReadinessSummary/)
  assert.match(source, /buildContentWorkbenchReviewQueueSummary/)
  assert.match(source, /buildContentWorkbenchDeliveryBrief/)
  assert.match(source, /completedJobCount: selectedUnitCompletedJobCount,\s+previewItemCount: selectedPreviewItemCount,\s+deliveryVersionCount: selectedDeliveryVersionCount/)
  assert.match(source, /const selectedUnitRunningJobCount = selectedUnitJobs\.filter/)
  assert.match(source, /const selectedUnitCompletedJobCount = selectedUnitJobs\.filter/)
  assert.match(source, /completedJobCount: selectedUnitCompletedJobCount/)
  assert.match(source, /buildContentWorkbenchActivityFeed/)
  assert.match(source, /pickContentWorkbenchRelevantJobs/)
  assert.match(source, /jobs: selectedUnitJobs\.map/)
  assert.match(source, /buildContentWorkbenchRouteSearch\(\{ sceneMomentId: selected\.moment\.ID \}\)/)
  assert.match(source, /pickContentWorkbenchRowIdForDeepLink/)
  assert.match(source, /contentUnitId: linkedContentUnitId/)
  assert.match(source, /linkedSceneMomentId > 0 \|\| linkedContentUnitId <= 0/)
  assert.match(source, /next\.set\('scene_moment_id', String\(selected\.moment\.ID\)\)/)
  assert.match(source, /buildContentWorkbenchUnitTrack/)
  assert.match(source, /buildContentWorkbenchAiSuggestPrompt/)
  assert.match(source, /sceneMomentId: selected\.moment\.ID/)
  assert.match(source, /findContentWorkbenchCanvas/)
  assert.match(source, /buildContentWorkbenchCanvasPayload/)
  assert.match(source, /打开生成画布失败/)
  assert.match(source, /function openSelectedUnitCanvas/)
  assert.match(source, /if \(openUnitCanvas\.isPending\) return/)
  assert.match(source, /AI 审稿队列/)
  assert.match(source, /function appendReviewGate/)
  assert.match(source, /label: 'AI 草案已处理'/)
  assert.match(source, /appendReviewGate\(baseStandards, reviewQueueSummary\.pending\)/)
  assert.match(source, /reviewPanelCollapsed/)
  assert.match(source, /const showReviewPanel = reviewMode \|\| reviewDraftsQuery\.isLoading \|\| \(reviewDrafts\.length > 0 && !reviewPanelCollapsed\)/)
  assert.match(source, /setReviewPanelCollapsed\(false\)/)
  assert.match(source, /setReviewPanelCollapsed\(true\)/)
  assert.match(source, /complete_unit_prompt: \(\) => openEditSelectedUnit\(\)/)
  assert.match(source, /resolve_generation_context: \(\) => openEditSelectedUnit\(\)/)
  assert.match(source, /<Dialog open=\{editingUnit\}/)
  assert.match(source, /rounded-md border border-border bg-card/)
  assert.match(source, /flex flex-wrap items-center justify-between gap-2 border-b/)
  assert.match(source, /cn\('p-2\.5', bodyClassName\)/)
  assert.match(source, /overflow-hidden rounded-md border border-border bg-background/)
  assert.match(source, /grid grid-cols-\[104px_minmax\(0,1fr\)\]/)
  assert.doesNotMatch(source, /function ContextStack[\s\S]{0,300}grid gap-3 md:grid-cols-2/)
  assert.match(source, /grid w-full grid-cols-2 gap-2 sm:w-auto sm:grid-cols-4/)
  assert.match(source, /localAgentClient\.rejectDraft/)
  assert.match(source, /退回草案/)
  assert.match(source, /data-testid="content-workbench-mark-draft-reviewed"/)
  assert.match(source, /reviewDisposition: 'manual_review_completed'/)
  assert.match(source, /backendWritePerformed: false/)
  assert.match(source, /contentWorkbenchProposalDefaults/)
  assert.match(source, /contentWorkbenchProposalSnapshot/)
  assert.match(source, /onSaved=\{\(record\) => \{\s+selectContentUnit\(record\.ID\)/)
  assert.match(source, /setOptimisticSelectedUnit\(record\)/)
  assert.match(source, /带入新建制作项/)
  assert.match(source, /\.\.\.unitDraftDefaults,\s+segment_id: selected\.segment\?\.ID \?\? null,\s+scene_moment_id: selected\.moment\.ID/)
  assert.match(source, /data-testid="content-workbench-create-proposal-unit"/)
  assert.match(source, /onCreateUnitFromProposal=\{openCreateUnitFromProposal\}/)
  assert.match(source, /currentUnitId: current\?\.ID/)
  assert.match(source, /编辑当前制作项/)
  assert.match(source, /data-testid="content-workbench-edit-current-unit"/)
  assert.match(source, /onEditCurrentUnit=\{openEditSelectedUnit\}/)
  assert.doesNotMatch(source, /内容单元|当前单元|草案单元|该单元/)
})

test('content workbench is the only exposed preview orchestration entry', () => {
  const appSource = readFileSync(resolve('src/App.tsx'), 'utf8')
  const routeSource = readFileSync(resolve('src/routes/projectRoutes.ts'), 'utf8')
  const sidebarSource = readFileSync(resolve('src/components/layout/Sidebar.tsx'), 'utf8')
  const headerSource = readFileSync(resolve('src/components/layout/Header.tsx'), 'utf8')
  const surfacesSource = readFileSync(resolve('src/pages/project/projectSurfaces.tsx'), 'utf8')
  const workbenchSource = readFileSync(resolve('src/pages/workbench/WorkbenchPage.tsx'), 'utf8')
  const zhSource = readFileSync(resolve('src/i18n/locales/zh-CN.json'), 'utf8')
  const enSource = readFileSync(resolve('src/i18n/locales/en-US.json'), 'utf8')
  const projectRoutesBlock = routeSource.match(/project: \{[\s\S]*?\n  \},/)?.[0] ?? ''

  assert.doesNotMatch(projectRoutesBlock, /productionPreview/)
  assert.match(routeSource, /LEGACY_ROUTES[\s\S]*productionPreview: '\/project\/production\/preview'/)
  assert.match(appSource, /path=\{LEGACY_ROUTES\.productionPreview\} element=\{<ProjectGuard><LegacyProductionPreviewRedirect \/><\/ProjectGuard>\}/)
  assert.doesNotMatch(appSource, /path=\{ROUTES\.project\.productionPreview\}/)
  assert.doesNotMatch(sidebarSource, /workbenchProductionPreview|ROUTES\.project\.productionPreview/)
  assert.doesNotMatch(headerSource, /ROUTES\.project\.productionPreview/)
  assert.doesNotMatch(surfacesSource, /\| 'preview'|value: 'preview'|制作预演/)
  assert.doesNotMatch(workbenchSource, /preview: \{|category === 'preview'|initialCategory === 'preview'|function ProductionPreviewWorkspace|loadProductionPreviewData/)
  assert.doesNotMatch(zhSource, /workbenchProductionPreview|制作预演/)
  assert.doesNotMatch(enSource, /workbenchProductionPreview|Production Preview/)
})
