import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('content workbench keeps the simplified scene-first workspace hooks', () => {
  const source = readFileSync(resolve('src/pages/workbench/WorkbenchPage.tsx'), 'utf8')
  const e2eSource = readFileSync(resolve('src/e2e/content-workbench.spec.ts'), 'utf8')
  const trackSource = readFileSync(resolve('src/lib/contentWorkbenchUnitTrack.ts'), 'utf8')
  const contentWorkbenchSource = source.slice(source.indexOf('function ContentGenerationWorkbench'))

  assert.match(source, /data-testid="content-workbench-command-center"/)
  assert.match(contentWorkbenchSource, /title="内容编排工作台"/)
  assert.match(contentWorkbenchSource, /编排视图/)
  assert.match(source, /data-testid="content-workbench-filter-sidebar"/)
  assert.match(source, /data-testid="content-workbench-sidebar-collapse"/)
  assert.match(contentWorkbenchSource, /const \[sidebarCollapsed, setSidebarCollapsed\] = useState\(false\)/)
  assert.match(contentWorkbenchSource, /sidebarCollapsed \? 'xl:grid-cols-\[64px_minmax\(0,1fr\)\]' : 'xl:grid-cols-\[280px_minmax\(0,1fr\)\]'/)
  assert.match(contentWorkbenchSource, /collapsed=\{sidebarCollapsed\}/)
  assert.match(contentWorkbenchSource, /onToggleCollapsed=\{\(\) => setSidebarCollapsed\(\(value\) => !value\)\}/)
  assert.match(source, /data-sidebar-rail-card=\{rail \? 'true' : undefined\}/)
  assert.match(source, /data-testid=\{rail \? 'content-workbench-scene-rail' : undefined\}/)
  assert.match(source, /rail=\{collapsed\}/)
  assert.match(source, /flex min-h-0 min-w-0 flex-1 flex-col rounded-md border border-border bg-background p-2/)
  assert.match(source, /min-h-0 flex-1 space-y-1 overflow-auto/)
  assert.match(source, /flex min-h-0 flex-1 flex-col gap-2 overflow-hidden/)
  assert.doesNotMatch(source, /max-h-56 space-y-1 overflow-auto/)
  assert.match(source, /testId="content-workbench-scene-moment-filter"/)
  assert.match(source, /data-testid="content-workbench-select-scene-empty"/)
  assert.match(source, /请先选择情节/)

  assert.match(source, /data-testid="content-workbench-scene-preview"/)
  assert.match(e2eSource, /content-workbench-scene-preview/)
  assert.doesNotMatch(source, /onEditUnit/)
  assert.doesNotMatch(source, /编辑\s+<\/Button>[\s\S]{0,160}生成画布\s+<\/Button>/)
  assert.doesNotMatch(source, /ContentWorkbenchShotInputFlow/)
  assert.doesNotMatch(source, /data-testid="content-workbench-shot-inputs"/)
  assert.doesNotMatch(source, /选中制作项生成输入/)

  assert.match(source, /data-testid="content-workbench-unit-track"/)
  assert.match(trackSource, /title: '内容单元'/)
  assert.doesNotMatch(trackSource, /制作轨道待确认|制作轨道存在阻塞/)
  assert.match(source, /data-testid="content-workbench-unit-kind-filter"/)
  assert.match(source, /const \[unitKindFilter, setUnitKindFilter\] = useState\('all'\)/)
  assert.match(source, /const visibleSummary = \{/)
  assert.match(source, /data-testid="content-workbench-create-unit-from-track"/)
  assert.match(source, />\s+新建\s+<\/Button>/)

  assert.match(source, /const timelineMemberItems = summary\.items/)
  assert.match(source, /const timelineKinds = Array\.from\(new Set\(summary\.items\.map/)
  assert.match(source, /visibleSummary\.items\.map\(\(item, index\)/)
  assert.match(source, /<div className="overflow-x-auto">\s+<div style=\{\{ minWidth: timelineCanvasWidth \}\}>/)
  assert.doesNotMatch(source, /<div className="mt-2\.5 overflow-x-auto pb-1">[\s\S]{0,120}content-workbench-unit-card/)
  assert.doesNotMatch(source, /grid-cols-\[64px_96px_104px_minmax\(220px,1fr\)_180px_160px_104px\]/)
  assert.match(source, /data-testid="content-workbench-unit-timeline"/)
  assert.match(source, /data-testid="content-workbench-timeline-lane"/)
  assert.match(source, /data-testid="content-workbench-schedule-panel-switcher"/)
  assert.match(source, /useState<'timeline' \| 'edit'>\('timeline'\)/)
  assert.match(source, /制作项时间轴/)
  assert.match(source, /内容编辑/)
  assert.match(source, /showInlineEditor=\{false\}/)
  assert.match(source, /data-testid="content-workbench-unit-inspector"/)
  assert.match(source, /function ContentWorkbenchUnitInspector/)
  assert.match(source, /compact\s+onSelectUnit=\{onSelectUnit\}/)
  assert.match(source, /selectedUnit && showInlineEditor \? \(\s+<button[\s\S]{0,500}内容编辑/)
  assert.match(source, /function selectOrClearUnit\(unitId: number\)/)
  assert.match(source, /if \(selectedUnitId === unitId\) \{\s+onSelectUnit\(null\)\s+return\s+\}\s+onSelectUnit\(unitId\)/)
  assert.doesNotMatch(source, /fallbackSelectedUnit/)
  assert.match(source, /data-testid="content-workbench-shot-list"/)
  assert.match(source, /data-testid="content-workbench-shot-list-row"/)
  assert.match(source, /schedulePanel === 'timeline' \|\| !showInlineEditor \? \(<>/)
  assert.match(source, /data-testid="content-workbench-unit-edit-cards"/)
  assert.match(source, /data-testid="content-workbench-edit-summary-card"/)
  assert.match(source, /data-testid="content-workbench-edit-goal-card"/)
  assert.match(source, /data-testid="content-workbench-edit-inputs-card"/)
  assert.match(source, /data-testid="content-workbench-generation-input-cards"/)
  assert.match(source, /type ContentUnitInputDrawerTab = 'generation' \| 'keyframes' \| 'storyboard' \| 'blocking'/)
  assert.match(source, /testId="content-workbench-blocking-input-card"/)
  assert.match(source, /testId="content-workbench-storyboard-input-card"/)
  assert.match(source, /data-testid="content-workbench-visual-plan-editor"/)
  assert.match(source, /data-testid="content-workbench-visual-plan-space"/)
  assert.match(source, /data-testid="content-workbench-visual-plan-blocking"/)
  assert.match(source, /data-testid="content-workbench-visual-plan-camera-path"/)
  assert.match(source, /data-testid="content-workbench-storyboard-brief-editor"/)
  assert.match(source, /data-testid="content-workbench-storyboard-purpose"/)
  assert.match(source, /data-testid="content-workbench-storyboard-composition"/)
  assert.match(source, /testId="content-workbench-keyframe-input-card"/)
  assert.match(source, /testId="content-workbench-asset-input-card"/)
  assert.match(source, /testId="content-workbench-canvas-input-card"/)
  assert.match(source, /data-testid="content-workbench-input-drawer"/)
  assert.match(source, /data-testid=\{`content-workbench-input-drawer-tab-\$\{tab\.key\}`\}/)
  assert.match(source, /data-testid=\{`content-workbench-input-drawer-panel-\$\{activeInputDrawer\}`\}/)
  assert.match(source, /data-testid="content-workbench-keyframe-editor"/)
  assert.match(source, /data-testid="content-workbench-keyframe-list"/)
  assert.match(source, /data-testid="content-workbench-keyframe-save"/)
  assert.match(source, /data-testid="content-workbench-keyframe-delete"/)
  assert.match(source, /data-testid="content-workbench-keyframe-generate-one"/)
  assert.match(source, /data-testid="content-workbench-keyframe-generate-missing"/)
  assert.match(source, /function CreateKeyframeQuickCard/)
  assert.match(source, /data-testid="content-workbench-create-keyframe-card"/)
  assert.match(source, /data-testid="content-workbench-create-keyframe-role"/)
  assert.match(source, /标题（可选）/)
  assert.match(source, /frame_role: frameRole/)
  assert.match(source, /feature_key: 'ref_image_gen'/)
  assert.match(source, /source: 'content_workbench_keyframe'/)
  assert.match(source, /setActiveInputDrawer\('generation'\)/)
  assert.match(source, /setActiveInputDrawer\('keyframes'\)/)
  assert.match(source, /setActiveInputDrawer\('storyboard'\)/)
  assert.match(source, /setActiveInputDrawer\('blocking'\)/)
  assert.match(source, /metadata_json: JSON\.stringify\(mergeMetadataJSON\(draft\.metadata_json, \{\s+visual_plan: visualPlan,\s+storyboard_brief: storyboardBrief,/)
  assert.match(source, /visualPlan: contentUnitVisualPlanPromptText\(unit\)/)
  assert.match(source, /storyboardBrief: contentUnitStoryboardBriefPromptText\(unit\)/)
  assert.match(source, /description: contentUnitGenerationCanvasDescription\(unit\)/)
  assert.match(source, /当前制作项视觉调度/)
  assert.match(source, /当前制作项故事板简述/)
  assert.match(source, /deleteSemanticEntity\(projectId, contentUnitConfig, unit\.ID\)/)
  assert.match(source, /data-testid="content-workbench-unit-edit-delete"/)
  assert.match(source, /onDeleteUnit=\{\(unit\) =>/)
  assert.match(source, /data-testid="content-workbench-unit-edit-save"/)
  assert.match(source, /function ContentUnitEditCards/)
  assert.match(source, /function ContentUnitGenerationInputCard/)
  assert.doesNotMatch(source, /data-testid="content-workbench-schedule-blank-panel"/)
  assert.doesNotMatch(source, /data-testid="content-workbench-schedule-row"/)

  assert.match(source, /data-testid="content-workbench-unit-inspector"/)
  assert.doesNotMatch(contentWorkbenchSource, /title="详情卡片"/)
  assert.doesNotMatch(source, /data-testid="content-workbench-candidate-queue"/)
  assert.doesNotMatch(source, /待确认候选/)
  assert.doesNotMatch(source, /data-testid="content-workbench-keyframe-track"/)
  assert.doesNotMatch(source, /画面锚点轨道/)
  assert.doesNotMatch(source, /data-testid="content-workbench-production-compressed-timeline"/)
  assert.doesNotMatch(source, /合并为一条|按情绪段拆分|按情节拆分/)
})

test('content workbench excludes AI keyframe candidates from official keyframe readiness', () => {
  const workbenchSource = readFileSync(resolve('src/pages/workbench/WorkbenchPage.tsx'), 'utf8')
  const contentUnitsSource = readFileSync(resolve('src/pages/project/content-units/ContentUnitsPage.tsx'), 'utf8')
  const segmentsSource = readFileSync(resolve('src/pages/segments/SegmentsPage.tsx'), 'utf8')
  const sceneMomentsSource = readFileSync(resolve('src/pages/scene-moments/SceneMomentsPage.tsx'), 'utf8')
  const overviewSource = readFileSync(resolve('src/pages/project/overview/ProjectOverviewPage.tsx'), 'utf8')
  const productionSource = readFileSync(resolve('src/pages/project/production/ProductionPage.tsx'), 'utf8')

  assert.match(workbenchSource, /isGeneratedKeyframeCandidateRecord/)
  assert.doesNotMatch(workbenchSource, /generatedKeyframeCandidateTargetId/)
  assert.doesNotMatch(workbenchSource, /isUnresolvedCandidateStatus/)
  assert.match(contentUnitsSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(segmentsSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(sceneMomentsSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(overviewSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(productionSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(contentUnitsSource, /\(keyframesQuery\.data \?\? \[\]\)\.filter\(\(item\) => !isGeneratedKeyframeCandidateRecord\(item\)\)/)
  assert.match(segmentsSource, /\(keyframesQuery\.data \?\? \[\]\)\.filter\(\(item\) => !isGeneratedKeyframeCandidateRecord\(item\)\)/)
  assert.match(sceneMomentsSource, /\(keyframesQuery\.data \?\? \[\]\)\.filter\(\(item\) => !isGeneratedKeyframeCandidateRecord\(item\)\)/)
  assert.match(overviewSource, /keyframes: keyframes\.filter\(\(keyframe\) => !isGeneratedKeyframeCandidateRecord\(keyframe\)\)/)
  assert.match(productionSource, /function keyframesForProduction[\s\S]*!isGeneratedKeyframeCandidateRecord\(keyframe\)/)
  assert.match(workbenchSource, /const keyframesData = \(data\.keyframes \?\? \[\]\)\.filter\(\(keyframe\) => !isGeneratedKeyframeCandidateRecord\(keyframe\)\)/)
  assert.equal((workbenchSource.match(/!isGeneratedKeyframeCandidateRecord\(keyframe\)/g) ?? []).length >= 5, true)
})

test('scene moment setting edits stay in production orchestration', () => {
  const workbenchSource = readFileSync(resolve('src/pages/workbench/WorkbenchPage.tsx'), 'utf8')
  const productionOrchestrationSource = readFileSync(resolve('src/pages/project/production/ProductionOrchestrationPage.tsx'), 'utf8')

  assert.doesNotMatch(workbenchSource, /data-testid="production-orchestration-scene-settings"/)
  assert.doesNotMatch(workbenchSource, /function SceneMomentSettingsEditor/)
  assert.doesNotMatch(workbenchSource, /onLinkReferenceToSceneMoment/)

  assert.match(productionOrchestrationSource, /data-testid="production-orchestration-scene-settings"/)
  assert.match(productionOrchestrationSource, /function SceneMomentSettingsEditor/)
  assert.match(productionOrchestrationSource, /createSemanticEntity\(projectId, semanticEntityConfig\('creativeReferenceUsages'\), \{\s+owner_type: 'scene_moment'/)
  assert.match(productionOrchestrationSource, /referencesForOwner\('scene_moment', moment\.ID, lookup\)/)
  assert.match(productionOrchestrationSource, /assetSlots=\{allAssetSlots\}/)
})

test('content workbench is the single exposed content orchestration entry', () => {
  const appSource = readFileSync(resolve('src/App.tsx'), 'utf8')
  const routeSource = readFileSync(resolve('src/routes/projectRoutes.ts'), 'utf8')
  const sidebarSource = readFileSync(resolve('src/components/layout/Sidebar.tsx'), 'utf8')
  const headerSource = readFileSync(resolve('src/components/layout/Header.tsx'), 'utf8')
  const surfacesSource = readFileSync(resolve('src/pages/project/projectSurfaces.tsx'), 'utf8')
  const workbenchSource = readFileSync(resolve('src/pages/workbench/WorkbenchPage.tsx'), 'utf8')
  const projectRoutesBlock = routeSource.match(/project: \{[\s\S]*?\n  \},/)?.[0] ?? ''

  assert.doesNotMatch(projectRoutesBlock, /productionPreview/)
  assert.doesNotMatch(routeSource, /productionPreview|workbenchProductionPlan|workbenchPreview|\/project\/production\/preview|\/workbench\/production-plan|\/workbench\/preview/)
  assert.doesNotMatch(appSource, /LegacyProductionPreviewRedirect|LEGACY_ROUTES\.productionPreview|LEGACY_ROUTES\.workbenchProductionPlan|LEGACY_ROUTES\.workbenchPreview|ROUTES\.project\.productionPreview/)
  assert.doesNotMatch(sidebarSource, /workbenchProductionPreview|ROUTES\.project\.productionPreview/)
  assert.doesNotMatch(headerSource, /workbenchPreview|workbenchProductionPlan|ROUTES\.project\.productionPreview/)
  assert.match(headerSource, /ROUTES\.project\.contentUnitWorkbench\]: 'header\.titles\.workbenchContentGeneration'/)
  assert.match(surfacesSource, /title: '内容编排工作台'/)
  assert.doesNotMatch(surfacesSource, /\| 'preview'|value: 'preview'|制作预演/)
  assert.match(workbenchSource, /title="内容编排工作台"/)
  assert.match(workbenchSource, /data-testid="content-workbench-command-center"/)
})
