import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('content workbench keeps stable production workspace hooks', () => {
  const source = readFileSync(resolve('src/pages/workbench/WorkbenchPage.tsx'), 'utf8')
  const canvasSource = readFileSync(resolve('src/lib/contentWorkbenchCanvas.ts'), 'utf8')
  const e2eSource = readFileSync(resolve('src/e2e/content-workbench.spec.ts'), 'utf8')
  const contentWorkbenchSource = source.slice(source.indexOf('function ContentGenerationWorkbench'))

  assert.match(source, /data-testid="content-workbench-command-center"/)
  assert.match(contentWorkbenchSource, /title="内容编排工作台"/)
  assert.match(contentWorkbenchSource, /当前情节/)
  assert.doesNotMatch(contentWorkbenchSource, /AI 画面创作指挥台|title="画面编排工作台"|进入画面编排|进入预演/)
  assert.match(source, /detail: '内容编排的入口层'/)
  assert.match(source, /existingCanvas \? '打开生成画布' : '创建生成画布'/)
  assert.doesNotMatch(contentWorkbenchSource, /generationKind="production"/)
  assert.doesNotMatch(source, /detail: '生成工作台的入口层'|label: '可直接生成'|还没有生成制作项的情节|尚未生成制作项|生成提示|existingCanvas \? '去生成'|创建并去生成/)
  assert.match(canvasSource, /内容编排/)
  assert.doesNotMatch(canvasSource, /画面编排/)
  assert.match(e2eSource, /content-workbench-unit-inspector/)
  assert.match(e2eSource, /not\.toContainText\('制作项详情'\)/)
  assert.match(source, /data-testid="content-workbench-review-action"/)
  assert.match(contentWorkbenchSource, /className="shrink-0" data-testid="content-workbench-review-action"/)
  assert.match(source, /testId="content-workbench-production-filter"/)
  assert.match(source, /testId="content-workbench-segment-filter"/)
  assert.match(source, /testId="content-workbench-scene-moment-filter"/)
  assert.match(source, /data-testid="content-workbench-hierarchy-filter"/)
  assert.match(source, /title="制作卡片"/)
  assert.match(source, /title="情绪段卡片"/)
  assert.match(source, /title="情节卡片"/)
  assert.match(source, /type ContentWorkbenchScopeLevel = 'production' \| 'segment' \| 'scene_moment'/)
  assert.match(contentWorkbenchSource, /<ClipboardCheck size=\{14\} \/>/)
  assert.match(contentWorkbenchSource, /data-action-key="review_ai_drafts"/)
  assert.doesNotMatch(source, /content-workbench-command-metrics/)
  assert.doesNotMatch(contentWorkbenchSource, /flex flex-wrap overflow-hidden rounded-md border border-border bg-background" data-testid="content-workbench-command-metrics"/)
  assert.doesNotMatch(contentWorkbenchSource, /label: '可生成'|label: '运行任务'|readyMomentCount/)
  assert.doesNotMatch(contentWorkbenchSource, /label: '完成任务'/)
  assert.doesNotMatch(contentWorkbenchSource, /grid grid-cols-2 gap-2 sm:grid-cols-4">\s+<QueueMiniMetric label="可生成"/)
  assert.doesNotMatch(source, /data-testid="content-workbench-command-brief"/)
  assert.doesNotMatch(source, /commandBriefRows|commandBriefIcons|buildContentWorkbenchCommandBrief/)
  assert.doesNotMatch(contentWorkbenchSource, /flex flex-wrap items-stretch overflow-hidden rounded-md border border-border bg-background" data-testid="content-workbench-command-brief"/)
  assert.doesNotMatch(contentWorkbenchSource, /label: 'AI 审稿'|key: 'review'|review: ClipboardCheck|next_action: nextActionIcons/)
  assert.doesNotMatch(contentWorkbenchSource, /grid gap-1\.5 md:grid-cols-4" data-testid="content-workbench-command-brief"/)
  assert.match(source, /buildContentWorkbenchPipeline/)
  assert.doesNotMatch(contentWorkbenchSource, /data-testid="content-workbench-production-pipeline"/)
  assert.match(contentWorkbenchSource, /production-workbench space-y-3/)
  assert.match(source, /data-step-key=\{step\.key\}/)
  assert.match(source, /flex min-w-\[108px\] items-center gap-1\.5 rounded px-1\.5 py-1/)
  assert.doesNotMatch(contentWorkbenchSource, /情节生产队列|min-w-\[240px\]|w-\[150px\] rounded-md border px-3 py-2|w-\[126px\] rounded-md border px-2\.5 py-2/)
  assert.match(source, /selectedPreviewItemCount/)
  assert.match(source, /selectedDeliveryVersionCount/)
  assert.match(source, /preview_delivery: Film/)
  assert.match(source, /searchParams\.get\('scene_moment_id'\)/)
  assert.match(source, /searchParams\.get\('content_unit_id'\)/)
  assert.match(source, /searchParams\.get\('productionId'\)/)
  assert.match(source, /setProductionFilter\(target\)/)
  assert.match(source, /function selectProductionFilter/)
  assert.match(source, /next\.set\('productionId', value\)/)
  assert.match(source, /next\.delete\('scene_moment_id'\)/)
  assert.match(source, /next\.delete\('content_unit_id'\)/)
  assert.match(source, /function selectSegmentFilter/)
  assert.match(source, /function selectSceneMoment/)
  assert.match(source, /next\.set\('scene_moment_id'/)
  assert.match(source, /function selectContentUnit/)
  assert.match(source, /next\.set\('content_unit_id'/)
  assert.match(source, /function selectContentUnitFromRow/)
  assert.match(source, /pickContentWorkbenchUploadTarget/)
  assert.match(source, /pickContentWorkbenchFirstUsableUnit/)
  assert.match(source, /pickContentWorkbenchFocusAfterIgnoredCandidate/)
  assert.match(source, /setCandidateUploadTargetSlot\(uploadTargetSlot\)/)
  assert.match(source, /if \(!file\) \{\s+setCandidateUploadTargetSlot\(null\)/)
  assert.match(source, /uploadCandidate\.mutate\(\{ file, slot \}\)/)
  assert.match(source, /if \(variables\.next === 'confirmed'\) \{\s+selectContentUnit\(variables\.unitId\)/)
  assert.match(source, /else if \(selectedUnit\?\.ID === variables\.unitId\)/)
  assert.doesNotMatch(source, /commandStageRows/)
  assert.match(source, /筛选与定位/)
  assert.match(contentWorkbenchSource, /<div className="space-y-2">\s+<div className="flex items-center gap-2 text-xs font-medium text-muted-foreground">\s+<Settings2 size=\{14\} \/>/)
  assert.doesNotMatch(contentWorkbenchSource, /SelectTrigger className="h-9" data-testid="content-workbench-production-filter"/)
  assert.doesNotMatch(contentWorkbenchSource, /SelectTrigger className="h-9" data-testid="content-workbench-segment-filter"/)
  assert.doesNotMatch(contentWorkbenchSource, /SelectTrigger className="h-9" data-testid="content-workbench-scene-moment-filter"/)
  assert.doesNotMatch(contentWorkbenchSource, /<div className="rounded-md border border-border bg-background p-3">\s+<div className="flex items-center gap-2 text-xs font-medium text-muted-foreground">\s+<Settings2 size=\{14\} \/>/)
  assert.doesNotMatch(contentWorkbenchSource, /SelectTrigger className="mt-[23] h-9"/)
  assert.doesNotMatch(source, /入口、筛选与动作/)
  assert.doesNotMatch(contentWorkbenchSource, /当前写入目标/)
  assert.doesNotMatch(source, /onClick=\{openAiSuggest\}/)
  assert.doesNotMatch(source, /onClick=\{\(\) => setCreatingUnit\(true\)\}/)
  assert.doesNotMatch(source, /onClick=\{openSelectedUnitCanvas\}/)
  assert.doesNotMatch(source, /const onClick = item\.actionKey \? nextActionHandlers/)
  assert.doesNotMatch(source, /key=\{item\.key\}\s+type="button"/)
  assert.match(source, /data-testid="content-workbench-production-grid"/)
  assert.match(source, /grid gap-3 xl:grid-cols-\[minmax\(0,1fr\)_320px\]" data-testid="content-workbench-production-grid"/)
  assert.doesNotMatch(source, /grid gap-4 xl:grid-cols-\[minmax\(0,1fr\)_340px\]" data-testid="content-workbench-production-grid"/)
  assert.match(contentWorkbenchSource, /<div className="min-w-0 space-y-3">\s+<WorkbenchPanel[\s\S]{0,120}title="制作项时间表"/)
  assert.doesNotMatch(contentWorkbenchSource, /<div className="min-w-0 space-y-4">\s+<WorkbenchPanel[\s\S]{0,120}title="制作项轨道"/)
  assert.doesNotMatch(source, /title="制作项列表"/)
  assert.doesNotMatch(contentWorkbenchSource, /<p className="text-xs text-muted-foreground">当前情节<\/p>/)
  assert.doesNotMatch(contentWorkbenchSource, /准备度 \{selected\.progress\}%/)
  assert.match(source, /function NextActionsPanel/)
  assert.doesNotMatch(contentWorkbenchSource, /data-testid="content-workbench-next-actions"/)
  assert.doesNotMatch(contentWorkbenchSource, /<span className="truncate">下一步动作<\/span>/)
  assert.doesNotMatch(contentWorkbenchSource, /<WorkbenchPanel[\s\S]{0,120}title="下一步动作"/)
  assert.match(source, /data-testid="content-workbench-review-queue"/)
  assert.match(source, /data-testid="content-workbench-review-metrics"/)
  assert.match(source, /mb-3 rounded-md border px-2\.5 py-2\.5/)
  assert.match(source, /grid gap-3 lg:grid-cols-\[240px_minmax\(0,1fr\)\]/)
  assert.doesNotMatch(source, /mt-3 grid gap-2 sm:grid-cols-4/)
  assert.doesNotMatch(source, /grid gap-4 lg:grid-cols-\[280px_minmax\(0,1fr\)\]/)
  assert.doesNotMatch(source, /QueueMiniMetric label="待审"|QueueMiniMetric label="新增"|QueueMiniMetric label="变更"|QueueMiniMetric label="风险"/)
  assert.doesNotMatch(contentWorkbenchSource, /<ReadinessSummaryCard rows=\{standards\}/)
  assert.doesNotMatch(contentWorkbenchSource, /<DeliveryBriefCard brief=\{deliveryBrief\} \/>/)
  assert.doesNotMatch(contentWorkbenchSource, /<ActivityFeedCard feed=\{activityFeed\} \/>/)
  assert.doesNotMatch(contentWorkbenchSource, /data-testid="content-workbench-generation-context-detail"/)
  assert.doesNotMatch(contentWorkbenchSource, /data-testid="content-workbench-gate-detail"/)
  assert.doesNotMatch(contentWorkbenchSource, /<span className="truncate">检查明细<\/span>/)
  assert.match(source, /尚未配置画面锚点/)
  assert.match(source, /建议先创建或采纳开头、结尾等画面锚点/)
  assert.doesNotMatch(source, /尚未绑定画面锚点|生成或绑定开头、结尾等画面锚点/)
  assert.doesNotMatch(contentWorkbenchSource, /<div className="border-t border-border pt-2\.5" data-testid="content-workbench-generation-context-detail">/)
  assert.doesNotMatch(contentWorkbenchSource, /<details className="mt-2 rounded-md border border-border bg-background" data-testid="content-workbench-generation-context-detail">/)
  assert.doesNotMatch(source, /<span className="truncate">门禁明细<\/span>|<span className="truncate">生成上下文详情<\/span>/)
  assert.doesNotMatch(contentWorkbenchSource, /<WorkbenchPanel[\s\S]{0,120}title="生成检查"/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="上下文 Inspector"/)
  assert.doesNotMatch(source, /当前上下文/)
  assert.doesNotMatch(source, /const contextRows = buildMomentContext\(selected\)/)
  assert.doesNotMatch(source, /className="production-context-stack"[\s\S]{0,180}\.\.\.contextRows/)
  assert.doesNotMatch(source, /<WorkbenchPanel[\s\S]{0,120}title="生成门禁"/)
  assert.doesNotMatch(source, /<WorkbenchPanel[\s\S]{0,120}title="当前制作项"/)
  assert.doesNotMatch(contentWorkbenchSource, /data-testid="content-workbench-execution-section"/)
  assert.match(source, /const executionSectionOpen = deliveryBrief\.tone !== 'ready' \|\| hasActiveExecutionItem \|\| selectedPreviewMissingAssets\.length > 0/)
  assert.match(source, /const executionStatusLabel = deliveryBrief\.tone === 'ready'/)
  assert.doesNotMatch(contentWorkbenchSource, /<details open=\{executionSectionOpen\} className="mt-2 rounded-md border border-border bg-background" data-testid="content-workbench-execution-section">/)
  assert.doesNotMatch(contentWorkbenchSource, /<span className="truncate">生成结果<\/span>/)
  assert.doesNotMatch(source, /\{deliveryBrief\.progress\}%/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="执行与交付" icon=\{PackageCheck\}>/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="生成上下文详情"/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="生成交付包"/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="生产活动流"/)
  assert.doesNotMatch(source, /<WorkbenchPanel title="素材与生成上下文"/)
  assert.doesNotMatch(source, /素材候选上传|上传素材候选|CandidateComparison|production-candidate-row/)
  assert.match(source, /data-testid="content-workbench-activity-feed"/)
  assert.match(source, /data-testid="content-workbench-activity-overflow"/)
  assert.match(source, /const hasActiveItem = feed\.items\.some\(\(item\) => item\.tone === 'blocked' \|\| item\.tone === 'running'\)/)
  assert.match(source, /<details className="rounded-md border border-border bg-background" data-testid="content-workbench-activity-feed" open=\{hasActiveItem\}>/)
  assert.doesNotMatch(source, /<div className="rounded-md border border-border bg-background p-2\.5" data-testid="content-workbench-activity-feed">/)
  assert.match(source, /const primaryItems = feed\.items\.slice\(0, 1\)/)
  assert.match(source, /const secondaryItems = feed\.items\.slice\(1\)/)
  assert.match(source, /data-action-key=\{item\.actionKey\}/)
  assert.doesNotMatch(contentWorkbenchSource, /<ActivityFeedCard feed=\{activityFeed\} \/>/)
  assert.doesNotMatch(source, /ActivityFeedCard feed=\{activityFeed\} actionIcons/)
  assert.doesNotMatch(source, /item\.actionLabel \?\? '处理'/)
  assert.match(source, /data-testid="content-workbench-unit-track"/)
  assert.match(source, /data-testid="content-workbench-scoped-tracks"/)
  assert.match(source, /const scopedTrackSections = useMemo/)
  assert.match(source, /data-testid="content-workbench-track-section"/)
  assert.match(source, /section\.rows\.map\(\(trackRow\)/)
  assert.match(source, /onSelectUnit=\{\(unitId\) => selectContentUnitFromRow\(trackRow, unitId\)\}/)
  assert.match(source, /onAiSuggest=\{\(\) => openAiSuggest\(trackRow\)\}/)
  assert.equal((source.match(/rounded-md border border-border bg-background p-2\.5" data-testid="content-workbench-unit-track"/g) ?? []).length >= 2, true)
  assert.match(source, /data-testid="content-workbench-unit-track-summary"/)
  assert.match(source, /data-testid="content-workbench-unit-schedule"/)
  assert.match(source, /data-testid="content-workbench-unit-timeline"/)
  assert.match(source, /data-testid="content-workbench-timeline-block"/)
  assert.match(source, /制作项时间表/)
  assert.match(source, /制作项时间轴/)
  assert.match(source, /时间尺/)
  assert.match(source, /data-testid="content-workbench-timeline-playhead"/)
  assert.match(source, /data-testid="content-workbench-timeline-playhead-label"/)
  assert.match(source, /const timelineMemberItems = summary\.items\.filter\(\(item\) => item\.timeSource === 'preview'\)/)
  assert.match(source, /const laneItems = timelineMemberItems\.filter/)
  assert.match(source, /const timelineOriginSec = contentWorkbenchTimelineOriginSec\(timelineMemberItems\)/)
  assert.match(source, /const selectedTimelineItemStartSec = selectedTimelineItem \? contentWorkbenchLocalTimelineSec\(selectedTimelineItem\.startSec, timelineOriginSec\) : 0/)
  assert.match(source, /data-testid="content-workbench-timeline-focus-label"/)
  assert.match(source, /播放头 \{formatTrackClock\(selectedTimelineItemStartSec\)\}/)
  assert.match(source, /const \[timelineZoom, setTimelineZoom\] = useState\(1\)/)
  assert.match(source, /data-testid="content-workbench-timeline-zoom"/)
  assert.match(source, /aria-label="缩小时间轴"/)
  assert.match(source, /aria-label="放大时间轴"/)
  assert.match(source, /const timelineCanvasWidth = Math\.round\(1040 \* timelineZoom\)/)
  assert.match(source, /data-testid="content-workbench-timeline-lane"/)
  assert.match(source, /onDrop=\{\(event\) => handleTimelineLaneDrop\(event\)\}/)
  assert.match(source, /function handleTimelineLaneDrop/)
  assert.match(source, /application\/x-movscript-timeline-drag-offset-sec/)
  assert.match(source, /const localStartSec = snapContentWorkbenchTimelineStartSec/)
  assert.match(source, /onMoveUnitOnTimeline\(sourceUnitId, Math\.round\(\(localStartSec \+ timelineOriginSec\) \* 10\) \/ 10\)/)
  assert.match(source, /function contentWorkbenchTimelineSnapStep/)
  assert.match(source, /contentUnitTimelineKindRank/)
  assert.match(source, /detail: kind === 'shot' \? '镜头 · 关键帧挂载' : '制作项'/)
  assert.match(source, /关键帧：\$\{item\.keyframeTitles\.slice\(0, 2\)\.join\('、'\)\}/)
  assert.doesNotMatch(source, /label: '对白\/声音'/)
  assert.doesNotMatch(source, /label: '关键帧\/缺口'/)
  assert.match(source, /当前情节还没有制作项/)
  assert.match(source, /添加或采纳制作项后，这里会显示时间位置、对白\/声音、关键帧和素材缺口。/)
  assert.match(source, /onCreateUnit: \(\) => void/)
  assert.match(source, /onSelectFirstMoment: \(\) => void/)
  assert.match(source, /function openCreateUnit\(\)/)
  assert.match(source, /onClick=\{openCreateUnit\}/)
  assert.match(source, /onCreateUnit=\{openCreateUnit\}/)
  assert.match(source, /onSelectFirstMoment=\{selectFirstSceneMoment\}/)
  assert.match(source, /<Plus size=\{13\} \/>\s+添加制作项/)
  assert.match(source, /选择第一个情节/)
  assert.match(source, /disabled=\{!selected\}/)
  assert.match(source, /formatTrackTimeRange\(contentWorkbenchLocalTimelineSec\(item\.startSec, timelineOriginSec\)/)
  assert.match(source, /buildTrackTimeTicks\(timelineDurationSec\)/)
  assert.match(source, /trackTimelinePercent\(contentWorkbenchLocalTimelineSec\(item\.startSec, timelineOriginSec\), timelineDurationSec\)/)
  assert.match(source, /trackTimelineWidthPercent\(item\.durationSec, timelineDurationSec\)/)
  assert.doesNotMatch(source, /min-w-\[1040px\]/)
  assert.match(source, /absolute top-1 h-9 min-w-0 overflow-hidden/)
  assert.doesNotMatch(source, /absolute top-1 h-9 min-w-\[72px\]/)
  assert.match(source, /type ContentWorkbenchDropPosition = 'before' \| 'after'/)
  assert.match(source, /draggable=\{canDragUnits\}/)
  assert.match(source, /onDragStart=\{\(event\) => handleUnitDragStart\(event, Number\(item\.id\)\)\}/)
  assert.match(source, /onDragStart=\{\(event\) => handleUnitDragStart\(event, Number\(item\.id\), 'timeline'\)\}/)
  assert.match(source, /onDrop=\{\(event\) => handleUnitDrop\(event, Number\(item\.id\)\)\}/)
  assert.match(source, /data-testid="content-workbench-unit-move-earlier"/)
  assert.match(source, /data-testid="content-workbench-unit-move-later"/)
  assert.match(source, /aria-label=\{`前移 \$\{item\.title\}`\}/)
  assert.match(source, /aria-label=\{`后移 \$\{item\.title\}`\}/)
  assert.match(source, /function reorderContentWorkbenchUnits/)
  assert.match(source, /const reorderContentUnits = useMutation/)
  assert.match(source, /updateSemanticEntity\(projectId, contentUnitConfig, unit\.ID, \{ order \}\)/)
  assert.doesNotMatch(source, /updateSemanticEntity\(projectId, previewTimelineItemConfig, timelineItem\.ID, \{ start_sec: startSec, order \}\)/)
  assert.match(source, /const moveContentUnitOnTimeline = useMutation/)
  assert.match(source, /preview_timeline_id: numberOf\(timelineItem\.preview_timeline_id\)/)
  assert.match(source, /start_sec: normalizedStartSec/)
  assert.match(source, /duration_sec: numberOf\(timelineItem\.duration_sec\) \|\| durationSec/)
  assert.match(source, /data-testid="content-workbench-schedule-row"/)
  assert.match(source, /pickPreviewTimelineItemForUnit\(row\?\.previewTimelineItems \?\? \[\], unit\.ID\)/)
  assert.match(source, /bestPreviewTimelineIdsForProductionIds\(productionIds, data\)/)
  assert.match(source, /scopedPreviewTimelineItems\(/)
  assert.match(source, /Boolean\(item\.is_primary\)/)
  assert.match(source, /startSec: previewTimelineItem \? numberOf\(previewTimelineItem\.start_sec\) : undefined/)
  assert.match(source, /durationSec: numberOf\(previewTimelineItem\?\.duration_sec\) \|\| numberOf\(unit\.duration_sec\)/)
  assert.match(source, /item\.timeSource === 'preview' \? '预览时间线' : '待加入时间线'/)
  assert.match(source, /trackKindLabel\(item\.kind\)/)
  assert.match(source, /scriptCue: scriptBlockCue\(scriptBlock\)/)
  assert.match(source, /soundCue: unitSoundCue\(unit, scriptBlock, audioSlots\)/)
  assert.match(source, /requiresKeyframe: contentWorkbenchUnitRequiresKeyframe\(unit\.kind\)/)
  assert.match(source, /<span>对白 \/ 声音<\/span>/)
  assert.match(source, /item\.scriptCue \|\| '未绑定对白'/)
  assert.match(source, /item\.soundCue \|\| '无显性声音需求'/)
  assert.match(source, /item\.requiresKeyframe \? \(item\.keyframeTitles\.length > 0 \? item\.keyframeTitles\.slice\(0, 2\)\.join\('、'\) : '无关键帧'\) : '不要求关键帧'/)
  assert.match(source, /item\.missingAssetTitles\.length > 0 \? item\.missingAssetTitles\.slice\(0, 2\)\.join\('、'\) : '无素材缺口'/)
  assert.match(source, /listSemanticEntities\(projectId, semanticEntityConfig\('scriptBlocks'\)\)/)
  assert.match(source, /scriptBlocks: scriptBlocks as WorkbenchRecord\[\]/)
  assert.match(source, /data-testid="content-workbench-unit-inspector"/)
  assert.doesNotMatch(contentWorkbenchSource, /title="制作项详情"/)
  assert.match(contentWorkbenchSource, /hideHeaderCopy/)
  assert.match(contentWorkbenchSource, /hideHeaderActions/)
  assert.match(contentWorkbenchSource, /content-workbench-unit-detail-actions/)
  assert.doesNotMatch(contentWorkbenchSource, /data-testid="content-workbench-asset-slot-panel"/)
  assert.doesNotMatch(contentWorkbenchSource, /上传候选会挂到：\{titleOfRecord\(uploadTargetSlot\)\}/)
  assert.match(source, /idScope=\{`content-workbench-create-asset-slot-\$\{selectedUnit\.ID\}`\}/)
  assert.match(source, /owner_type: 'content_unit'/)
  assert.match(source, /status: 'missing'/)
  assert.match(source, /idScope=\{`content-workbench-unit-inspector-\$\{selectedUnit\.ID\}`\}/)
  assert.doesNotMatch(source, /idScope=\{`content-workbench-unit-inspector-\$\{selectedUnit\.ID\}`\}[\s\S]{0,240}editKey=\{selectedUnit\.ID\}/)
  assert.match(source, /idScope="content-workbench-create-unit"/)
  assert.match(source, /idScope=\{`content-workbench-edit-unit-\$\{selectedUnit\.ID\}`\}/)
  assert.match(source, /idScope=\{`content-workbench-create-keyframe-\$\{selectedUnit\.ID\}`\}/)
  assert.match(source, /setOptimisticSelectedUnit\(record\)/)
  assert.doesNotMatch(source, /QueueMiniMetric label="制作项"|QueueMiniMetric label="总时长"|QueueMiniMetric label="阻塞"|QueueMiniMetric label="关键帧"/)
  assert.doesNotMatch(source, /<Progress value=\{item\.readiness\}/)
  assert.match(source, /w-\[172px\] shrink-0 rounded-md border px-2 py-1\.5 text-left transition-colors/)
  assert.match(source, /trackKindLabel\(item\.kind\)\} · \{item\.labels\.slice\(0, 2\)\.join\(' · '\) \|\| '待补输入'/)
  assert.match(source, /item\.blockers\[0\]\}\{item\.blockers\.length > 1 \? ` · 另 \$\{item\.blockers\.length - 1\}` : ''\}/)
  assert.doesNotMatch(source, /item\.readiness\}%/)
  assert.doesNotMatch(source, /item\.labels\.map\(\(label\)/)
  assert.doesNotMatch(source, /w-\[188px\] shrink-0 rounded-md border px-2\.5 py-2 text-left transition-colors/)
  assert.doesNotMatch(source, /w-\[220px\] shrink-0 rounded-md border px-3 py-3 text-left transition-colors/)
  assert.match(source, /data-testid="content-workbench-candidate-queue"/)
  assert.doesNotMatch(source, /action=\{unitCandidates\.length > 0 \? <Badge variant="secondary">\{unitCandidates\.length\} 条待确认<\/Badge> : undefined\}/)
  assert.doesNotMatch(source, /variant=\{unitCandidates\.length > 0 \? 'secondary' : 'outline'\}/)
  assert.match(source, /<details className="overflow-hidden rounded-md border border-border bg-background" data-testid="content-workbench-candidate-queue">/)
  assert.match(source, /<summary className="flex cursor-pointer list-none items-center justify-between gap-2 px-2\.5 py-2">/)
  assert.match(source, /className="h-7 gap-1 px-2"/)
  assert.doesNotMatch(source, /rounded-md border border-border bg-background p-2\.5" data-testid="content-workbench-candidate-queue"/)
  assert.doesNotMatch(source, /overflow-hidden rounded-md border border-border bg-card">\s+\{unitCandidates\.map/)
  assert.doesNotMatch(source, /unitCandidates\.map[\s\S]{0,220}rounded-md border border-border bg-card p-3/)
  assert.doesNotMatch(source, /当前情节没有待确认的候选制作项/)
  assert.doesNotMatch(source, /选择情节后查看候选制作项/)
  assert.match(source, /data-testid="content-workbench-keyframe-continuity"/)
  assert.match(source, /const showMomentKeyframeContinuity = selectedKeyframeSequence\.length > 0/)
  assert.match(source, /showMomentKeyframeContinuity \? \(\s+<KeyframeContinuityStrip[\s\S]{0,120}sequence=\{selectedKeyframeSequence\}/)
  assert.doesNotMatch(source, /<KeyframeContinuityStrip[\s\S]{0,160}onCreateKeyframe/)
  assert.doesNotMatch(source, /连续关键帧总览/)
  assert.doesNotMatch(source, /给当前制作项补开头帧、结尾帧后，这里会形成一条可扫读的连续性检查带。/)
  assert.match(source, /data-testid="content-workbench-keyframe-track"/)
  assert.match(source, /className="order-first rounded-md border border-border bg-background p-2\.5" data-testid="content-workbench-keyframe-track"/)
  assert.match(source, /generatedKeyframeCandidateTargetId/)
  assert.match(source, /isUnresolvedCandidateStatus/)
  assert.match(source, /function keyframeCandidatesForTargets/)
  assert.match(source, /!isUnresolvedCandidateStatus\(keyframe\.status\)/)
  assert.match(source, /const selectedUnitKeyframeCandidates = data\s+\? keyframeCandidatesForTargets\(data\.keyframes, selectedUnitKeyframes\)/)
  assert.match(source, /data-testid="content-workbench-keyframe-candidates"/)
  assert.match(source, /function keyframeResourceCandidatePayload\(keyframe: WorkbenchRecord, resourceId: number, source: 'library' \| 'upload'\)/)
  assert.match(source, /source_origin: source === 'upload' \? 'workbench_upload' : 'workbench_resource_library'/)
  assert.match(source, /createSemanticEntity\(projectId, semanticEntityConfig\('keyframes'\), keyframeResourceCandidatePayload\(keyframe, resourceId, 'library'\)\)/)
  assert.match(source, /createSemanticEntity\(projectId, semanticEntityConfig\('keyframes'\), keyframeResourceCandidatePayload\(keyframe, resource\.ID, 'upload'\)\)/)
  assert.match(source, /已加入画面锚点候选/)
  assert.match(source, /关键帧素材已上传并加入候选/)
  assert.doesNotMatch(source, /keyframeResourcePatchPayload/)
  assert.doesNotMatch(source, /关键帧已绑定资源|关键帧素材已上传并绑定|绑定关键帧资源失败/)
  assert.match(source, /const rejectKeyframeCandidate = useMutation/)
  assert.match(source, /keyframeStatusPatchPayload\(candidate, 'rejected'\)/)
  assert.match(source, /只能拒绝 AI 生成的画面锚点候选/)
  assert.match(source, /rejectKeyframeCandidate\.mutate\(candidate\)/)
  assert.match(source, /拒绝画面锚点候选失败/)
  assert.match(source, /function hasLoadedResource/)
  assert.match(source, /numberOf\(record\?\.resource\?\.ID\) > 0/)
  assert.match(source, /const candidateResourceId = hasLoadedResource\(candidate\) \? numberOf\(candidate\.resource\?\.ID\) : 0/)
  assert.match(source, /const adoptableCandidates = candidates\.filter\(hasLoadedResource\)/)
  assert.match(source, /可采纳 \{adoptableCandidates\.length\}/)
  assert.match(source, /disabled=\{adoptableCandidates\.length === 0\}/)
  assert.match(source, /暂无有资源的候选/)
  assert.match(source, /candidateResourceId > 0 \? \(/)
  assert.match(source, /缺资源/)
  assert.match(source, /selectedUnitKeyframeCandidateCount > 0/)
  assert.match(source, /navigate\(mergeSearch\(ROUTES\.project\.tasks, '', \{/)
  assert.match(source, /create: '1'/)
  assert.match(source, /purpose: 'accept_keyframe'/)
  assert.match(source, /target_type: 'keyframe'/)
  assert.match(source, /target_id: keyframe\.ID/)
  assert.match(source, /candidate_id: adoptableCandidates\[0\]\?\.ID/)
  assert.match(source, /candidate_id: candidate\.ID/)
  assert.doesNotMatch(source, /candidate_id: candidates\[0\]\?\.ID/)
  assert.doesNotMatch(source, /当前制作项：\{titleOfRecord\(selectedUnit\)\}/)
  assert.doesNotMatch(source, /rounded-md border border-border bg-background p-2\.5">\s+<div className="mb-2\.5 flex items-center justify-between gap-3">[\s\S]{0,180}画面锚点轨道/)
  assert.match(source, /rounded-md border border-dashed border-border px-3 py-4 text-sm text-muted-foreground">选择或创建制作项后查看画面锚点。/)
  assert.match(source, /flex flex-wrap items-center justify-between gap-3 rounded-md border border-dashed border-border bg-muted\/20 px-3 py-3/)
  assert.doesNotMatch(source, /rounded-md border border-dashed border-border bg-muted\/20 px-3 py-5/)
  assert.match(source, /w-\[168px\] shrink-0 overflow-hidden rounded-md border border-border bg-card/)
  assert.match(source, /flex w-\[112px\] shrink-0 flex-col items-center justify-center/)
  assert.doesNotMatch(source, /flex w-\[132px\] shrink-0 flex-col items-center justify-center/)
  assert.match(source, /aria-label="上传关键帧图片"/)
  assert.match(source, /aria-label="从资源库选择关键帧素材"/)
  assert.match(source, /data-testid="content-workbench-current-unit-panel"/)
  assert.doesNotMatch(contentWorkbenchSource, /data-testid="content-workbench-generation-target"/)
  assert.doesNotMatch(contentWorkbenchSource, /data-testid="content-workbench-unit-health"/)
  assert.doesNotMatch(source, /<details className="rounded-md border border-border bg-background" data-testid="content-workbench-generation-target">/)
  assert.doesNotMatch(source, /<span className="block text-\[11px\] font-medium text-muted-foreground">生成目标<\/span>/)
  assert.doesNotMatch(source, /<div className="border-b border-border pb-2">\s+<p className="text-xs text-muted-foreground">生成目标<\/p>/)
  assert.match(source, /buildContentWorkbenchUnitHealth/)
  assert.match(source, /function unitHealthStatusLabel/)
  assert.match(source, /function unitHealthBadgeVariant/)
  assert.doesNotMatch(contentWorkbenchSource, /data-testid="content-workbench-unit-health-status"/)
  assert.doesNotMatch(contentWorkbenchSource, /<Badge variant=\{unitHealthBadgeVariant\(currentUnitHealth\)\} data-testid="content-workbench-unit-health-status">/)
  assert.doesNotMatch(source, /function UnitHealthCard/)
  assert.doesNotMatch(source, /\{health\.score\}%/)
  assert.doesNotMatch(source, /UnitHealthCard[\s\S]{0,1800}<Progress value=\{health\.score\}/)
  assert.doesNotMatch(source, /visibleChecks/)
  assert.match(source, /data-action-key=\{action\.key\}/)
  assert.match(source, /buildContentWorkbenchNextActions/)
  assert.match(source, /function selectFirstSceneMoment/)
  assert.match(source, /function selectFirstContentUnit/)
  assert.match(source, /select_scene_moment: selectFirstSceneMoment/)
  assert.match(source, /select_unit: selectFirstContentUnit/)
  assert.match(source, /inspect_preview_mount: Film/)
  assert.match(source, /open_delivery_workspace: PackageCheck/)
  assert.match(source, /const previewMountSectionRef = useRef<HTMLDivElement>\(null\)/)
  assert.match(source, /function inspectPreviewMount\(\)/)
  assert.match(source, /querySelector<HTMLDetailsElement>\('\[data-testid="content-workbench-preview-mount"\]'\)/)
  assert.match(source, /previewMount\.open = true/)
  assert.match(source, /previewMountSectionRef\.current\?\.scrollIntoView\(\{ behavior: 'smooth', block: 'center' \}\)/)
  assert.match(source, /inspect_preview_mount: inspectPreviewMount/)
  assert.doesNotMatch(source, /inspect_preview_mount: \(\) => navigate/)
  assert.doesNotMatch(source, /open_preview_workspace|focus: 'preview'|检查预演挂载|当前画面编排工作台/)
  assert.match(source, /data-testid="content-workbench-preview-mount"/)
  assert.match(source, /data-testid="content-workbench-preview-metrics"/)
  assert.match(source, /const hasPreviewBlocker = gaps\.length > 0 \|\| blockedUnits > 0/)
  assert.match(source, /<details className="rounded-md border border-border bg-background" data-testid="content-workbench-preview-mount" open=\{hasPreviewBlocker\}>/)
  assert.match(source, /<summary className="flex cursor-pointer list-none flex-wrap items-start justify-between gap-2 px-2\.5 py-2 marker:text-muted-foreground">/)
  assert.match(source, /flex flex-wrap overflow-hidden rounded-md border border-border bg-card" data-testid="content-workbench-preview-metrics"/)
  assert.doesNotMatch(source, /<div className="rounded-md border border-border bg-background p-2\.5" data-testid="content-workbench-preview-mount">/)
  assert.doesNotMatch(source, /function PreviewMountMetric|mt-2 grid grid-cols-4 gap-1\.5|<PreviewMountMetric/)
  assert.match(source, /const firstGap = gaps\[0\]/)
  assert.match(source, /优先缺口：\{firstGap\.name\}/)
  assert.doesNotMatch(source, /gaps\.slice\(0, 2\)\.map/)
  assert.doesNotMatch(source, /onOpenAssets=\{/)
  assert.doesNotMatch(source, /onOpenDelivery=\{/)
  assert.doesNotMatch(source, /function ProductionPreviewWorkspace/)
  assert.doesNotMatch(source, /loadProductionPreviewData|ProductionPreviewData|ForPreviewProduction/)
  assert.match(source, /previewTimelinesForWorkbenchProduction/)
  assert.match(source, /open_delivery_workspace: \(\) => navigate\(withRouteParams\(ROUTES\.project\.deliveryWorkbench/)
  assert.match(source, /buildContentWorkbenchReadinessSummary/)
  assert.match(source, /buildContentWorkbenchReviewQueueSummary/)
  assert.match(source, /buildContentWorkbenchDeliveryBrief/)
  assert.match(source, /completedJobCount: selectedUnitCompletedJobCount,\s+previewItemCount: selectedPreviewItemCount,\s+deliveryVersionCount: selectedDeliveryVersionCount/)
  assert.match(source, /const selectedUnitRunningJobCount = selectedUnitJobs\.filter/)
  assert.match(source, /const selectedUnitCompletedJobCount = selectedUnitJobs\.filter/)
  assert.match(source, /completedJobCount: selectedUnitCompletedJobCount/)
  assert.match(source, /buildContentWorkbenchActivityFeed/)
  assert.match(source, /pickContentWorkbenchRelevantJobs/)
  assert.match(source, /jobs: selectedUnitJobs\.map/)
  assert.match(source, /buildContentWorkbenchRouteSearch\(\{ sceneMomentId: targetRow\.moment\.ID \}\)/)
  assert.match(source, /pickContentWorkbenchRowIdForDeepLink/)
  assert.match(source, /contentUnitId: linkedContentUnitId/)
  assert.match(source, /linkedSceneMomentId > 0 \|\| linkedContentUnitId <= 0/)
  assert.match(source, /next\.set\('scene_moment_id', String\(selected\.moment\.ID\)\)/)
  assert.match(source, /buildContentWorkbenchUnitTrack/)
  assert.match(source, /buildContentWorkbenchAiSuggestPrompt/)
  assert.match(source, /sceneMomentId: targetRow\.moment\.ID/)
  assert.match(source, /findContentWorkbenchCanvas/)
  assert.match(source, /buildContentWorkbenchCanvasPayload/)
  assert.match(source, /打开生成画布失败/)
  assert.match(source, /function openSelectedUnitCanvas/)
  assert.match(source, /if \(openUnitCanvas\.isPending\) return/)
  assert.match(source, /AI 审稿队列/)
  assert.match(source, /function appendReviewGate/)
  assert.match(source, /label: 'AI 草案已处理'/)
  assert.match(source, /appendReviewGate\(baseStandards, reviewQueueSummary\.pending\)/)
  assert.match(source, /reviewPanelCollapsed/)
  assert.match(source, /const showReviewPanel = reviewMode \|\| reviewDraftsQuery\.isLoading \|\| \(reviewDrafts\.length > 0 && !reviewPanelCollapsed\)/)
  assert.match(source, /setReviewPanelCollapsed\(false\)/)
  assert.match(source, /setReviewPanelCollapsed\(true\)/)
  assert.match(source, /complete_unit_prompt: \(\) => openEditSelectedUnit\(\)/)
  assert.match(source, /resolve_generation_context: \(\) => openEditSelectedUnit\(\)/)
  assert.match(source, /<Dialog open=\{editingUnit\}/)
  assert.match(source, /rounded-md border border-border bg-card/)
  assert.match(source, /flex flex-wrap items-center justify-between gap-2 border-b/)
  assert.match(source, /cn\('p-2\.5', bodyClassName\)/)
  assert.match(source, /overflow-hidden rounded-md border border-border bg-background/)
  assert.match(source, /grid grid-cols-\[104px_minmax\(0,1fr\)\]/)
  assert.doesNotMatch(source, /function ContextStack[\s\S]{0,300}grid gap-3 md:grid-cols-2/)
  assert.match(source, /flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground" data-testid="content-workbench-unit-track-summary"/)
  assert.match(source, /localAgentClient\.rejectDraft/)
  assert.match(source, /退回草案/)
  assert.match(source, /data-testid="content-workbench-mark-draft-reviewed"/)
  assert.match(source, /reviewDisposition: 'manual_review_completed'/)
  assert.match(source, /backendWritePerformed: false/)
  assert.match(source, /contentWorkbenchProposalDefaults/)
  assert.match(source, /contentWorkbenchProposalSnapshot/)
  assert.match(source, /onSaved=\{\(record\) => \{\s+selectContentUnit\(record\.ID\)/)
  assert.match(source, /setOptimisticSelectedUnit\(record\)/)
  assert.match(source, /带入新建制作项/)
  assert.match(source, /\.\.\.unitDraftDefaults,\s+segment_id: selected\.segment\?\.ID \?\? null,\s+scene_moment_id: selected\.moment\.ID/)
  assert.match(source, /production_id: nullableNumber\(selectedUnit\?\.production_id \?\? selected\.moment\.production_id \?\? selected\.segment\?\.production_id \?\? selected\.productionIds\[0\]\)/)
  assert.match(source, /script_block_id: nullableNumber\(selectedUnit\?\.script_block_id \?\? selected\.moment\.script_block_id \?\? selected\.segment\?\.script_block_id\)/)
  assert.match(source, /data-testid="content-workbench-create-proposal-unit"/)
  assert.match(source, /onCreateUnitFromProposal=\{openCreateUnitFromProposal\}/)
  assert.match(source, /currentUnitId: current\?\.ID/)
  assert.match(source, /编辑当前制作项/)
  assert.match(source, /data-testid="content-workbench-edit-current-unit"/)
  assert.match(source, /onEditCurrentUnit=\{openEditSelectedUnit\}/)
  assert.doesNotMatch(source, /内容单元|当前单元|草案单元|该单元/)
})

test('content workbench excludes AI keyframe candidates from official keyframe readiness', () => {
  const workbenchSource = readFileSync(resolve('src/pages/workbench/WorkbenchPage.tsx'), 'utf8')
  const contentUnitsSource = readFileSync(resolve('src/pages/project/content-units/ContentUnitsPage.tsx'), 'utf8')
  const segmentsSource = readFileSync(resolve('src/pages/segments/SegmentsPage.tsx'), 'utf8')
  const sceneMomentsSource = readFileSync(resolve('src/pages/scene-moments/SceneMomentsPage.tsx'), 'utf8')
  const overviewSource = readFileSync(resolve('src/pages/project/overview/ProjectOverviewPage.tsx'), 'utf8')
  const productionSource = readFileSync(resolve('src/pages/project/production/ProductionPage.tsx'), 'utf8')

  assert.match(workbenchSource, /generatedKeyframeCandidateTargetId/)
  assert.match(workbenchSource, /isGeneratedKeyframeCandidateRecord/)
  assert.match(workbenchSource, /isUnresolvedCandidateStatus/)
  assert.match(contentUnitsSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(segmentsSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(sceneMomentsSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(overviewSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(productionSource, /import \{ isGeneratedKeyframeCandidateRecord \} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(contentUnitsSource, /\(keyframesQuery\.data \?\? \[\]\)\.filter\(\(item\) => !isGeneratedKeyframeCandidateRecord\(item\)\)/)
  assert.match(segmentsSource, /\(keyframesQuery\.data \?\? \[\]\)\.filter\(\(item\) => !isGeneratedKeyframeCandidateRecord\(item\)\)/)
  assert.match(sceneMomentsSource, /\(keyframesQuery\.data \?\? \[\]\)\.filter\(\(item\) => !isGeneratedKeyframeCandidateRecord\(item\)\)/)
  assert.match(overviewSource, /keyframes: keyframes\.filter\(\(keyframe\) => !isGeneratedKeyframeCandidateRecord\(keyframe\)\)/)
  assert.match(overviewSource, /function assetSlotCandidateIsActive/)
  assert.match(overviewSource, /return status !== 'rejected' && status !== 'selected'/)
  assert.match(overviewSource, /const activeAssetSlotCandidates = data\.assetSlotCandidates\.filter\(assetSlotCandidateIsActive\)/)
  assert.match(overviewSource, /candidateAssets = statusCount\(data\.assetSlots, \['candidate'\]\) \+ activeAssetSlotCandidates\.length/)
  assert.match(productionSource, /function keyframesForProduction[\s\S]*!isGeneratedKeyframeCandidateRecord\(keyframe\)/)
  assert.match(workbenchSource, /const keyframesData = \(data\.keyframes \?\? \[\]\)\.filter\(\(keyframe\) => !isGeneratedKeyframeCandidateRecord\(keyframe\)\)/)
  assert.equal((workbenchSource.match(/!isGeneratedKeyframeCandidateRecord\(keyframe\)/g) ?? []).length >= 5, true)
  assert.match(workbenchSource, /function keyframesForWorkbenchProduction[\s\S]*!isGeneratedKeyframeCandidateRecord\(keyframe\)/)
  assert.match(workbenchSource, /function buildPreviewPlanSegments[\s\S]*const keyframesData = data\.keyframes\.filter\(\(keyframe\) => !isGeneratedKeyframeCandidateRecord\(keyframe\)\)/)
  assert.match(workbenchSource, /function buildPreviewAssetGaps[\s\S]*!isGeneratedKeyframeCandidateRecord\(keyframe\) && Number\(keyframe\.content_unit_id\) === unit\.ID/)
})

test('content workbench is the single exposed content orchestration entry', () => {
  const appSource = readFileSync(resolve('src/App.tsx'), 'utf8')
  const routeSource = readFileSync(resolve('src/routes/projectRoutes.ts'), 'utf8')
  const sidebarSource = readFileSync(resolve('src/components/layout/Sidebar.tsx'), 'utf8')
  const headerSource = readFileSync(resolve('src/components/layout/Header.tsx'), 'utf8')
  const semanticEntitiesSource = readFileSync(resolve('src/api/semanticEntities.ts'), 'utf8')
  const surfacesSource = readFileSync(resolve('src/pages/project/projectSurfaces.tsx'), 'utf8')
  const overviewSource = readFileSync(resolve('src/pages/project/overview/ProjectOverviewPage.tsx'), 'utf8')
  const productionSource = readFileSync(resolve('src/pages/project/production/ProductionPage.tsx'), 'utf8')
  const productionOrchestrationSource = readFileSync(resolve('src/pages/project/production/ProductionOrchestrationPage.tsx'), 'utf8')
  const contentUnitsSource = readFileSync(resolve('src/pages/project/content-units/ContentUnitsPage.tsx'), 'utf8')
  const deliveryWorkbenchSource = readFileSync(resolve('src/pages/project/delivery/DeliveryWorkbenchPage.tsx'), 'utf8')
  const segmentsSource = readFileSync(resolve('src/pages/segments/SegmentsPage.tsx'), 'utf8')
  const sceneMomentsSource = readFileSync(resolve('src/pages/scene-moments/SceneMomentsPage.tsx'), 'utf8')
  const referenceRelationsSource = readFileSync(resolve('src/pages/reference-relations/ReferenceRelationsPage.tsx'), 'utf8')
  const previewDrawerSource = readFileSync(resolve('src/components/preview/PreviewDrawer.tsx'), 'utf8')
  const canvasDomainCardSource = readFileSync(resolve('src/components/canvas/CanvasDomainEntityCard.tsx'), 'utf8')
  const semanticDialogSource = readFileSync(resolve('src/components/shared/SemanticEntityCrudDialog.tsx'), 'utf8')
  const semanticInlineEditorSource = readFileSync(resolve('src/components/shared/SemanticEntityInlineEditor.tsx'), 'utf8')
  const draftDomainSource = readFileSync(resolve('src/lib/draftDomainModel.ts'), 'utf8')
  const workbenchSource = readFileSync(resolve('src/pages/workbench/WorkbenchPage.tsx'), 'utf8')
  const zhSource = readFileSync(resolve('src/i18n/locales/zh-CN.json'), 'utf8')
  const enSource = readFileSync(resolve('src/i18n/locales/en-US.json'), 'utf8')
  const projectRoutesBlock = routeSource.match(/project: \{[\s\S]*?\n  \},/)?.[0] ?? ''
  const contentUnitsBottomSource = contentUnitsSource.slice(contentUnitsSource.indexOf('bottom={('))
  const contentUnitsMetricSource = contentUnitsSource.slice(contentUnitsSource.indexOf('function MetricCard'), contentUnitsSource.indexOf('function RelatedPanel'))

  assert.doesNotMatch(projectRoutesBlock, /productionPreview/)
  assert.doesNotMatch(routeSource, /productionPreview|workbenchProductionPlan|workbenchPreview|\/project\/production\/preview|\/workbench\/production-plan|\/workbench\/preview/)
  assert.doesNotMatch(appSource, /LegacyProductionPreviewRedirect|LEGACY_ROUTES\.productionPreview|LEGACY_ROUTES\.workbenchProductionPlan|LEGACY_ROUTES\.workbenchPreview|ROUTES\.project\.productionPreview/)
  assert.doesNotMatch(sidebarSource, /workbenchProductionPreview|ROUTES\.project\.productionPreview/)
  assert.doesNotMatch(headerSource, /workbenchPreview|workbenchProductionPlan|ROUTES\.project\.productionPreview/)
  assert.match(headerSource, /ROUTES\.project\.contentUnitWorkbench\]: 'header\.titles\.workbenchContentGeneration'/)
  assert.doesNotMatch(headerSource, /header\.titles\.workbenchProduction/)
  assert.doesNotMatch(semanticEntitiesSource, /内容单元|生成提示/)
  assert.match(semanticEntitiesSource, /情节和制作项稳定引用具体行/)
  assert.doesNotMatch(surfacesSource, /\| 'preview'|value: 'preview'|制作预演/)
  assert.match(surfacesSource, /title: '内容编排工作台'/)
  assert.match(surfacesSource, /title: '制作执行'/)
  assert.match(surfacesSource, /shortTitle: '执行'/)
  assert.doesNotMatch(surfacesSource, /title: '画面编排工作台'|可进入画面编排工作台验证/)
  assert.doesNotMatch(overviewSource, /focus: 'preview'|画面编排|检查预演挂载|制作预演|预演/)
  assert.match(overviewSource, /area: '内容编排'/)
  assert.match(overviewSource, /title: '检查预览挂载'/)
  assert.match(overviewSource, /预览与生产的最小颗粒/)
  assert.match(overviewSource, /title: '创作编排'[\s\S]{0,500}workbenchHref: ROUTES\.project\.productionOrchestration/)
  assert.match(overviewSource, /title: '制作执行'/)
  assert.match(overviewSource, /制作项可推进/)
  assert.match(overviewSource, /function nextLaneActionLabel/)
  assert.match(overviewSource, /if \(lane\.key === 'content'\) return '进入内容编排'/)
  assert.match(overviewSource, /<Link to=\{lane\.workbenchHref\}>\{nextLaneActionLabel\(lane\)\}<\/Link>/)
  assert.match(overviewSource, /title: '拆解或确认制作项'/)
  assert.match(overviewSource, /href: ROUTES\.project\.contentUnitWorkbench/)
  assert.match(overviewSource, /个可推进/)
  assert.match(overviewSource, /对象页管理事实源/)
  assert.match(overviewSource, /对象入口/)
  assert.doesNotMatch(overviewSource, /进入下一步|>进入处理<\/Link>/)
  assert.doesNotMatch(overviewSource, /生成或确认制作项|个可生产|href: ROUTES\.project\.contentUnits,[\s\S]{0,120}detail: '制作创建后/)
  assert.doesNotMatch(productionSource, /focus: 'preview'|项目预演|画面编排|制作预演|预演/)
  assert.match(productionSource, /内容编排/)
  assert.match(productionSource, /function productionContentWorkbenchHref/)
  assert.doesNotMatch(productionSource, /productionPlaybackHref/)
  assert.match(productionSource, /预览挂载/)
  assert.match(productionSource, /制作项准备情况/)
  assert.match(productionSource, /制作项结构/)
  assert.match(productionSource, /制作项结构由内容编排工作台统一拆解、检查和推进/)
  assert.match(productionSource, /进入内容编排拆解制作项/)
  assert.match(productionSource, /if \(action\.includes\('内容编排'\)\) return productionContentWorkbenchHref\(production\)/)
  assert.doesNotMatch(productionSource, /当前预览挂载|可从预览生成|直接开始制作项生成|内容准备情况|内容结构|内容候选/)
  assert.doesNotMatch(productionOrchestrationSource, /内容单元|生成提示/)
  assert.match(productionOrchestrationSource, /制作项 \$\{unitIndex \+ 1\}/)
  assert.match(productionOrchestrationSource, /下游制作项/)
  assert.doesNotMatch(productionOrchestrationSource, /下游内容/)
  assert.doesNotMatch(contentUnitsSource, /画面编排工作台|预演挂载|制作预演|>\s*预演\s*<|内容 #/)
  assert.match(contentUnitsSource, /进入内容编排工作台拆解制作项骨架/)
  assert.match(contentUnitsSource, /<span>生产对象<\/span>/)
  assert.match(contentUnitsSource, /拆解、关键帧、素材补齐和生成决策统一在内容编排工作台完成/)
  assert.match(contentUnitsSource, /进入内容编排/)
  assert.match(contentUnitsSource, /aria-label="刷新制作项"/)
  assert.doesNotMatch(contentUnitsSource, /关系图谱|ROUTES\.project\.referenceRelations|GitBranch/)
  assert.match(contentUnitsSource, /data-testid="content-units-summary-strip"/)
  assert.match(contentUnitsSource, /grid grid-cols-2 overflow-hidden rounded-md border border-border bg-card md:grid-cols-4/)
  assert.match(contentUnitsSource, /flex min-w-0 items-center gap-2 border-b border-r border-border px-3 py-2/)
  assert.doesNotMatch(contentUnitsSource, /grid grid-cols-4 gap-3/)
  assert.doesNotMatch(contentUnitsMetricSource, /text-2xl font-semibold tabular-nums|flex h-10 w-10 items-center/)
  assert.doesNotMatch(contentUnitsSource, /制作项是制作项|新建内容|制作项生成/)
  assert.match(contentUnitsSource, /buildContentWorkbenchRouteSearch\(\{[\s\S]{0,120}contentUnitId: item\.unit\.ID/)
  assert.match(contentUnitsSource, /进入编排/)
  assert.match(contentUnitsSource, /data-testid="content-unit-list-card"/)
  assert.match(contentUnitsSource, /rounded-md border bg-background px-3 py-2\.5 text-left transition-colors/)
  assert.doesNotMatch(contentUnitsSource, /border-b border-border bg-gradient-to-br from-indigo-500\/15 to-cyan-500\/10 p-3[\s\S]{0,600}line-clamp-2 min-h-10/)
  assert.match(contentUnitsSource, /compact: true/)
  assert.doesNotMatch(contentUnitsSource, /accentClassName: 'from-indigo-500\/15/)
  assert.match(semanticInlineEditorSource, /compact\?: boolean/)
  assert.match(semanticInlineEditorSource, /idScope\?: string/)
  assert.match(semanticInlineEditorSource, /const editorDomScope = idScope \?\? `\$\{config\.kind\}-\$\{record\?\.ID \?\? 'new'\}`/)
  assert.match(semanticInlineEditorSource, /const id = `semantic-inline-\$\{idScope \?\? configKind\}-\$\{field\.key\}`/)
  assert.match(semanticInlineEditorSource, /compactHero \? 'h-8 w-8 bg-muted text-muted-foreground'/)
  assert.doesNotMatch(contentUnitsSource, /<div className="border-b border-border bg-gradient-to-br/)
  assert.match(contentUnitsSource, /<div className="border-b border-border p-3">/)
  assert.match(contentUnitsSource, /flex h-8 w-8 items-center justify-center rounded-md bg-muted text-muted-foreground/)
  assert.doesNotMatch(contentUnitsSource, /InfoChip/)
  assert.match(contentUnitsSource, /data-testid="content-unit-detail-context"/)
  assert.match(contentUnitsSource, /详细上下文/)
  assert.match(contentUnitsSource, /grid grid-cols-1 gap-4 lg:grid-cols-3/)
  assert.match(contentUnitsBottomSource, /title="来源剧本块"/)
  assert.match(contentUnitsBottomSource, /title="涉及到的编排段"/)
  assert.match(contentUnitsBottomSource, /title="涉及的情景"/)
  assert.doesNotMatch(contentUnitsBottomSource, /title="涉及的设定资料"|title="涉及的素材需求"|title="关键帧"/)
  assert.doesNotMatch(contentUnitsSource, /api\.post\('\/canvases'|onOpenCanvas|openingCanvas|去生成|生成准备度|生成提示|生成工作台/)
  assert.doesNotMatch(deliveryWorkbenchSource, /预演|CU#|ContentUnit #/)
  assert.match(deliveryWorkbenchSource, /关联预览时间线/)
  assert.doesNotMatch(segmentsSource, /预演|内容 #|内容设计|生成提示|<span>内容区<\/span>/)
  assert.match(segmentsSource, /<span>生产对象<\/span>/)
  assert.match(segmentsSource, /情景与制作项设计/)
  assert.doesNotMatch(sceneMomentsSource, /预演|内容 #|内容设计|<span>内容区<\/span>/)
  assert.match(sceneMomentsSource, /<span>生产对象<\/span>/)
  assert.match(sceneMomentsSource, /制作项设计/)
  assert.doesNotMatch(referenceRelationsSource, /预演|<span>内容区<\/span>/)
  assert.match(referenceRelationsSource, /<span>生产对象<\/span>/)
  assert.doesNotMatch(previewDrawerSource, /预演/)
  assert.match(previewDrawerSource, /整集预览画面/)
  assert.doesNotMatch(canvasDomainCardSource, /预演/)
  assert.doesNotMatch(semanticDialogSource, /预演/)
  assert.match(draftDomainSource, /title: 'Production item proposal'/)
  assert.doesNotMatch(workbenchSource, /preview: \{|category === 'preview'|initialCategory === 'preview'|function ProductionPreviewWorkspace|loadProductionPreviewData|ProductionPreviewData|ForPreviewProduction/)
  assert.match(zhSource, /"workbenchContentGeneration": "内容编排"/)
  assert.match(zhSource, /"production": "制作"/)
  assert.match(zhSource, /"contentArea": "生产对象"/)
  assert.match(zhSource, /"content": "对象"/)
  assert.doesNotMatch(zhSource, /workbenchProduction"|workbenchProductionPreview|workbenchPreview|制作预演|内容单元提案|画面编排|"production": "内容制作"|"contentArea": "内容区"|"content": "内容"/)
  assert.match(enSource, /"workbenchContentGeneration": "Content Orchestration"/)
  assert.match(enSource, /"production": "Production"/)
  assert.match(enSource, /"contentArea": "Production Objects"/)
  assert.match(enSource, /"content": "Objects"/)
  assert.match(enSource, /"contentUnits": "Production Items"/)
  assert.match(enSource, /"contentUnit": "Production Item"/)
  assert.doesNotMatch(enSource, /workbenchProduction"|workbenchProductionPreview|workbenchPreview|Production Preview|Content unit proposal|Production Decisions|Content Units|Content Unit|"production": "Content Production"|"contentArea": "Content Area"|"content": "Content"/)
})
