import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('pre-production review only loads explicitly opened proposal drafts', () => {
  const source = readFileSync(resolve('src/pages/pre-production/PreProductionPage.tsx'), 'utf8')
  const launchSource = readFileSync(resolve('src/lib/preProductionAgentLaunch.ts'), 'utf8')
  const canvasLaunchSource = readFileSync(resolve('src/lib/preProductionCanvasLaunch.ts'), 'utf8')
  const dataControllerSource = readFileSync(resolve('src/lib/preProductionDataController.ts'), 'utf8')
  const assetRowsSource = readFileSync(resolve('src/lib/preProductionAssetRows.ts'), 'utf8')
  const assetWriteSource = readFileSync(resolve('src/lib/preProductionAssetCandidateWrite.ts'), 'utf8')
  const candidateControllerSource = readFileSync(resolve('src/lib/preProductionAssetCandidateController.ts'), 'utf8')
  const assetProposalControllerSource = readFileSync(resolve('src/lib/preProductionAssetProposalController.ts'), 'utf8')
  const auditControllerSource = readFileSync(resolve('src/lib/preProductionAuditController.ts'), 'utf8')
  const mediaControllerSource = readFileSync(resolve('src/lib/preProductionMediaCandidateController.ts'), 'utf8')
  const pageControllerSource = readFileSync(resolve('src/lib/preProductionPageController.ts'), 'utf8')
  const resourceLibrarySource = readFileSync(resolve('src/lib/preProductionResourceLibrary.ts'), 'utf8')
  const refreshControllerSource = readFileSync(resolve('src/lib/preProductionRefreshController.ts'), 'utf8')
  const reviewControllerSource = readFileSync(resolve('src/lib/preProductionReviewController.ts'), 'utf8')
  const uploadInputSource = readFileSync(resolve('src/lib/preProductionUploadInput.ts'), 'utf8')
  const reviewWorkspaceSource = readFileSync(resolve('src/components/workbench/PreProductionReviewWorkspace.tsx'), 'utf8')
  const assetBoardSource = readFileSync(resolve('src/components/workbench/PreProductionAssetBoard.tsx'), 'utf8')
  const assetDetailSource = readFileSync(resolve('src/components/workbench/PreProductionAssetDetail.tsx'), 'utf8')
  const resourceLibraryDialogSource = readFileSync(resolve('src/components/workbench/PreProductionResourceLibraryDialog.tsx'), 'utf8')

  assert.match(source, /usePreProductionReviewController\(\{ projectId, searchParams, setSearchParams \}\)/)
  assert.match(reviewControllerSource, /export async function loadPreProductionReviewDrafts/)
  assert.match(reviewControllerSource, /localAgentClient\.getDraft\(draftId\)/)
  assert.match(reviewControllerSource, /openedSettingDraftId/)
  assert.match(reviewControllerSource, /openedAssetProposalDraftId/)
  assert.match(reviewControllerSource, /queryKey: \['asset-proposal-drafts', projectId, openedAssetProposalDraftId, openedDraftId\]/)
  assert.match(reviewControllerSource, /queryKey: \['setting-proposal-drafts', projectId, openedSettingDraftId, openedDraftId\]/)
  assert.match(source, /buildPreProductionAssetProposalMutationOptions/)
  assert.match(source, /runPreProductionMediaCandidateGeneration/)
  assert.match(source, /runPreProductionAudit/)
  assert.match(source, /buildPreProductionAssetSlotCanvasMutationOptions/)
  assert.match(source, /refreshPreProductionWorkbenchContext/)
  assert.match(source, /usePreProductionWorkbenchData\(projectId\)/)
  assert.match(source, /buildUpdatePreProductionAssetSlotMutationOptions/)
  assert.match(source, /buildCreatePreProductionAssetSlotMutationOptions/)
  assert.match(source, /usePreProductionUploadInput/)
  assert.match(source, /<PreProductionReviewWorkspace/)
  assert.match(source, /buildPreProductionLockCandidateMutationOptions/)
  assert.match(source, /buildPreProductionRejectCandidateMutationOptions/)
  assert.match(source, /buildPreProductionAddCandidateMutationOptions/)
  assert.match(source, /buildPreProductionAttachLibraryCandidateMutationOptions/)
  assert.match(source, /buildPreProductionUploadCandidateMutationOptions/)
  assert.match(source, /usePreProductionPageController\(\{/)
  assert.match(source, /usePreProductionResourceLibrary\(\)/)
  assert.match(source, /<PreProductionAssetBoard/)
  assert.match(source, /<PreProductionResourceLibraryDialog/)
  assert.match(launchSource, /export function buildAssetCandidateProposalReviewSearchParams/)
  assert.match(launchSource, /export function buildPreProductionAuditReviewSearchParams/)
  assert.match(launchSource, /export function buildMediaCandidateGenerationAgentPanelDraftPayload/)
  assert.match(launchSource, /export function getMediaCandidateGenerationResult/)
  assert.match(launchSource, /mergeProjectWorkbenchArtifactReviewSearchParams/)
  assert.match(canvasLaunchSource, /export function buildPreProductionAssetSlotCanvasPayload/)
  assert.match(canvasLaunchSource, /export async function createPreProductionAssetSlotCanvas/)
  assert.match(canvasLaunchSource, /export function preProductionCanvasRoute/)
  assert.match(canvasLaunchSource, /export function buildPreProductionAssetSlotCanvasMutationOptions/)
  assert.match(dataControllerSource, /export function usePreProductionWorkbenchData/)
  assert.match(dataControllerSource, /export function buildUpdatePreProductionAssetSlotMutationOptions/)
  assert.match(dataControllerSource, /export function buildCreatePreProductionAssetSlotMutationOptions/)
  assert.match(dataControllerSource, /listSemanticEntities\(projectId!, referenceConfig\)/)
  assert.match(dataControllerSource, /buildPreProductionAssetRows/)
  assert.match(dataControllerSource, /buildReferenceAssetClusters/)
  assert.match(dataControllerSource, /buildPreProductionAssetSlotCreatePayload/)
  assert.match(dataControllerSource, /createSemanticEntity/)
  assert.match(dataControllerSource, /updateSemanticEntity/)
  assert.match(dataControllerSource, /preProductionAssetSlotsQueryKey/)
  assert.match(assetRowsSource, /export function buildPreProductionAssetRows/)
  assert.match(assetRowsSource, /export function buildReferenceAssetClusters/)
  assert.match(assetRowsSource, /export function buildAssetCandidatePatchPayload/)
  assert.match(assetRowsSource, /export function assetSlotHasLoadedResource/)
  assert.match(assetRowsSource, /export function candidateReferenceResourceIds/)
  assert.match(assetWriteSource, /export function buildPreProductionAssetSlotCreatePayload/)
  assert.match(assetWriteSource, /export function buildPreProductionLibraryCandidatePayload/)
  assert.match(assetWriteSource, /export function buildPreProductionUploadCandidatePayload/)
  assert.match(assetWriteSource, /export function buildPreProductionGeneratedCandidatePayload/)
  assert.match(assetWriteSource, /export function preProductionResourceLibraryPageCount/)
  assert.match(assetWriteSource, /export const initialPreProductionResourceLibraryState/)
  assert.match(assetWriteSource, /export function openPreProductionResourceLibraryState/)
  assert.match(assetWriteSource, /export function setPreProductionResourceLibrarySearch/)
  assert.match(candidateControllerSource, /export function buildPreProductionLockCandidateMutationOptions/)
  assert.match(candidateControllerSource, /export function buildPreProductionRejectCandidateMutationOptions/)
  assert.match(candidateControllerSource, /export function buildPreProductionAddCandidateMutationOptions/)
  assert.match(candidateControllerSource, /export function buildPreProductionAttachLibraryCandidateMutationOptions/)
  assert.match(candidateControllerSource, /export function buildPreProductionUploadCandidateMutationOptions/)
  assert.match(candidateControllerSource, /invalidateAssetCandidateConsumers/)
  assert.match(candidateControllerSource, /api\.patch/)
  assert.match(candidateControllerSource, /api\.post/)
  assert.match(assetProposalControllerSource, /export function buildPreProductionAssetProposalMutationOptions/)
  assert.match(assetProposalControllerSource, /createAssetCandidateProposalDraft/)
  assert.match(assetProposalControllerSource, /launchAssetCandidateProposalAgent/)
  assert.match(assetProposalControllerSource, /candidateReferenceResourceIds/)
  assert.match(assetProposalControllerSource, /buildAssetCandidateProposalReviewSearchParams/)
  assert.match(auditControllerSource, /export function runPreProductionAudit/)
  assert.match(auditControllerSource, /launchPreProductionAuditAgent/)
  assert.match(auditControllerSource, /buildPreProductionAuditReviewSearchParams/)
  assert.match(auditControllerSource, /pre_production_audit/)
  assert.match(mediaControllerSource, /export function runPreProductionMediaCandidateGeneration/)
  assert.match(mediaControllerSource, /launchMediaCandidateGenerationAgent/)
  assert.match(mediaControllerSource, /buildPreProductionGeneratedCandidatePayload/)
  assert.match(pageControllerSource, /export function usePreProductionPageController/)
  assert.match(pageControllerSource, /export function resolvePreProductionPageSelection/)
  assert.match(pageControllerSource, /export function buildPreProductionFilterParams/)
  assert.match(pageControllerSource, /readNumberParam\(searchParams, 'asset_slot_id'\)/)
  assert.match(pageControllerSource, /setNewSlotEditId/)
  assert.match(pageControllerSource, /setNewReferenceEditKey/)
  assert.match(pageControllerSource, /updateContentFilterParams/)
  assert.match(resourceLibrarySource, /export function usePreProductionResourceLibrary/)
  assert.match(resourceLibrarySource, /export function buildPreProductionResourceLibraryQueryKey/)
  assert.match(resourceLibrarySource, /export function buildPreProductionResourceLibraryParams/)
  assert.match(resourceLibrarySource, /api\.get\('\/resources'/)
  assert.match(resourceLibrarySource, /preProductionResourceLibraryPageCount/)
  assert.match(resourceLibrarySource, /preProductionResourceLibraryTotal/)
  assert.match(resourceLibrarySource, /setPreProductionResourceLibrarySearch/)
  assert.match(resourceLibrarySource, /setPreProductionResourceLibraryType/)
  assert.match(refreshControllerSource, /export async function refreshPreProductionWorkbenchContext/)
  assert.match(refreshControllerSource, /'pre-production-creative-references'/)
  assert.match(refreshControllerSource, /'semantic-asset-slots-page'/)
  assert.match(refreshControllerSource, /'semantic-asset-slot-candidates-page'/)
  assert.match(uploadInputSource, /export function usePreProductionUploadInput/)
  assert.match(uploadInputSource, /triggerUpload/)
  assert.match(uploadInputSource, /resetUpload/)
  assert.match(reviewWorkspaceSource, /ProjectLayerProposalReviewPanel/)
  assert.match(reviewWorkspaceSource, /kind="setting_proposal"/)
  assert.match(reviewWorkspaceSource, /kind="asset_proposal"/)
  assert.match(assetBoardSource, /export function PreProductionAssetBoard/)
  assert.match(assetBoardSource, /export function SlotThumb/)
  assert.match(assetBoardSource, /export function SlotStatusBadge/)
  assert.match(assetBoardSource, /WorkbenchEntityCard/)
  assert.match(assetBoardSource, /assetKindOrder/)
  assert.match(assetDetailSource, /export function AssetSlotDetail/)
  assert.match(assetDetailSource, /function CandidateRow/)
  assert.match(assetDetailSource, /assetSlotHasLoadedResource/)
  assert.match(assetDetailSource, /SlotThumb/)
  assert.match(resourceLibraryDialogSource, /export function PreProductionResourceLibraryDialog/)
  assert.match(resourceLibraryDialogSource, /ResourceLibraryPicker/)
  assert.match(resourceLibraryDialogSource, /assetKindLabel/)
  assert.doesNotMatch(source, /api\.post\('\/canvases'/)
  assert.doesNotMatch(source, /navigate\(`\/canvases\/\$\{canvas\.ID\}`\)/)
  assert.doesNotMatch(source, /createPreProductionAssetSlotCanvas/)
  assert.doesNotMatch(source, /preProductionCanvasRoute/)
  assert.doesNotMatch(source, /function buildRows/)
  assert.doesNotMatch(source, /listSemanticEntities\(projectId!/)
  assert.doesNotMatch(source, /createSemanticEntity\(projectId/)
  assert.doesNotMatch(source, /updateSemanticEntity\(projectId!/)
  assert.doesNotMatch(source, /buildPreProductionAssetSlotCreatePayload/)
  assert.doesNotMatch(source, /buildPreProductionAssetRows\(visibleSlots/)
  assert.doesNotMatch(source, /buildReferenceAssetClusters\(creativeReferences/)
  assert.doesNotMatch(source, /function candidatePatchPayload/)
  assert.doesNotMatch(source, /function buildReferenceAssetClusters/)
  assert.doesNotMatch(source, /function candidateReferenceResourceIds/)
  assert.doesNotMatch(source, /function assetSlotHasLoadedResource/)
  assert.doesNotMatch(source, /function defaultResourceTypeForAssetKind/)
  assert.doesNotMatch(source, /function runMediaCandidateGeneration/)
  assert.doesNotMatch(source, /function PreProductionAssetBoard/)
  assert.doesNotMatch(source, /function ReferenceClusterButton/)
  assert.doesNotMatch(source, /function ReferenceAssetTile/)
  assert.doesNotMatch(source, /function AssetSlotDetail/)
  assert.doesNotMatch(source, /function CandidateRow/)
  assert.doesNotMatch(source, /function AssetResourceLibraryDialog/)
  assert.doesNotMatch(source, /from '@\/components\/shared\/ResourceLibraryPicker'/)
  assert.doesNotMatch(source, /<ResourceLibraryPicker/)
  assert.doesNotMatch(source, /uploadInputRef/)
  assert.doesNotMatch(source, /const \[uploading, setUploading\]/)
  assert.doesNotMatch(source, /api\.(patch|post)\(/)
  assert.doesNotMatch(source, /api\.get\('\/resources'/)
  assert.doesNotMatch(source, /invalidateAssetCandidateConsumers/)
  assert.doesNotMatch(source, /preProductionResourceLibraryPageCount/)
  assert.doesNotMatch(source, /initialPreProductionResourceLibraryState/)
  assert.doesNotMatch(source, /setPreProductionResourceLibrarySearch/)
  assert.doesNotMatch(source, /setPreProductionResourceLibraryType/)
  assert.doesNotMatch(source, /readNumberParam\(searchParams, 'asset_slot_id'\)/)
  assert.doesNotMatch(source, /readStringParam\(searchParams, 'kind'\)/)
  assert.doesNotMatch(source, /updateContentFilterParams\(searchParams/)
  assert.doesNotMatch(source, /const \[newSlotEditId, setNewSlotEditId\]/)
  assert.doesNotMatch(source, /const \[newReferenceEditKey, setNewReferenceEditKey\]/)
  assert.doesNotMatch(source, /useState\(false\)[\s\S]{0,200}useState\(''\)[\s\S]{0,200}useState<ResourceTypeFilter>\('all'\)/)
  assert.doesNotMatch(source, /note: `从资源库选择/)
  assert.doesNotMatch(source, /note: `手动上传候选/)
  assert.doesNotMatch(source, /selectLatestDraftArtifact/)
  assert.doesNotMatch(source, /selectLatestGeneratedResource/)
  assert.doesNotMatch(source, /buildEmptyAssetProposalDraftContent/)
  assert.doesNotMatch(source, /buildCommandFirstClientInput/)
  assert.doesNotMatch(source, /openAgentPanelDraft/)
  assert.doesNotMatch(source, /registerAgentPanelPageTool/)
  assert.doesNotMatch(source, /taskType: 'pre_production_audit'/)
  assert.doesNotMatch(source, /launchPreProductionAuditAgent/)
  assert.doesNotMatch(source, /buildPreProductionAuditReviewSearchParams/)
  assert.doesNotMatch(source, /taskType: 'asset_candidate_proposal'/)
  assert.doesNotMatch(source, /createAssetCandidateProposalDraft/)
  assert.doesNotMatch(source, /launchAssetCandidateProposalAgent/)
  assert.doesNotMatch(source, /buildAssetCandidateProposalReviewSearchParams/)
  assert.doesNotMatch(source, /taskType: 'asset_candidate_generation'/)
  assert.doesNotMatch(source, /localAgentClient\.listDrafts\(\{ projectId, kind: 'setting_proposal'/)
  assert.doesNotMatch(source, /localAgentClient\.listDrafts\(\{ projectId, kind: 'asset_proposal'/)
  assert.doesNotMatch(source, /function loadPreProductionReviewDrafts/)
  assert.doesNotMatch(source, /localAgentClient\.getDraft\(draftId\)/)
  assert.doesNotMatch(source, /openedSettingDraftId/)
  assert.doesNotMatch(source, /openedAssetProposalDraftId/)
})

test('pre-production proposal panel does not link to historical draft inventory', () => {
  const source = readFileSync(resolve('src/components/proposals/ProjectLayerProposalReviewPanel.tsx'), 'utf8')

  assert.doesNotMatch(source, /查看全部 AI 草稿/)
  assert.doesNotMatch(source, /href="\/agent\/drafts"/)
  assert.doesNotMatch(source, /FileText/)
})

test('pre-production detail editors use one inspector with asset/reference modes', () => {
  const source = readFileSync(resolve('src/pages/pre-production/PreProductionPage.tsx'), 'utf8')
  const editorSource = readFileSync(resolve('src/components/shared/SemanticEntityInlineEditor.tsx'), 'utf8')

  assert.match(editorSource, /collapsedMode\?: 'vertical' \| 'horizontal'/)
  assert.match(editorSource, /data-inline-editor-collapsed-mode="horizontal"/)
  assert.match(source, /type InspectorMode = 'asset' \| 'reference'/)
  assert.match(source, /function PreProductionInspector/)
  assert.match(source, /const \[inspectorMode, setInspectorMode\] = useState<InspectorMode>\('reference'\)/)
  assert.match(source, /onModeChange=\{setInspectorMode\}/)
  assert.match(source, /const detailOpen = Boolean\(selected \|\| selectedReference \|\| newReferenceEditKey\)/)
  assert.match(source, /detailOpen \? 'xl:grid-cols-\[minmax\(0,1fr\)_420px\] 2xl:grid-cols-\[minmax\(0,1fr\)_440px\]' : ''/)
  assert.match(source, /variant=\{mode === 'asset' \? 'secondary' : 'ghost'\}/)
  assert.match(source, /variant=\{mode === 'reference' \? 'secondary' : 'ghost'\}/)
  assert.match(source, /<AssetSlotDetail\s+row=\{selected\}/)
  assert.match(source, /hideHeaderActions/)
  assert.match(source, /hideDeleteAction/)
  assert.match(source, /hiddenFieldKeys=\{\['status'\]\}/)
  assert.match(source, /showAdvancedFields=\{false\}/)
  assert.match(source, /openAssetCreateDialog/)
  assert.match(source, /素材必须先归属到一个设定/)
  assert.doesNotMatch(source, /const detailRailCollapsed = referenceEditorCollapsed && assetEditorCollapsed/)
  assert.doesNotMatch(source, /data-detail-rail-collapsed/)
  assert.doesNotMatch(source, /collapsedMode="horizontal"/)
  assert.doesNotMatch(source, /fixed right-0 top-0/)
})
