import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('pre-production candidate lock keeps slot and candidate statuses in sync', () => {
  const source = readFileSync(resolve('src/pages/pre-production/PreProductionPage.tsx'), 'utf8')
  const candidateControllerSource = readFileSync(resolve('src/lib/preProductionAssetCandidateController.ts'), 'utf8')
  const mediaCandidateControllerSource = readFileSync(resolve('src/lib/preProductionMediaCandidateController.ts'), 'utf8')
  const assetRowsSource = readFileSync(resolve('src/lib/preProductionAssetRows.ts'), 'utf8')
  const assetDetailSource = readFileSync(resolve('src/components/workbench/PreProductionAssetDetail.tsx'), 'utf8')
  const agentLaunchSource = readFileSync(resolve('src/lib/preProductionAgentLaunch.ts'), 'utf8')
  const invalidationSource = readFileSync(resolve('src/lib/assetCandidateQueryInvalidation.ts'), 'utf8')

  assert.match(source, /buildPreProductionLockCandidateMutationOptions\(\{ projectId, queryClient \}\)/)
  assert.match(source, /buildPreProductionRejectCandidateMutationOptions\(\{ projectId, queryClient \}\)/)
  assert.match(candidateControllerSource, /entities\/asset-slot-candidates\/\$\{candidate\.ID\}/)
  assert.match(candidateControllerSource, /buildAssetCandidatePatchPayload\(row\.slot\.ID,\s*candidate,\s*'selected'\)/)
  assert.match(candidateControllerSource, /buildAssetCandidatePatchPayload\(row\.slot\.ID,\s*candidate,\s*'rejected'\)/)
  assert.match(candidateControllerSource, /if \(!assetSlotHasLoadedResource\(candidate\.candidate_asset_slot\)\) throw new Error\('候选资源不存在或未加载'\)/)
  assert.match(assetRowsSource, /export function assetSlotHasLoadedResource/)
  assert.match(assetRowsSource, /Boolean\(slot\?\.resource\?\.ID\)/)
  assert.match(assetDetailSource, /候选资源不存在或未加载，暂不能锁定。/)
  assert.match(assetDetailSource, /canLock \? '锁定此候选' : '缺资源'/)
  assert.match(source, /const rejectCandidateMutation = useMutation/)
  assert.match(candidateControllerSource, /toast\.success\('素材候选已拒绝'\)/)
  assert.match(assetDetailSource, /onReject=\{\(\) => onReject\(candidate\)\}/)
  assert.match(assetRowsSource, /candidate\.asset_slot_id === slot\.ID && candidate\.status !== 'rejected'/)
  assert.match(assetRowsSource, /if \(rowHasActiveAssetCandidates\(row\)\) cluster\.candidate \+= 1/)
  assert.match(assetRowsSource, /return row\.candidates\.some\(\(candidate\) => candidate\.status !== 'selected'\)/)
  assert.match(mediaCandidateControllerSource, /const outputResourceIds = mediaCandidateOutputResourceIds\(generated\)/)
  assert.match(mediaCandidateControllerSource, /outputResourceIds\.map\(\(outputResourceId\) =>/)
  assert.match(mediaCandidateControllerSource, /options\.addCandidateMutation\.mutateAsync/)
  assert.match(mediaCandidateControllerSource, /Promise\.allSettled/)
  assert.match(mediaCandidateControllerSource, /const successCount = results\.filter/)
  assert.match(mediaCandidateControllerSource, /toast\.info\(`已加入 \$\{successCount\} 个候选，\$\{failedCount\} 个失败`\)/)
  assert.match(mediaCandidateControllerSource, /已加入 \$\{outputResourceIds\.length\} 个/)
  assert.match(agentLaunchSource, /如果得到一个或多个 output_resource_id，请逐个加入候选集并逐项报告写入结果/)
  assert.doesNotMatch(source, /locked_asset_slot_id:\s*candidate\.candidate_asset_slot_id/)
  assert.doesNotMatch(source, /item\.ID === candidate\.ID \? 'selected' : 'rejected'/)
  assert.match(assetRowsSource, /export function buildAssetCandidatePatchPayload/)
  assert.match(assetRowsSource, /status,\s*\.\.\.\(candidate\.source_type/)
  assert.match(candidateControllerSource, /invalidateAssetCandidateConsumers\(queryClient,\s*projectId\)/)
  assert.match(invalidationSource, /'semantic-asset-slot-candidates-page'/)
  assert.match(invalidationSource, /'project-overview'/)
})
