import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('task creation selects asset slot candidates from the current target instead of manual ids', () => {
  const source = readFileSync(resolve('src/pages/project/tasks/TasksPage.tsx'), 'utf8')

  assert.match(source, /semanticEntityConfig\('assetSlotCandidates'\)/)
  assert.match(source, /function candidateOptionsForAssetSlot/)
  assert.match(source, /numericField\(candidate,\s*'asset_slot_id'\) === assetSlotId/)
  assert.match(source, /import \{[\s\S]*isUnresolvedCandidateStatus[\s\S]*\} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(source, /isUnresolvedCandidateStatus\(candidate\.status\)/)
  assert.match(source, /function assetSlotCandidateHasResource/)
  assert.match(source, /recordField\(candidate,\s*'candidate_asset_slot'\)/)
  assert.match(source, /function recordHasLoadedResource/)
  assert.match(source, /recordField\(record,\s*'resource'\)/)
  assert.match(source, /candidateSlot \? recordHasLoadedResource\(candidateSlot\) : recordHasLoadedResource\(candidate\)/)
  assert.match(source, /const matchedAssetCandidate = candidateOptions\.find/)
  assert.match(source, /const requestedAssetCandidateUnavailable = resultType === 'lock_asset_candidate'/)
  assert.match(source, /&& candidateID === String\(initialDraft\.candidateId\)/)
  assert.match(source, /const selectedCandidate = requestedAssetCandidateUnavailable[\s\S]*\? undefined[\s\S]*: matchedAssetCandidate \?\? candidateOptions\[0\]/)
  assert.match(source, /if \(requestedAssetCandidateUnavailable\) return/)
  assert.match(source, /&& !requestedAssetCandidateUnavailable/)
  assert.match(source, /指定素材候选缺少资源或已不可采纳/)
  assert.match(source, /requestedAssetCandidateUnavailable && <option value="">指定候选不可采纳<\/option>/)
  assert.match(source, /JSON\.stringify\(\{\s*asset_slot_candidate_id: selectedCandidate\.ID\s*\}\)/)
  assert.match(source, /<select[\s\S]*value=\{selectedCandidate \? String\(selectedCandidate\.ID\) : ''\}/)
  assert.match(source, /当前素材需求暂无可采纳候选/)
  assert.doesNotMatch(source, /placeholder="输入 asset_slot_candidate_id"/)
  assert.doesNotMatch(source, /optionalPositiveID\(candidateID\)/)
})

test('task creation can select keyframe candidates from the current target', () => {
  const source = readFileSync(resolve('src/pages/project/tasks/TasksPage.tsx'), 'utf8')

  assert.match(source, /useSearchParams/)
  assert.match(source, /function taskCreateInitialDraftFromSearch\(params: URLSearchParams\)/)
  assert.match(source, /params\.get\('create'\) !== '1'/)
  assert.match(source, /params\.get\('purpose'\)/)
  assert.match(source, /params\.get\('target_type'\)/)
  assert.match(source, /params\.get\('target_id'\)/)
  assert.match(source, /params\.get\('candidate_id'\)/)
  assert.match(source, /initialDraft\?: TaskCreateDialogInitialDraft/)
  assert.match(source, /setCandidateID\(initialDraft\?\.candidateId \? String\(initialDraft\.candidateId\) : ''\)/)
  assert.match(source, /function keyframeCandidateOptionsForTarget/)
  assert.match(source, /generatedKeyframeCandidateTargetId\(keyframe\) === targetKeyframeId/)
  assert.match(source, /isUnresolvedCandidateStatus\(keyframe\.status\)/)
  assert.match(source, /recordHasLoadedResource\(keyframe\)/)
  assert.match(source, /const matchedKeyframeCandidate = keyframeCandidateOptions\.find/)
  assert.match(source, /const requestedKeyframeCandidateUnavailable = resultType === 'accept_keyframe'/)
  assert.match(source, /&& candidateID === String\(initialDraft\.candidateId\)/)
  assert.match(source, /const selectedKeyframeCandidate = requestedKeyframeCandidateUnavailable[\s\S]*\? undefined[\s\S]*: matchedKeyframeCandidate \?\? keyframeCandidateOptions\[0\]/)
  assert.match(source, /if \(requestedKeyframeCandidateUnavailable\) return/)
  assert.match(source, /&& !requestedKeyframeCandidateUnavailable/)
  assert.match(source, /指定候选缺少资源或已不可采纳/)
  assert.match(source, /重新选择一个可采纳候选/)
  assert.match(source, /requestedKeyframeCandidateUnavailable && <option value="">指定候选不可采纳<\/option>/)
  assert.match(source, /JSON\.stringify\(\{\s*keyframe_candidate_id: selectedKeyframeCandidate\.ID\s*\}\)/)
  assert.match(source, /<select[\s\S]*value=\{selectedKeyframeCandidate \? String\(selectedKeyframeCandidate\.ID\) : ''\}/)
  assert.match(source, /!isGeneratedKeyframeCandidateRecord\(record\)/)
  assert.match(source, /当前画面锚点暂无 AI 候选/)
  assert.match(source, /采纳候选画面锚点，或直接将当前画面锚点状态变为 accepted/)
  assert.match(source, /通过后系统会采纳候选画面锚点，并把候选资源同步到目标画面锚点。/)
})

test('task approval refreshes candidate consumers after candidate locking results', () => {
  const source = readFileSync(resolve('src/pages/project/tasks/TasksPage.tsx'), 'utf8')
  const invalidationSource = readFileSync(resolve('src/lib/assetCandidateQueryInvalidation.ts'), 'utf8')

  assert.match(source, /variables\.task\.resultType === 'lock_asset_candidate'/)
  assert.match(source, /variables\.task\.resultType === 'accept_keyframe'/)
  assert.match(source, /invalidateAssetCandidateConsumers\(qc,\s*projectId\)/)
  assert.match(invalidationSource, /'work-targets', projectId, 'asset-slots'/)
  assert.match(invalidationSource, /'work-targets', projectId, 'asset-slot-candidates'/)
  assert.match(invalidationSource, /'work-targets', projectId, 'keyframes'/)
  assert.match(invalidationSource, /'semantic-keyframes-page'/)
  assert.match(invalidationSource, /'semantic-asset-slot-candidates-page'/)
  assert.match(invalidationSource, /'semantic-candidate-decisions-page'/)
  assert.match(invalidationSource, /'semantic-review-events-page'/)
  assert.match(invalidationSource, /'project-overview'/)
  assert.match(invalidationSource, /'project-workspace'/)
})
