import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('task creation selects asset slot candidates from the current target instead of manual ids', () => {
  const source = readFileSync(resolve('src/pages/project/tasks/TasksPage.tsx'), 'utf8')

  assert.match(source, /semanticEntityConfig\('assetSlotCandidates'\)/)
  assert.match(source, /function candidateOptionsForAssetSlot/)
  assert.match(source, /numericField\(candidate,\s*'asset_slot_id'\) === assetSlotId/)
  assert.match(source, /import \{[\s\S]*isUnresolvedCandidateStatus[\s\S]*\} from '@\/lib\/agentGeneratedResourceBinding'/)
  assert.match(source, /isUnresolvedCandidateStatus\(candidate\.status\)/)
  assert.match(source, /function assetSlotCandidateHasResource/)
  assert.match(source, /recordField\(candidate,\s*'candidate_asset_slot'\)/)
  assert.match(source, /function recordHasLoadedResource/)
  assert.match(source, /recordField\(record,\s*'resource'\)/)
  assert.match(source, /candidateSlot \? recordHasLoadedResource\(candidateSlot\) : recordHasLoadedResource\(candidate\)/)
  assert.match(source, /const matchedAssetCandidate = candidateOptions\.find/)
  assert.match(source, /const requestedAssetCandidateUnavailable = resultType === 'lock_asset_candidate'/)
  assert.match(source, /&& candidateID === String\(initialDraft\.candidateId\)/)
  assert.match(source, /const selectedCandidate = requestedAssetCandidateUnavailable[\s\S]*\? undefined[\s\S]*: matchedAssetCandidate \?\? candidateOptions\[0\]/)
  assert.match(source, /if \(requestedAssetCandidateUnavailable\) return/)
  assert.match(source, /&& !requestedAssetCandidateUnavailable/)
  assert.match(source, /指定素材候选缺少资源或已不可采纳/)
  assert.match(source, /requestedAssetCandidateUnavailable && <option value="">指定候选不可采纳<\/option>/)
  assert.match(source, /JSON\.stringify\(\{\s*asset_slot_candidate_id: selectedCandidate\.ID\s*\}\)/)
  assert.match(source, /<select[\s\S]*value=\{selectedCandidate \? String\(selectedCandidate\.ID\) : ''\}/)
  assert.match(source, /当前素材需求暂无可采纳候选/)
  assert.doesNotMatch(source, /placeholder="输入 asset_slot_candidate_id"/)
  assert.doesNotMatch(source, /optionalPositiveID\(candidateID\)/)
})

test('task creation can select keyframe candidates from the current target', () => {
  const source = readFileSync(resolve('src/pages/project/tasks/TasksPage.tsx'), 'utf8')

  assert.match(source, /useSearchParams/)
  assert.match(source, /function taskCreateInitialDraftFromSearch\(params: URLSearchParams\)/)
  assert.match(source, /params\.get\('create'\) !== '1'/)
  assert.match(source, /params\.get\('purpose'\)/)
  assert.match(source, /params\.get\('target_type'\)/)
  assert.match(source, /params\.get\('target_id'\)/)
  assert.match(source, /params\.get\('candidate_id'\)/)
  assert.match(source, /initialDraft\?: TaskCreateDialogInitialDraft/)
  assert.match(source, /setCandidateID\(initialDraft\?\.candidateId \? String\(initialDraft\.candidateId\) : ''\)/)
  assert.match(source, /function keyframeCandidateOptionsForTarget/)
  assert.match(source, /generatedKeyframeCandidateTargetId\(keyframe\) === targetKeyframeId/)
  assert.match(source, /isUnresolvedCandidateStatus\(keyframe\.status\)/)
  assert.match(source, /recordHasLoadedResource\(keyframe\)/)
  assert.match(source, /const matchedKeyframeCandidate = keyframeCandidateOptions\.find/)
  assert.match(source, /const requestedKeyframeCandidateUnavailable = resultType === 'accept_keyframe'/)
  assert.match(source, /&& candidateID === String\(initialDraft\.candidateId\)/)
  assert.match(source, /const selectedKeyframeCandidate = requestedKeyframeCandidateUnavailable[\s\S]*\? undefined[\s\S]*: matchedKeyframeCandidate \?\? keyframeCandidateOptions\[0\]/)
  assert.match(source, /if \(requestedKeyframeCandidateUnavailable\) return/)
  assert.match(source, /&& !requestedKeyframeCandidateUnavailable/)
  assert.match(source, /指定候选缺少资源或已不可采纳/)
  assert.match(source, /重新选择一个可采纳候选/)
  assert.match(source, /requestedKeyframeCandidateUnavailable && <option value="">指定候选不可采纳<\/option>/)
  assert.match(source, /JSON\.stringify\(\{\s*keyframe_candidate_id: selectedKeyframeCandidate\.ID\s*\}\)/)
  assert.match(source, /<select[\s\S]*value=\{selectedKeyframeCandidate \? String\(selectedKeyframeCandidate\.ID\) : ''\}/)
  assert.match(source, /!isGeneratedKeyframeCandidateRecord\(record\)/)
  assert.match(source, /当前画面锚点暂无 AI 候选/)
  assert.match(source, /采纳候选画面锚点，或直接将当前画面锚点状态变为 accepted/)
  assert.match(source, /通过后系统会采纳候选画面锚点，并把候选资源同步到目标画面锚点。/)
})

test('task approval refreshes candidate consumers after candidate locking results', () => {
  const source = readFileSync(resolve('src/pages/project/tasks/TasksPage.tsx'), 'utf8')
  const invalidationSource = readFileSync(resolve('src/lib/assetCandidateQueryInvalidation.ts'), 'utf8')

  assert.match(source, /variables\.task\.resultType === 'lock_asset_candidate'/)
  assert.match(source, /variables\.task\.resultType === 'accept_keyframe'/)
  assert.match(source, /invalidateAssetCandidateConsumers\(qc,\s*projectId\)/)
  assert.match(invalidationSource, /'work-targets', projectId, 'asset-slots'/)
  assert.match(invalidationSource, /'work-targets', projectId, 'asset-slot-candidates'/)
  assert.match(invalidationSource, /'work-targets', projectId, 'keyframes'/)
  assert.match(invalidationSource, /'semantic-keyframes-page'/)
  assert.match(invalidationSource, /'semantic-asset-slot-candidates-page'/)
  assert.match(invalidationSource, /'semantic-candidate-decisions-page'/)
  assert.match(invalidationSource, /'semantic-review-events-page'/)
  assert.match(invalidationSource, /'project-overview'/)
  assert.match(invalidationSource, /'project-workspace'/)
})

test('task detail can publish work items into the agent panel and reopen the linked conversation', () => {
  const source = readFileSync(resolve('src/pages/project/tasks/TasksPage.tsx'), 'utf8')
  const bridgeSource = readFileSync(resolve('src/lib/agentPanelBridge.ts'), 'utf8')
  const panelSource = readFileSync(resolve('src/components/layout/AIAgentPanel.tsx'), 'utf8')
  const builtinChatShellSource = readFileSync(resolve('src/components/agent/AgentBuiltinChatShell.tsx'), 'utf8')
  const builtinChatControllerSource = readFileSync(resolve('src/components/agent/useAgentBuiltinChatController.ts'), 'utf8')

  assert.match(source, /openAgentPanelDraft/)
  assert.match(source, /openAgentPanelThread/)
  assert.match(source, /registerAgentPanelPageTool/)
  assert.match(source, /function publishTaskToAgent\(task: ProjectTask,\s*preferredAgentKey\?: TaskAgentKey\)/)
  assert.match(source, /agent_request_id/)
  assert.match(source, /agent_key/)
  assert.match(source, /agent_name/)
  assert.match(source, /agent_thread_id/)
  assert.match(source, /agent_run_id/)
  assert.match(source, /agent_status/)
  assert.match(source, /function agentRequestCanRetry\(status\?: string\)/)
  assert.match(source, /task\.metadata\.agent_request_id && !agentRequestCanRetry\(task\.metadata\.agent_status\)/)
  assert.match(source, /buildAgentTaskMessage\(task, project\?\.name \?\? '当前项目'\)/)
  assert.match(source, /labels: \['project-tasks', 'work-item', 'task-publish'\]/)
  assert.match(source, /selection: \{\s*entityType: 'work_item'/)
  assert.match(source, /title="AI 助手"/)
  assert.match(source, /`交给\$\{taskAgentOptionByKey\(selectedTask\.metadata\.agent_key\)\.name\}`/)
  assert.match(source, /等待 AI 会话/)
  assert.match(source, /打开 AI 会话/)

  assert.match(bridgeSource, /AGENT_PANEL_THREAD_EVENT/)
  assert.match(bridgeSource, /function openAgentPanelThread\(threadId: string\)/)
  assert.match(panelSource, /pendingThreadIdToOpen/)
  assert.match(panelSource, /<AgentBuiltinChatShell/)
  assert.match(builtinChatShellSource, /useAgentBuiltinChatController\(\{/)
  assert.match(builtinChatControllerSource, /handleRestoreLocalThread\(pendingThreadIdToOpen\)/)
})

test('task creation dialog keeps publish controls visible and can publish to a named agent', () => {
  const source = readFileSync(resolve('src/pages/project/tasks/TasksPage.tsx'), 'utf8')

  assert.match(source, /type TaskAgentKey = 'project_assistant' \| 'asset_agent' \| 'storyboard_agent' \| 'delivery_agent'/)
  assert.match(source, /const taskAgentOptions: TaskAgentOption\[\] = \[/)
  assert.match(source, /项目助理 Agent/)
  assert.match(source, /素材 Agent/)
  assert.match(source, /分镜 Agent/)
  assert.match(source, /交付检查 Agent/)
  assert.match(source, /agentKey\?: TaskAgentKey/)
  assert.match(source, /const \[agentKey, setAgentKey\] = useState<TaskAgentKey \| ''>\(''\)/)
  assert.match(source, /<DialogContent className="flex max-h-\[88vh\] w-\[min\(920px,calc\(100vw-32px\)\)\] flex-col overflow-hidden p-0">/)
  assert.match(source, /<DialogHeader className="shrink-0 border-b border-border px-5 py-4">/)
  assert.match(source, /<div className="min-h-0 flex-1 overflow-y-auto">/)
  assert.match(source, /<DialogFooter className="shrink-0 border-t border-border bg-card px-5 py-4">/)
  assert.match(source, /<option value="">不发送给 AI 助手<\/option>/)
  assert.match(source, /taskAgentOptions\.map\(\(agent\) =>/)
  assert.match(source, /发布后交给\{selectedAgent\.name\}/)
  assert.match(source, /agentKey: selectedAgent\?\.key/)
  assert.match(source, /mutationFn: \(input: \{ payload: Record<string, unknown>; agentKey\?: TaskAgentKey \}\)/)
  assert.match(source, /variables\.agentKey/)
  assert.match(source, /publishTaskToAgent\(workItemToProjectTask\(item, reviewerName\), variables\.agentKey\)/)
  assert.match(source, /agent_name: taskAgentOptionByKey\(draft\.agentKey\)\.name/)
  assert.match(source, /agent_name: agentOption\.name/)
  assert.match(source, /title: `\$\{agentOption\.name\}: \$\{task\.title\}`/)
  assert.match(source, /displayMessage: `请以\$\{agentOption\.name\}处理任务：\$\{task\.title\}`/)
})
