import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

test('content canvas inline prompt references expose type role and source identity', () => {
  const source = readFileSync(resolve(__dirname, '../components/ContentCanvasPromptReferences.tsx'), 'utf8')
  const editorSource = readFileSync(resolve(__dirname, '../components/ContentCanvasPromptEditor.tsx'), 'utf8')
  const styles = readFileSync(resolve(__dirname, '../components/ContentCanvasWorkspacePage.inspector-prompt.css'), 'utf8')

  assert.match(source, /generationReferenceMediaTypeShortLabel/)
  assert.match(source, /resolveResourceFileImageUrl\(reference\.previewResourceId\)/)
  assert.match(source, /resolveResourceFileUrl\(reference\.previewResourceId\)/)
  assert.match(source, /promptReferenceInlineRoleLabel/)
  assert.match(source, /promptReferenceMediaLabel/)
  assert.match(source, /part\.reference\.title/)
  assert.match(source, /function promptReferenceSourceLabel/)
  assert.match(source, /if \(kind === 'resource'\) return '资源'/)
  assert.match(source, /if \(kind === 'keyframe'\) return '关键帧'/)
  assert.match(source, /if \(kind === 'storyboard'\) return '故事版'/)
  assert.match(source, /if \(kind === 'asset'\) return '资源'/)
  assert.match(source, /function contentUnitTypeShortLabel/)
  assert.match(source, /function defaultReferenceRoleForReference/)
  assert.doesNotMatch(source, /<strong>\$\{escapeHtml\(part\.reference\.title\)\}<\/strong>/)
  assert.doesNotMatch(source, /if \(reference\.state === 'selected'\) return '已选'/)
  assert.doesNotMatch(source, /return 'Asset'/)
  assert.doesNotMatch(source, /<em>\{reference\.sourceLabel\}<\/em>/)
  assert.match(source, /<small>\{promptReferenceMediaLabel\(reference\.previewMediaType \?\? reference\.selectedMediaType \?\? reference\.mediaType\)\}<\/small>/)
  assert.match(source, /<b>\{promptReferenceInlineRoleLabel\(reference\)\}<\/b>/)
  assert.match(source, /const mentionMenuOpen = Boolean\(mentionRange\)/)
  assert.match(source, /emptyLabel=\{referenceItems \? '先在引用区添加图片或视频参考' : '没有可引用的节点'\}/)
  assert.match(source, /content-canvas-prompt-mention-menu__empty/)
  assert.match(source, /readResourceDragPayload/)
  assert.match(source, /onResourceReferenceDrop\?/)
  assert.match(source, /data-empty=\{references\.length \? undefined : 'true'\}/)
  assert.match(editorSource, /PromptReferenceInlineEditor[\s\S]*PromptReferencePoolStrip/)
  assert.match(editorSource, /references=\{referenceItems\}/)
  assert.match(editorSource, /generationReferenceFromDroppedResource/)
  assert.match(editorSource, /commitReferencePool\(promptDraft, \[\.\.\.withoutExisting, nextReference\]\)/)
  assert.doesNotMatch(editorSource, /PromptReferenceStrip/)

  assert.match(styles, /content-canvas-prompt-inline-reference__body/)
  assert.match(styles, /content-canvas-prompt-inline-reference__meta/)
  assert.match(styles, /content-canvas-prompt-mention-menu__empty/)
  assert.match(styles, /content-canvas-prompt-reference-strip\[data-empty="true"\]/)
  assert.match(styles, /max-width: min\(100%, 238px\)/)
  assert.match(styles, /data-role="first_frame"/)
  assert.match(styles, /data-role="last_frame"/)
})

test('content canvas candidate prompt preview keeps compiled resource chips compact and semantic', () => {
  const source = readFileSync(resolve(__dirname, '../components/ContentCanvasInspectorParts.tsx'), 'utf8')
  const styles = readFileSync(resolve(__dirname, '../components/ContentCanvasWorkspacePage.inspector-candidates.css'), 'utf8')

  assert.match(source, /parseResourceMentions\(text\)/)
  assert.match(source, /CompiledPromptResourceThumb/)
  assert.match(source, /<ResourceFileImage resourceId=\{resourceId\}/)
  assert.match(source, /<ResourceFileVideo resourceId=\{resourceId\}/)
  assert.match(source, /generationReferenceRoleLabel\(part\.role\) \|\| '参考'/)
  assert.doesNotMatch(source, /GenerationReferenceAssetSummary/)
  assert.doesNotMatch(source, /<small>\{`Resource \$\{String\(part\.resourceId\)\}`\}<\/small>/)

  assert.match(styles, /content-canvas-generation-candidate-resource-token__type/)
  assert.match(styles, /content-canvas-generation-candidate-resource-token img/)
  assert.doesNotMatch(styles, /content-canvas-generation-candidate-reference-summary/)
  assert.match(styles, /min-height: 22px/)
  assert.match(styles, /vertical-align: -0\.18em/)
  assert.match(styles, /data-role="first_frame"/)
  assert.match(styles, /data-role="reference_video"/)
})

test('generation surfaces expose specialized model parameter controls', () => {
  const inputSource = readFileSync(resolve(__dirname, '../../../../../../apps/desktop/src/shared/ui/GenInputCard.tsx'), 'utf8')
  const candidateSource = readFileSync(resolve(__dirname, '../components/ContentCanvasInspectorParts.tsx'), 'utf8')
  const promptCanvasSource = readFileSync(resolve(__dirname, '../components/ContentPromptCanvasPanel.tsx'), 'utf8')
  const workflowSource = readFileSync(resolve(__dirname, '../../../../../../surface/canvas/src/features/ui/canvasGenerationNodes.tsx'), 'utf8')
  const uiSource = readFileSync(resolve(__dirname, '../../../../../../packages/ui/src/components/business/generation/input/params/index.tsx'), 'utf8')
  const contentParamSource = readFileSync(resolve(__dirname, '../components/ContentCanvasGenerationParamControls.tsx'), 'utf8')

  assert.match(uiSource, /GenerationParamPreview/)
  assert.match(inputSource, /<GenerationParamPreview items=\{paramPreviewItems\}/)
  assert.doesNotMatch(candidateSource, /<GenerationParamPreview items=\{parameterPreviewItems\}/)
  assert.doesNotMatch(promptCanvasSource, /<GenerationParamPreview items=\{parameterPreviewItems\}/)
  assert.match(workflowSource, /<GenerationParamPreview items=\{parameterPreviewItems\}/)
  assert.match(contentParamSource, /contentCanvasGenerationParamKind/)
  assert.match(contentParamSource, /content-canvas-generation-param-switch/)
  assert.match(contentParamSource, /content-canvas-generation-param-seed/)
})

test('content canvas generation meta bar is horizontal and connection opens reference role choice', () => {
  const candidateSource = readFileSync(resolve(__dirname, '../components/ContentCanvasInspectorParts.tsx'), 'utf8')
  const promptCanvasSource = readFileSync(resolve(__dirname, '../components/ContentPromptCanvasPanel.tsx'), 'utf8')
  const candidateStyles = readFileSync(resolve(__dirname, '../components/ContentCanvasWorkspacePage.inspector-candidates.css'), 'utf8')
  const promptCanvasStyles = readFileSync(resolve(__dirname, '../components/ContentCanvasWorkspacePage.prompt-canvas.css'), 'utf8')

  assert.match(candidateSource, /content-canvas-generation-candidate-meta-row/)
  assert.match(candidateSource, /content-canvas-generation-candidate-meta-field--model/)
  assert.match(promptCanvasSource, /content-prompt-flow-node__generation-field--model/)
  assert.match(promptCanvasSource, /promptReferenceMenuPointForNode/)
  assert.match(promptCanvasSource, /appendReferenceToPromptTarget\([\s\S]*promptTarget,[\s\S]*referenceSource\.id,[\s\S]*promptReferenceMenuPointForNode\(promptTarget\.id\)/)
  assert.match(promptCanvasSource, /onGenerationReferenceAppend\(targetNode, sourceNode/)
  assert.doesNotMatch(promptCanvasSource, /appendReferenceToPromptTargetWithRole\(target, source\)/)
  assert.doesNotMatch(promptCanvasSource, /upsertContentNodeReferenceInPrompt/)

  assert.match(candidateStyles, /\.content-canvas-generation-candidate-meta-row\s*\{[\s\S]*display: flex;/)
  assert.match(candidateStyles, /\.content-canvas-generation-candidate-meta-field--model\s*\{[\s\S]*flex: 1 1 280px;/)
  assert.match(promptCanvasStyles, /\.content-prompt-flow-node__generation-grid\s*\{[\s\S]*display: flex;/)
  assert.match(promptCanvasStyles, /\.content-prompt-flow-node__generation-field--model\s*\{[\s\S]*flex: 1 1 176px;/)
})
