import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'node:test'

test('project home exposes multiple content canvas documents instead of a single canvas card', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')

  assert.match(source, /ProjectOverviewCanvasList/)
  assert.match(source, /title="内容画布"/)
  assert.match(source, /createCanvasForProduction/)
  assert.match(source, /onCreateCanvas=\{createCanvasForProduction\}/)
  assert.match(source, /readContentCanvasDocumentsState/)
  assert.match(source, /createContentCanvasDocument/)
  assert.match(source, /contentCanvasDocumentNodeIds/)
  assert.match(source, /scope: \{ kind: 'global' \}/)
  assert.match(source, /kind: 'production'/)
  assert.match(source, /productionId: production\.id/)
  assert.match(source, /productionTitle: production\.title/)
  assert.match(source, /surfaceRoutePath\('project\.contentCanvas', \{[\s\S]*projectId,[\s\S]*canvasId/)
  assert.doesNotMatch(source, /\`\$\{base\}\?canvasId=\$\{encodeURIComponent\(canvasId\)\}\`/)
  assert.doesNotMatch(source, /ProjectOverviewWorkbenchCard/)
})

test('project home groups plugins, scripts, productions, settings, and canvases as card groups', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')
  const groupSource = readFileSync(resolve('src/features/project/components/ProjectHomeCardGroup.tsx'), 'utf8')
  const productionIndex = source.indexOf('<ProjectOverviewProductionList')
  const settingIndex = source.indexOf('<ProjectOverviewSettingPreviewList')
  const canvasIndex = source.indexOf('<ProjectOverviewCanvasList')
  const scriptIndex = source.indexOf('<ProjectOverviewScriptList')

  assert.match(source, /project-overview-summary/)
  assert.match(source, /project-home-card-groups/)
  assert.match(source, /project-home-card-column--left/)
  assert.match(source, /project-home-card-column--right/)
  assert.match(source, /project-overview-summary__settings/)
  assert.match(source, /surfaceRoutePath\('project\.settings'/)
  assert.match(source, /ProjectOverviewProductionEditingDialog/)
  assert.match(source, /onOpenEditingWorkspaces=\{setEditingWorkspaceProduction\}/)
  assert.match(source, /ProjectOverviewPluginList/)
  assert.match(source, /aria-label="项目插件"/)
  assert.match(source, /<h2>项目插件<\/h2>/)
  assert.match(source, /ProjectBuiltInStandardsPluginCard/)
  assert.match(source, /title="创作手记"/)
  assert.match(source, /title="制作"/)
  assert.match(source, /title="设定预览"/)
  assert.match(source, /title="内容画布"/)
  assert.match(source, /<Scissors size=\{14\} \/>/)
  assert.match(source, /剪辑台/)
  assert.ok(canvasIndex > -1)
  assert.ok(productionIndex > -1)
  assert.ok(settingIndex > productionIndex)
  assert.ok(canvasIndex > settingIndex)
  assert.ok(scriptIndex > canvasIndex)
  assert.match(groupSource, /ProjectHomeCardGroup/)
  assert.match(groupSource, /project-home-card-group__body/)
})

test('project home uses distinct variants with paginated filters for creative lists', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')
  const styleSource = readFileSync(resolve('src/features/project/components/ProjectHomeCardGroup.css'), 'utf8')
  const groupSource = readFileSync(resolve('src/features/project/components/ProjectHomeCardGroup.tsx'), 'utf8')

  assert.match(source, /PROJECT_HOME_CARD_PAGE_SIZE = 3/)
  assert.match(source, /PROJECT_HOME_CANVAS_PAGE_SIZE = 8/)
  assert.match(source, /PROJECT_HOME_SETTING_PAGE_SIZE = 24/)
  assert.match(source, /PROJECT_HOME_ROW_PAGE_SIZE_OPTIONS/)
  assert.match(source, /ProjectHomeCardListPageSizeSelect/)
  assert.match(source, /onPageSizeChange/)
  assert.match(source, /useProjectHomeCardList/)
  assert.match(source, /ProjectHomeCardListToolbar/)
  assert.match(source, /ProjectHomeCardListPager/)
  assert.match(source, /AppPager/)
  assert.match(source, /projectHomeCanvasFilterLabel/)
  assert.match(source, /allFilterLabel="全部作用域"/)
  assert.match(source, /projectHomeCanvasBreadcrumb/)
  assert.match(source, /projectHomeSettingImageUrl/)
  assert.match(source, /projectHomeSettingMedia/)
  assert.match(source, /resolveResourceFileUrl/)
  assert.match(source, /ImageOff/)
  assert.match(source, /project-home-setting-card__placeholder/)
  assert.match(source, /data-state=\{setting\.media\.state\}/)
  assert.match(source, /已选择/)
  assert.match(source, /候选/)
  assert.match(source, /去画布生成/)
  assert.doesNotMatch(source, /projectHomeSettingFallbackImage/)
  assert.match(source, /全局内容画布/)
  assert.match(source, /variant="library"/)
  assert.match(source, /variant="canvas"/)
  assert.match(source, /variant="pipeline"/)
  assert.match(source, /variant="reference"/)
  assert.match(source, /layout="rows"/)
  assert.doesNotMatch(source, /project-home-row-card/)
  assert.doesNotMatch(source, /searchPlaceholder=/)
  assert.doesNotMatch(source, /facts=\{\[/)
  assert.doesNotMatch(source, /toolbar=\{/)
  assert.doesNotMatch(source, /description="(?:Script|ContentCanvasDocument|ProjectHome)/)
  assert.doesNotMatch(source, /projectHomeCanvasScopeLabel/)
  assert.match(groupSource, /ProjectHomeCardGroupVariant/)
  assert.match(styleSource, /project-overview-plugin-list/)
  assert.match(styleSource, /overflow-x: auto/)
  assert.match(styleSource, /project-home-card-column/)
  assert.match(styleSource, /grid-template-rows: minmax\(0, 1fr\) minmax\(0, 1fr\)/)
  assert.match(styleSource, /overflow-y: auto/)
  assert.match(styleSource, /data-variant="pipeline"/)
  assert.match(styleSource, /project-home-production-row/)
  assert.match(styleSource, /grid-template-columns: minmax\(0, 1fr\) 92px 92px 112px/)
  assert.match(styleSource, /project-home-canvas-create-card/)
  assert.match(styleSource, /project-home-card-group__page-size/)
  assert.match(styleSource, /project-home-setting-card__image/)
  assert.match(styleSource, /project-home-setting-card__placeholder/)
  assert.match(styleSource, /project-home-setting-card__state/)
  assert.match(styleSource, /data-state="selected"/)
  assert.match(styleSource, /data-state="candidate"/)
  assert.match(styleSource, /data-state="missing"/)
  assert.match(styleSource, /project-home-card-group__body\[data-variant="reference"\]/)
  assert.match(styleSource, /grid-template-columns: repeat\(6, minmax\(0, 1fr\)\)/)
  assert.match(styleSource, /project-home-card-group__body\[data-variant="canvas"\]/)
  assert.match(styleSource, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
  assert.match(styleSource, /text-overflow: ellipsis/)
  assert.match(styleSource, /project-home-card-group__pager/)
  const footerBlock = styleSource.match(/\.project-home-card-group__footer \{[^}]*\}/)?.[0] ?? ''
  assert.doesNotMatch(footerBlock, /border-top:/)
})

test('project home creates productions with production type templates', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')

  assert.match(source, /ProjectOverviewProductionList/)
  assert.match(source, /writeMovScriptEngineHierarchyNode/)
  assert.match(source, /projectHomeProductionInitialTimelineNodes/)
  assert.match(source, /contentCanvasTimelineProfileProductionType/)
  assert.match(source, /production_type: index === 0 \? productionType/)
  assert.match(source, /timeline_namespaces: index === 0 && timelineNamespaces\.length/)
  assert.match(source, /namespace_kind: node\.namespaceKind/)
  assert.match(source, /新建画布/)
  assert.doesNotMatch(source, /productionCanvasRoute/)
})

test('project home routes production and setting previews through focused content preview links', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')
  const dialogStyleSource = readFileSync(resolve('src/features/project/components/ProjectOverviewProductionEditingDialog.css'), 'utf8')
  const editingWorkspaceSource = readFileSync(resolve('../editing/src/pages/EditingWorkspacePage.tsx'), 'utf8')
  const editingExportSource = readFileSync(resolve('../editing/src/features/application/useEditingExportController.ts'), 'utf8')

  assert.match(source, /projectHomeProductionPreviewPath/)
  assert.match(source, /ProjectOverviewProductionEditingDialog/)
  assert.match(source, /listProductionEditingWorkspaces/)
  assert.match(source, /createProductionEditingWorkspace/)
  assert.match(source, /openProductionEditingWorkspace/)
  assert.match(source, /deleteProductionEditingWorkspace/)
  assert.match(source, /refreshProductionEditingResources/)
  assert.match(source, /createWorkspace\.mutate\('system_editing'\)/)
  assert.match(source, /createWorkspace\.mutate\('remotion'\)/)
  assert.match(source, /projectGateway\.openProductionEditingWorkspace/)
  assert.match(source, /onNavigate\(route\)/)
  assert.match(source, /projectHomeProductionEditingWorkspaceDetails\(workspace\)/)
  assert.match(source, /projectHomeProductionEditingWorkspaceSummary\(workspace\)/)
  assert.match(source, /className="project-production-editing-dialog__workspace-summary"/)
  assert.match(source, /className="project-production-editing-dialog__workspace-details"/)
  assert.match(source, /title: 'Remotion 预览工作台'/)
  assert.match(source, /status: previewCommand \? '已配置启动命令' : '待生成启动命令'/)
  assert.match(source, /label: '工作目录'/)
  assert.match(source, /label: '入口'/)
  assert.match(source, /label: '合成'/)
  assert.match(source, /label: '启动'/)
  assert.match(source, /function projectHomeProductionEditingCommandText/)
  assert.match(source, /function projectHomeProductionEditingCompactPath/)
  assert.match(dialogStyleSource, /\.project-production-editing-dialog__workspace-details \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(dialogStyleSource, /\.project-production-editing-dialog__workspace-summary \{[\s\S]*grid-template-columns: auto minmax\(0, 1fr\) auto/)
  assert.match(dialogStyleSource, /@media \(max-width: 720px\) \{[\s\S]*\.project-production-editing-dialog__create-grid \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(dialogStyleSource, /@media \(max-width: 720px\) \{[\s\S]*\.project-production-editing-dialog__workspace-details \{[\s\S]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/)
  assert.match(dialogStyleSource, /@media \(max-width: 720px\) \{[\s\S]*\.project-production-editing-dialog__workspace-details div:nth-child\(n \+ 3\) \{[\s\S]*display: none;/)
  assert.match(dialogStyleSource, /@media \(max-width: 720px\) \{[\s\S]*\.project-production-editing-dialog__workspace-details dd \{[\s\S]*white-space: nowrap;/)
  assert.match(dialogStyleSource, /@media \(max-width: 360px\) \{[\s\S]*\.project-production-editing-dialog__metrics,[\s\S]*\.project-production-editing-dialog__create-grid \{[\s\S]*grid-template-columns: 1fr;/)
  assert.match(source, /projectOverviewRemotionStudioHref/)
  assert.match(source, /runtime\.navigator\.href\('remotionStudio'/)
  assert.match(source, /ProjectOverviewProductionEditingDialog\.css/)
  assert.match(source, /\.\.\.\(projectDirectory \? \{ projectDirectory \} : \{\}\)/)
  assert.match(source, /\.\.\.\(entrypoint \? \{ entrypoint \} : \{\}\)/)
  assert.match(source, /\.\.\.\(compositionId \? \{ compositionId \} : \{\}\)/)
  assert.match(source, /remotionStudioSession/)
  assert.match(source, /const previewNodeId = `production:\$\{production\.id\}`/)
  assert.match(source, /productionId: production\.id/)
  assert.match(source, /canvasNode: previewNodeId/)
  assert.match(source, /scopeKind: 'production'/)
  assert.match(source, /targetKind: 'production'/)
  assert.doesNotMatch(source, /timeline_assembly_ref: targetRef/)
  assert.match(source, /ProjectOverviewSettingPreviewList/)
  assert.match(source, /surfaceRoutePath\('project\.settingPreview'/)
  assert.match(source, /canvasNode: `setting:\$\{setting\.id\}`/)
  assert.match(editingWorkspaceSource, /useSearchParams/)
  assert.match(editingWorkspaceSource, /searchParams\.get\('projectId'\)/)
  assert.match(editingWorkspaceSource, /STANDALONE_EDITING_PROJECT_ID/)
  assert.match(editingWorkspaceSource, /useEditingTaskStates\(mediaAPI, editingProjectProjectId\)/)
  assert.match(editingWorkspaceSource, /editingProjectProjectId,/)
  assert.match(editingExportSource, /shouldAutoImportRenderResult/)
  assert.match(editingExportSource, /format === 'mp4' && shouldAutoImportRenderResult\(savedProject\)/)
  assert.match(editingExportSource, /importToResource: true/)
  assert.match(editingExportSource, /autoImportRenderResult/)
  assert.match(editingExportSource, /targetKind.*production/)
  assert.match(editingExportSource, /scopeKind.*production/)
})

test('project home uses the injected desktop project gateway for project resource data', () => {
  const pageSource = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')
  const dataSource = readFileSync(resolve('src/features/project/application/projectOverviewData.ts'), 'utf8')
  const desktopRoutesSource = readFileSync(resolve('../../apps/desktop/src/features/app-shell/application/DesktopProjectSurfaceRoutes.tsx'), 'utf8')
  const appRouteSource = readFileSync(resolve('../../apps/desktop/src/features/app-shell/application/appRouteComponents.tsx'), 'utf8')

  assert.match(pageSource, /useOptionalProjectSurfaceRuntime/)
  assert.match(pageSource, /projectGateway: projectSurfaceRuntime\.gateways\.project/)
  assert.match(desktopRoutesSource, /<DesktopProjectSurfaceProvider>/)
  assert.match(desktopRoutesSource, /<ProjectSurfaceOverviewPage \/>/)
  assert.match(desktopRoutesSource, /ProjectRemotionStudioSurface/)
  assert.match(appRouteSource, /ProjectOverviewPage = lazyWithRetry\(\(\) => import\('\.\/DesktopProjectSurfaceRoutes'\)/)
  assert.match(appRouteSource, /ProjectRemotionStudioPage = lazyWithRetry\(\(\) => import\('\.\/DesktopProjectSurfaceRoutes'\)/)
  assert.doesNotMatch(dataSource, /fetch\('\/v1\/project\/resources\/view'/)
  assert.doesNotMatch(dataSource, /window\.location\.origin/)
})

test('project surface remotion studio opens shell jobs through runtime shell gateway', () => {
  const runtimeSource = readFileSync(resolve('src/runtime/ProjectSurfaceRuntime.ts'), 'utf8')
  const runtimeIndexSource = readFileSync(resolve('src/runtime/index.ts'), 'utf8')
  const remotionSource = readFileSync(resolve('src/components/remotion/ProjectRemotionStudioSurface.tsx'), 'utf8')
  const remotionStyleSource = readFileSync(resolve('src/components/remotion/ProjectRemotionStudioSurface.css'), 'utf8')
  const shellIntentCardSource = readFileSync(resolve('src/components/ProjectSurfaceShellIntentCard.tsx'), 'utf8')
  const shellIntentCardStyleSource = readFileSync(resolve('src/components/ProjectSurfaceShellIntentCard.css'), 'utf8')

  assert.match(runtimeSource, /export interface ShellGateway/)
  assert.match(runtimeSource, /export type ProjectSurfaceShellReveal = boolean \| 'always' \| 'on_error' \| 'silent'/)
  assert.match(runtimeSource, /export type ProjectSurfaceShellIntentSchema = 'movscript\.shell_intent\.v1'/)
  assert.match(runtimeSource, /export interface ProjectSurfaceShellIntent \{[\s\S]*schema: ProjectSurfaceShellIntentSchema[\s\S]*intentId: string[\s\S]*command: string\[\][\s\S]*commandText: string[\s\S]*ownerFeature: string[\s\S]*destructive: boolean/)
  assert.match(runtimeSource, /export type ProjectSurfaceShellJobSchema = 'movscript\.shell_job\.v1'/)
  assert.match(runtimeSource, /export type ProjectSurfaceShellJobStatus = 'queued' \| 'running' \| 'succeeded' \| 'failed' \| 'stopped'/)
  assert.match(runtimeSource, /export interface ProjectSurfaceShellJob \{[\s\S]*schema: ProjectSurfaceShellJobSchema[\s\S]*jobId: string[\s\S]*sessionId: string[\s\S]*command: string\[\][\s\S]*commandText: string[\s\S]*command_text\?: string[\s\S]*reveal: 'always' \| 'on_error' \| 'silent'/)
  assert.match(runtimeSource, /export type ProjectSurfaceRemotionStudioSessionSchema = 'movscript\.remotion_studio_session\.v1'/)
  assert.match(runtimeSource, /export type ProjectSurfaceRemotionStudioSessionLogsSchema = 'movscript\.remotion_studio_session_logs\.v1'/)
  assert.match(runtimeSource, /export interface ProjectSurfaceRemotionStudioSessionBlocker \{[\s\S]*shellIntent\?: ProjectSurfaceShellIntent/)
  assert.match(runtimeSource, /export interface ProjectSurfaceShellSession \{[\s\S]*projectDir\?: string[\s\S]*previewUrl\?: string/)
  assert.match(runtimeSource, /export interface ProjectSurfaceRemotionStudioSession \{[\s\S]*schema: ProjectSurfaceRemotionStudioSessionSchema[\s\S]*status: ProjectSurfaceRemotionStudioStatus[\s\S]*shellIntent\?: ProjectSurfaceShellIntent[\s\S]*shellSessionId\?: string[\s\S]*shellJobId\?: string/)
  assert.match(runtimeSource, /export interface ProjectSurfaceRemotionStudioSessionLogs \{[\s\S]*schema: ProjectSurfaceRemotionStudioSessionLogsSchema[\s\S]*logs: ProjectSurfaceRemotionStudioSessionLogEntry\[\]/)
  assert.match(runtimeSource, /open\(input: Record<string, unknown>\): Promise<ProjectSurfaceRemotionStudioSession>/)
  assert.match(runtimeSource, /logs\(input: Record<string, unknown>\): Promise<ProjectSurfaceRemotionStudioSessionLogs>/)
  assert.match(runtimeSource, /listJobs\(input\?: ProjectSurfaceShellJobListInput\): Promise<\{ jobs: ProjectSurfaceShellJob\[\] \}>/)
  assert.match(runtimeSource, /getJob\(input: ProjectSurfaceShellJobInput\): Promise<ProjectSurfaceShellJob \| undefined>/)
  assert.match(runtimeSource, /jobLogs\(input: ProjectSurfaceShellJobInput\): Promise<ProjectSurfaceShellJobLogsResult>/)
  assert.match(runtimeSource, /shell\?: ShellGateway/)
  assert.match(runtimeSource, /reveal\?: ProjectSurfaceShellReveal/)
  assert.match(runtimeSource, /shell: false/)
  assert.match(runtimeIndexSource, /ProjectSurfaceShellIntent/)
  assert.match(runtimeIndexSource, /ProjectSurfaceShellIntentSchema/)
  assert.match(runtimeIndexSource, /ProjectSurfaceShellJob/)
  assert.match(runtimeIndexSource, /ProjectSurfaceShellJobLogsResult/)
  assert.match(runtimeIndexSource, /ProjectSurfaceRemotionStudioSession/)
  assert.match(runtimeIndexSource, /ProjectSurfaceRemotionStudioSessionLogs/)
  assert.match(runtimeIndexSource, /ProjectSurfaceShellReveal/)
  assert.match(runtimeIndexSource, /ShellGateway/)
  assert.match(remotionSource, /const shellGateway = runtime\.gateways\.shell/)
  assert.match(remotionSource, /if \(lookup\.sessionId\) \{[\s\S]*const response = recordValue\(await gateway\.get\(lookup\)\) \?\? \{\}[\s\S]*if \(!remotionStudioSessionNeedsOpenFallback\(response\)\) return response[\s\S]*const response = await gateway\.open\(lookup\)/)
  assert.match(remotionSource, /function remotionStudioSessionNeedsOpenFallback\(session: Record<string, unknown>\): boolean/)
  assert.match(remotionSource, /const installIntent = installShellIntent\(blockers, projectDirectory\)/)
  assert.match(remotionSource, /const \[dependencyInstallStartedAt, setDependencyInstallStartedAt\] = useState<number \| null>\(null\)/)
  assert.match(remotionSource, /const \[dependencyInstallShellSessionId, setDependencyInstallShellSessionId\] = useState<string \| null>\(null\)/)
  assert.match(remotionSource, /const sessionQueryKey = useMemo\(\(\) => \['project-surface', 'remotion-studio-session', lookup\] as const/)
  assert.match(remotionSource, /if \(dependencyInstallStartedAt && status === 'blocked'\) return 2000/)
  assert.match(remotionSource, /const dependencyInstallShellQuery = useQuery\(\{[\s\S]*runtime\.gateways\.shell[\s\S]*shellGateway\.get\(\{ sessionId: dependencyInstallShellSessionId \}\)/)
  assert.match(remotionSource, /const continueAfterDependencyInstall = useMutation\(\{[\s\S]*gateway\.open\(\{[\s\S]*forceRestart: true[\s\S]*force_restart: true/)
  assert.match(remotionSource, /installStatus === 'exited' && installExitCode === 0[\s\S]*continueAfterDependencyInstall\.mutateAsync\(\)/)
  assert.match(remotionSource, /Remotion 依赖安装失败/)
  assert.match(remotionSource, /const activeShellSessionId = shellSessionId \?\? \(status === 'blocked' \? dependencyInstallShellSessionId \?\? undefined : undefined\)/)
  assert.match(remotionSource, /const sessionError = stringValue\(session\?\.error \?\? session\?\.message \?\? session\?\.errorMessage \?\? session\?\.error_message\)/)
  assert.match(remotionSource, /remotionStudioStatusDetail\(status, iframeState, blockers, sessionError\)/)
  assert.match(remotionSource, /remotionStudioWaitingDetail\(status, blockers, sessionError\)/)
  assert.match(remotionSource, /if \(sessionError && \(status === 'failed' \|\| status === 'blocked'\)\) return sessionError/)
  assert.match(remotionSource, /if \(input\.sessionError\) diagnostics\.push\(\['错误', input\.sessionError\]\)/)
  assert.match(remotionSource, /type RemotionStudioStatus = 'checking' \| 'installing' \| 'starting' \| 'ready' \| 'failed' \| 'stopped' \| 'blocked' \| 'needs_external_shell'/)
  assert.match(remotionSource, /status !== 'needs_external_shell'/)
  assert.match(remotionSource, /status === 'needs_external_shell'\) return '需要在 Shell 中启动 Remotion Studio'/)
  assert.match(remotionSource, /const runShellIntent = async \([\s\S]*intent: RemotionShellIntent,[\s\S]*title\?: string,[\s\S]*reveal: boolean \| 'always' \| 'on_error' \| 'silent' = 'on_error'[\s\S]*ownerFeature: 'remotion_studio'/)
  assert.match(remotionSource, /shellGateway\.reveal/)
  assert.match(remotionSource, /activeShellSessionId && shellGateway\.reveal && !remotionShellSessionFinished\(shellStatus\)/)
  assert.match(remotionSource, /findExistingRemotionShellJob\(shellGateway, \{[\s\S]*ownerFeature: 'remotion_studio'/)
  assert.match(remotionSource, /function remotionShellJobMatches\([\s\S]*job\.status !== 'queued' && job\.status !== 'running'[\s\S]*job\.ownerFeature !== 'remotion_studio'/)
  assert.match(remotionSource, /queryClient\.setQueryData\(sessionQueryKey, remotionStudioSessionWithShellJob\(existingJob\)\)/)
  assert.match(remotionSource, /queryClient\.setQueryData\(sessionQueryKey, remotionStudioSessionWithShellSession\(shellSession\)\)/)
  assert.match(remotionSource, /function remotionShellSessionFinished\(status: unknown\): boolean \{[\s\S]*status === 'failed' \|\| status === 'exited'/)
  assert.match(remotionSource, /await revealRemotionShellSession\(shellGateway, activeShellSessionId\)/)
  assert.match(remotionSource, /await revealRemotionShellSession\(shellGateway, existingJob\.sessionId\)/)
  assert.match(remotionSource, /requestHostShellWorkbenchReveal\(shellSession\.id\)/)
  assert.match(remotionSource, /window\.dispatchEvent\(new CustomEvent\('movscript:shell-workbench-reveal', \{ detail: \{ sessionId \} \}\)\)/)
  assert.match(remotionSource, /renderPreviewFrame\?: \(props: ProjectRemotionStudioPreviewFrameProps\) => ReactNode/)
  assert.match(remotionSource, /shellGateway\.run\(\{[\s\S]*title: title \?\? intent\.title \?\? 'Remotion Studio'[\s\S]*scope: 'workspace'[\s\S]*command: intent\.commandText[\s\S]*projectDir: cwd/)
  assert.match(remotionSource, /const command = commandText \?\? shellIntent\?\.commandText/)
  assert.match(remotionSource, /const installDependencies = useMutation\(\{[\s\S]*runShellIntent\(installIntent, '安装 Remotion 依赖', 'always'\)/)
  assert.match(remotionSource, /setDependencyInstallShellSessionId\(shellSession\.id\)/)
  assert.match(remotionSource, /setDependencyInstallStartedAt\(Date\.now\(\)\)/)
  assert.match(remotionSource, /invalidateQueries\(\{ queryKey: \['project-surface', 'remotion-studio-session'\] \}\)/)
  assert.match(remotionSource, /const restartSession = useMutation\(\{[\s\S]*gateway\.open\(\{[\s\S]*forceRestart: true[\s\S]*force_restart: true/)
  assert.match(remotionSource, /const restartAvailable = Boolean\(gateway && canLookup && \(status === 'stopped' \|\| status === 'failed'\)\)/)
  assert.match(remotionSource, /remotionStudioRestartInput\(lookup, session\)/)
  assert.match(remotionSource, /const copyPreviewUrl = useMutation\(\{[\s\S]*navigator\.clipboard\?\.writeText/)
  assert.match(remotionSource, /navigator\.clipboard\.writeText\(previewUrl\)/)
  assert.match(remotionSource, /预览地址已复制/)
  assert.match(remotionSource, /无法复制预览地址/)
  assert.match(remotionSource, /复制预览地址/)
  assert.match(remotionSource, /shellActionAvailable = Boolean\(hasDesktopShell && \(activeShellSessionId \|\| commandText \|\| shellIntent\?\.commandText\)\)/)
  assert.match(remotionSource, /安装依赖/)
  assert.match(remotionSource, /检查依赖/)
  assert.match(remotionSource, /重新启动/)
  assert.match(remotionSource, /在 Shell 打开/)
  assert.doesNotMatch(remotionSource, /chips=\{/)
  assert.doesNotMatch(remotionSource, /AgentSurfacePanel/)
  assert.doesNotMatch(remotionSource, /AgentSurfaceKeyValues/)
  assert.doesNotMatch(remotionSource, /remotion-studio-surface__logs/)
  assert.doesNotMatch(remotionSource, /remotion-studio-surface__toolbar/)
  assert.match(remotionSource, /chrome="immersive"/)
  assert.match(remotionSource, /remotion-studio-surface__status-strip/)
  assert.match(remotionSource, /remotion-studio-surface__status-facts/)
  assert.match(remotionSource, /remotion-studio-surface__diagnostics/)
  assert.match(remotionSource, /remotion-studio-surface__diagnostics-drawer/)
  assert.match(remotionSource, /remotion-studio-surface__diagnostics-panel/)
  assert.match(remotionSource, /remotionStudioCanRenderPreview/)
  assert.match(remotionSource, /remotionStudioFrameTitle/)
  assert.match(remotionSource, /remotionStudioIframeStateLabel/)
  assert.match(remotionSource, /setIframeRefreshNonce\(\(value\) => value \+ 1\)/)
  assert.match(remotionSource, /key=\{`\$\{previewUrl\}:\$\{iframeRefreshNonce\}`\}/)
  assert.match(remotionSource, /aria-live="polite"/)
  assert.match(remotionSource, /刷新嵌入页/)
  assert.match(remotionSource, /查看 Shell/)
  assert.match(remotionSource, /remotionStudioStatusFacts/)
  assert.match(remotionSource, /remotionStudioDiagnostics/)
  assert.match(remotionSource, /预览服务已返回/)
  assert.doesNotMatch(remotionSource, /logEntries/)
  assert.doesNotMatch(remotionSource, /logLine/)
  assert.doesNotMatch(remotionSource, /\['Status',/)
  assert.doesNotMatch(remotionSource, /\['Project Dir',/)
  assert.doesNotMatch(remotionSource, /\['Preview URL',/)
  assert.match(remotionSource, /\['预览地址',/)
  assert.match(remotionSource, /\['工作目录',/)
  assert.match(remotionSource, /\['嵌入页',/)
  assert.match(remotionSource, /\['会话',/)
  assert.match(remotionSource, /\['入口文件',/)
  assert.match(remotionSource, /\['嵌入状态',/)
  assert.match(remotionSource, /\['启动命令',/)
  assert.match(remotionSource, /\['Shell 会话',/)
  assert.match(remotionSource, /\['Shell Job',/)
  assert.match(remotionSource, /\['Shell 状态',/)
  assert.match(remotionSource, /\['错误',/)
  assert.doesNotMatch(remotionSource, /status: \$\{statusLabel\}/)
  assert.doesNotMatch(remotionSource, /session: \$\{sessionId\}/)
  assert.match(remotionSource, /shellIntentRecord/)
  assert.match(remotionSource, /shellIntentRecord\(record\?\.shellIntent \?\? record\?\.shell_intent\)/)
  assert.match(remotionSource, /if \(blocker\?\.shellIntent\) return blocker\.shellIntent/)
  assert.match(remotionSource, /schema: 'movscript\.shell_intent\.v1'/)
  assert.match(remotionSource, /const commandText = stringValue\(record\.commandText \?\? record\.command_text\) \?\? arrayText\(record\.command\)/)
  assert.match(remotionSource, /const command = stringArrayValue\(record\.command\) \?\? shellCommandTextFallbackArray\(commandText\)/)
  assert.match(remotionSource, /const intentId = stringValue\(record\.intentId \?\? record\.intent_id\)/)
  assert.match(remotionSource, /commandText,[\s\S]*command_text: commandText/)
  assert.match(remotionSource, /ownerFeature,[\s\S]*owner_feature: ownerFeature/)
  assert.match(remotionSource, /destructive: destructive \?\? false/)
  assert.match(remotionSource, /installShellIntent/)
  assert.match(remotionSource, /intentId: `remotion-install-dependencies:\$\{cwd \|\| commandText\}`/)
  assert.match(remotionSource, /command: blocker\.installCommand,[\s\S]*commandText,[\s\S]*command_text: commandText/)
  assert.match(remotionSource, /destructive: false/)
  assert.match(remotionSource, /function shellCommandTextFallbackArray\(commandText: string\): string\[\]/)
  assert.match(remotionSource, /remotionStudioRestartInput/)
  assert.match(remotionSource, /shellSessionStatus/)
  assert.match(remotionSource, /shellSessionExitCode/)
  assert.match(remotionSource, /ProjectSurfaceShellIntentCard/)
  assert.doesNotMatch(remotionSource, /function RemotionShellIntentCard/)
  assert.match(remotionSource, /!hasDesktopShell && shellIntent/)
  assert.match(remotionSource, /className="remotion-studio-surface__preparing" data-status=\{statusTone\}/)
  assert.match(remotionSource, /className="remotion-studio-surface__pulse" data-status=\{statusTone\}/)
  assert.match(remotionSource, /remotion-studio-surface__preparing[\s\S]*ProjectSurfaceShellIntentCard/)
  assert.match(remotionSource, /className="remotion-studio-surface__intent-card"/)
  assert.match(remotionSource, /primaryActionLabel=\{installIntent \? '复制安装命令' : '复制启动命令'\}/)
  assert.match(remotionSource, /checkAgainLabel=\{installIntent \? '安装完成，重新检查' : '我已启动，重新检查'\}/)
  assert.match(shellIntentCardSource, /export function ProjectSurfaceShellIntentCard/)
  assert.match(shellIntentCardSource, /checkAgainLabel\?: string/)
  assert.match(shellIntentCardSource, /checkAgainLabel = '重新检查'/)
  assert.match(shellIntentCardSource, /const IntentIcon = intent\.destructive \? AlertTriangle : SquareTerminal/)
  assert.match(shellIntentCardSource, /const riskLabel = intent\.destructive \? '需要确认' : '工作区命令'/)
  assert.match(shellIntentCardSource, /data-risk=\{intent\.destructive \? 'destructive' : 'workspace'\}/)
  assert.match(shellIntentCardSource, /className="project-surface-shell-intent-card__risk"/)
  assert.match(shellIntentCardSource, /aria-label="Shell 命令信息"/)
  assert.match(shellIntentCardSource, /<dt>工作目录<\/dt>/)
  assert.doesNotMatch(shellIntentCardSource, /<dt>cwd<\/dt>/)
  assert.match(shellIntentCardSource, /<dd><code>\{intent\.commandText\}<\/code><\/dd>/)
  assert.match(shellIntentCardSource, /intent\.expectedPreviewUrl \? \([\s\S]*<dt>预期预览地址<\/dt>[\s\S]*<dd>\{intent\.expectedPreviewUrl\}<\/dd>/)
  assert.match(remotionSource, /剪贴板 API 不可用。/)
  assert.match(remotionSource, /navigator\.clipboard\.writeText\(shellIntent\.commandText\)/)
  assert.match(shellIntentCardSource, /<span>\{checkAgainLabel\}<\/span>/)
  assert.match(remotionStyleSource, /\.remotion-studio-surface__preparing \.project-surface-shell-intent-card/)
  assert.match(remotionStyleSource, /\.remotion-studio-surface__pulse\[data-status="blocked"\],[\s\S]*\.remotion-studio-surface__pulse\[data-status="failed"\],[\s\S]*\.remotion-studio-surface__pulse\[data-status="stopped"\] \{[\s\S]*animation: none;/)
  assert.match(remotionStyleSource, /\.remotion-studio-surface__pulse\[data-status="blocked"\] \{[\s\S]*border-top-color: #facc15;/)
  assert.match(remotionStyleSource, /\.remotion-studio-surface__pulse\[data-status="failed"\] \{[\s\S]*border-top-color: #f87171;/)
  assert.doesNotMatch(remotionStyleSource, /remotion-studio-surface__intent-title-row/)
  assert.doesNotMatch(remotionStyleSource, /remotion-studio-surface__intent-risk/)
  assert.match(shellIntentCardStyleSource, /\.project-surface-shell-intent-card \{/)
  assert.match(shellIntentCardStyleSource, /\.project-surface-shell-intent-card__title-row \{/)
  assert.match(shellIntentCardStyleSource, /\.project-surface-shell-intent-card__risk \{/)
  assert.match(shellIntentCardStyleSource, /white-space: pre-wrap/)
  assert.match(shellIntentCardStyleSource, /word-break: break-word/)
  assert.doesNotMatch(remotionStyleSource, /remotion-studio-surface__side/)
  assert.doesNotMatch(remotionStyleSource, /remotion-studio-surface__logs/)
  assert.doesNotMatch(remotionStyleSource, /remotion-studio-surface__toolbar/)
  assert.doesNotMatch(remotionStyleSource, /aspect-ratio: 16 \/ 9/)
  assert.doesNotMatch(remotionStyleSource, /max-height: calc\(100vh - 160px\)/)
  assert.match(remotionStyleSource, /\.remotion-studio-surface \{[\s\S]*height: 100%;/)
  assert.match(remotionStyleSource, /\.remotion-studio-surface__preview \{[\s\S]*grid-template-rows: auto minmax\(0, 1fr\);/)
  assert.match(remotionStyleSource, /\.remotion-studio-surface__frame \{[\s\S]*min-height: 0;/)
  assert.match(remotionStyleSource, /remotion-studio-surface__status-strip/)
  assert.match(remotionStyleSource, /data-status="ready"/)
  assert.match(remotionStyleSource, /\.remotion-studio-surface__diagnostics-drawer/)
  assert.match(remotionStyleSource, /\.remotion-studio-surface__diagnostics-panel \{[\s\S]*position: absolute;/)
  assert.match(remotionStyleSource, /remotion-studio-surface__diagnostics/)
  assert.match(remotionStyleSource, /grid-template-columns: repeat\(auto-fit, minmax\(116px, 1fr\)\);/)
  assert.match(remotionStyleSource, /grid-template-columns: repeat\(auto-fit, minmax\(136px, 1fr\)\);/)
  assert.doesNotMatch(remotionSource, /readElectronApi/)
  assert.doesNotMatch(remotionSource, /MEDIA_PIPELINE/)
})
