import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'node:test'

test('project home exposes multiple content canvas documents instead of a single canvas card', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')

  assert.match(source, /ProjectOverviewCanvasList/)
  assert.match(source, /title="内容画布"/)
  assert.match(source, /createCanvasForProduction/)
  assert.match(source, /onCreateCanvas=\{createCanvasForProduction\}/)
  assert.match(source, /readContentCanvasDocumentsState/)
  assert.match(source, /createContentCanvasDocument/)
  assert.match(source, /contentCanvasDocumentNodeIds/)
  assert.match(source, /scope: \{ kind: 'global' \}/)
  assert.match(source, /kind: 'production'/)
  assert.match(source, /productionId: production\.id/)
  assert.match(source, /productionTitle: production\.title/)
  assert.match(source, /canvasId=\$\{encodeURIComponent\(canvasId\)\}/)
  assert.doesNotMatch(source, /ProjectOverviewWorkbenchCard/)
})

test('project home groups plugins, scripts, productions, settings, and canvases as card groups', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')
  const groupSource = readFileSync(resolve('src/features/project/components/ProjectHomeCardGroup.tsx'), 'utf8')
  const productionIndex = source.indexOf('<ProjectOverviewProductionList')
  const settingIndex = source.indexOf('<ProjectOverviewSettingPreviewList')
  const canvasIndex = source.indexOf('<ProjectOverviewCanvasList')
  const scriptIndex = source.indexOf('<ProjectOverviewScriptList')

  assert.match(source, /project-overview-summary/)
  assert.match(source, /project-home-card-groups/)
  assert.match(source, /project-home-card-column--left/)
  assert.match(source, /project-home-card-column--right/)
  assert.match(source, /project-overview-summary__settings/)
  assert.match(source, /surfaceRoutePath\('project\.settings'/)
  assert.match(source, /ProjectOverviewPluginList/)
  assert.match(source, /aria-label="项目插件"/)
  assert.match(source, /<h2>项目插件<\/h2>/)
  assert.match(source, /ProjectBuiltInStandardsPluginCard/)
  assert.match(source, /title="创作手记"/)
  assert.match(source, /title="制作"/)
  assert.match(source, /title="设定预览"/)
  assert.match(source, /title="内容画布"/)
  assert.ok(canvasIndex > -1)
  assert.ok(productionIndex > -1)
  assert.ok(settingIndex > productionIndex)
  assert.ok(canvasIndex > settingIndex)
  assert.ok(scriptIndex > canvasIndex)
  assert.match(groupSource, /ProjectHomeCardGroup/)
  assert.match(groupSource, /project-home-card-group__body/)
})

test('project home uses distinct variants with paginated filters for creative lists', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')
  const styleSource = readFileSync(resolve('src/features/project/components/ProjectHomeCardGroup.css'), 'utf8')
  const groupSource = readFileSync(resolve('src/features/project/components/ProjectHomeCardGroup.tsx'), 'utf8')

  assert.match(source, /PROJECT_HOME_CARD_PAGE_SIZE = 3/)
  assert.match(source, /PROJECT_HOME_CANVAS_PAGE_SIZE = 8/)
  assert.match(source, /PROJECT_HOME_SETTING_PAGE_SIZE = 24/)
  assert.match(source, /PROJECT_HOME_ROW_PAGE_SIZE_OPTIONS/)
  assert.match(source, /ProjectHomeCardListPageSizeSelect/)
  assert.match(source, /onPageSizeChange/)
  assert.match(source, /useProjectHomeCardList/)
  assert.match(source, /ProjectHomeCardListToolbar/)
  assert.match(source, /ProjectHomeCardListPager/)
  assert.match(source, /AppPager/)
  assert.match(source, /projectHomeCanvasFilterLabel/)
  assert.match(source, /allFilterLabel="全部作用域"/)
  assert.match(source, /projectHomeCanvasBreadcrumb/)
  assert.match(source, /projectHomeSettingImageUrl/)
  assert.match(source, /projectHomeSettingMedia/)
  assert.match(source, /resolveResourceFileUrl/)
  assert.match(source, /ImageOff/)
  assert.match(source, /project-home-setting-card__placeholder/)
  assert.match(source, /data-state=\{setting\.media\.state\}/)
  assert.match(source, /已选择/)
  assert.match(source, /候选/)
  assert.match(source, /去画布生成/)
  assert.doesNotMatch(source, /projectHomeSettingFallbackImage/)
  assert.match(source, /全局内容画布/)
  assert.match(source, /variant="library"/)
  assert.match(source, /variant="canvas"/)
  assert.match(source, /variant="pipeline"/)
  assert.match(source, /variant="reference"/)
  assert.match(source, /layout="rows"/)
  assert.doesNotMatch(source, /project-home-row-card/)
  assert.doesNotMatch(source, /searchPlaceholder=/)
  assert.doesNotMatch(source, /facts=\{\[/)
  assert.doesNotMatch(source, /toolbar=\{/)
  assert.doesNotMatch(source, /description="(?:Script|ContentCanvasDocument|ProjectHome)/)
  assert.doesNotMatch(source, /projectHomeCanvasScopeLabel/)
  assert.match(groupSource, /ProjectHomeCardGroupVariant/)
  assert.match(styleSource, /project-overview-plugin-list/)
  assert.match(styleSource, /overflow-x: auto/)
  assert.match(styleSource, /project-home-card-column/)
  assert.match(styleSource, /grid-template-rows: minmax\(0, 1fr\) minmax\(0, 1fr\)/)
  assert.match(styleSource, /overflow-y: auto/)
  assert.match(styleSource, /data-variant="pipeline"/)
  assert.match(styleSource, /project-home-production-row/)
  assert.match(styleSource, /project-home-canvas-create-card/)
  assert.match(styleSource, /project-home-card-group__page-size/)
  assert.match(styleSource, /project-home-setting-card__image/)
  assert.match(styleSource, /project-home-setting-card__placeholder/)
  assert.match(styleSource, /project-home-setting-card__state/)
  assert.match(styleSource, /data-state="selected"/)
  assert.match(styleSource, /data-state="candidate"/)
  assert.match(styleSource, /data-state="missing"/)
  assert.match(styleSource, /project-home-card-group__body\[data-variant="reference"\]/)
  assert.match(styleSource, /grid-template-columns: repeat\(6, minmax\(0, 1fr\)\)/)
  assert.match(styleSource, /project-home-card-group__body\[data-variant="canvas"\]/)
  assert.match(styleSource, /grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/)
  assert.match(styleSource, /text-overflow: ellipsis/)
  assert.match(styleSource, /project-home-card-group__pager/)
  const footerBlock = styleSource.match(/\.project-home-card-group__footer \{[^}]*\}/)?.[0] ?? ''
  assert.doesNotMatch(footerBlock, /border-top:/)
})

test('project home creates productions with production type templates', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')

  assert.match(source, /ProjectOverviewProductionList/)
  assert.match(source, /writeMovScriptEngineHierarchyNode/)
  assert.match(source, /projectHomeProductionInitialTimelineNodes/)
  assert.match(source, /contentCanvasTimelineProfileProductionType/)
  assert.match(source, /production_type: index === 0 \? productionType/)
  assert.match(source, /timeline_namespaces: index === 0 && timelineNamespaces\.length/)
  assert.match(source, /namespace_kind: node\.namespaceKind/)
  assert.match(source, /新建画布/)
  assert.doesNotMatch(source, /productionCanvasRoute/)
})

test('project home routes production and setting previews through focused content preview links', () => {
  const source = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')

  assert.match(source, /projectHomeProductionPreviewPath/)
  assert.match(source, /const previewNodeId = `production:\$\{production\.id\}`/)
  assert.match(source, /canvasNode: previewNodeId/)
  assert.match(source, /productionId: production\.id/)
  assert.match(source, /scopeKind: 'production'/)
  assert.match(source, /timeline_assembly_ref: targetRef/)
  assert.match(source, /ProjectOverviewSettingPreviewList/)
  assert.match(source, /surfaceRoutePath\('project\.settingPreview'/)
  assert.match(source, /canvasNode: `setting:\$\{setting\.id\}`/)
})

test('project home uses the injected desktop project gateway for project resource data', () => {
  const pageSource = readFileSync(resolve('src/features/project/components/ProjectOverviewPage.tsx'), 'utf8')
  const dataSource = readFileSync(resolve('src/features/project/application/projectOverviewData.ts'), 'utf8')
  const desktopRoutesSource = readFileSync(resolve('../../apps/desktop/src/features/app-shell/application/DesktopProjectSurfaceRoutes.tsx'), 'utf8')
  const appRouteSource = readFileSync(resolve('../../apps/desktop/src/features/app-shell/application/appRouteComponents.tsx'), 'utf8')

  assert.match(pageSource, /useOptionalProjectSurfaceRuntime/)
  assert.match(pageSource, /projectGateway: projectSurfaceRuntime\.gateways\.project/)
  assert.match(desktopRoutesSource, /<DesktopProjectSurfaceProvider>/)
  assert.match(desktopRoutesSource, /<ProjectSurfaceOverviewPage \/>/)
  assert.match(appRouteSource, /ProjectOverviewPage = lazyWithRetry\(\(\) => import\('\.\/DesktopProjectSurfaceRoutes'\)/)
  assert.doesNotMatch(dataSource, /fetch\('\/v1\/project\/resources\/view'/)
  assert.doesNotMatch(dataSource, /window\.location\.origin/)
})
