export const PRE_PRODUCTION_WORKBENCH_RAIL_MIN_WIDTH = 260
export const PRE_PRODUCTION_WORKBENCH_DETAIL_PANE_ID = 'pre-production.detail-pane'
export const PRE_PRODUCTION_WORKBENCH_DETAIL_PANE_WIDTH_STORAGE_KEY = 'movscript.preProduction.detailPaneWidth'
export const PRE_PRODUCTION_WORKBENCH_DETAIL_PANE_DEFAULT_WIDTH = 760
export const PRE_PRODUCTION_WORKBENCH_DETAIL_PANE_MIN_WIDTH = 420
export const PRE_PRODUCTION_WORKBENCH_DETAIL_PANE_MAX_WIDTH = 960

export function preProductionWorkbenchDetailPaneMaxWidth(containerRect: DOMRectReadOnly): number {
  return Math.max(
    PRE_PRODUCTION_WORKBENCH_DETAIL_PANE_MIN_WIDTH,
    Math.min(PRE_PRODUCTION_WORKBENCH_DETAIL_PANE_MAX_WIDTH, containerRect.width - PRE_PRODUCTION_WORKBENCH_RAIL_MIN_WIDTH),
  )
}
