export function normalizeModelCapabilityAlias(value: string | undefined): string | undefined {
  const normalized = value?.trim().toLowerCase().replace(/-/g, '_')
  switch (normalized) {
    case 'text':
    case 'reasoning':
    case 'image':
    case 'image_edit':
    case 'video':
    case 'video_i2v':
    case 'video_v2v':
    case 'audio':
    case 'audio_tts':
    case 'audio_transcribe':
    case 'audio_translate':
    case 'audio_music':
    case 'audio_sfx':
    case 'audio_chat':
    case 'voice_clone':
    case 'voice_design':
    case 'subtitle_align':
    case 'subtitle_translate':
      return normalized
    case 'text_to_image':
    case 'image_generation':
    case 'prompt_to_image':
    case 't2i':
    case 'txt2img':
      return 'image'
    case 'image_to_image':
    case 'i2i':
    case 'img2img':
      return 'image_edit'
    case 'text_to_video':
    case 'video_generation':
    case 'prompt_to_video':
    case 't2v':
    case 'txt2video':
      return 'video'
    case 'image_to_video':
    case 'i2v':
    case 'img2video':
      return 'video_i2v'
    case 'video_to_video':
    case 'v2v':
      return 'video_v2v'
    case 'text_generation':
    case 'prompt_to_text':
      return 'text'
    case 'tts':
    case 'text_to_speech':
    case 'voiceover':
    case 'voiceover_generation':
    case 'audio_voiceover':
      return 'audio_tts'
    case 'speech_translation':
    case 'audio_translation':
    case 'translate_audio':
      return 'audio_translate'
    case 'speech_to_text':
    case 'stt':
    case 'transcription':
    case 'subtitle':
    case 'subtitle_generate':
    case 'generate_subtitle':
    case 'transcribe_subtitle':
      return 'audio_transcribe'
    case 'voice_chat':
    case 'audio_conversation':
    case 'audio_omni':
    case 'omni':
    case 'realtime_audio':
      return 'audio_chat'
    case 'music':
    case 'music_generation':
    case 'generate_music':
      return 'audio_music'
    case 'sfx':
    case 'sound_effect':
    case 'sound_effects':
    case 'sound_effect_generation':
    case 'generate_sfx':
      return 'audio_sfx'
    case 'clone_voice':
    case 'voice_cloning':
      return 'voice_clone'
    case 'design_voice':
    case 'voice_generation':
      return 'voice_design'
    case 'forced_alignment':
    case 'subtitle_alignment':
    case 'align_subtitles':
      return 'subtitle_align'
    case 'subtitle_translation':
    case 'translate_subtitles':
    case 'translate_subtitle':
      return 'subtitle_translate'
    default:
      return undefined
  }
}
