import { PROJECT_SURFACE_ROUTES } from '@movscript/project-surface/routes'
import { RESOURCE_SURFACE_ROUTES } from '@movscript/resource-surface/routes'

export const ROUTES = {
  root: '/',
  toolHome: '/tools',
  canvases: '/canvases',
  canvasEditor: '/canvases/:id',
  editing: '/editing',
  editingProject: '/editing/:editingProjectId',
  shotLibrary: '/shot-library',
  jobs: '/jobs',
  toolRoute: '/tools/:toolId',
  tools: {
    refImageGen: '/tools/ref-image-gen',
    refVideoGen: '/tools/ref-video-gen',
    audioGen: '/tools/audio-gen',
    audioTranscribe: '/tools/audio-transcribe',
    audioTranslate: '/tools/audio-translate',
    musicGen: '/tools/music-gen',
    audioSfx: '/tools/audio-sfx',
    voiceClone: '/tools/voice-clone',
    voiceDesign: '/tools/voice-design',
    motionImitation: '/tools/motion-imitation',
    styleTransfer: '/tools/style-transfer',
    multiAngle: '/tools/multi-angle',
  },
  projects: '/projects',
  resources: RESOURCE_SURFACE_ROUTES.resources,
  externalResources: RESOURCE_SURFACE_ROUTES.externalResources,
  agentResources: RESOURCE_SURFACE_ROUTES.agentResources,
  agentResourceDetail: RESOURCE_SURFACE_ROUTES.agentResourceDetail,
  studioProject: '/studio/*',
  studioOverview: PROJECT_SURFACE_ROUTES.overview,
  studioScripts: PROJECT_SURFACE_ROUTES.scripts,
  studioStandards: PROJECT_SURFACE_ROUTES.standards,
  studioContent: PROJECT_SURFACE_ROUTES.content,
  studioSettings: PROJECT_SURFACE_ROUTES.settings,
} as const
