import { PROJECT_SURFACE_ROUTES } from '@movscript/project-surface/routes'
import { RESOURCE_SURFACE_ROUTES } from '@movscript/resource-surface/routes'

export const ROUTES = {
  root: '/',
  toolHome: '/tools',
  canvases: '/canvases',
  canvasEditor: '/canvases/:id',
  editing: '/editing',
  editingProject: '/editing/:editingProjectId',
  shotLibrary: '/shot-library',
  jobs: '/jobs',
  toolRoute: '/tools/:toolId',
  tools: {
    image: '/tools/image',
    video: '/tools/video',
    audio: '/tools/audio',
    text: '/tools/text',
  },
  projects: '/projects',
  resources: RESOURCE_SURFACE_ROUTES.resources,
  externalResources: RESOURCE_SURFACE_ROUTES.externalResources,
  agentResources: RESOURCE_SURFACE_ROUTES.agentResources,
  agentResourceDetail: RESOURCE_SURFACE_ROUTES.agentResourceDetail,
  studioProject: '/studio/*',
  studioOverview: PROJECT_SURFACE_ROUTES.overview,
  studioScripts: PROJECT_SURFACE_ROUTES.scripts,
  studioStandards: PROJECT_SURFACE_ROUTES.standards,
  studioContent: PROJECT_SURFACE_ROUTES.content,
  studioContentCanvas: PROJECT_SURFACE_ROUTES.contentCanvas,
  studioContentPreview: PROJECT_SURFACE_ROUTES.contentPreview,
  studioRemotionStudio: PROJECT_SURFACE_ROUTES.remotionStudio,
  studioSettingPreview: PROJECT_SURFACE_ROUTES.settingPreview,
  studioSettings: PROJECT_SURFACE_ROUTES.settings,
} as const
