import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { test } from 'node:test'
import { fileURLToPath } from 'node:url'

const testDir = dirname(fileURLToPath(import.meta.url))
const resourceRoot = resolve(testDir, '../../..')
const repoRoot = resolve(resourceRoot, '../..')

function readResourceSource(path) {
  return readFileSync(resolve(resourceRoot, path), 'utf8')
}

function readRepoSource(path) {
  return readFileSync(resolve(repoRoot, path), 'utf8')
}

test('resource page context menu positioning is owned by the resource interaction helper', () => {
  const resourcePageSource = readResourceSource('src/features/components/ResourcesPage.tsx')
  const resourceBrowserSource = readResourceSource('src/resource-browser.ts')
  const resourceItemsSource = readResourceSource('src/features/components/ResourcesPageItems.tsx')
  const externalResourceSearchSource = readResourceSource('src/features/components/ResourcesPageExternalSearch.tsx')
  const externalResourceSearchControllerSource = readResourceSource('src/features/application/useExternalResourceSearchController.ts')
  const resourceSurfaceIndexSource = readResourceSource('src/index.ts')
  const resourceSurfaceDragPayloadSource = readResourceSource('src/resourceDragPayload.ts')
  const interactionSource = readResourceSource('src/resourceInteraction.ts')
  const externalSearchSnapshotSource = readResourceSource('src/features/application/externalResourceSearchSnapshot.ts')
  const coreResourcesIndexSource = readRepoSource('packages/core/src/resources/index.ts')
  const coreDragPayloadSource = readRepoSource('packages/core/src/resources/dragPayload.ts')
  const canvasResourceShelfSource = readRepoSource('surface/canvas/src/features/ui/CanvasResourceShelf.tsx')
  const desktopResourcePanelItemsSource = readRepoSource('apps/desktop/src/shared/ui/ResourcePanelItems.tsx')

  assert.equal(existsSync(resolve(resourceRoot, 'src/features/domain/resourceInteraction.ts')), false)
  assert.equal(existsSync(resolve(resourceRoot, 'src/features/domain/resourceDragPayload.ts')), false)
  assert.match(resourceSurfaceIndexSource, /from '\.\/resourceInteraction\.js'/)
  assert.match(resourceSurfaceIndexSource, /from '\.\/resourceDragPayload\.js'/)
  assert.match(coreResourcesIndexSource, /export \* from '\.\/dragPayload\.js'/)
  assert.match(coreDragPayloadSource, /export const RESOURCE_ID_DRAG_TYPE/)
  assert.match(coreDragPayloadSource, /export function writeResourceDragPayload/)
  assert.match(coreDragPayloadSource, /export function readResourceDragPayload/)
  assert.match(resourceSurfaceDragPayloadSource, /from '@movscript\/core\/resources'/)
  assert.doesNotMatch(resourceSurfaceDragPayloadSource, /setData\(RESOURCE_ID_DRAG_TYPE/)
  assert.match(interactionSource, /export function resourceContextMenuPositionFromClient/)
  assert.match(interactionSource, /export function resourceContextMenuPositionFromEvent/)
  assert.match(interactionSource, /export function resourceViewportBoundaryFromWindow/)
  assert.match(interactionSource, /export function startResourceDragSource/)
  assert.match(interactionSource, /export function isResourceInteractiveDragTarget/)
  assert.match(interactionSource, /export function acceptResourceDropDragOver/)
  assert.match(interactionSource, /export function resolveResourceDropResource/)
  assert.match(resourcePageSource, /useResourceLibraryController\(\{/)
  assert.match(resourceBrowserSource, /resourceContextMenuPositionFromEvent\(event, resourceViewportBoundaryFromWindow\(window\)\)/)
  assert.match(resourceBrowserSource, /resourceViewportBoundaryFromWindow\(window\)/)
  assert.match(externalSearchSnapshotSource, /export function loadExternalResourceSearchSnapshot/)
  assert.match(externalSearchSnapshotSource, /EXTERNAL_RESOURCE_SEARCH_DESKTOP_STATE_KEY = 'movscript-external-resource-search-last-v1'/)
  assert.match(externalSearchSnapshotSource, /getDesktopState/)
  assert.match(externalSearchSnapshotSource, /setDesktopState/)
  assert.match(externalSearchSnapshotSource, /removeBrowserStorageItem\('local', EXTERNAL_RESOURCE_SEARCH_STORAGE_KEY\)/)
  assert.doesNotMatch(externalSearchSnapshotSource, /window\.localStorage/)
  assert.match(externalResourceSearchSource, /useExternalResourceSearchController\(\)/)
  assert.doesNotMatch(externalResourceSearchSource, /loadExternalResourceSearchSnapshot\(\)/)
  assert.doesNotMatch(externalResourceSearchSource, /subscribeExternalResourceSearchSnapshot/)
  assert.doesNotMatch(externalResourceSearchSource, /saveExternalResourceSearchSnapshot\(\{/)
  assert.match(externalResourceSearchControllerSource, /loadExternalResourceSearchSnapshot\(\)/)
  assert.match(externalResourceSearchControllerSource, /subscribeExternalResourceSearchSnapshot/)
  assert.match(externalResourceSearchControllerSource, /externalSearchUserEditedRef/)
  assert.match(externalResourceSearchControllerSource, /saveExternalResourceSearchSnapshot\(\{/)
  assert.match(resourceBrowserSource, /startResourceDragSource\(\{/)
  assert.match(resourceItemsSource, /startResourceDragSource\(\{/)
  assert.match(resourceItemsSource, /from '\.\.\/\.\.\/resourceInteraction\.js'/)
  assert.match(canvasResourceShelfSource, /startResourceDragSource\(\{/)
  assert.match(canvasResourceShelfSource, /from '@movscript\/resource-surface\/resource-interaction'/)
  assert.match(desktopResourcePanelItemsSource, /startResourceDragSource\(\{/)
  assert.match(desktopResourcePanelItemsSource, /from '@movscript\/resource-surface\/resource-interaction'/)
  assert.doesNotMatch(resourcePageSource + resourceBrowserSource, /window\.localStorage\.(getItem|setItem|removeItem)/)
  assert.doesNotMatch(resourcePageSource + resourceBrowserSource, /setContextMenu\(\{\s*x: event\.clientX,\s*y: event\.clientY/)
  assert.doesNotMatch(resourcePageSource + resourceBrowserSource, /writeResourceDragPayload\(/)
  assert.doesNotMatch(resourcePageSource + resourceBrowserSource, /function isResourceInteractiveTarget/)
  assert.doesNotMatch(desktopResourcePanelItemsSource, /writeResourceDragPayload\(/)
  assert.doesNotMatch(canvasResourceShelfSource, /writeResourceDragPayload\(/)
  assert.doesNotMatch(canvasResourceShelfSource + desktopResourcePanelItemsSource, /@movscript\/agent-surface/)
})

test('project resource binding controls are hidden when the host disables project scope', () => {
  const resourcePageSource = readResourceSource('src/features/components/ResourcesPage.tsx')
  const resourceBrowserSource = readResourceSource('src/resource-browser.ts')
  const resourceToolbarSource = readResourceSource('src/features/components/ResourcesPageToolbar.tsx')
  const resourceContentSource = readResourceSource('src/features/components/ResourcesPageLibraryContent.tsx')
  const resourceItemsSource = readResourceSource('src/features/components/ResourcesPageItems.tsx')
  const controllerSource = readResourceSource('src/features/components/useResourceLibraryController.ts')

  assert.match(controllerSource, /projectScopeEnabled = appSettings\?\.launchMode !== 'local'/)
  assert.match(resourceBrowserSource, /projectScopeEnabled = true/)
  assert.match(resourceBrowserSource, /nextScope === 'project' && !projectScopeEnabled/)
  assert.match(resourceBrowserSource, /if \(tab === 'project' && !projectScopeEnabled\) return/)
  assert.match(resourceToolbarSource, /tabItem\.value === 'project' && !projectScopeEnabled/)
  assert.match(resourceToolbarSource, /projectScopeEnabled \? \(/)
  assert.match(resourcePageSource, /projectScopeEnabled=\{controller\.projectScopeEnabled\}/)
  assert.match(resourceContentSource, /onShareToProject=\{projectScopeEnabled \?/)
  assert.match(resourceItemsSource, /canShareToProject \? \(/)
})
