import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { test } from 'node:test'

test('resource page context menu positioning is owned by the resource interaction helper', () => {
  const resourcePageSource = readFileSync(resolve('src/features/resources/components/ResourcesPage.tsx'), 'utf8')
  const resourceLibraryControllerSource = readFileSync(resolve('src/features/resources/components/useResourceLibraryController.ts'), 'utf8')
  const externalResourceSearchSource = readFileSync(resolve('src/features/resources/components/ResourcesPageExternalSearch.tsx'), 'utf8')
  const externalResourceSearchControllerSource = readFileSync(resolve('src/features/resources/application/useExternalResourceSearchController.ts'), 'utf8')
  const resourcePanelSource = readFileSync(resolve('src/shared/ui/ResourcePanel.tsx'), 'utf8')
  const resourcePanelItemsSource = readFileSync(resolve('src/shared/ui/ResourcePanelItems.tsx'), 'utf8')
  const canvasResourceShelfSource = readFileSync(resolve('src/features/canvas/ui/CanvasResourceShelf.tsx'), 'utf8')
  const toolDialogSource = readFileSync(resolve('src/features/tools/components/ToolDialog.tsx'), 'utf8')
  const interactionSource = readFileSync(resolve('src/features/resources/domain/resourceInteraction.ts'), 'utf8')
  const externalSearchSnapshotSource = readFileSync(resolve('src/features/resources/application/externalResourceSearchSnapshot.ts'), 'utf8')

  assert.match(interactionSource, /export function resourceContextMenuPositionFromClient/)
  assert.match(interactionSource, /export function resourceContextMenuPositionFromEvent/)
  assert.match(interactionSource, /export function resourceViewportBoundaryFromWindow/)
  assert.match(interactionSource, /export function startResourceDragSource/)
  assert.match(interactionSource, /export function isResourceInteractiveDragTarget/)
  assert.match(interactionSource, /export function acceptResourceDropDragOver/)
  assert.match(interactionSource, /export function resolveResourceDropResource/)
  assert.match(resourcePageSource, /useResourceLibraryController\(\)/)
  assert.match(resourceLibraryControllerSource, /resourceContextMenuPositionFromEvent\(event, resourceViewportBoundaryFromWindow\(window\)\)/)
  assert.match(resourceLibraryControllerSource, /resourceViewportBoundaryFromWindow\(window\)/)
  assert.match(externalSearchSnapshotSource, /export function loadExternalResourceSearchSnapshot/)
  assert.match(externalSearchSnapshotSource, /EXTERNAL_RESOURCE_SEARCH_DESKTOP_STATE_KEY = 'movscript-external-resource-search-last-v1'/)
  assert.match(externalSearchSnapshotSource, /getDesktopState/)
  assert.match(externalSearchSnapshotSource, /setDesktopState/)
  assert.match(externalSearchSnapshotSource, /removeBrowserStorageItem\('local', EXTERNAL_RESOURCE_SEARCH_STORAGE_KEY\)/)
  assert.doesNotMatch(externalSearchSnapshotSource, /window\.localStorage/)
  assert.match(externalResourceSearchSource, /useExternalResourceSearchController\(\)/)
  assert.doesNotMatch(externalResourceSearchSource, /loadExternalResourceSearchSnapshot\(\)/)
  assert.doesNotMatch(externalResourceSearchSource, /subscribeExternalResourceSearchSnapshot/)
  assert.doesNotMatch(externalResourceSearchSource, /saveExternalResourceSearchSnapshot\(\{/)
  assert.match(externalResourceSearchControllerSource, /loadExternalResourceSearchSnapshot\(\)/)
  assert.match(externalResourceSearchControllerSource, /subscribeExternalResourceSearchSnapshot/)
  assert.match(externalResourceSearchControllerSource, /externalSearchUserEditedRef/)
  assert.match(externalResourceSearchControllerSource, /saveExternalResourceSearchSnapshot\(\{/)
  assert.match(resourceLibraryControllerSource, /startResourceDragSource\(\{/)
  assert.match(resourcePanelSource, /from '@\/shared\/ui\/ResourcePanelItems'/)
  assert.match(resourcePanelItemsSource, /startResourceDragSource\(\{/)
  assert.match(canvasResourceShelfSource, /startResourceDragSource\(\{/)
  assert.match(resourceLibraryControllerSource, /position: ResourceClientPoint/)
  assert.match(toolDialogSource, /acceptResourceDropDragOver\(event\.dataTransfer\)/)
  assert.match(toolDialogSource, /resolveResourceDropResource\(\{/)
  assert.doesNotMatch(resourcePageSource + resourceLibraryControllerSource, /event\.clientX/)
  assert.doesNotMatch(resourcePageSource + resourceLibraryControllerSource, /event\.clientY/)
  assert.doesNotMatch(resourcePageSource + resourceLibraryControllerSource, /window\.localStorage\.(getItem|setItem|removeItem)/)
  assert.doesNotMatch(resourcePageSource + resourceLibraryControllerSource, /setContextMenu\(\{\s*x: event\.clientX,\s*y: event\.clientY/)
  assert.doesNotMatch(resourcePageSource + resourceLibraryControllerSource, /writeResourceDragPayload\(/)
  assert.doesNotMatch(resourcePageSource + resourceLibraryControllerSource, /function isResourceInteractiveTarget/)
  assert.doesNotMatch(resourcePanelSource, /writeResourceDragPayload\(/)
  assert.doesNotMatch(resourcePanelItemsSource, /writeResourceDragPayload\(/)
  assert.doesNotMatch(canvasResourceShelfSource, /writeResourceDragPayload\(/)
  assert.doesNotMatch(toolDialogSource, /readResourceIdDragPayload/)
})
