import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

test('agent session UI keeps explicit local runtime thread recovery contracts', () => {
  const panelSource = readFileSync(resolve('src/features/agent/components/AIAgentPanel.tsx'), 'utf8')
  const appSource = readFileSync(resolve('src/App.tsx'), 'utf8')
  const appTopControlsSource = readFileSync(resolve('src/features/app-shell/components/AppTopControls.tsx'), 'utf8')
  const agentPanelDockControllerSource = readFileSync(resolve('src/features/agent/presentation/useAIAgentPanelDockController.ts'), 'utf8')
  const agentPanelUiStoreSource = readFileSync(resolve('src/features/agent/presentation/agentPanelUiStore.ts'), 'utf8')
  const builtinChatShellSource = readFileSync(resolve('src/features/agent/components/AgentBuiltinChatShell.tsx'), 'utf8')
  const chatViewSource = readFileSync(resolve('src/features/agent/components/AgentChatView.tsx'), 'utf8')
  const chatPanelLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPanelLayout.tsx'), 'utf8')
  const chatPageLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPageLayout.tsx'), 'utf8')
  const chatViewControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatViewController.ts'), 'utf8')
  const threadSectionSource = readFileSync(resolve('src/features/agent/components/AgentConversationThreadSection.tsx'), 'utf8')
  const clientSource = readFileSync(resolve('src/shared/infrastructure/localAgentClient.ts'), 'utf8')
  const sessionStoreSource = readFileSync(resolve('src/features/agent/state/agentSessionStore.ts'), 'utf8')
  const agentStoreSource = readFileSync(resolve('src/features/agent/state/agentStore.ts'), 'utf8')
  const runtimeHydrationHookSource = readFileSync(resolve('src/features/agent/presentation/useAgentRuntimeThreadHydration.ts'), 'utf8')
  const conversationHydrationSource = readFileSync(resolve('src/features/agent/application/agentRuntimeThreadConversationHydration.ts'), 'utf8')
  const agentConversationSource = readFileSync(resolve('../../packages/conversation/src/index.ts'), 'utf8')
  const protocolSource = readFileSync(resolve('../../packages/protocol/src/index.ts'), 'utf8')
  const sendActivitySource = readFileSync(resolve('src/features/agent/application/agentSendActivity.ts'), 'utf8')
  const sendCompletionSource = readFileSync(resolve('src/features/agent/application/agentSendCompletion.ts'), 'utf8')
  const sendCommitSource = readFileSync(resolve('src/features/agent/application/agentSendCommit.ts'), 'utf8')
  const runtimeRestoreSource = readFileSync(resolve('src/features/agent/application/agentRuntimeThreadRestore.ts'), 'utf8')
  const builtinChatControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentBuiltinChatController.ts'), 'utf8')
  const interactionControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatInteractionController.ts'), 'utf8')
  const interactionInputsSource = readFileSync(resolve('src/features/agent/presentation/agentChatInteractionInputs.ts'), 'utf8')
  const actionInputsSource = readFileSync(resolve('src/features/agent/presentation/agentChatActionInputs.ts'), 'utf8')
  const sendPipelineInputsSource = readFileSync(resolve('src/features/agent/presentation/agentChatSendPipelineInputs.ts'), 'utf8')
  const sendPipelineSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatSendPipeline.ts'), 'utf8')
  const commitSendHookSource = readFileSync(resolve('src/features/agent/presentation/useAgentCommitSendDraft.ts'), 'utf8')
  const conversationHeaderSource = readFileSync(resolve('src/features/agent/components/AgentChatHeaderSection.tsx'), 'utf8')
  const conversationTabsSource = readFileSync(resolve('src/features/agent/components/AgentConversationTabs.tsx'), 'utf8')
  const conversationTabRuntimeLightsSource = readFileSync(resolve('src/features/agent/presentation/useAgentConversationTabRuntimeStatusLights.ts'), 'utf8')
  const projectAgentModePageSource = readFileSync(resolve('src/features/agent/components/ProjectAgentModePage.tsx'), 'utf8')
  const uiAgentSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/index.tsx'), 'utf8')
  const uiAgentPanelSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/panel.tsx'), 'utf8')
  const uiAgentChatSource = [
    '../../packages/ui/src/components/business/agent/chat/index.tsx',
    '../../packages/ui/src/components/business/agent/chat/types.ts',
    '../../packages/ui/src/components/business/agent/chat/list/index.tsx',
    '../../packages/ui/src/components/business/agent/chat/tabs/index.tsx',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentChatCssSource = [
    '../../packages/ui/src/components/business/agent/chat/styles.css',
    '../../packages/ui/src/components/business/agent/chat/tabs/styles.css',
    '../../packages/ui/src/components/business/agent/chat/history/styles.css',
    '../../packages/ui/src/components/business/agent/chat/toolbar/styles.css',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentShellCssSource = [
    '../../packages/ui/src/components/business/agent/shell/styles.css',
    '../../packages/ui/src/components/business/agent/shell/sidebar/styles.css',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentPanelCssSource = [
    '../../packages/ui/src/components/business/agent/panel/styles.css',
    '../../packages/ui/src/components/business/agent/panel/frame/styles.css',
    '../../packages/ui/src/components/business/agent/panel/card/styles.css',
    '../../packages/ui/src/components/business/agent/panel/composer-mention/styles.css',
    '../../packages/ui/src/components/business/agent/panel/shell-layout/styles.css',
    '../../packages/ui/src/components/business/agent/panel/thread-message/styles.css',
    '../../packages/ui/src/components/business/agent/panel/context/styles.css',
    '../../packages/ui/src/components/business/agent/panel/embedded-runtime/styles.css',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentPageCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/page/styles.css'), 'utf8')
  const uiCssSource = readFileSync(resolve('../../packages/ui/src/styles.css'), 'utf8')
  const uiAgentCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/styles.css'), 'utf8')
  const cssSource = readFileSync(resolve('src/index.css'), 'utf8')
  const zhSource = readFileSync(resolve('src/i18n/locales/zh-CN.json'), 'utf8')
  const enSource = readFileSync(resolve('src/i18n/locales/en-US.json'), 'utf8')

  assert.doesNotMatch(clientSource, /getThreadOrCreate/)
  assert.match(clientSource, /RunMessageResult/)
  assert.match(protocolSource, /export interface RunMessageResult[\s\S]*threadResolution: AgentThreadResolution/)
  assert.match(clientSource, /if \(!options\.input\.threadId \|\| !isLocalAgentNotFoundError\(error\)\) throw error/)
  assert.match(clientSource, /runMessageStream[\s\S]*threadResolution: resolvedThread\.resolution/)

  assert.doesNotMatch(sessionStoreSource, /conversationIdForLocalThread/)
  assert.match(agentConversationSource, /export function conversationIdForRuntimeThread/)
  assert.match(agentStoreSource, /export type Conversation = AgentConversation/)
  assert.match(protocolSource, /runtimeSessionId\?: string/)
  assert.match(protocolSource, /runtimeThreadId\?: string/)
  assert.match(agentStoreSource, /setConversationRuntimeSessionId/)
  assert.match(agentStoreSource, /setConversationRuntimeThreadId/)
  assert.match(agentConversationSource, /conversation\.runtimeSessionId === sessionId/)
  assert.match(agentConversationSource, /conversation\.runtimeThreadId === threadId/)
  assert.match(chatViewSource, /surface === 'page'/)
  assert.match(chatViewSource, /<AgentChatPageLayout/)
  assert.match(chatViewSource, /<AgentChatPanelLayout/)
  assert.match(chatViewControllerSource, /useAgentChatInteractionController\(buildAgentChatInteractionControllerInput\(\{/)
  assert.match(interactionControllerSource, /useAgentChatSendPipeline\(\{/)
  assert.match(interactionInputsSource, /actionBindings: buildAgentChatActionBindingsInput\(options\)/)
  assert.match(interactionInputsSource, /sendPipeline: buildAgentChatSendPipelineInput\(options\)/)
  assert.match(actionInputsSource, /runResultActions: \{/)
  assert.match(actionInputsSource, /messageStore: \{[\s\S]*upsertMessage: store\.messageStore\.upsertMessage/)
  assert.match(actionInputsSource, /workflowActions: \{/)
  assert.match(actionInputsSource, /planActions: \{/)
  assert.match(actionInputsSource, /stopAction: \{/)
  assert.match(sendPipelineInputsSource, /draftBuilder: \{/)
  assert.match(sendPipelineInputsSource, /commitDraft: \{/)
  assert.match(sendPipelineInputsSource, /runtimeThreadHydration: \{/)
  assert.match(sendPipelineInputsSource, /sendActions: \{/)
  assert.match(sendPipelineInputsSource, /sendActions: \{[\s\S]*loading: presentation\.loading/)
  assert.match(sendPipelineSource, /useAgentRuntimeThreadHydration\(runtimeThreadHydration\)/)
  assert.doesNotMatch(conversationHeaderSource, /sort\(\(a, b\) => b\.updatedAt - a\.updatedAt\)/)
  assert.match(conversationHeaderSource, /agents\.chat\.conversationHistory/)
  assert.match(conversationHeaderSource, /historyOpen/)
  assert.match(conversationHeaderSource, /onReorderConversation/)
  assert.match(chatPanelLayoutSource, /const conversationStarted = thread\.messages\.length > 0 \|\| thread\.conversationBlocks\.length > 0 \|\| !!debugPreview\.draft/)
  assert.match(chatPanelLayoutSource, /const emptyConversation = !conversationStarted/)
  assert.match(chatPanelLayoutSource, /setHistoryOpen\(!conversationStarted\)/)
  assert.match(chatPanelLayoutSource, /if \(conversationStarted\) setHistoryOpen\(false\)/)
  assert.match(chatPanelLayoutSource, /historyThreads/)
  assert.match(chatPanelLayoutSource, /agents\.chat\.conversationHistory/)
  assert.match(chatPanelLayoutSource, /agents\.chat\.noHistoryConversations/)
  assert.match(chatPanelLayoutSource, /<AgentConversationThreadSection \{\.\.\.thread\} \/>/)
  assert.match(chatPanelLayoutSource, /const historyPanel = historyOpen \? \(/)
  assert.match(chatPanelLayoutSource, /<AgentComposerSection \{\.\.\.composer\} \/>\s*\{historyPanel\}/)
  assert.doesNotMatch(chatPanelLayoutSource, /const composerInContent = emptyConversation \|\| historyOpen/)
  assert.match(chatPageLayoutSource, /agent-page-chat-empty/)
  assert.match(chatPageLayoutSource, /agent-page-chat-empty-composer/)
  assert.match(chatPageLayoutSource, /const conversationStarted = thread\.messages\.length > 0 \|\| thread\.conversationBlocks\.length > 0 \|\| !!debugPreview\.draft/)
  assert.match(chatPageLayoutSource, /emptyAccessory/)
  assert.match(chatPageLayoutSource, /agent-page-chat-empty-accessory/)
  assert.doesNotMatch(threadSectionSource, /agents\.chat\.startChat/)
  assert.doesNotMatch(threadSectionSource, /AgentSuggestions/)
  assert.match(conversationTabsSource, /<AgentConversationTabsPanel/)
  assert.match(conversationTabsSource, /onReorderConversation=\{onReorderConversation\}/)
  assert.match(conversationTabsSource, /runtimeStatusLights/)
  assert.match(uiAgentChatSource, /draggable/)
  assert.match(uiAgentChatSource, /onReorderConversation\(draggedId, item\.id, position\)/)
  assert.match(uiAgentChatSource, /data-runtime-state/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-conversation-tab-close \{[\s\S]*position: absolute/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-chat-toolbar-tabs \{[\s\S]*overflow: hidden/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-chat-toolbar-actions \{[\s\S]*flex: 0 0 auto/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-chat-toolbar-actions > \.ms-button \{[\s\S]*flex: 0 0 auto/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-chat-toolbar \.ms-button:hover:not\(:disabled\)/)
  assert.match(uiAgentCssSource, /@import "\.\/chat\/styles\.css"/)
  assert.match(uiAgentChatCssSource, /flex: 0 1 min\(42%, 260px\)/)
  assert.match(conversationTabRuntimeLightsSource, /localAgentClient\.getSessionRuntime/)
  assert.match(conversationTabRuntimeLightsSource, /localAgentClient\.getSessionRuntime/)
  assert.match(conversationTabRuntimeLightsSource, /localAgentClient\.getThreadRuntime/)
  assert.match(conversationTabRuntimeLightsSource, /localAgentClient\.streamSession/)
  assert.match(conversationTabRuntimeLightsSource, /localAgentClient\.streamThread/)
  assert.match(conversationTabRuntimeLightsSource, /localThreadIdsByConversation/)
  assert.match(conversationTabRuntimeLightsSource, /sessionIdsByConversation/)
  assert.match(conversationTabRuntimeLightsSource, /sessionIdsByConversation/)
  assert.match(runtimeHydrationHookSource, /hydratedRuntimeThreadKeysRef/)
  assert.match(conversationHydrationSource, /runtimeThreadHydrationKey\(input\.conversationId, sessionId \? `\$\{sessionId\}:\$\{threadId\}` : threadId\)/)
  assert.match(runtimeHydrationHookSource, /const controller = new AbortController\(\)/)
  assert.match(runtimeHydrationHookSource, /building \|\| runtimeBuilding \|\| loading \|\| runtimeLoading/)
  assert.match(runtimeHydrationHookSource, /localAgentClient\.streamSession/)
  assert.match(runtimeHydrationHookSource, /signal: controller\.signal/)
  assert.match(runtimeHydrationHookSource, /controller\.abort\(\)/)
  assert.match(runtimeHydrationHookSource, /loadRuntimeThreadProjection\(\{[\s\S]*threadId/)
  assert.match(conversationHydrationSource, /deps\.messageStore\.setConversationMessages\([\s\S]*mergeRuntimeThreadProjectionMessages\(input\.existingMessages, projection\)/)
  assert.match(agentConversationSource, /markRuntimeMessagesRestored\(projection\.messages, deps\.restoredLabel\)/)
  assert.match(agentConversationSource, /deps\.messageStore\.upsertMessage/)
  assert.match(agentConversationSource, /conversationIdForRuntimeSession/)
  assert.match(agentConversationSource, /conversationIdForRuntimeThread\(\{[\s\S]*localThreadIdsByConversation[\s\S]*conversationRuntimes/)
  assert.match(agentConversationSource, /if \(existingConversationId\) \{[\s\S]*activateConversation\(existingConversationId\)[\s\S]*return/)
  assert.match(panelSource, /<AgentBuiltinChatShell/)
  assert.match(panelSource, /hasOpenConversations/)
  assert.match(panelSource, /className="hidden"/)
  assert.match(appTopControlsSource, /conversationCount === 0 \? Plus : MessageCircle/)
  assert.match(appTopControlsSource, /createConversation\(userId\)/)
  assert.match(appTopControlsSource, /setAgentPanelOpen\(true\)/)
  assert.match(appTopControlsSource, /getAppRouteSurface\(pathname\)/)
  assert.match(appTopControlsSource, /workModeForRoute\(pathname, workMode\)/)
  assert.match(appTopControlsSource, /navigate\(routeForWorkMode\(nextMode, !!current\), \{ replace: routeSurface !== 'detail' \}\)/)
  assert.match(appTopControlsSource, /routeSurface === 'agent'/)
  assert.match(appSource, /function ProjectAgentModeRoute\(\)/)
  assert.match(appSource, /function ProjectAgentModeRoute\(\) \{\s*return <AgentModePage \/>\s*\}/)
  assert.doesNotMatch(appSource, /if \(workMode !== 'agent'\) return <Navigate to=\{ROUTES\.project\.overview\} replace \/>/)
  assert.match(agentPanelDockControllerSource, /DETAIL_AGENT_PANEL_DEFAULT_WIDTH = 320/)
  assert.match(agentPanelDockControllerSource, /DETAIL_AGENT_PANEL_MAX_WIDTH = 420/)
  assert.match(agentPanelDockControllerSource, /Math\.round\(viewportWidth \* 0\.28\)/)
  assert.match(agentPanelDockControllerSource, /const dockLayout = true/)
  assert.doesNotMatch(agentPanelDockControllerSource, /\b680\b/)
  assert.doesNotMatch(agentPanelDockControllerSource, /innerWidth >= 960/)
  assert.doesNotMatch(agentPanelDockControllerSource, /setDockLayout/)
  assert.match(uiAgentPanelSource, /data-dock-layout=\{dockLayout \? "true" : "false"\}/)
  assert.match(uiAgentPanelSource, /className="ai-agent-panel"/)
  assert.doesNotMatch(uiAgentPanelSource, /w-\[/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel\[data-dock-layout="true"\]/)
  assert.match(uiAgentPanelCssSource, /flex: 0 0 var\(--ui-agent-panel-width\)/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel\[data-dock-layout="false"\]/)
  assert.match(uiAgentPanelCssSource, /position: absolute/)
  assert.match(uiAgentPanelCssSource, /width: min\(var\(--ui-agent-panel-width\), calc\(100vw - 24px\)\)/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel__body > \.ai-agent-panel-shell/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell > \.ai-agent-panel-main > \.ai-agent-panel-input-card/)
  assert.match(appTopControlsSource, /toggleAgentModeContentPanelCollapsed/)
  assert.match(appTopControlsSource, /PanelRightOpen/)
  assert.match(appTopControlsSource, /PanelRightClose/)
  assert.match(agentPanelUiStoreSource, /agentModeContentPanelCollapsed: readAgentModeContentPanelCollapsed\(\)/)
  assert.match(agentPanelUiStoreSource, /return saved === null \? true : saved === 'true'/)
  assert.match(agentPanelUiStoreSource, /toggleAgentModeContentPanelCollapsed/)
  assert.match(projectAgentModePageSource, /pageEmptyAccessory=\{<AgentModeProjectSelectCard \/>}/)
  assert.match(projectAgentModePageSource, /agent-page-project-select-card/)
  assert.match(projectAgentModePageSource, /\bButton\b/)
  assert.match(projectAgentModePageSource, /function AgentModeProjectSelectCard[\s\S]*?<Button[\s\S]*?className="agent-page-project-select-card"/)
  assert.match(projectAgentModePageSource, /\bAgentNavItem\b/)
  assert.match(projectAgentModePageSource, /\bAgentConversationItem\b/)
  assert.match(projectAgentModePageSource, /function AgentModeNavItem[\s\S]*?ms-agent-nav-item/)
  assert.match(uiAgentSource, /export const AgentNavItem/)
  assert.match(uiAgentSource, /icon\?: React\.ReactNode/)
  assert.match(uiCssSource, /components\/business\/agent\/styles\.css/)
  assert.match(uiAgentShellCssSource, /\.ms-agent-nav-item\s*\{/)
  assert.match(uiAgentShellCssSource, /\.ms-agent-conversation__icon\s*\{/)
  assert.doesNotMatch(projectAgentModePageSource, /flex h-8 w-full min-w-0 items-center gap-2 rounded-md px-2/)
  assert.doesNotMatch(projectAgentModePageSource, /hover:bg-muted\/50 hover:text-foreground/)
  assert.match(projectAgentModePageSource, /agentModeProjectPicker\.title/)
  assert.match(projectAgentModePageSource, /if \(collapsed \|\| !contentPanelFits\) return null/)
  assert.doesNotMatch(projectAgentModePageSource, /PanelRightOpen/)
  assert.doesNotMatch(projectAgentModePageSource, /PanelRightClose/)
  assert.match(uiAgentCssSource, /page\/styles\.css/)
  assert.match(uiAgentPageCssSource, /agent-page-project-select-card/)
  assert.match(uiAgentPageCssSource, /\.project-agent-chat-shell \.agent-page-chat-main \{[\s\S]*display: flex/)
  assert.doesNotMatch(cssSource, /agent-page-project-select-card/)
  assert.match(zhSource, /"expandAgentContentPanel": "展开右侧内容区"/)
  assert.match(enSource, /"expandAgentContentPanel": "Expand right content panel"/)
  assert.match(builtinChatShellSource, /useAgentBuiltinChatController\(\{/)
  assert.match(builtinChatShellSource, /<AgentChatView/)
  assert.match(builtinChatShellSource, /pageEmptyAccessory/)
  assert.match(builtinChatControllerSource, /restoreRuntimeThreadConversation\(normalizedThreadId, \{/)
  assert.match(builtinChatControllerSource, /consumeQueuedPanelDrafts\(consumeAgentPanelDraft/)
  assert.match(builtinChatControllerSource, /activateConversationForPanelDraft\(detail, \{/)

  assert.match(sendActivitySource, /function threadResolutionActivityEvent/)
  assert.match(sendActivitySource, /本地线程不存在，已创建新线程/)
  assert.match(agentConversationSource, /completeRuntimeSendRunResult/)
  assert.match(agentConversationSource, /appendAssistantRunResult\(run, thread, liveEvents\)/)
  assert.match(agentConversationSource, /mergeRuntimeThreadProjectionMessages\(existingMessages, projection\)/)
  assert.match(sendCompletionSource, /completeRuntimeSendRunResult/)
  assert.match(sendCompletionSource, /threadResolutionActivityEvent/)
  assert.match(sendCompletionSource, /loadRuntimeThreadProjection: \(projectionInput\) => loadRuntimeThreadProjection/)
  assert.match(sendPipelineSource, /useAgentCommitSendDraft\(\{/)
  assert.match(sendPipelineInputsSource, /messageStore: \{/)
  assert.match(commitSendHookSource, /commitAgentSendDraft\(draft, \{/)
  assert.match(commitSendHookSource, /messageStore,/)
  assert.match(agentConversationSource, /interface AgentConversationMessageStore/)
  assert.match(conversationHydrationSource, /messageStore: Pick<AgentConversationMessageStore<ChatMessage, ChatMessageMeta>, 'setConversationMessages'>/)
  assert.match(sendCommitSource, /messageStore: AgentConversationMessageStore<ChatMessage, ChatMessageMeta>/)
  assert.match(sendCommitSource, /completeSendRunResult\(\{/)
})

test('agent session UI keeps worker trace drilldown contracts', () => {
  const planOverviewSource = readFileSync(resolve('src/features/agent/components/AgentPlanOverviewPanel.tsx'), 'utf8')

  assert.match(planOverviewSource, /const \[traceSummaries, setTraceSummaries\]/)
  assert.match(planOverviewSource, /const \[traceEventsByRunId, setTraceEventsByRunId\]/)
  assert.match(planOverviewSource, /localAgentClient\.getRunTraceSummary\(runId\)/)
  assert.match(planOverviewSource, /localAgentClient\.getRunTraceEvents\(runId, \{ limit: 8/)
  assert.match(planOverviewSource, /traceEventHasMoreByRunId/)
  assert.match(planOverviewSource, /traceEventKindFilters/)
  assert.match(planOverviewSource, /轨迹统计/)
  assert.match(planOverviewSource, /运行事件/)
  assert.match(planOverviewSource, /加载更多/)
})

test('agent session UI pins live task, plan, and subagent status at top of the thread', () => {
  const threadSectionSource = readFileSync(resolve('src/features/agent/components/AgentConversationThreadSection.tsx'), 'utf8')
  const layoutPropsSource = readFileSync(resolve('src/features/agent/presentation/agentChatViewLayoutProps.ts'), 'utf8')
  const conversationPresentationSource = readFileSync(resolve('src/features/agent/domain/agentConversationPresentation.ts'), 'utf8')
  const pinnedStatusShelfSource = readFileSync(resolve('src/features/agent/components/AgentPinnedStatusShelf.tsx'), 'utf8')
  const derivedStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatDerivedState.ts'), 'utf8')

  assert.match(threadSectionSource, /<AgentPinnedStatusShelf/)
  assert.match(layoutPropsSource, /generationProgressStates: presentation\.generationProgressStates/)
  assert.match(derivedStateSource, /generationProgressStatesForPinnedStatus/)
  assert.match(conversationPresentationSource, /showLiveRunActivity/)
  assert.doesNotMatch(conversationPresentationSource, /blocks\.push\(\.\.\.generationProgressStates/)
  assert.match(pinnedStatusShelfSource, /data-testid="agent-pinned-status-shelf"/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.tabs\.generation/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.tabs\.worker/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.workersCount/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.tabs\.plan/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.viewPlanDetails/)
  assert.match(pinnedStatusShelfSource, /const \[collapsed, setCollapsed\] = useState\(false\)/)
  assert.match(pinnedStatusShelfSource, /aria-expanded=\{!collapsed\}/)
  assert.match(pinnedStatusShelfSource, /aria-controls="agent-pinned-status-shelf-body"/)
  assert.match(pinnedStatusShelfSource, /event\.target !== event\.currentTarget/)
  assert.match(pinnedStatusShelfSource, /!collapsed && activeCount > 0/)
  assert.match(pinnedStatusShelfSource, /h-28 overflow-y-auto overscroll-contain/)
})

test('agent session UI routes pending input answers before starting a new run', () => {
  const chatViewSource = readFileSync(resolve('src/features/agent/components/AgentChatView.tsx'), 'utf8')
  const chatViewControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatViewController.ts'), 'utf8')
  const chatPanelLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPanelLayout.tsx'), 'utf8')
  const chatPageLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPageLayout.tsx'), 'utf8')
  const interactionControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatInteractionController.ts'), 'utf8')
  const derivedStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatDerivedState.ts'), 'utf8')
  const workflowStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatWorkflowState.ts'), 'utf8')
  const composerSource = readFileSync(resolve('src/features/agent/components/AgentComposerSection.tsx'), 'utf8')
  const threadSectionSource = readFileSync(resolve('src/features/agent/components/AgentConversationThreadSection.tsx'), 'utf8')
  const threadItemsSource = readFileSync(resolve('src/features/agent/domain/agentConversationThreadItems.ts'), 'utf8')
  const chatActionBindingsSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatActionBindings.ts'), 'utf8')
  const sendActionsSource = readFileSync(resolve('src/features/agent/presentation/useAgentSendActions.ts'), 'utf8')
  const workflowBindingsSource = readFileSync(resolve('src/features/agent/presentation/useAgentWorkflowActionBindings.ts'), 'utf8')
  const workflowActionsSource = readFileSync(resolve('src/features/agent/application/agentWorkflowActions.ts'), 'utf8')
  const runPageSource = readFileSync(resolve('src/features/agent/components/AIAgentRunPage.tsx'), 'utf8')

  assert.match(derivedStateSource, /useAgentChatWorkflowState\(\{/)
  assert.match(workflowStateSource, /const activePendingInputRequest = firstPendingInputRequest\(actionableLocalRun\)/)
  assert.match(workflowStateSource, /const answeringPendingInput = !!activePendingInputRequest/)
  assert.match(chatViewSource, /useAgentChatViewController\(props\)/)
  assert.match(chatViewControllerSource, /useAgentChatInteractionController\(buildAgentChatInteractionControllerInput\(\{/)
  assert.match(interactionControllerSource, /useAgentChatActionBindings\(actionBindings\)/)
  assert.match(chatActionBindingsSource, /useAgentWorkflowActionBindings\(\{/)
  assert.match(workflowBindingsSource, /answerWorkflowRunInputAction\(\{/)
  assert.match(workflowActionsSource, /sourceMessageId: localMessageId/)
  assert.match(workflowActionsSource, /answerRunInput\(run\.id, \{[\s\S]*requestId,[\s\S]*\.\.\.answer,[\s\S]*sourceMessageId/)
  assert.match(workflowActionsSource, /optimisticInputAnswerRun\(run, requestId, answer\)/)
  assert.match(workflowStateSource, /workflowAnswerEchoesForMessages\(messages, workflowRuns\)/)
  assert.match(chatViewSource, /<AgentChatPanelLayout/)
  assert.match(chatViewSource, /<AgentChatPageLayout/)
  assert.match(chatPanelLayoutSource, /<AgentConversationThreadSection/)
  assert.match(chatPageLayoutSource, /<AgentConversationThreadSection/)
  assert.match(threadSectionSource, /buildAgentConversationThreadItems\(\{/)
  assert.match(threadSectionSource, /<LocalAgentWorkflowBubble/)
  assert.match(threadItemsSource, /isWorkflowAnswerEchoMessage\(message, workflowAnswerEchoes\)/)
  assert.match(threadItemsSource, /workflowRunFromActivity\(message\.meta\?\.localRunActivity\)/)
  assert.match(chatPanelLayoutSource, /<AgentComposerSection/)
  assert.match(chatPageLayoutSource, /<AgentComposerSection/)
  assert.match(composerSource, /answeringPendingInput \? '回答' : debugBeforeSend/)
  assert.match(composerSource, /buildingSendDraft \|\| \(answeringPendingInput && !canAnswerPendingInputWithText\)/)
  assert.match(sendActionsSource, /answerActiveLocalRunInput\(activePendingInputRequest\.id, \{ text \}\)/)
  assert.match(sendActionsSource, /if \(canSendActiveRunRuntimeInput\)/)
  assert.match(sendActionsSource, /sendActiveRunRuntimeInput\(\{ content, attachments \}\)/)

  const pendingBranch = sendActionsSource.indexOf('if (answeringPendingInput && activePendingInputRequest)')
  const runtimeInputPath = sendActionsSource.indexOf('if (canSendActiveRunRuntimeInput)')
  const newRunPath = sendActionsSource.indexOf('const draft = await buildSendDraft')
  assert.ok(pendingBranch > 0, 'pending input answer branch must exist in send()')
  assert.ok(newRunPath > pendingBranch, 'pending input must be handled before building a new send draft')
  assert.ok(runtimeInputPath > pendingBranch, 'active run runtime input branch must run after pending input answers')
  assert.ok(newRunPath > runtimeInputPath, 'active run messages must be routed as runtime input before building a new send draft')

  assert.match(runPageSource, /import \{ LocalAgentInputRequestCard \}/)
  assert.match(runPageSource, /<LocalAgentInputRequestCard/)
  assert.doesNotMatch(runPageSource, /inputDrafts/)
})

test('agent session UI renders generation job approvals as summary cards', () => {
  const workflowBubbleSource = readFileSync(resolve('src/features/agent/components/AgentWorkflowBubble.tsx'), 'utf8')

  assert.match(workflowBubbleSource, /GenerationJobApprovalDetails/)
  assert.match(workflowBubbleSource, /generationJobApprovalView\(approval\)/)
  assert.match(workflowBubbleSource, /approval\.toolName === 'core_work_start' && kind === 'generation_job'/)
  assert.match(workflowBubbleSource, /approval\.toolName !== 'generation_job_create'/)
  assert.match(workflowBubbleSource, /view\.targetLabel/)
  assert.match(workflowBubbleSource, /view\.prompt/)
  assert.match(workflowBubbleSource, /referenceResourceIds/)
  assert.match(workflowBubbleSource, /ApprovalResourceThumbnail resourceId=\{previewResourceId\}/)
  assert.match(workflowBubbleSource, /resourceFileUrl\(resourceId\)/)
  assert.match(workflowBubbleSource, /safeJSONStringify\(approval\.args\)/)
})

test('agent session UI renders asset slot candidate approvals as summary cards', () => {
  const workflowBubbleSource = readFileSync(resolve('src/features/agent/components/AgentWorkflowBubble.tsx'), 'utf8')

  assert.match(workflowBubbleSource, /AssetSlotCandidateApprovalDetails/)
  assert.match(workflowBubbleSource, /assetSlotCandidateApprovalView\(approval\)/)
  assert.match(workflowBubbleSource, /approval\.toolName !== 'candidate_asset_slot_attach'/)
  assert.match(workflowBubbleSource, /素材槽 #/)
  assert.match(workflowBubbleSource, /只加入候选集，不会锁定、采纳或替换当前素材。/)
  assert.match(workflowBubbleSource, /output_resource_id/)
  assert.match(workflowBubbleSource, /resource_id/)
  assert.match(workflowBubbleSource, /AuthedImage/)
})

test('agent panel keeps recent resources as mention candidates, not automatic context labels', () => {
  const chatViewSource = readFileSync(resolve('src/features/agent/components/AgentChatView.tsx'), 'utf8')
  const composerStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatComposerState.ts'), 'utf8')
  const composerControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentComposerController.ts'), 'utf8')
  const sendDraftSource = readFileSync(resolve('src/features/agent/application/agentSendDraft.ts'), 'utf8')

  assert.doesNotMatch(chatViewSource, /recentResourcesCount/)
  assert.doesNotMatch(composerStateSource, /recentResourcesCount/)
  assert.match(composerStateSource, /recentResources,\s*fileRef,\s*inputRef/)
  assert.match(composerControllerSource, /for \(const resource of recentResources\)[\s\S]*attachmentFromResource\(resource\)/)
  assert.match(composerControllerSource, /input\.matchAll\(RESOURCE_MENTION_RE\)/)
  assert.match(sendDraftSource, /recentResources: \[\]/)
})

test('agent panel no longer renders the context card surface', () => {
  const chatViewSource = readFileSync(resolve('src/features/agent/components/AgentChatView.tsx'), 'utf8')
  const chatViewControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatViewController.ts'), 'utf8')
  const chatPanelLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPanelLayout.tsx'), 'utf8')
  const chatPageLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPageLayout.tsx'), 'utf8')
  const contextStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatContextState.ts'), 'utf8')

  assert.match(chatViewSource, /useAgentChatViewController\(props\)/)
  assert.match(chatViewControllerSource, /useAgentChatContextState\(\{/)
  assert.match(contextStateSource, /useAgentContextSummary\(\{/)
  assert.match(chatViewSource, /<AgentChatPanelLayout/)
  assert.match(chatViewSource, /<AgentChatPageLayout/)
  assert.doesNotMatch(chatPanelLayoutSource, /AgentContextSection/)
  assert.doesNotMatch(chatPanelLayoutSource, /context:/)
  assert.doesNotMatch(chatPageLayoutSource, /AgentContextSection/)
  assert.doesNotMatch(chatPageLayoutSource, /context:/)
  assert.doesNotMatch(contextStateSource, /useAgentContextPaneController/)
})
