import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

test('agent session UI keeps explicit local runtime thread recovery contracts', () => {
  const panelSource = readFileSync(resolve('src/features/agent/components/AIAgentPanel.tsx'), 'utf8')
  const appSource = readFileSync(resolve('src/App.tsx'), 'utf8')
  const frontendArchitectureSource = readFileSync(resolve('src/features/agent/ARCHITECTURE.md'), 'utf8')
  const appTopControlsSource = readFileSync(resolve('src/features/app-shell/components/AppTopControls.tsx'), 'utf8')
  const agentPanelDockControllerSource = readFileSync(resolve('src/features/agent/presentation/useAIAgentPanelDockController.ts'), 'utf8')
  const agentPanelUiStoreSource = readFileSync(resolve('src/features/agent/presentation/agentPanelUiStore.ts'), 'utf8')
  const builtinChatShellSource = readFileSync(resolve('src/features/agent/components/AgentBuiltinChatShell.tsx'), 'utf8')
  const chatViewSource = readFileSync(resolve('src/features/agent/components/AgentChatView.tsx'), 'utf8')
  const chatPanelLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPanelLayout.tsx'), 'utf8')
  const chatPageLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPageLayout.tsx'), 'utf8')
  const chatPresentationStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatPresentationState.ts'), 'utf8')
  const chatStoreBindingsSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatStoreBindings.ts'), 'utf8')
  const chatViewControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatViewController.ts'), 'utf8')
  const threadSectionSource = readFileSync(resolve('src/features/agent/components/AgentConversationThreadSection.tsx'), 'utf8')
  const clientSource = readFileSync(resolve('src/shared/infrastructure/localAgentClient.ts'), 'utf8')
  const sessionStoreSource = readFileSync(resolve('src/features/agent/state/agentSessionStore.ts'), 'utf8')
  const agentStoreSource = readFileSync(resolve('src/features/agent/state/agentStore.ts'), 'utf8')
  const agentConversationSource = readFileSync(resolve('../../packages/conversation/src/index.ts'), 'utf8')
  const protocolSource = readFileSync(resolve('../../packages/protocol/src/index.ts'), 'utf8')
  const sendActivitySource = readFileSync(resolve('src/features/agent/application/agentSendActivity.ts'), 'utf8')
  const sendCompletionSource = readFileSync(resolve('src/features/agent/application/agentSendCompletion.ts'), 'utf8')
  const sendCommitSource = readFileSync(resolve('src/features/agent/application/agentSendCommit.ts'), 'utf8')
  const runtimeRestoreSource = readFileSync(resolve('src/features/agent/application/agentRuntimeThreadRestore.ts'), 'utf8')
  const builtinChatControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentBuiltinChatController.ts'), 'utf8')
  const interactionControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatInteractionController.ts'), 'utf8')
  const interactionInputsSource = readFileSync(resolve('src/features/agent/presentation/agentChatInteractionInputs.ts'), 'utf8')
  const actionInputsSource = readFileSync(resolve('src/features/agent/presentation/agentChatActionInputs.ts'), 'utf8')
  const sendPipelineInputsSource = readFileSync(resolve('src/features/agent/presentation/agentChatSendPipelineInputs.ts'), 'utf8')
  const sendPipelineSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatSendPipeline.ts'), 'utf8')
  const commitSendHookSource = readFileSync(resolve('src/features/agent/presentation/useAgentCommitSendWorkspace.ts'), 'utf8')
  const conversationHeaderSource = readFileSync(resolve('src/features/agent/components/AgentChatHeaderSection.tsx'), 'utf8')
  const conversationHeaderActionsSource = readFileSync(resolve('src/features/agent/components/AgentChatHeaderActions.tsx'), 'utf8')
  const conversationListSource = readFileSync(resolve('src/features/agent/components/AgentConversationList.tsx'), 'utf8')
  const composerSectionSource = readFileSync(resolve('src/features/agent/components/AgentComposerSection.tsx'), 'utf8')
  const mentionEditorSource = readFileSync(resolve('src/features/agent/components/AgentMentionEditor.tsx'), 'utf8')
  const conversationTabsSource = readFileSync(resolve('src/features/agent/components/AgentConversationTabs.tsx'), 'utf8')
  const conversationTabRuntimeLightsSource = readFileSync(resolve('src/features/agent/presentation/useAgentConversationTabRuntimeStatusLights.ts'), 'utf8')
  const runtimeStatusLightControllerSource = readFileSync(resolve('src/features/agent/presentation/agentRuntimeStatusLightController.ts'), 'utf8')
  const projectAgentModePageSource = readFileSync(resolve('src/features/agent/components/ProjectAgentModePage.tsx'), 'utf8')
  const uiAgentSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/index.tsx'), 'utf8')
  const uiAgentModeSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/mode/index.tsx'), 'utf8')
  const uiAgentModeCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/mode/styles.css'), 'utf8')
  const uiAgentPanelSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/panel.tsx'), 'utf8')
  const uiAgentChatSource = [
    '../../packages/ui/src/components/business/agent/chat/index.tsx',
    '../../packages/ui/src/components/business/agent/chat/types.ts',
    '../../packages/ui/src/components/business/agent/chat/list/index.tsx',
    '../../packages/ui/src/components/business/agent/chat/tabs/index.tsx',
    '../../packages/ui/src/components/business/agent/chat/tabs/panel/index.tsx',
    '../../packages/ui/src/components/business/agent/chat/tabs/item/index.tsx',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentChatCssSource = [
    '../../packages/ui/src/components/business/agent/chat/styles.css',
    '../../packages/ui/src/components/business/agent/chat/tabs/styles.css',
    '../../packages/ui/src/components/business/agent/chat/tabs/panel/styles.css',
    '../../packages/ui/src/components/business/agent/chat/tabs/item/styles.css',
    '../../packages/ui/src/components/business/agent/chat/history/styles.css',
    '../../packages/ui/src/components/business/agent/chat/toolbar/styles.css',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentShellCssSource = [
    '../../packages/ui/src/components/business/agent/shell/styles.css',
    '../../packages/ui/src/components/business/agent/shell/layout/styles.css',
    '../../packages/ui/src/components/business/agent/shell/sidebar/styles.css',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentThreadCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/thread/foundation/styles.css'), 'utf8')
  const uiAgentComposerCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/composer/styles.css'), 'utf8')
  const uiAgentPanelCssSource = [
    '../../packages/ui/src/components/business/agent/panel/styles.css',
    '../../packages/ui/src/components/business/agent/panel/frame/styles.css',
    '../../packages/ui/src/components/business/agent/panel/card/styles.css',
    '../../packages/ui/src/components/business/agent/panel/composer-mention/styles.css',
    '../../packages/ui/src/components/business/agent/panel/shell-layout/styles.css',
    '../../packages/ui/src/components/business/agent/panel/thread-message/styles.css',
    '../../packages/ui/src/components/business/agent/panel/context/styles.css',
    '../../packages/ui/src/components/business/agent/panel/embedded-runtime/styles.css',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentPageCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/page/styles.css'), 'utf8')
  const uiAgentGeneratedFeedbackCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/feedback/styles.css'), 'utf8')
  const uiAgentGeneratedResultSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/result-card/item/index.tsx'), 'utf8')
  const uiAgentGeneratedResultShellSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/result-card/shell/index.tsx'), 'utf8')
  const uiAgentGeneratedResultNoticeSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/result-card/notice/index.tsx'), 'utf8')
  const uiAgentGeneratedResultCssSource = [
    '../../packages/ui/src/components/business/agent/generated/result-card/header/styles.css',
    '../../packages/ui/src/components/business/agent/generated/result-card/item/styles.css',
    '../../packages/ui/src/components/business/agent/generated/result-card/notice/styles.css',
    '../../packages/ui/src/components/business/agent/generated/result-card/shell/styles.css',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentGeneratedCandidateResourceSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/candidate-dialog/resource/index.tsx'), 'utf8')
  const uiAgentGeneratedCandidateResourceCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/candidate-dialog/resource/styles.css'), 'utf8')
  const uiAgentGeneratedCandidateTargetSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/candidate-dialog/target/index.tsx'), 'utf8')
  const uiAgentGeneratedCandidateTargetCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/candidate-dialog/target/styles.css'), 'utf8')
  const uiAgentRunInteractionApprovalSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/run-interaction/card/index.tsx'), 'utf8')
  const uiAgentRunInteractionApprovalCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/run-interaction/card/styles.css'), 'utf8')
  const uiAgentRunInteractionApprovalFeedbackSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/run-interaction/feedback/index.tsx'), 'utf8')
  const uiAgentRunActivitySource = [
    '../../packages/ui/src/components/business/agent/run-activity/bubble/index.tsx',
    '../../packages/ui/src/components/business/agent/run-activity/code/index.tsx',
    '../../packages/ui/src/components/business/agent/run-activity/disclosure/index.tsx',
    '../../packages/ui/src/components/business/agent/run-activity/item/index.tsx',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentRunActivityCssSource = [
    '../../packages/ui/src/components/business/agent/run-activity/bubble/styles.css',
    '../../packages/ui/src/components/business/agent/run-activity/disclosure/styles.css',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentPlanOverviewSource = [
    '../../packages/ui/src/components/business/agent/plan-overview/disclosure/index.tsx',
    '../../packages/ui/src/components/business/agent/plan-overview/feedback/index.tsx',
    '../../packages/ui/src/components/business/agent/plan-overview/item/index.tsx',
    '../../packages/ui/src/components/business/agent/plan-overview/shell/index.tsx',
    '../../packages/ui/src/components/business/agent/plan-overview/task/index.tsx',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiAgentPageSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/page/index.tsx'), 'utf8')
  const agentManagementPageSource = [
    'src/features/agent/components/AgentConsolePage.tsx',
    'src/features/agent/components/AgentRunsPage.tsx',
    'src/features/agent/components/AIAgentRunPage.tsx',
    'src/features/agent/components/AIAgentSettingsPage.tsx',
    'src/features/agent/components/AIAgentPerformancePage.tsx',
    'src/features/agent/components/AIWorkspacesPage.tsx',
    'src/features/agent/components/AgentModeCanvasListPage.tsx',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiLayoutSource = [
    '../../packages/ui/src/components/layout/chrome.ts',
    '../../packages/ui/src/components/layout/index.tsx',
    '../../packages/ui/src/components/layout/workspace/index.tsx',
  ].map((relativePath) => readFileSync(resolve(relativePath), 'utf8')).join('\n')
  const uiCssSource = readFileSync(resolve('../../packages/ui/src/styles.css'), 'utf8')
  const uiAgentCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/styles.css'), 'utf8')
  const cssSource = readFileSync(resolve('src/index.css'), 'utf8')
  const zhSource = readFileSync(resolve('src/i18n/locales/zh-CN.json'), 'utf8')
  const enSource = readFileSync(resolve('src/i18n/locales/en-US.json'), 'utf8')

  assert.doesNotMatch(clientSource, /getThreadOrCreate/)
  assert.match(clientSource, /RunMessageResult/)
  assert.match(protocolSource, /export interface RunMessageResult[\s\S]*threadResolution: AgentThreadResolution/)
  assert.match(clientSource, /if \(!options\.input\.threadId \|\| !isLocalAgentNotFoundError\(error\)\) throw error/)
  assert.match(clientSource, /runMessageStream[\s\S]*threadResolution: resolvedThread\.resolution/)
  assert.match(frontendArchitectureSource, /Chat timeline renders only visible transcript messages for one runtime thread/)
  assert.match(frontendArchitectureSource, /must not fall back to session-level message aggregation/)
  assert.match(frontendArchitectureSource, /UI-only assistant anchors can stay in raw feed state/)
  assert.match(frontendArchitectureSource, /Runtime input answers and approval echoes are filtered only from visible transcript evidence/)

  assert.doesNotMatch(sessionStoreSource, /conversationIdForLocalThread/)
  assert.match(agentConversationSource, /export function conversationIdForRuntimeThread/)
  assert.match(agentStoreSource, /export type Conversation = AgentConversation/)
  assert.match(protocolSource, /runtimeSessionId\?: string/)
  assert.match(protocolSource, /runtimeThreadId\?: string/)
  assert.doesNotMatch(agentStoreSource, /convsByUser/)
  assert.doesNotMatch(agentStoreSource, /createRuntimeConversation: \(userId/)
  assert.match(sessionStoreSource, /activeConversationIdsByUser: Record<string, string \| null>/)
  assert.match(sessionStoreSource, /workspacesByUser: Record<string, Record<string, ConversationWorkspace>>/)
  assert.match(sessionStoreSource, /setConversationRuntimeSessionId/)
  assert.match(sessionStoreSource, /setConversationRuntimeThreadId/)
  assert.match(agentConversationSource, /conversation\.runtimeSessionId === sessionId/)
  assert.match(agentConversationSource, /conversation\.runtimeThreadId === threadId/)
  assert.match(chatViewSource, /surface === 'page'/)
  assert.match(chatViewSource, /<AgentChatPageLayout/)
  assert.match(chatViewSource, /<AgentChatPanelLayout/)
  assert.match(chatViewControllerSource, /useAgentChatInteractionController\(buildAgentChatInteractionControllerInput\(\{/)
  assert.match(interactionControllerSource, /useAgentChatSendPipeline\(\{/)
  assert.match(interactionInputsSource, /actionBindings: buildAgentChatActionBindingsInput\(options\)/)
  assert.match(interactionInputsSource, /sendPipeline: buildAgentChatSendPipelineInput\(options\)/)
  assert.match(actionInputsSource, /runResultActions: \{/)
  assert.doesNotMatch(actionInputsSource, /upsertMessage: store\.messageStore\.upsertMessage/)
  assert.match(actionInputsSource, /runInteractionActions: \{/)
  assert.match(actionInputsSource, /planActions: \{/)
  assert.match(actionInputsSource, /stopAction: \{/)
  assert.match(sendPipelineInputsSource, /workspaceBuilder: \{/)
  assert.match(sendPipelineInputsSource, /commitWorkspace: \{/)
  assert.doesNotMatch(sendPipelineInputsSource, /runtimeThreadHydration/)
  assert.match(sendPipelineInputsSource, /sendActions: \{/)
  assert.match(sendPipelineInputsSource, /sendActions: \{[\s\S]*loading: presentation\.loading/)
  assert.doesNotMatch(sendPipelineSource, /useAgentRuntimeThreadHydration/)
  assert.match(chatViewControllerSource, /useAgentMessageFeed\(\{/)
  assert.match(chatViewControllerSource, /useAgentMessageFeed\(\{[\s\S]*requireThread: true/)
  assert.match(chatStoreBindingsSource, /resolveAgentChatRuntimeBindingIds/)
  assert.match(chatStoreBindingsSource, /input\.conversationRuntime\?\.threadId/)
  assert.doesNotMatch(chatViewControllerSource, /runtimeThreadProjectionMessages/)
  assert.doesNotMatch(chatViewControllerSource, /transientMessages/)
  assert.doesNotMatch(conversationHeaderSource, /sort\(\(a, b\) => b\.updatedAt - a\.updatedAt\)/)
  assert.match(conversationHeaderSource, /onReorderConversation/)
  assert.match(conversationHeaderActionsSource, /agents\.chat\.conversationHistory/)
  assert.match(conversationHeaderActionsSource, /historyOpen/)
  assert.match(conversationHeaderActionsSource, /agents\.chat\.pinnedStatus\.title/)
  assert.match(chatPanelLayoutSource, /setDetailHeaderActions\(/)
  assert.match(chatPanelLayoutSource, /<AgentChatHeaderActions[\s\S]*historyOpen=\{historyOpen\}[\s\S]*pinnedStatusExpanded=\{pinnedStatusExpanded\}/)
  assert.match(chatPanelLayoutSource, /visibleTranscriptChatMessages\(thread\.messages\)/)
  assert.match(chatPanelLayoutSource, /const conversationStarted = visibleMessages\.length > 0 \|\| thread\.conversationBlocks\.length > 0 \|\| !!debugPreview\.workspace/)
  assert.match(chatPanelLayoutSource, /const emptyConversation = !conversationStarted/)
  assert.match(chatPanelLayoutSource, /const \[historyOpen, setHistoryOpen\] = useState\(false\)/)
  assert.match(chatPanelLayoutSource, /setHistoryOpen\(false\)/)
  assert.match(chatPanelLayoutSource, /if \(conversationStarted\) setHistoryOpen\(false\)/)
  assert.match(chatPanelLayoutSource, /historyThreads/)
  assert.match(chatPanelLayoutSource, /agents\.chat\.conversationHistory/)
  assert.match(chatPanelLayoutSource, /agents\.chat\.noHistoryConversations/)
  assert.match(chatPanelLayoutSource, /<AgentConversationThreadSection[\s\S]*\{\.\.\.thread\}[\s\S]*pinnedStatusExpanded=\{pinnedStatusExpanded\}[\s\S]*onPinnedStatusExpandedChange=\{setPinnedStatusExpanded\}/)
  assert.match(chatPanelLayoutSource, /const historyPanel = historyOpen \? \(/)
  assert.match(chatPanelLayoutSource, /<AgentComposerSection \{\.\.\.composer\} chrome="flush" \/>\s*\{historyPanel\}/)
  assert.doesNotMatch(chatPanelLayoutSource, /chrome="bottom-bar"/)
  assert.doesNotMatch(chatPanelLayoutSource, /chrome="card"/)
  assert.doesNotMatch(chatPanelLayoutSource, /const composerInContent = emptyConversation \|\| historyOpen/)
  assert.match(chatPageLayoutSource, /agent-page-chat-empty/)
  assert.match(chatPageLayoutSource, /agent-page-chat-empty-composer/)
  assert.doesNotMatch(chatPageLayoutSource, /<AgentMain[\s\S]*<AgentDebugPreviewDialog \{\.\.\.debugPreview\} \/>\s*\{pageActions\}/)
  assert.match(chatPageLayoutSource, /className="agent-page-chat-thread-shell agent-page-chat-thread-shell--empty"[\s\S]*\{pageActions\}/)
  assert.match(chatPageLayoutSource, /className="agent-page-chat-thread-shell"[\s\S]*\{pageActions\}/)
  assert.doesNotMatch(chatPageLayoutSource, /chrome="bottom-bar"/)
  assert.doesNotMatch(chatPageLayoutSource, /chrome="card"/)
  assert.doesNotMatch(composerSectionSource, /回答请求/)
  assert.doesNotMatch(composerSectionSource, /ai-agent-panel-input-header/)
  assert.match(composerSectionSource, /AgentSurfaceBlock/)
  assert.doesNotMatch(mentionEditorSource, /AgentSurfaceBlock/)
  assert.match(mentionEditorSource, /function ComposerAttachmentChip/)
  assert.match(mentionEditorSource, /className="flex min-w-0 items-center gap-2 border-t border-border px-0 py-1/)
  assert.doesNotMatch(uiAgentPageCssSource, /ai-agent-panel-input-header/)
  assert.match(chatPageLayoutSource, /visibleTranscriptChatMessages\(thread\.messages\)\.length > 0/)
  assert.match(chatPresentationStateSource, /messageCount: visibleTranscriptChatMessages\(derivedInput\.messages\)\.length/)
  assert.match(chatPageLayoutSource, /emptyAccessory/)
  assert.match(chatPageLayoutSource, /agent-page-chat-empty-accessory/)
  assert.doesNotMatch(threadSectionSource, /agents\.chat\.startChat/)
  assert.doesNotMatch(threadSectionSource, /AgentSuggestions/)
  assert.doesNotMatch(threadSectionSource, /border-l border-border/)
  assert.doesNotMatch(threadSectionSource, /pl-3/)
  assert.match(threadSectionSource, /className="ai-agent-panel-run-group"/)
  assert.match(conversationTabsSource, /<AgentConversationTabsPanel/)
  assert.match(conversationTabsSource, /visibleTranscriptChatMessages\(item\.messages\)/)
  assert.match(conversationListSource, /latestVisibleTranscriptChatMessage\(conv\.messages\)/)
  assert.match(conversationTabsSource, /onReorderConversation=\{onReorderConversation\}/)
  assert.match(conversationTabsSource, /runtimeStatusLights/)
  assert.match(uiAgentChatSource, /draggable/)
  assert.match(uiAgentChatSource, /onReorderConversation\(draggedId, item\.id, position\)/)
  assert.match(uiAgentChatSource, /data-runtime-state/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-conversation-tab-close \{[\s\S]*position: absolute/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-chat-toolbar-tabs \{[\s\S]*overflow: hidden/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-chat-toolbar-actions \{[\s\S]*flex: 0 0 auto/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-chat-toolbar-actions > \.ms-button \{[\s\S]*flex: 0 0 auto/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-chat-toolbar \.ms-button:not\(\.ai-agent-panel-conversation-tab-close\):hover:not\(:disabled\)/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-shell \.ai-agent-panel-chat-header \{[\s\S]*min-height: 34px;[\s\S]*border-bottom: 0;[\s\S]*background: transparent;[\s\S]*padding: 0;/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-chat-toolbar \{[\s\S]*border: 0;[\s\S]*border-radius: 0;[\s\S]*box-shadow: none;/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-conversation-tab-main:focus-visible,[\s\S]*\.ai-agent-panel-conversation-tab-close:focus-visible \{[\s\S]*border-radius: 0;/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-conversation-tab-close \{[\s\S]*border-radius: 0;/)
  assert.match(uiAgentCssSource, /@import "\.\/chat\/styles\.css"/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-empty-history \{[\s\S]*order: 3;[\s\S]*flex: 0 0 calc\(100% \/ 3\)/)
  assert.match(uiAgentChatCssSource, /\.ai-agent-panel-empty-history-list \{[\s\S]*min-height: 0;[\s\S]*overflow-y: auto;/)
  assert.match(chatPanelLayoutSource, /useResizablePanel\(\{[\s\S]*resizeEdge: 'top'[\s\S]*collapseMode: 'after-min'/)
  assert.match(chatPanelLayoutSource, /\{\.{3}historyResize\.resizeHandleProps\}/)
  assert.doesNotMatch(chatPanelLayoutSource, /resizeStartRef/)
  assert.doesNotMatch(chatPanelLayoutSource, /document\.body\.style\.cursor/)
  assert.doesNotMatch(chatPanelLayoutSource, /window\.addEventListener\('pointermove'/)
  assert.doesNotMatch(conversationTabRuntimeLightsSource, /localAgentClient\.streamSession/)
  assert.doesNotMatch(conversationTabRuntimeLightsSource, /localAgentClient\.streamThread/)
  assert.match(conversationTabRuntimeLightsSource, /agentRuntimeStatusLightController\.setOwnerTargets/)
  assert.match(conversationTabRuntimeLightsSource, /useAgentRuntimeStatusLightStore/)
  assert.match(runtimeStatusLightControllerSource, /private readonly connections = new Map<string, RuntimeConnection>\(\)/)
  assert.match(runtimeStatusLightControllerSource, /this\.connections\.set\(ref\.targetKey, connection\)/)
  assert.match(runtimeStatusLightControllerSource, /this\.connections\.delete\(targetKey\)/)
  assert.match(runtimeStatusLightControllerSource, /if \(!this\.connections\.has\(ref\.targetKey\)\) this\.startConnection\(ref\)/)
  assert.match(runtimeStatusLightControllerSource, /this\.client\.getSessionRuntime/)
  assert.match(runtimeStatusLightControllerSource, /this\.client\.getThreadRuntime/)
  assert.match(runtimeStatusLightControllerSource, /this\.client\.streamSession/)
  assert.match(runtimeStatusLightControllerSource, /this\.client\.streamThread/)
  assert.match(runtimeStatusLightControllerSource, /refreshDebounceMs/)
  assert.match(conversationTabRuntimeLightsSource, /localThreadIdsByConversation/)
  assert.match(conversationTabRuntimeLightsSource, /sessionIdsByConversation/)
  assert.match(conversationTabRuntimeLightsSource, /sessionIdsByConversation/)
  assert.doesNotMatch(sendPipelineSource, /runtimeThreadHydration/)
  assert.doesNotMatch(sendCompletionSource, /loadRuntimeThreadProjection/)
  assert.doesNotMatch(sendCommitSource, /setRuntimeThreadProjection/)
  assert.doesNotMatch(agentConversationSource, /markRuntimeMessagesRestored/)
  assert.doesNotMatch(agentConversationSource, /mergeRuntimeThreadProjectionMessages/)
  assert.doesNotMatch(agentConversationSource, /buildRuntimeThreadConversationProjection/)
  assert.doesNotMatch(runtimeRestoreSource, /setRuntimeThreadProjection/)
  assert.match(agentConversationSource, /conversationIdForRuntimeSession/)
  assert.match(agentConversationSource, /conversationIdForRuntimeThread\(\{[\s\S]*localThreadIdsByConversation[\s\S]*conversationRuntimes/)
  assert.match(runtimeRestoreSource, /if \(existingConversationId\) \{[\s\S]*activateConversation\(existingConversationId\)[\s\S]*return/)
  assert.match(panelSource, /<AgentBuiltinChatShell/)
  assert.match(panelSource, /hasOpenConversations/)
  assert.match(panelSource, /className="hidden"/)
  assert.match(appSource, /assistantPanel=\{detailAgentPanelOpen \|\| hasOpenConversations \? <AIAgentPanel \/> : undefined\}/)
  assert.match(appTopControlsSource, /const AssistantShortcutIcon = agentPanelOpen \? PanelRightClose : PanelRightOpen/)
  assert.match(appTopControlsSource, /active=\{agentPanelOpen && conversationCount > 0\}/)
  assert.match(appTopControlsSource, /showAssistantShortcut && conversationCount === 0/)
  assert.doesNotMatch(appTopControlsSource, /createConversation\(userId\)/)
  assert.match(appTopControlsSource, /setAgentPanelOpen\(true\)/)
  assert.match(appTopControlsSource, /getAppRouteSurface\(pathname\)/)
  assert.match(appTopControlsSource, /workModeForRoute\(pathname, workMode\)/)
  assert.match(appTopControlsSource, /navigate\(routeForWorkMode\(nextMode, !!current\), \{ replace: routeSurface !== 'detail' \}\)/)
  assert.match(appTopControlsSource, /routeSurface === 'agent'/)
  assert.match(appSource, /function ProjectAgentModeRoute\(\)/)
  assert.match(appSource, /function ProjectAgentModeRoute\(\) \{\s*return <AgentModePage \/>\s*\}/)
  assert.doesNotMatch(appSource, /if \(workMode !== 'agent'\) return <Navigate to=\{ROUTES\.project\.overview\} replace \/>/)
  assert.match(agentPanelDockControllerSource, /DETAIL_AGENT_PANEL_DEFAULT_WIDTH = 360/)
  assert.match(agentPanelDockControllerSource, /DETAIL_AGENT_PANEL_MAX_WIDTH = 720/)
  assert.match(agentPanelDockControllerSource, /DETAIL_AGENT_PANEL_RESERVED_WIDTH = 760/)
  assert.match(agentPanelDockControllerSource, /viewportWidth - DETAIL_AGENT_PANEL_RESERVED_WIDTH/)
  assert.match(agentPanelDockControllerSource, /const dockLayout = true/)
  assert.doesNotMatch(agentPanelDockControllerSource, /\b680\b/)
  assert.doesNotMatch(agentPanelDockControllerSource, /innerWidth >= 960/)
  assert.doesNotMatch(agentPanelDockControllerSource, /setDockLayout/)
  assert.match(uiAgentPanelSource, /data-dock-layout=\{dockLayout \? "true" : "false"\}/)
  assert.match(uiAgentPanelSource, /data-chrome=\{resolvedChrome\}/)
  assert.match(uiAgentPanelSource, /className="ai-agent-panel"/)
  assert.doesNotMatch(uiAgentPanelSource, /w-\[/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel\[data-chrome="dock"\]/)
  assert.match(uiAgentPanelCssSource, /flex: 0 0 var\(--ui-agent-panel-width\)/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel \.ai-agent-panel__resize-handle\.panel-resize-handle--left \{[\s\S]*width: 28px;[\s\S]*transform: translateX\(-14px\);/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel\[data-chrome="floating"\]/)
  assert.match(uiAgentPanelCssSource, /position: absolute/)
  assert.match(uiAgentPanelCssSource, /width: min\(var\(--ui-agent-panel-width\), calc\(100vw - 24px\)\)/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel__body > \.ai-agent-panel-shell/)
  assert.match(uiAgentPanelCssSource, /\.ms-agent-shell\.ai-agent-panel-shell \{[\s\S]*border: 0;[\s\S]*border-radius: 0;[\s\S]*box-shadow: none;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell \.ms-agent-header \{[\s\S]*border-bottom: 0;/)
  assert.match(uiAgentShellCssSource, /\.ms-agent-main \{[\s\S]*container-type: inline-size;/)
  assert.match(uiAgentPageCssSource, /\.agent-page-chat-empty \{[\s\S]*padding: clamp\(18px, 4vh, 40px\) 0 18px;/)
  assert.match(uiAgentPageCssSource, /\.agent-page-project-select-card \{[\s\S]*width: 100%;/)
  assert.match(uiAgentPageCssSource, /\.agent-page-chat-composer \{[\s\S]*padding: 8px 0 12px;/)
  assert.match(uiAgentPageCssSource, /\.agent-page-chat-empty-composer \{[\s\S]*width: 100%;/)
  assert.match(uiAgentPageCssSource, /\.agent-page-chat-thread-shell--empty \.agent-page-chat-composer \.ai-agent-panel-composer \{[\s\S]*padding: 10px 0;/)
  assert.match(uiAgentThreadCssSource, /padding: 20px 0;/)
  assert.match(uiAgentComposerCssSource, /margin: 0 0 16px;/)
  assert.match(uiAgentComposerCssSource, /padding: 9px 0;/)
  assert.match(uiAgentComposerCssSource, /\.ms-agent-shell--compact \.ms-agent-composer \{[\s\S]*margin: 0 0 12px;[\s\S]*padding: 8px 0;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-input-card\[data-chrome="flush"\] \{[\s\S]*padding: 8px 0 10px;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell \.ms-agent-message--assistant \{[\s\S]*padding: 8px 0 6px;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell\.ms-agent-shell--compact \.ms-agent-message__body \{[\s\S]*width: 100%;[\s\S]*max-width: 100%;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell \.ms-agent-message--user \.ms-agent-message__body \{[\s\S]*width: 100%;[\s\S]*max-width: 100%;[\s\S]*align-items: stretch;[\s\S]*margin-left: 0;[\s\S]*padding-right: 0;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell\.ms-agent-shell--compact \.ms-agent-message--user \.ms-agent-message__body \{[\s\S]*width: 100%;[\s\S]*max-width: 100%;[\s\S]*align-items: stretch;[\s\S]*margin-left: 0;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell \.ms-agent-message--user \.ms-agent-message__content \{[\s\S]*padding: 7px 12px;/)
  assert.match(uiAgentPageCssSource, /\.project-agent-chat-shell\.ms-agent-shell--compact \.ms-agent-message__body \{[\s\S]*width: 100%;[\s\S]*max-width: 100%;/)
  assert.match(uiAgentPageCssSource, /\.project-agent-chat-shell\.ms-agent-shell--compact \.ms-agent-message--user \.ms-agent-message__body \{[\s\S]*align-items: stretch;[\s\S]*margin-left: 0;/)
  assert.match(uiAgentPageCssSource, /\.project-agent-chat-shell\.ms-agent-shell--compact \.ms-agent-message__content \{[\s\S]*width: 100%;[\s\S]*max-width: 100%;[\s\S]*padding-right: 0;[\s\S]*padding-left: 0;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-input-card\[data-chrome="bottom-bar"\]/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-input-card\[data-chrome="flush"\] \.ai-agent-panel-composer \{[\s\S]*margin: 0;[\s\S]*border: 1px solid[\s\S]*border-radius: var\(--ms-radius-md\);[\s\S]*padding: 8px 0;[\s\S]*box-shadow: 0 8px 22px/)
  assert.doesNotMatch(uiAgentPanelCssSource, /\.ms-agent-message--assistant \.ms-agent-surface-block,/)
  assert.doesNotMatch(uiAgentPanelCssSource, /:has\(\.ms-agent-surface-block\)/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell \.ms-agent-message--assistant \.ms-agent-message__body \{[\s\S]*max-width: 100%;[\s\S]*flex-basis: 100%;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell \.ms-agent-message--assistant \.ms-agent-message__content > \* \{[\s\S]*width: 100%;[\s\S]*max-width: 100%;/)
  assert.doesNotMatch(uiAgentPanelCssSource, /data-agent-divider-label/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell \.ms-agent-message--assistant \.ms-agent-run-activity,[\s\S]*\.ms-agent-plan-overview,[\s\S]*\.ms-agent-generated-result-card \{[\s\S]*background: transparent;[\s\S]*padding: 0;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell \.ms-agent-message--assistant \.ms-agent-run-activity-item,[\s\S]*\.ms-agent-generated-result-item,[\s\S]*\.ms-agent-plan-overview-task,[\s\S]*box-shadow: none;/)
  assert.match(uiAgentPanelCssSource, /\.ai-agent-panel-shell \.ms-agent-message--assistant \.ms-agent-run-interaction-thumb \{[\s\S]*width: 40px;[\s\S]*flex: 0 0 auto;/)
  assert.match(uiAgentGeneratedFeedbackCssSource, /\.agent-generated-card__header \{[\s\S]*flex-wrap: wrap;[\s\S]*align-items: flex-start;/)
  assert.match(uiAgentGeneratedFeedbackCssSource, /\.agent-generated-card__header-copy \{[\s\S]*flex: 1 1 11rem;/)
  assert.match(uiAgentGeneratedFeedbackCssSource, /\.agent-generated-card__header-copy:last-child \{[\s\S]*justify-content: flex-end;[\s\S]*margin-left: auto;/)
  assert.doesNotMatch(uiAgentGeneratedFeedbackSource(), /AgentGeneratedIntentSurfaceBlock/)
  assert.match(uiAgentGeneratedFeedbackSource(), /function AgentGeneratedCard[\s\S]*?AgentSurfaceBlock/)
  assert.match(uiAgentGeneratedFeedbackCssSource, /\.agent-generated-card \{[\s\S]*background: transparent;[\s\S]*box-shadow: none;/)
  assert.match(uiAgentGeneratedFeedbackSource(), /function AgentGeneratedItem[\s\S]*?AgentSurfaceBlock/)
  assert.match(uiAgentGeneratedFeedbackCssSource, /\.agent-generated-stack > \.agent-generated-item \+ \.agent-generated-item \{[\s\S]*border-top: 1px solid/)
  assert.match(uiAgentGeneratedFeedbackCssSource, /\.agent-generated-stat-grid \.agent-generated-item \{[\s\S]*padding: 0;/)
  assert.match(uiAgentGeneratedFeedbackCssSource, /\.agent-generated-item__header \{[\s\S]*flex-wrap: wrap;[\s\S]*align-items: flex-start;/)
  assert.match(uiAgentGeneratedFeedbackCssSource, /\.agent-generated-item__copy \{[\s\S]*flex: 1 1 12rem;/)
  assert.match(uiAgentGeneratedFeedbackCssSource, /\.agent-generated-item__header > \.agent-generated-status-badge \{[\s\S]*margin-left: auto;/)
  assert.doesNotMatch(uiAgentGeneratedResultSource, /AgentSurfaceBlock/)
  assert.doesNotMatch(uiAgentGeneratedResultSource, /variant/)
  assert.doesNotMatch(uiAgentGeneratedResultShellSource, /AgentSurfaceBlock/)
  assert.doesNotMatch(uiAgentGeneratedResultShellSource, /variant/)
  assert.doesNotMatch(uiAgentGeneratedResultNoticeSource, /AgentSurfaceBlock/)
  assert.doesNotMatch(uiAgentGeneratedResultNoticeSource, /variant/)
  assert.match(uiAgentGeneratedResultCssSource, /\.ms-agent-generated-result-card__header \{[\s\S]*flex-wrap: wrap;[\s\S]*align-items: flex-start;/)
  assert.match(uiAgentGeneratedResultCssSource, /\.ms-agent-generated-result-card__actions \{[\s\S]*flex-wrap: wrap;[\s\S]*margin-left: auto;/)
  assert.match(uiAgentGeneratedResultCssSource, /\.ms-agent-generated-result-item__row \{[\s\S]*flex-wrap: wrap;[\s\S]*align-items: flex-start;/)
  assert.match(uiAgentGeneratedResultCssSource, /\.ms-agent-generated-result-item__body \{[\s\S]*flex: 1 1 12rem;/)
  assert.match(uiAgentGeneratedResultCssSource, /\.ms-agent-generated-result-card \{[\s\S]*background: transparent;/)
  assert.match(uiAgentGeneratedResultCssSource, /\.ms-agent-generated-result-missing-notice \{[\s\S]*border-left: 2px solid/)
  assert.match(uiAgentGeneratedResultCssSource, /\.ms-agent-generated-result-card__list > \* \+ \* \{[\s\S]*border-top: 1px solid/)
  assert.doesNotMatch(uiAgentGeneratedCandidateResourceSource, /AgentSurfaceBlock/)
  assert.doesNotMatch(uiAgentGeneratedCandidateResourceSource, /variant/)
  assert.match(uiAgentGeneratedCandidateResourceCssSource, /\.ms-agent-generated-candidate-resource-item \+ \.ms-agent-generated-candidate-resource-item \{[\s\S]*border-top: 1px solid/)
  assert.match(uiAgentGeneratedCandidateResourceCssSource, /\.ms-agent-generated-candidate-resource-item__row \{[\s\S]*flex-wrap: wrap;[\s\S]*align-items: flex-start;/)
  assert.match(uiAgentGeneratedCandidateResourceCssSource, /\.ms-agent-generated-candidate-resource-item__body \{[\s\S]*flex: 1 1 10rem;/)
  assert.doesNotMatch(uiAgentGeneratedCandidateTargetSource, /AgentSurfaceBlock/)
  assert.doesNotMatch(uiAgentGeneratedCandidateTargetSource, /variant/)
  assert.match(uiAgentGeneratedCandidateTargetCssSource, /\.ms-agent-generated-candidate-target-list \{[\s\S]*border: 1px solid[\s\S]*border-radius: 0;/)
  assert.match(uiAgentGeneratedCandidateTargetCssSource, /\.ms-agent-generated-candidate-target-row \{[\s\S]*flex-wrap: wrap;[\s\S]*align-items: flex-start;/)
  assert.match(uiAgentGeneratedCandidateTargetCssSource, /\.ms-agent-generated-candidate-target-title \{[\s\S]*flex: 1 1 12rem;/)
  assert.match(uiAgentGeneratedCandidateTargetCssSource, /\.ms-agent-generated-candidate-selected-target \{[\s\S]*border: 1px solid[\s\S]*border-radius: 0;/)
  assert.match(uiAgentRunInteractionApprovalSource, /export const AgentRunInteractionApprovalCard[\s\S]*return <div ref=\{ref\} className=\{cn\("ms-agent-run-interaction-card"/)
  assert.doesNotMatch(uiAgentRunInteractionApprovalSource, /export const AgentRunInteractionApprovalCard[\s\S]*variant = "subtle"[\s\S]*AgentRunInteractionApprovalCard\.displayName/)
  assert.match(uiAgentRunInteractionApprovalCssSource, /\.ms-agent-run-interaction-card \{[\s\S]*background: transparent;[\s\S]*box-shadow: none;/)
  assert.match(uiAgentRunInteractionApprovalCssSource, /\.ms-agent-run-interaction-card__header \{[\s\S]*flex-wrap: wrap;[\s\S]*align-items: flex-start;/)
  assert.match(uiAgentRunInteractionApprovalCssSource, /\.ms-agent-run-interaction-card__body \{[\s\S]*flex: 1 1 12rem;/)
  assert.match(uiAgentRunInteractionApprovalCssSource, /\.ms-agent-run-interaction-card__title \{[\s\S]*flex: 1 1 12rem;/)
  assert.doesNotMatch(uiAgentRunActivitySource, /AgentSurfaceBlock/)
  assert.doesNotMatch(uiAgentRunActivitySource, /variant="subtle"/)
  assert.doesNotMatch(uiAgentRunActivityCssSource, /box-shadow: var\(--ms-shadow-sm\)/)
  assert.doesNotMatch(uiAgentPlanOverviewSource, /AgentSurfaceBlock/)
  assert.doesNotMatch(uiAgentPlanOverviewSource, /variant="subtle"/)
  assert.doesNotMatch(uiAgentRunInteractionApprovalFeedbackSource, /AgentSurfaceBlock/)
  assert.doesNotMatch(uiAgentRunInteractionApprovalFeedbackSource, /variant="subtle"/)
  assert.match(uiLayoutSource, /export type LayoutChrome =/)
  assert.match(uiLayoutSource, /export type WorkspaceShellSurface = "agent" \| "detail" \| "canvas"/)
  assert.match(uiLayoutSource, /layoutChromeContracts/)
  assert.match(uiLayoutSource, /chrome = "workspace"/)
  assert.match(uiLayoutSource, /data-surface=\{surface\}/)
  assert.match(uiLayoutSource, /data-chrome=\{resolvedChrome\}/)
  assert.doesNotMatch(uiLayoutSource, /contentPaddingClassName/)
  assert.doesNotMatch(uiLayoutSource, /contentFrameClassName/)
  assert.match(appSource, /surface=\{shellSurface\}/)
  assert.match(appSource, /surface="canvas"/)
  assert.match(uiAgentPageSource, /export function AgentPageShell/)
  assert.match(uiAgentPageSource, /Omit<ComponentProps<typeof AppPageShell>, "chrome">/)
  assert.match(uiAgentPageSource, /<AppPageShell chrome="immersive"/)
  assert.doesNotMatch(sourceFunctionBlock(uiAgentPageSource, 'AgentWorkspaceListState'), /AgentSurfaceBlock/)
  assert.doesNotMatch(sourceFunctionBlock(uiAgentPageSource, 'AgentRunSidebarLoading'), /AgentSurfaceBlock/)
  assert.doesNotMatch(sourceFunctionBlock(uiAgentPageSource, 'AgentRunTraceEmptyState'), /AgentSurfaceBlock/)
  assert.doesNotMatch(sourceFunctionBlock(uiAgentPageSource, 'AgentRunDebugMutedNote'), /AgentSurfaceBlock/)
  assert.doesNotMatch(sourceFunctionBlock(uiAgentPageSource, 'AgentRunDebugStatusNote'), /AgentSurfaceBlock/)
  assert.doesNotMatch(sourceFunctionBlock(uiAgentPageSource, 'AgentRunDebugMutedNote'), /variant/)
  assert.doesNotMatch(sourceFunctionBlock(uiAgentPageSource, 'AgentRunDebugStatusNote'), /variant/)
  assert.match(agentManagementPageSource, /<AgentPageShell/)
  assert.doesNotMatch(agentManagementPageSource, /\bAppPageShell\b/)
  assert.match(appTopControlsSource, /toggleAgentModeContentPanelCollapsed/)
  assert.match(appTopControlsSource, /PanelRightOpen/)
  assert.match(appTopControlsSource, /PanelRightClose/)
  assert.match(agentPanelUiStoreSource, /agentModeContentPanelCollapsed: readAgentModeContentPanelCollapsed\(\)/)
  assert.match(agentPanelUiStoreSource, /return saved === null \? true : saved === 'true'/)
  assert.match(agentPanelUiStoreSource, /toggleAgentModeContentPanelCollapsed/)
  assert.doesNotMatch(projectAgentModePageSource, /pageEmptyAccessory=\{<AgentModeProjectSelectCard \/>}/)
  assert.doesNotMatch(projectAgentModePageSource, /function AgentModeProjectSelectCard/)
  assert.match(appSource, /function ProjectRequiredDialog\(\)/)
  assert.doesNotMatch(appSource, /\bforced\b/)
  assert.match(appTopControlsSource, /openProjectDialog\(\)/)
  assert.match(appTopControlsSource, /const ModeIcon = nextMode === 'agent' \? Bot : LayoutDashboard/)
  assert.match(appTopControlsSource, /onClick=\{switchMode\}/)
  assert.match(appTopControlsSource, /<ModeIcon size=\{compact \? 11 : 14\} \/>/)
  assert.match(uiAgentModeSource, /\bAgentNavItem\b/)
  assert.match(projectAgentModePageSource, /\bAgentModeConversationItem\b/)
  assert.match(projectAgentModePageSource, /useAgentConversationTabRuntimeStatusLights\(openConversations\)/)
  assert.match(projectAgentModePageSource, /runtimeStatusLight=\{runtimeStatusLights\[conversation\.id\]\}/)
  assert.match(projectAgentModePageSource, /className="agent-mode-conversation-runtime-light"/)
  assert.match(projectAgentModePageSource, /title=\{title\}/)
  assert.match(projectAgentModePageSource, /meta=\{relativeTime\}/)
  assert.match(projectAgentModePageSource, /readAgentConversationOpenState\(userId\)/)
  assert.match(projectAgentModePageSource, /openAgentConversationIds\(conversationOpenState\)/)
  assert.match(projectAgentModePageSource, /setAgentConversationOpen\(current, \[conversation\.id\], false\)/)
  assert.doesNotMatch(projectAgentModePageSource, /compareConversationCreationOrder/)
  assert.match(builtinChatControllerSource, /reorderAgentConversationOpenState\(merged, draggedId, targetId, position\)/)
  assert.match(builtinChatControllerSource, /setAgentConversationOpen\(current, ids, false\)/)
  assert.match(builtinChatControllerSource, /reorderConversation: handleReorderConversation/)
  assert.doesNotMatch(sourceFunctionBlock(projectAgentModePageSource, 'startNewConversation'), /archiveConversations/)
  assert.doesNotMatch(sourceFunctionBlock(projectAgentModePageSource, 'selectConversation'), /archiveConversations/)
  assert.match(uiAgentModeSource, /\bAgentConversationItem\b/)
  assert.match(uiAgentSource, /export const AgentNavItem/)
  assert.match(uiAgentSource, /export const AgentConversationItem/)
  assert.match(uiAgentSource, /icon\?: React\.ReactNode/)
  assert.match(uiCssSource, /components\/business\/agent\/styles\.css/)
  assert.match(uiAgentShellCssSource, /\.ms-agent-nav-item\s*\{/)
  assert.match(uiAgentShellCssSource, /\.ms-agent-conversation__icon\s*\{/)
  assert.match(uiAgentModeCssSource, /\.agent-mode-group__list--nested \{[\s\S]*margin-left: 0;[\s\S]*border-left: 0;[\s\S]*padding-left: 2px;/)
  assert.match(uiAgentModeCssSource, /\.agent-mode-conversation \{[\s\S]*grid-template-columns: minmax\(0, 1fr\) auto;[\s\S]*padding: 4px 6px 4px 10px;/)
  assert.match(uiAgentModeCssSource, /\.agent-mode-conversation\[data-has-icon="true"\] \{[\s\S]*grid-template-columns: auto minmax\(0, 1fr\) auto;/)
  assert.match(uiAgentModeCssSource, /\.agent-mode-conversation \.ms-agent-conversation__indicator \{[\s\S]*display: none;/)
  assert.match(uiAgentModeCssSource, /\.agent-mode-conversation-runtime-light \{[\s\S]*width: 7px;[\s\S]*height: 7px;/)
  assert.match(uiAgentModeCssSource, /\.agent-mode-conversation\[data-active="true"\] \{[\s\S]*background: color-mix\(in srgb, var\(--ms-color-surface\) 86%, var\(--ms-color-background\)\);/)
  assert.doesNotMatch(projectAgentModePageSource, /flex h-8 w-full min-w-0 items-center gap-2 rounded-md px-2/)
  assert.doesNotMatch(projectAgentModePageSource, /hover:bg-muted\/50 hover:text-foreground/)
  assert.match(appTopControlsSource, /AppTopProjectMenuContent/)
  assert.match(appTopControlsSource, /header\.titles\.projects/)
  assert.match(projectAgentModePageSource, /manageOwnWidth \? \(/)
  assert.match(projectAgentModePageSource, /collapsed[\s\S]*\? \{ width: 0, flexBasis: 0, minWidth: 0 \}/)
  assert.match(projectAgentModePageSource, /useResizablePanel\(\{[\s\S]*resizeEdge: 'right'[\s\S]*collapseMode: 'after-min'/)
  assert.match(projectAgentModePageSource, /useResizablePanel\(\{[\s\S]*resizeEdge: 'left'[\s\S]*collapseMode: 'after-min'/)
  assert.match(projectAgentModePageSource, /\{\.{3}sidebarResize\.resizeHandleProps\}[\s\S]*side="right"/)
  assert.match(projectAgentModePageSource, /\{\.{3}panelResize\.resizeHandleProps\}[\s\S]*side="left"/)
  assert.match(agentPanelDockControllerSource, /useResizablePanel\(\{[\s\S]*resizeEdge: 'left'[\s\S]*collapseMode: 'after-min'/)
  assert.match(panelSource, /resizeHandleProps=\{resizeHandleProps\}/)
  assert.match(uiAgentPanelSource, /resizeHandleProps\?: HTMLAttributes<HTMLDivElement>/)
  assert.doesNotMatch(agentPanelDockControllerSource, /window\.addEventListener\('pointermove'/)
  assert.doesNotMatch(projectAgentModePageSource, /resizeStart/)
  assert.doesNotMatch(projectAgentModePageSource, /window\.addEventListener\('pointermove'/)
  assert.match(projectAgentModePageSource, /\? \{ width: 0, flexBasis: 0, minWidth: 0 \}/)
  assert.match(projectAgentModePageSource, /width: panelWidth,[\s\S]*flexBasis: panelWidth,[\s\S]*minWidth: AGENT_MODE_CONTENT_PANEL_MIN_WIDTH/)
  assert.doesNotMatch(projectAgentModePageSource, /PanelRightOpen/)
  assert.doesNotMatch(projectAgentModePageSource, /PanelRightClose/)
  assert.match(uiAgentCssSource, /page\/styles\.css/)
  assert.match(uiAgentPageCssSource, /agent-page-project-select-card/)
  assert.match(uiAgentPageCssSource, /\.project-agent-chat-shell \.agent-page-chat-main \{[\s\S]*display: flex/)
  assert.match(uiAgentPageCssSource, /\.agent-page-chat-actions \{[\s\S]*position: absolute;[\s\S]*width: 28px;[\s\S]*height: 28px;[\s\S]*pointer-events: none;/)
  assert.match(uiAgentPageCssSource, /\.agent-page-chat-actions__trigger \{[\s\S]*pointer-events: auto;/)
  assert.match(uiAgentPageCssSource, /\.agent-page-chat-thread-shell \{[\s\S]*position: relative;/)
  assert.doesNotMatch(cssSource, /agent-page-project-select-card/)
  assert.match(zhSource, /"expandAgentContentPanel": "展开右侧内容区"/)
  assert.match(enSource, /"expandAgentContentPanel": "Expand right content panel"/)
  assert.match(builtinChatShellSource, /useAgentBuiltinChatController\(\{/)
  assert.match(builtinChatShellSource, /<AgentChatView/)
  assert.match(builtinChatShellSource, /pageEmptyAccessory/)
  assert.match(builtinChatControllerSource, /restoreRuntimeThreadConversation\(normalizedThreadId, \{/)
  assert.match(builtinChatControllerSource, /consumeQueuedPanelWorkspaces\(consumeAgentPanelWorkspace/)
  assert.match(builtinChatControllerSource, /activateConversationForPanelWorkspace\(detail, \{/)
  assert.match(builtinChatControllerSource, /archiveConversation: handleArchiveConversation/)
  assert.match(builtinChatControllerSource, /archiveConversations: handleArchiveConversations/)
  assert.match(builtinChatControllerSource, /deleteConversation: handleDeleteConversation/)
  assert.match(builtinChatControllerSource, /localAgentClient\.deleteThread\(runtimeThreadId\)/)
  assert.doesNotMatch(builtinChatControllerSource, /deleteConversation: handleArchiveConversation/)
  assert.doesNotMatch(builtinChatControllerSource, /deleteConversations: handleArchiveConversations/)
  assert.match(sessionStoreSource, /removeRuntimeConversation: \(userId: string, conversationId: string\) => void/)
  assert.match(sessionStoreSource, /clearConversationRuntimeState: \(conversationId: string\) => void/)
  assert.match(uiAgentChatSource, /deleteConversationLabel: string/)

  assert.match(sendActivitySource, /function threadResolutionActivityEvent/)
  assert.match(sendActivitySource, /本地线程不存在，已创建新线程/)
  assert.doesNotMatch(agentConversationSource, /completeRuntimeSendRunResult/)
  assert.doesNotMatch(agentConversationSource, /appendAssistantRunResultMessage/)
  assert.doesNotMatch(sendCompletionSource, /completeRuntimeSendRunResult/)
  assert.doesNotMatch(sendCompletionSource, /setRuntimeThreadProjection/)
  assert.doesNotMatch(sendCompletionSource, /mergeRuntimeThreadProjectionMessages/)
  assert.match(sendCompletionSource, /threadResolutionActivityEvent/)
  assert.match(sendPipelineSource, /useAgentCommitSendWorkspace\(\{/)
  assert.doesNotMatch(sendPipelineInputsSource, /messageStore/)
  assert.match(commitSendHookSource, /commitAgentSendWorkspace\(workspace, \{/)
  assert.doesNotMatch(commitSendHookSource, /messageStore/)
  assert.doesNotMatch(agentConversationSource, /interface AgentConversationMessageStore/)
  assert.doesNotMatch(agentConversationSource, /sendRuntimeInputMessage/)
  assert.doesNotMatch(sendCommitSource, /setRuntimeThreadProjection/)
  assert.match(sendCommitSource, /completeSendRunResult\(\{/)
})

function sourceFunctionBlock(source: string, functionName: string): string {
  const start = source.indexOf(`function ${functionName}(`)
  assert.ok(start >= 0, `missing function ${functionName}`)
  const bodyStart = source.indexOf('{', start)
  assert.ok(bodyStart >= 0, `missing function body for ${functionName}`)
  let depth = 0
  for (let index = bodyStart; index < source.length; index += 1) {
    const character = source[index]
    if (character === '{') depth += 1
    if (character === '}') {
      depth -= 1
      if (depth === 0) return source.slice(bodyStart, index + 1)
    }
  }
  assert.fail(`unterminated function ${functionName}`)
}

function uiAgentGeneratedFeedbackSource(): string {
  return readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/feedback/index.tsx'), 'utf8')
}

test('agent session UI keeps worker trace drilldown contracts', () => {
  const planOverviewSource = readFileSync(resolve('src/features/agent/components/AgentPlanOverviewPanel.tsx'), 'utf8')

  assert.match(planOverviewSource, /const \[traceSummaries, setTraceSummaries\]/)
  assert.match(planOverviewSource, /const \[traceEventsByRunId, setTraceEventsByRunId\]/)
  assert.match(planOverviewSource, /localAgentClient\.getRunTraceSummary\(runId\)/)
  assert.match(planOverviewSource, /localAgentClient\.getRunTraceEvents\(runId, \{ limit: 8/)
  assert.match(planOverviewSource, /traceEventHasMoreByRunId/)
  assert.match(planOverviewSource, /traceEventKindFilters/)
  assert.match(planOverviewSource, /轨迹统计/)
  assert.match(planOverviewSource, /运行事件/)
  assert.match(planOverviewSource, /加载更多/)
})

test('agent session UI pins live task, plan, and subagent status at top of the thread', () => {
  const threadSectionSource = readFileSync(resolve('src/features/agent/components/AgentConversationThreadSection.tsx'), 'utf8')
  const layoutPropsSource = readFileSync(resolve('src/features/agent/presentation/agentChatViewLayoutProps.ts'), 'utf8')
  const conversationPresentationSource = readFileSync(resolve('src/features/agent/domain/agentConversationPresentation.ts'), 'utf8')
  const pinnedStatusViewSource = readFileSync(resolve('src/features/agent/domain/agentPinnedStatusView.ts'), 'utf8')
  const pinnedStatusShelfSource = readFileSync(resolve('src/features/agent/components/AgentPinnedStatusShelf.tsx'), 'utf8')
  const chatBubblesSource = readFileSync(resolve('src/features/agent/components/AgentChatBubbles.tsx'), 'utf8')
  const pinnedStatusCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/pinned-status/styles.css'), 'utf8')
  const uiAgentPageCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/page/styles.css'), 'utf8')
  const derivedStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatDerivedState.ts'), 'utf8')

  assert.match(threadSectionSource, /<AgentPinnedStatusShelf/)
  assert.match(layoutPropsSource, /generationProgressStates: presentation\.generationProgressStates/)
  assert.match(derivedStateSource, /generationProgressStatesForPinnedStatus/)
  assert.match(derivedStateSource, /const generationProgressActivityEvents = visibleActivityEvents/)
  assert.match(derivedStateSource, /visibleActivityEvents: generationProgressActivityEvents/)
  assert.match(conversationPresentationSource, /showLiveRunActivity/)
  assert.doesNotMatch(conversationPresentationSource, /blocks\.push\(\.\.\.generationProgressStates/)
  assert.match(pinnedStatusShelfSource, /data-testid="agent-pinned-status-shelf"/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.tabs\.generation/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.tabs\.worker/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.workersCount/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.tabs\.plan/)
  assert.match(pinnedStatusShelfSource, /agents\.chat\.pinnedStatus\.viewPlanDetails/)
  assert.match(pinnedStatusShelfSource, /resolveAgentPinnedStatusView\(selectedView, \{/)
  assert.match(pinnedStatusViewSource, /export function resolveAgentPinnedStatusView/)
  assert.match(pinnedStatusViewSource, /if \(currentView && agentPinnedStatusViewAvailable\(currentView, availability\)\) return currentView/)
  assert.match(pinnedStatusShelfSource, /const \[collapsed, setCollapsed\] = useState\(!defaultExpanded\)/)
  assert.match(pinnedStatusShelfSource, /const isExpanded = expanded \?\? !collapsed/)
  assert.match(pinnedStatusShelfSource, /aria-expanded=\{isExpanded\}/)
  assert.match(pinnedStatusShelfSource, /aria-controls="agent-pinned-status-shelf-body"/)
  assert.match(pinnedStatusShelfSource, /event\.target !== event\.currentTarget/)
  assert.match(pinnedStatusShelfSource, /activeCount > 0 && <AgentPinnedStatusActiveCount>/)
  assert.match(pinnedStatusShelfSource, /<AgentPinnedStatusSummaryRow>/)
  assert.match(pinnedStatusShelfSource, /<AgentPinnedStatusBody id="agent-pinned-status-shelf-body">/)
  assert.match(threadSectionSource, /const showPinnedStatus = useMemo\(\(\) => hasAgentPinnedStatus\(\{/)
  assert.doesNotMatch(threadSectionSource, /showPinnedStatus[\s\S]*pinnedStatusExpanded \?\? true/)
  assert.match(pinnedStatusCssSource, /\.agent-pinned-status-root \{[\s\S]*border-bottom: 1px solid var\(--ms-color-border\);/)
  assert.match(uiAgentPageCssSource, /\.project-agent-chat-shell \.agent-pinned-status-root \{[\s\S]*border-bottom: 1px solid var\(--ms-color-border\);/)
  assert.match(pinnedStatusCssSource, /\.agent-pinned-status-surface \{[\s\S]*border-radius: 0;[\s\S]*background: transparent;[\s\S]*box-shadow: none;/)
  assert.doesNotMatch(pinnedStatusCssSource, /border-radius: 0 0 var\(--ms-radius-md\) var\(--ms-radius-md\)/)
  assert.match(chatBubblesSource, /activityFeedRun && \(/)
  assert.match(chatBubblesSource, /!activityFeedRun && localRunActivity && \(/)
  assert.match(chatBubblesSource, /<RunActivityTitleBubble/)
})

test('agent session UI routes pending input answers before starting a new run', () => {
  const chatViewSource = readFileSync(resolve('src/features/agent/components/AgentChatView.tsx'), 'utf8')
  const chatViewControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatViewController.ts'), 'utf8')
  const chatPanelLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPanelLayout.tsx'), 'utf8')
  const chatPageLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPageLayout.tsx'), 'utf8')
  const interactionControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatInteractionController.ts'), 'utf8')
  const derivedStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatDerivedState.ts'), 'utf8')
  const runInteractionStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatRunInteractionState.ts'), 'utf8')
  const composerSource = readFileSync(resolve('src/features/agent/components/AgentComposerSection.tsx'), 'utf8')
  const threadSectionSource = readFileSync(resolve('src/features/agent/components/AgentConversationThreadSection.tsx'), 'utf8')
  const messageBoundariesSource = readFileSync(resolve('src/features/agent/domain/agentMessageBoundaries.ts'), 'utf8')
  const threadItemsSource = readFileSync(resolve('src/features/agent/domain/agentConversationThreadItems.ts'), 'utf8')
  const runInteractionAnchorsSource = readFileSync(resolve('src/features/agent/domain/agentRunInteractionAnchors.ts'), 'utf8')
  const chatActionBindingsSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatActionBindings.ts'), 'utf8')
  const sendActionsSource = readFileSync(resolve('src/features/agent/presentation/useAgentSendActions.ts'), 'utf8')
  const runtimeInputSource = readFileSync(resolve('src/features/agent/application/agentRuntimeInput.ts'), 'utf8')
  const runInteractionBindingsSource = readFileSync(resolve('src/features/agent/presentation/useAgentRunInteractionActionBindings.ts'), 'utf8')
  const runInteractionActionsSource = readFileSync(resolve('src/features/agent/application/agentRunInteractionActions.ts'), 'utf8')
  const runPageSource = readFileSync(resolve('src/features/agent/components/AIAgentRunPage.tsx'), 'utf8')

  assert.match(derivedStateSource, /useAgentChatRunInteractionState\(\{/)
  assert.match(runInteractionStateSource, /const activePendingInputRequest = firstPendingInputRequest\(actionableLocalRun\)/)
  assert.match(runInteractionStateSource, /const answeringPendingInput = !!activePendingInputRequest/)
  assert.match(chatViewSource, /useAgentChatViewController\(props\)/)
  assert.match(chatViewControllerSource, /useAgentChatInteractionController\(buildAgentChatInteractionControllerInput\(\{/)
  assert.match(interactionControllerSource, /useAgentChatActionBindings\(actionBindings\)/)
  assert.match(chatActionBindingsSource, /useAgentRunInteractionActionBindings\(\{/)
  assert.match(runInteractionBindingsSource, /answerRunInteractionInputAction\(\{/)
  assert.doesNotMatch(runInteractionActionsSource, /sourceMessageId: localMessageId/)
  assert.match(runInteractionActionsSource, /answerRunInput\(run\.id, \{[\s\S]*requestId,[\s\S]*\.\.\.answer,[\s\S]*\}\)/)
  assert.match(runInteractionActionsSource, /optimisticInputAnswerRun\(run, requestId, answer\)/)
  assert.match(runInteractionStateSource, /runInteractionAnswerEchoesForMessages\(messages, interactionRuns\)/)
  assert.match(chatViewSource, /<AgentChatPanelLayout/)
  assert.match(chatViewSource, /<AgentChatPageLayout/)
  assert.match(chatPanelLayoutSource, /<AgentConversationThreadSection/)
  assert.match(chatPageLayoutSource, /<AgentConversationThreadSection/)
  assert.match(threadSectionSource, /buildAgentConversationThreadItems\(\{/)
  assert.match(threadSectionSource, /<LocalAgentRunInteractionBubble/)
  assert.match(threadSectionSource, /const activityMessageRunIds = useMemo\(\(\) => runIdsWithActivityMessages\(messages\)/)
  assert.match(threadSectionSource, /if \(activityMessageRunIds\.has\(runId\)\) return false/)
  assert.match(messageBoundariesSource, /isAgentChatUiOnlyAssistantMessage/)
  assert.match(messageBoundariesSource, /isAgentChatVisibleAssistantMessage/)
  assert.match(messageBoundariesSource, /visibleAssistantRuntimeMessageRunId/)
  assert.match(messageBoundariesSource, /visibleAssistantRelatedRunId/)
  assert.match(messageBoundariesSource, /visibleAssistantActivityRunId/)
  assert.match(threadItemsSource, /isRunInteractionAnswerEchoMessage\(message, runInteractionAnswerEchoes\)/)
  assert.match(threadItemsSource, /isUiOnlyAssistantChatMessage\(message\)/)
  assert.match(threadItemsSource, /visibleAssistantRelatedRunId\(message\)/)
  assert.match(threadItemsSource, /visibleAssistantActivityRunId\(message\)/)
  assert.match(threadSectionSource, /visibleAssistantRelatedRunId\(message\)/)
  assert.match(runInteractionAnchorsSource, /isUiOnlyAssistantChatMessage\(message\)/)
  assert.match(runInteractionAnchorsSource, /isVisibleAssistantChatMessage\(message\)/)
  assert.match(runInteractionAnchorsSource, /visibleAssistantRelatedRunId\(message\)/)
  assert.match(threadItemsSource, /runInteractionFromActivity\(message\.meta\?\.localRunActivity\)/)
  assert.match(threadSectionSource, /activeRun\?\.status !== 'requires_action'/)
  assert.match(chatPanelLayoutSource, /<AgentComposerSection/)
  assert.match(chatPageLayoutSource, /<AgentComposerSection/)
  assert.match(composerSource, /answeringPendingInput \? '回答' : debugBeforeSend/)
  assert.match(composerSource, /buildingSendWorkspace \|\| \(answeringPendingInput && !canAnswerPendingInputWithText\)/)
  assert.match(sendActionsSource, /answerActiveLocalRunInput\(activePendingInputRequest\.id, \{ text \}\)/)
  assert.match(sendActionsSource, /if \(canSendActiveRunRuntimeInput\)/)
  assert.match(sendActionsSource, /sendActiveRunRuntimeInput\(\{ content, attachments \}\)/)
  assert.match(runtimeInputSource, /notifyAgentMessageFeedAcceptedSource\(result\.message, result\.run\)/)

  const pendingBranch = sendActionsSource.indexOf('if (answeringPendingInput && activePendingInputRequest)')
  const runtimeInputPath = sendActionsSource.indexOf('if (canSendActiveRunRuntimeInput)')
  const newRunPath = sendActionsSource.indexOf('const workspace = await buildSendWorkspace')
  assert.ok(pendingBranch > 0, 'pending input answer branch must exist in send()')
  assert.ok(newRunPath > pendingBranch, 'pending input must be handled before building a new send workspace')
  assert.ok(runtimeInputPath > pendingBranch, 'active run runtime input branch must run after pending input answers')
  assert.ok(newRunPath > runtimeInputPath, 'active run messages must be routed as runtime input before building a new send workspace')

  assert.match(runPageSource, /import \{ LocalAgentInputRequestCard \}/)
  assert.match(runPageSource, /<LocalAgentInputRequestCard/)
  assert.doesNotMatch(runPageSource, /inputWorkspaces/)
})

test('agent session UI renders generation job approvals as summary cards', () => {
  const runInteractionBubbleSource = readFileSync(resolve('src/features/agent/components/AgentRunInteractionBubble.tsx'), 'utf8')

  assert.match(runInteractionBubbleSource, /GenerationJobApprovalDetails/)
  assert.match(runInteractionBubbleSource, /generationJobApprovalView\(approval\)/)
  assert.match(runInteractionBubbleSource, /approval\.toolName === 'core_work_start' && kind === 'generation_job'/)
  assert.match(runInteractionBubbleSource, /approval\.toolName !== 'generation_job_create'/)
  assert.match(runInteractionBubbleSource, /view\.targetLabel/)
  assert.match(runInteractionBubbleSource, /view\.prompt/)
  assert.match(runInteractionBubbleSource, /referenceResourceIds/)
  assert.match(runInteractionBubbleSource, /ApprovalResourceThumbnail resourceId=\{previewResourceId\}/)
  assert.match(runInteractionBubbleSource, /ResourceFileImage/)
  assert.match(runInteractionBubbleSource, /safeJSONStringify\(approval\.args\)/)
})

test('agent session UI renders asset slot candidate approvals as summary cards', () => {
  const runInteractionBubbleSource = readFileSync(resolve('src/features/agent/components/AgentRunInteractionBubble.tsx'), 'utf8')

  assert.match(runInteractionBubbleSource, /AssetSlotCandidateApprovalDetails/)
  assert.match(runInteractionBubbleSource, /assetSlotCandidateApprovalView\(approval\)/)
  assert.match(runInteractionBubbleSource, /approval\.toolName !== 'candidate_asset_slot_attach'/)
  assert.match(runInteractionBubbleSource, /素材槽 #/)
  assert.match(runInteractionBubbleSource, /只加入候选集，不会锁定、采纳或替换当前素材。/)
  assert.match(runInteractionBubbleSource, /output_resource_id/)
  assert.match(runInteractionBubbleSource, /resource_id/)
  assert.match(runInteractionBubbleSource, /ResourceFileImage/)
})

test('agent panel keeps recent resources as mention candidates, not automatic context labels', () => {
  const chatViewSource = readFileSync(resolve('src/features/agent/components/AgentChatView.tsx'), 'utf8')
  const composerStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatComposerState.ts'), 'utf8')
  const composerControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentComposerController.ts'), 'utf8')
  const sendWorkspaceSource = readFileSync(resolve('src/features/agent/application/agentSendWorkspace.ts'), 'utf8')

  assert.doesNotMatch(chatViewSource, /recentResourcesCount/)
  assert.doesNotMatch(composerStateSource, /recentResourcesCount/)
  assert.match(composerStateSource, /recentResources,\s*fileRef,\s*inputRef/)
  assert.match(composerControllerSource, /for \(const resource of recentResources\)[\s\S]*attachmentFromResource\(resource\)/)
  assert.match(composerControllerSource, /input\.matchAll\(RESOURCE_MENTION_RE\)/)
  assert.match(sendWorkspaceSource, /recentResources: \[\]/)
})

test('agent composer supports clipboard file uploads with a blocking resource transfer dialog', () => {
  const composerControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentComposerController.ts'), 'utf8')
  const composerSectionSource = readFileSync(resolve('src/features/agent/components/AgentComposerSection.tsx'), 'utf8')
  const mentionEditorSource = readFileSync(resolve('src/features/agent/components/AgentMentionEditor.tsx'), 'utf8')
  const layoutPropsSource = readFileSync(resolve('src/features/agent/presentation/agentChatViewLayoutProps.ts'), 'utf8')

  assert.match(composerControllerSource, /function clipboardFiles\(event: ClipboardEvent\): File\[\]/)
  assert.match(composerControllerSource, /event\.clipboardData\.files/)
  assert.match(composerControllerSource, /item\.getAsFile\(\)/)
  assert.match(composerControllerSource, /async function handleComposerPaste\(event: ClipboardEvent\)/)
  assert.match(composerControllerSource, /await uploadFiles\(files\)/)
  assert.match(composerControllerSource, /setUploading\(true\)[\s\S]*setUploadingFileNames/)
  assert.match(composerControllerSource, /setUploadedFileCount\(index \+ 1\)/)
  assert.match(composerSectionSource, /<Dialog open=\{uploading\}>/)
  assert.match(composerSectionSource, /hideClose/)
  assert.match(composerSectionSource, /onEscapeKeyDown=\{\(event\) => event\.preventDefault\(\)\}/)
  assert.match(composerSectionSource, /agents\.chat\.uploadDialogDescription/)
  assert.match(composerSectionSource, /onPaste=\{onComposerPaste\}/)
  assert.match(mentionEditorSource, /onPaste\?\.\(event\)/)
  assert.match(mentionEditorSource, /if \(event\.defaultPrevented\) return/)
  assert.match(layoutPropsSource, /onComposerPaste: composer\.handleComposerPaste/)
})

test('agent panel no longer renders the context card surface', () => {
  const chatViewSource = readFileSync(resolve('src/features/agent/components/AgentChatView.tsx'), 'utf8')
  const chatViewControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatViewController.ts'), 'utf8')
  const chatPanelLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPanelLayout.tsx'), 'utf8')
  const chatPageLayoutSource = readFileSync(resolve('src/features/agent/components/AgentChatPageLayout.tsx'), 'utf8')
  const contextStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatContextState.ts'), 'utf8')

  assert.match(chatViewSource, /useAgentChatViewController\(props\)/)
  assert.match(chatViewControllerSource, /useAgentChatContextState\(\{/)
  assert.match(contextStateSource, /useAgentContextSummary\(\{/)
  assert.match(chatViewSource, /<AgentChatPanelLayout/)
  assert.match(chatViewSource, /<AgentChatPageLayout/)
  assert.doesNotMatch(chatPanelLayoutSource, /AgentContextSection/)
  assert.doesNotMatch(chatPanelLayoutSource, /context:/)
  assert.doesNotMatch(chatPageLayoutSource, /AgentContextSection/)
  assert.doesNotMatch(chatPageLayoutSource, /context:/)
  assert.doesNotMatch(contextStateSource, /useAgentContextPaneController/)
})
