import assert from 'node:assert/strict'
import test from 'node:test'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

function sourceFunctionBlock(source: string, functionName: string): string {
  const start = source.indexOf(`function ${functionName}(`)
  assert.ok(start >= 0, `missing function ${functionName}`)
  const bodyStart = source.indexOf('{', start)
  assert.ok(bodyStart >= 0, `missing function body for ${functionName}`)
  let depth = 0
  for (let index = bodyStart; index < source.length; index += 1) {
    const character = source[index]
    if (character === '{') depth += 1
    if (character === '}') {
      depth -= 1
      if (depth === 0) return source.slice(bodyStart, index + 1)
    }
  }
  assert.fail(`unterminated function ${functionName}`)
}

function sourceBetween(source: string, startNeedle: string, endNeedle: string): string {
  const start = source.indexOf(startNeedle)
  assert.ok(start >= 0, `missing source marker ${startNeedle}`)
  const end = source.indexOf(endNeedle, start)
  assert.ok(end >= 0, `missing source marker ${endNeedle}`)
  return source.slice(start, end)
}

function uiAgentGeneratedFeedbackSource(): string {
  return readFileSync(resolve('../../packages/ui/src/components/business/agent/generated/feedback/index.tsx'), 'utf8')
}

test('agent session UI keeps worker trace summary contracts without run detail pages', () => {
  const planOverviewSource = readFileSync(resolve('src/features/agent/components/AgentPlanOverviewPanel.tsx'), 'utf8')

  assert.match(planOverviewSource, /const \[traceSummaries, setTraceSummaries\]/)
  assert.match(planOverviewSource, /const \[traceEventsByRunId, setTraceEventsByRunId\]/)
  assert.match(planOverviewSource, /providerSessionClient\.forSession\(\{ sessionId: snapshotSessionId \}\)/)
  assert.match(planOverviewSource, /providerSessionTraceClient\.getRunTraceSummary\(runId\)/)
  assert.match(planOverviewSource, /providerSessionTraceClient\.getRunTraceEvents\(runId, \{ limit: 8/)
  assert.match(planOverviewSource, /navigate\(ROUTES\.agentConsole\)/)
  assert.match(planOverviewSource, /traceEventHasMoreByRunId/)
  assert.match(planOverviewSource, /traceEventKindFilters/)
  assert.match(planOverviewSource, /轨迹统计/)
  assert.match(planOverviewSource, /运行事件/)
  assert.match(planOverviewSource, /加载更多/)
})

test('desktop bootstrap does not auto-start a workspace-global provider session', () => {
  const managedBootstrapSource = readFileSync(resolve('electron/managedServices/bootstrap.ts'), 'utf8')
  const settingsIpcSource = readFileSync(resolve('electron/ipc/settingsIpc.ts'), 'utf8')

  assert.doesNotMatch(managedBootstrapSource, new RegExp(['ensure', 'Agent', 'Runtime', 'Running'].join('')))
  assert.doesNotMatch(managedBootstrapSource, new RegExp(['start', 'Agent', 'Runtime', 'On', 'App', 'Ready'].join('')))
  assert.doesNotMatch(managedBootstrapSource, /registerDesktopMCPProviderWithAgent/)
  assert.match(managedBootstrapSource, /provider sessions will use this backend by default/)

  assert.doesNotMatch(settingsIpcSource, new RegExp(['ensure', 'Agent', 'Runtime', 'Running'].join('')))
  assert.doesNotMatch(settingsIpcSource, new RegExp(['get', 'Agent', 'Runtime', 'Launch', 'Policy'].join('')))
  assert.match(settingsIpcSource, /ensureMCPServerReady/)
})

test('agent composer supports clipboard file uploads with a blocking resource transfer dialog', () => {
  const composerControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentComposerController.ts'), 'utf8')
  const composerSectionSource = readFileSync(resolve('src/features/agent/components/AgentComposerSection.tsx'), 'utf8')
  const mentionEditorSource = readFileSync(resolve('src/features/agent/components/AgentMentionEditor.tsx'), 'utf8')
  const layoutPropsSource = readFileSync(resolve('src/features/agent/presentation/agentChatViewLayoutProps.ts'), 'utf8')

  assert.match(composerControllerSource, /function clipboardFiles\(event: ClipboardEvent\): File\[\]/)
  assert.match(composerControllerSource, /acceptAgentComposerDropDragOver\(event\.dataTransfer\)/)
  assert.match(composerControllerSource, /agentComposerDropKind\(event\.dataTransfer\)/)
  assert.match(composerControllerSource, /readAgentComposerResourceDrop\(event\.dataTransfer\)/)
  assert.doesNotMatch(composerControllerSource, /event\.dataTransfer\.dropEffect = 'copy'/)
  assert.doesNotMatch(composerControllerSource, /hasResourceDragPayload/)
  assert.doesNotMatch(composerControllerSource, /readResourceDragPayload/)
  assert.match(composerControllerSource, /event\.clipboardData\.files/)
  assert.match(composerControllerSource, /item\.getAsFile\(\)/)
  assert.match(composerControllerSource, /async function handleComposerPaste\(event: ClipboardEvent\)/)
  assert.match(composerControllerSource, /await uploadFiles\(files\)/)
  assert.match(composerControllerSource, /setUploading\(true\)[\s\S]*setUploadingFileNames/)
  assert.match(composerControllerSource, /setUploadedFileCount\(index \+ 1\)/)
  assert.match(composerSectionSource, /showAttachmentTools = true/)
  assert.match(composerSectionSource, /showMentionTools = true/)
  assert.match(composerSectionSource, /showDebugPreview = true/)
  assert.match(composerSectionSource, /\{showAttachmentTools \? \(/)
  assert.match(composerSectionSource, /\{showMentionTools \? \(/)
  assert.match(composerSectionSource, /\{showDebugPreview \? \(/)
  assert.match(composerSectionSource, /<Dialog open=\{uploading\}>/)
  assert.match(composerSectionSource, /hideClose/)
  assert.match(composerSectionSource, /onEscapeKeyDown=\{\(event\) => event\.preventDefault\(\)\}/)
  assert.match(composerSectionSource, /agents\.chat\.uploadDialogDescription/)
  assert.match(composerSectionSource, /onPaste=\{onComposerPaste\}/)
  assert.match(mentionEditorSource, /onPaste\?\.\(event\)/)
  assert.match(mentionEditorSource, /if \(event\.defaultPrevented\) return/)
  assert.match(layoutPropsSource, /onComposerPaste: composer\.handleComposerPaste/)
})

test('agent chat composer uses the same chrome in page and detail surfaces', () => {
  const dataSourceShellSource = readFileSync(resolve('src/features/agent/components/AgentChatDataSourceShell.tsx'), 'utf8')
  const panelShellLayoutCss = readFileSync(resolve('../../packages/ui/src/components/business/agent/panel/shell-layout/styles.css'), 'utf8')

  assert.match(dataSourceShellSource, /<AgentComposerSection[\s\S]*?chrome="flush"/)
  assert.match(dataSourceShellSource, /ai-agent-panel-composer-wrap/)
  assert.match(panelShellLayoutCss, /\.ai-agent-panel-shell \.ai-agent-panel-composer-wrap/)
  assert.doesNotMatch(dataSourceShellSource, /chrome=\{surface === 'page' \? 'flush' : 'bottom-bar'\}/)
})

test('agent mode sidebar keeps conversations scoped to unbound chats', () => {
  const agentModePageSource = readFileSync(resolve('src/features/agent/components/ProjectAgentModePage.tsx'), 'utf8')
  const conversationGroupSource = sourceBetween(
    agentModePageSource,
    "<AgentSidebarGroup\n          title={t('agents.chat.agentModeSidebar.conversations')}",
    "<AgentSidebarGroup\n          title={t('agents.chat.conversationHistory')}",
  )

  assert.match(agentModePageSource, /const \{ projectGroups, chatConversations \} = conversationsByScope/)
  assert.match(agentModePageSource, /const sortedChatConversations = chatConversations/)
  assert.match(conversationGroupSource, /trailing=\{chatConversations\.length > 0 \? `\$\{chatConversations\.length\}` : undefined\}/)
  assert.match(conversationGroupSource, /sortedChatConversations\.length === 0/)
  assert.match(conversationGroupSource, /visibleChatConversations\.map/)
  assert.doesNotMatch(conversationGroupSource, /appServerMode \?/)
  assert.doesNotMatch(agentModePageSource, /appServerActiveThreadId/)
  assert.doesNotMatch(agentModePageSource, /AppServerSidebarActiveThread/)
})

test('agent composer locks workspace context after a session starts', () => {
  const composerControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentComposerController.ts'), 'utf8')
  const composerSectionSource = readFileSync(resolve('src/features/agent/components/AgentComposerSection.tsx'), 'utf8')
  const dataSourceShellSource = readFileSync(resolve('src/features/agent/components/AgentChatDataSourceShell.tsx'), 'utf8')
  const layoutPropsSource = readFileSync(resolve('src/features/agent/presentation/agentChatViewLayoutProps.ts'), 'utf8')
  const sessionStoreSource = readFileSync(resolve('src/features/agent/state/agentSessionStore.ts'), 'utf8')
  const composerCssSource = readFileSync(resolve('../../packages/ui/src/components/business/agent/composer/styles.css'), 'utf8')

  assert.match(composerControllerSource, /workspaceContextLocked/)
  assert.match(composerControllerSource, /if \(workspaceContextLocked\) return/)
  assert.match(composerSectionSource, /workspaceProjectLocked/)
  assert.match(composerSectionSource, /selectedWorkspaceProjectLabel/)
  assert.doesNotMatch(composerSectionSource, /ProviderMark/)
  assert.match(composerSectionSource, /collaborationMode === 'plan'/)
  assert.match(composerSectionSource, /goalModeEnabled \? \(/)
  assert.match(dataSourceShellSource, /const composerWorkspaceContextLocked = Boolean\(activeThreadId\)/)
  assert.match(dataSourceShellSource, /workspaceProjectLocked=\{composerWorkspaceContextLocked\}/)
  assert.match(dataSourceShellSource, /workspaceContext: composer\.selectedWorkspaceContext/)
  assert.match(layoutPropsSource, /workspaceProjectLocked: conversationEstablished/)
  assert.match(sessionStoreSource, /const workspaceContext = userWorkspaces\[conversationId\]\?\.workspaceContext/)
  assert.match(sessionStoreSource, /input: '',[\s\S]*attachments: \[\],[\s\S]*workspaceContext/)
  assert.match(composerCssSource, /\.ms-agent-composer \.ms-agent-composer__workspace-select,[\s\S]*\.ms-agent-composer \.ai-agent-model-select[\s\S]*border-color: transparent;[\s\S]*background: transparent;/)
})

test('agent new conversation drafts bind selected project without starting a thread before send', () => {
  const composerControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentComposerController.ts'), 'utf8')
  const agentModePageSource = readFileSync(resolve('src/features/agent/components/ProjectAgentModePage.tsx'), 'utf8')
  const agentStoreSource = readFileSync(resolve('src/features/agent/state/agentStore.ts'), 'utf8')
  const dataSourceShellSource = readFileSync(resolve('src/features/agent/components/AgentChatDataSourceShell.tsx'), 'utf8')
  const agentBrowserPanelSource = readFileSync(resolve('src/features/agent/components/AgentBrowserPanel.tsx'), 'utf8')
  const agentContentAreaStoreSource = readFileSync(resolve('src/features/agent/state/agentContentAreaStore.ts'), 'utf8')
  const aiAgentPanelSource = readFileSync(resolve('src/features/agent/components/AIAgentPanel.tsx'), 'utf8')
  const appSource = readFileSync(resolve('src/App.tsx'), 'utf8')
  const headerSource = readFileSync(resolve('src/features/app-shell/components/Header.tsx'), 'utf8')
  const topControlsSource = readFileSync(resolve('src/features/app-shell/components/AppTopControls.tsx'), 'utf8')
  const layoutPropsSource = readFileSync(resolve('src/features/agent/presentation/agentChatViewLayoutProps.ts'), 'utf8')
  const viewControllerSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatViewController.ts'), 'utf8')
  const contextStateSource = readFileSync(resolve('src/features/agent/presentation/useAgentChatContextState.ts'), 'utf8')
  const interactionInputTypesSource = readFileSync(resolve('src/features/agent/presentation/agentChatInteractionInputTypes.ts'), 'utf8')
  const sendPipelineSource = readFileSync(resolve('src/features/agent/presentation/agentChatSendPipelineInputs.ts'), 'utf8')
  const sendWorkspaceSource = readFileSync(resolve('src/features/agent/application/agentSendWorkspace.ts'), 'utf8')
  const normalizeWorkspaceContextBlock = sourceFunctionBlock(composerControllerSource, 'normalizeAgentWorkspaceContext')
  const resumeThreadBlock = sourceBetween(dataSourceShellSource, 'void dataSource.resumeThread({', '})\n        .then')
  const updateThreadSettingsBlock = sourceBetween(dataSourceShellSource, 'void dataSource.updateThreadSettings({', '})\n      .then')
  const sendMessageBlock = sourceBetween(dataSourceShellSource, 'const sendMessage = useCallback', 'const submitQueuedInputsAsTurn = useCallback')
  const queuedTurnBlock = sourceBetween(dataSourceShellSource, 'const submitQueuedInputsAsTurn = useCallback', 'const submitQueuedInputAsTurn = useCallback')

  assert.doesNotMatch(composerControllerSource, /normalizeAgentWorkspaceContext\([\s\S]*\{ projectId: currentProject\?\.ID \}/)
  assert.doesNotMatch(composerControllerSource, /useProjectStore/)
  assert.doesNotMatch(normalizeWorkspaceContextBlock, /fallback\.projectId/)
  assert.match(normalizeWorkspaceContextBlock, /scope: 'global'/)
  assert.match(composerControllerSource, /label: '全局', meta: '不绑定项目'/)
  assert.match(composerControllerSource, /project\.ID === currentProject\?\.ID[\s\S]*\? '当前项目'/)
  assert.match(composerControllerSource, /currentProject = null/)
  assert.doesNotMatch(agentModePageSource, /AgentWorkspaceScopeSelection/)
  assert.doesNotMatch(agentModePageSource, /useProjectStore/)
  assert.doesNotMatch(agentModePageSource, /project\?\.ID/)
  assert.doesNotMatch(agentModePageSource, /setNewConversationWorkspaceScope/)
  assert.doesNotMatch(agentModePageSource, /选择新建会话范围/)
  assert.doesNotMatch(agentModePageSource, /newConversationWorkspaceContext/)
  assert.doesNotMatch(agentModePageSource, /selectedNewConversationProjectId/)
  assert.match(agentModePageSource, /openAgentPanelNewConversation\(\{[\s\S]*workspaceContext: \{ scope: 'global' \}/)
  assert.doesNotMatch(agentModePageSource, /sortedProjectOptions\.map/)
  assert.doesNotMatch(agentModePageSource, /当前项目/)
  assert.doesNotMatch(agentModePageSource, /scope: 'project', projectId: item\.ID/)
  assert.doesNotMatch(agentModePageSource, /await dataSource\.startThread/)
  assert.doesNotMatch(agentModePageSource, /startSharedProvisionalConversation\(/)
  assert.doesNotMatch(agentModePageSource, /projectId: selectedNewConversationProjectId/)
  assert.match(sendPipelineSource, /workspaceContext: composer\.selectedWorkspaceContext/)
  assert.match(interactionInputTypesSource, /conversationEstablished: boolean/)
  assert.match(viewControllerSource, /conversationEstablished,/)
  assert.match(sendPipelineSource, /const draftThreadControl = conversationEstablished[\s\S]*\? undefined[\s\S]*composer\.collaborationMode/)
  assert.match(sendPipelineSource, /const threadControl = draftThreadControl && Object\.keys\(draftThreadControl\)\.length > 0/)
  assert.match(sendPipelineSource, /\.\.\.\(threadControl \? \{ threadControl \} : \{\}\)/)
  assert.match(layoutPropsSource, /selectedWorkspaceProjectId/)
  assert.match(layoutPropsSource, /projectId: selectedWorkspaceProjectId/)
  assert.doesNotMatch(layoutPropsSource, /projectId: currentProject\?\.ID/)
  assert.match(viewControllerSource, /selectedWorkspaceProjectName/)
  assert.match(viewControllerSource, /composer\.selectedWorkspaceContext\.scope === 'project'/)
  assert.match(contextStateSource, /selectedProjectName/)
  assert.doesNotMatch(contextStateSource, /currentProject\?\.name/)
  assert.match(sendWorkspaceSource, /resolveProviderSessionProjectId/)
  assert.match(agentStoreSource, /resetDraftModeSettings/)
  assert.match(agentStoreSource, /goalModeEnabled: DEFAULT_AGENT_SETTINGS\.goalModeEnabled/)
  assert.match(dataSourceShellSource, /type StartThreadInput[\s\S]*useDraftModeSettings\?: boolean/)
  assert.match(dataSourceShellSource, /const resetDraftModeSettings = useCallback/)
  assert.match(dataSourceShellSource, /function draftThreadControlOptions/)
  assert.match(dataSourceShellSource, /useDraftModeSettings \? draftThreadControlOptions\(\{ collaborationMode, goalModeEnabled \}\) : \{\}/)
  assert.doesNotMatch(resumeThreadBlock, /collaborationMode|goalModeEnabled/)
  assert.doesNotMatch(updateThreadSettingsBlock, /collaborationMode|goalModeEnabled/)
  assert.match(sendMessageBlock, /let firstTurnDraftControls/)
  assert.match(sendMessageBlock, /firstTurnDraftControls = draftThreadControlOptions\(\{ collaborationMode, goalModeEnabled \}\)/)
  assert.doesNotMatch(sendMessageBlock, /ensureAgentChatThreadReadyForTurn\(\{[\s\S]*controls:/)
  assert.doesNotMatch(sendMessageBlock, /\.\.\.\(collaborationMode === 'plan'/)
  assert.doesNotMatch(sendMessageBlock, /\.\.\.\(goalModeEnabled/)
  assert.doesNotMatch(queuedTurnBlock, /collaborationMode|goalModeEnabled/)
  assert.match(dataSourceShellSource, /function workspaceContextFromNewConversationPayload/)
  assert.match(dataSourceShellSource, /if \(payload\?\.workspaceContext\) return payload\.workspaceContext/)
  assert.match(dataSourceShellSource, /scope: 'project'[\s\S]*projectId/)
  assert.match(dataSourceShellSource, /const createDraftConversation = useCallback/)
  assert.match(dataSourceShellSource, /resetDraftModeSettings\(\)[\s\S]*createDraftConversation\(/)
  assert.match(sendMessageBlock, /startThreadResult\(\{[\s\S]*useDraftModeSettings: true/)
  assert.match(appSource, /showProjectControls=\{false\}/)
  assert.match(headerSource, /showProjectControls \? <ProjectGitHeaderActions compact \/> : null/)
  assert.match(topControlsSource, /showProjectSelector \? \(/)
  assert.match(agentModePageSource, /sessionWorkspaceContext/)
  assert.match(agentModePageSource, /sessionProjectId = positiveInteger\(sessionWorkspaceContext\?\.projectId\)/)
  assert.match(agentModePageSource, /<AgentBrowserPanel contentAreaId=\{contentAreaId\} conversationId=\{sessionConversationId\} project=\{sessionProject\} \/>/)
  assert.doesNotMatch(agentBrowserPanelSource, /useProjectStore/)
  assert.match(aiAgentPanelSource, /useProjectStore/)
  assert.match(aiAgentPanelSource, /currentProject=\{currentProject\}/)
  assert.match(agentContentAreaStoreSource, /AGENT_BLANK_TAB_ID = 'blank_home'/)
  assert.match(agentBrowserPanelSource, /defaultTab: hasProject \? 'project_home' : 'blank'/)
})
