import type { MovScriptWorkspaceFileRepository } from './types.js'

export const MOVSCRIPT_PROJECT_STANDARD_SKILL_ID = 'movscript_project-standards/project-standards'

export const MOVSCRIPT_PROJECT_STANDARD_SKILL_PATHS = [
  '.codex/skills/plugins/movscript_project-standards/project-standards/SKILL.md',
  '.claude/skills/plugins/movscript_project-standards/project-standards/SKILL.md',
  '.mova/skills/plugins/movscript_project-standards/project-standards/SKILL.md',
] as const

export interface MovScriptProjectStandardSkillsSyncInput {
  fileRepository: MovScriptWorkspaceFileRepository
  standards: Record<string, unknown>
}

export interface MovScriptProjectStandardSkillsSyncResult {
  path: string
  content: string
}

export async function syncMovScriptProjectStandardSkills(
  input: MovScriptProjectStandardSkillsSyncInput,
): Promise<MovScriptProjectStandardSkillsSyncResult[]> {
  const content = renderMovScriptProjectStandardSkill(input.standards)
  const results: MovScriptProjectStandardSkillsSyncResult[] = []
  for (const path of MOVSCRIPT_PROJECT_STANDARD_SKILL_PATHS) {
    await input.fileRepository.write({ path, content })
    results.push({ path, content })
  }
  return results
}

export function renderMovScriptProjectStandardSkill(
  standards: Record<string, unknown>,
): string {
  const projectStyle = parseProjectStyle(standards.project_style)
  const coreSections = [
    fieldSection('Aspect ratio', standards.aspect_ratio ?? projectStyle.aspect_ratio),
    fieldSection('Visual style', standards.visual_style ?? projectStyle.visual_style),
    fieldSection('Lighting style', standards.lighting_style ?? projectStyle.lighting_style),
    fieldSection('Camera language', standards.camera_language ?? projectStyle.camera_language),
    fieldSection('Color palette', standards.color_palette ?? projectStyle.color_palette),
    fieldSection('Pacing rules', standards.pacing_rules ?? projectStyle.pacing_rules),
    listSection('Shot size system', standards.shot_size_system ?? projectStyle.shot_size_system),
    listSection('Negative rules', standards.negative_rules ?? projectStyle.negative_rules),
    customRulesSection(standards.custom_rules ?? projectStyle.custom_rules),
    styleReferenceSection(standards, projectStyle),
  ].filter(Boolean)

  return [
    '---',
    'name: project-standards',
    'description: Apply the current MovScript project standards from project_standards.json when planning, coding, prompting, or generating project-scoped work.',
    '---',
    '',
    '# MovScript Project Standards',
    '',
    'Generated from `project_standards.json`. Do not edit this file manually; update project standards through MovScript source or domain tools.',
    '',
    'Use this skill whenever work depends on this MovScript project, especially planning, content-unit prompts, generation, style-sensitive code, or provider behavior.',
    '',
    '## Rules',
    '',
    '- Treat `project_standards.json` as the source of truth.',
    '- Apply these standards as project-wide house style and constraints.',
    '- Do not change project standards unless the user explicitly asks to add, remove, replace, or refine them.',
    '- For visual generation that supports references, pass listed style reference resource ids as house-style references.',
    '',
    ...(coreSections.length
      ? ['## Current Standards', '', ...coreSections]
      : ['## Current Standards', '', '- No project standards are currently filled.', '']),
  ].join('\n')
}

function fieldSection(label: string, value: unknown): string | undefined {
  const text = textValue(value)
  return text ? `### ${label}\n\n${text}\n` : undefined
}

function listSection(label: string, value: unknown): string | undefined {
  const items = arrayValues(value)
  if (!items.length) return undefined
  return `### ${label}\n\n${items.map((item) => `- ${item}`).join('\n')}\n`
}

function customRulesSection(value: unknown): string | undefined {
  const rules = arrayRecords(value)
    .filter((rule) => rule.enabled !== false)
    .map((rule) => {
      const key = textValue(rule.key) ?? 'custom_rule'
      const ruleValue = rule.value ?? rule.text ?? rule.description
      const text = textValue(ruleValue) ?? JSON.stringify(ruleValue)
      return text ? `- ${key}: ${text}` : undefined
    })
    .filter((rule): rule is string => Boolean(rule))
  if (!rules.length) return undefined
  return `### Custom rules\n\n${rules.join('\n')}\n`
}

function styleReferenceSection(
  standards: Record<string, unknown>,
  projectStyle: Record<string, unknown>,
): string | undefined {
  const ids = uniqueNumbers([
    ...resourceIdsFromValue(standards.style_reference_images),
    ...resourceIdsFromValue(standards.style_references),
    ...resourceIdsFromValue(standards.reference_resource_ids),
    ...resourceIdsFromValue(projectStyle.style_reference_images),
    ...resourceIdsFromValue(projectStyle.style_references),
    ...resourceIdsFromValue(projectStyle.reference_resource_ids),
    ...arrayRecords(standards.custom_rules)
      .filter((rule) => rule.enabled !== false)
      .filter((rule) => textValue(rule.key) === 'style_reference_images')
      .flatMap((rule) => resourceIdsFromValue(rule.value)),
    ...arrayRecords(projectStyle.custom_rules)
      .filter((rule) => rule.enabled !== false)
      .filter((rule) => textValue(rule.key) === 'style_reference_images')
      .flatMap((rule) => resourceIdsFromValue(rule.value)),
  ])
  if (!ids.length) return undefined
  return `### Style reference resource ids\n\n${ids.map((id) => `- ${id}`).join('\n')}\n`
}

function resourceIdsFromValue(value: unknown): number[] {
  if (Array.isArray(value)) return value.flatMap(resourceIdsFromValue)
  if (typeof value === 'number' && Number.isInteger(value)) return [value]
  if (isRecord(value)) {
    return [
      ...resourceIdsFromValue(value.resource_id),
      ...resourceIdsFromValue(value.resource_ids),
      ...resourceIdsFromValue(value.id),
    ]
  }
  const text = textValue(value)
  if (!text) return []
  return Array.from(text.matchAll(/\b(?:resource[_-]?id|resource)[_:#\s-]*(\d+)\b/gi))
    .map((match) => Number(match[1]))
    .filter((id) => Number.isInteger(id))
}

function parseProjectStyle(value: unknown): Record<string, unknown> {
  if (isRecord(value)) return value
  const text = textValue(value)
  if (!text) return {}
  try {
    const parsed = JSON.parse(text) as unknown
    return isRecord(parsed) ? parsed : {}
  } catch {
    return {}
  }
}

function arrayValues(value: unknown): string[] {
  if (Array.isArray(value)) return value.map(textValue).filter((item): item is string => Boolean(item))
  const text = textValue(value)
  return text ? [text] : []
}

function arrayRecords(value: unknown): Record<string, unknown>[] {
  return Array.isArray(value) ? value.filter(isRecord) : []
}

function uniqueNumbers(values: number[]): number[] {
  return Array.from(new Set(values)).sort((left, right) => left - right)
}

function textValue(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value)
}
