import react from '@vitejs/plugin-react'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'

const serviceRoot = __dirname
const adminRoot = resolve(serviceRoot, '../../surface/admin')
const uiBusinessAliases = {
  '@movscript/ui/business/agent': resolve(serviceRoot, '../../packages/ui/src/business/agent.ts'),
  '@movscript/ui/business/app': resolve(serviceRoot, '../../packages/ui/src/business/app.ts'),
  '@movscript/ui/business/canvas': resolve(serviceRoot, '../../packages/ui/src/business/canvas.ts'),
  '@movscript/ui/business/generation': resolve(serviceRoot, '../../packages/ui/src/business/generation.ts'),
  '@movscript/ui/business/resource': resolve(serviceRoot, '../../packages/ui/src/business/resource.ts'),
  '@movscript/ui/business/review': resolve(serviceRoot, '../../packages/ui/src/business/review.ts'),
  '@movscript/ui/business/workbench': resolve(serviceRoot, '../../packages/ui/src/business/workbench.ts'),
}
const uiStyleAliases = {
  '@movscript/ui/styles/base.css': resolve(serviceRoot, '../../packages/ui/src/styles/base.css'),
  '@movscript/ui/styles/primitives.css': resolve(serviceRoot, '../../packages/ui/src/styles/primitives.css'),
  '@movscript/ui/styles/semantic.css': resolve(serviceRoot, '../../packages/ui/src/styles/semantic.css'),
  '@movscript/ui/styles/layout.css': resolve(serviceRoot, '../../packages/ui/src/styles/layout.css'),
  '@movscript/ui/styles/business/agent.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/agent.css'),
  '@movscript/ui/styles/business/app.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/app.css'),
  '@movscript/ui/styles/business/canvas.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/canvas.css'),
  '@movscript/ui/styles/business/generation.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/generation.css'),
  '@movscript/ui/styles/business/resource.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/resource.css'),
  '@movscript/ui/styles/business/review.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/review.css'),
  '@movscript/ui/styles/business/workbench.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/workbench.css'),
}

export default defineConfig({
  base: process.env.MOVSCRIPT_WEB_SURFACE_HOST_BASE ?? '/',
  plugins: [react()],
  resolve: {
    alias: {
      '@movscript/admin-surface/app': resolve(adminRoot, 'src/main.tsx'),
      '@movscript/admin-surface': resolve(serviceRoot, '../../surface/admin/src/index.ts'),
      '@movscript/project-surface/data': resolve(serviceRoot, '../../surface/project/src/data.ts'),
      '@movscript/project-surface/i18n': resolve(serviceRoot, '../../surface/project/src/i18n.ts'),
      '@movscript/project-surface/layout': resolve(serviceRoot, '../../surface/project/src/layout.ts'),
      '@movscript/project-surface/pages': resolve(serviceRoot, '../../surface/project/src/pages/index.ts'),
      '@movscript/project-surface/react': resolve(serviceRoot, '../../surface/project/src/react.ts'),
      '@movscript/project-surface/routes': resolve(serviceRoot, '../../surface/project/src/routes.ts'),
      '@movscript/project-surface/runtime': resolve(serviceRoot, '../../surface/project/src/runtime.ts'),
      '@movscript/project-surface': resolve(serviceRoot, '../../surface/project/src/index.ts'),
      '@movscript/resource-surface/data': resolve(serviceRoot, '../../surface/resource/src/data.ts'),
      '@movscript/resource-surface/i18n': resolve(serviceRoot, '../../surface/resource/src/i18n.ts'),
      '@movscript/resource-surface/pages': resolve(serviceRoot, '../../surface/resource/src/pages/index.ts'),
      '@movscript/resource-surface/resource-browser': resolve(serviceRoot, '../../surface/resource/src/resource-browser.ts'),
      '@movscript/resource-surface/resource-candidate-attach-panel': resolve(serviceRoot, '../../surface/resource/src/resourceCandidateAttachPanel.tsx'),
      '@movscript/resource-surface/resource-interaction': resolve(serviceRoot, '../../surface/resource/src/resourceInteraction.ts'),
      '@movscript/resource-surface/resource-library-picker': resolve(serviceRoot, '../../surface/resource/src/resourceLibraryPicker.tsx'),
      '@movscript/resource-surface/resource-library-picker-ui': resolve(serviceRoot, '../../surface/resource/src/resourceLibraryPickerUi.tsx'),
      '@movscript/resource-surface/resource-media': resolve(serviceRoot, '../../surface/resource/src/resourceMediaBrowser.ts'),
      '@movscript/resource-surface/resource-media-components': resolve(serviceRoot, '../../surface/resource/src/resourceMediaComponents.tsx'),
      '@movscript/resource-surface/resource-media-diagnostics': resolve(serviceRoot, '../../surface/resource/src/resourceMediaDiagnostics.ts'),
      '@movscript/resource-surface/resource-media-viewer': resolve(serviceRoot, '../../surface/resource/src/resourceMediaViewer.tsx'),
      '@movscript/resource-surface/react': resolve(serviceRoot, '../../surface/resource/src/react.ts'),
      '@movscript/resource-surface/routes': resolve(serviceRoot, '../../surface/resource/src/routes.ts'),
      '@movscript/resource-surface': resolve(serviceRoot, '../../surface/resource/src/index.ts'),
      '@movscript/editing/browser': resolve(serviceRoot, '../../packages/editing/src/browser.ts'),
      '@movscript/editing': resolve(serviceRoot, '../../packages/editing/src/browser.ts'),
      '@movscript/resources': resolve(serviceRoot, '../../packages/resources/src/index.ts'),
      '@movscript/core/agent': resolve(serviceRoot, '../../packages/core/src/agent/index.ts'),
      '@movscript/core/content': resolve(serviceRoot, '../../packages/core/src/content/index.ts'),
      '@movscript/core/generation': resolve(serviceRoot, '../../packages/core/src/generation/index.ts'),
      '@movscript/core/resources': resolve(serviceRoot, '../../packages/core/src/resources/index.ts'),
      '@movscript/core/workspace': resolve(serviceRoot, '../../packages/core/src/workspace/index.ts'),
      '@movscript/core/mcp': resolve(serviceRoot, '../../packages/core/src/mcp/index.ts'),
      '@movscript/core/backend': resolve(serviceRoot, '../../packages/core/src/backend/index.ts'),
      '@movscript/core/plugins': resolve(serviceRoot, '../../packages/core/src/plugins/index.ts'),
      '@movscript/domain': resolve(serviceRoot, '../../packages/domain/src/index.ts'),
      '@movscript/workspace/home': resolve(serviceRoot, '../../packages/workspace/src/home/index.ts'),
      '@movscript/workspace/indexer': resolve(serviceRoot, '../../packages/workspace/src/indexer/index.ts'),
      '@movscript/workspace/layout': resolve(serviceRoot, '../../packages/workspace/src/layout/index.ts'),
      '@movscript/workspace/node': resolve(serviceRoot, '../../packages/workspace/src/node/index.ts'),
      '@movscript/workspace/repository': resolve(serviceRoot, '../../packages/workspace/src/repository/index.ts'),
      '@movscript/workspace': resolve(serviceRoot, '../../packages/workspace/src/index.ts'),
      '@movscript/theme/theme.css': resolve(serviceRoot, '../../packages/theme/src/theme.css'),
      '@movscript/theme': resolve(serviceRoot, '../../packages/theme/src/index.ts'),
      '@movscript/ui/style-system': resolve(serviceRoot, '../../packages/ui/src/style-system.ts'),
      '@movscript/ui/semantic': resolve(serviceRoot, '../../packages/ui/src/semantic.ts'),
      '@movscript/ui/primitives': resolve(serviceRoot, '../../packages/ui/src/primitives.ts'),
      '@movscript/ui/layout': resolve(serviceRoot, '../../packages/ui/src/layout.ts'),
      '@movscript/ui/debug': resolve(serviceRoot, '../../packages/ui/src/debug-entry.ts'),
      '@movscript/ui/toast': resolve(serviceRoot, '../../packages/ui/src/toast.ts'),
      ...uiBusinessAliases,
      ...uiStyleAliases,
      '@movscript/ui': resolve(serviceRoot, '../../packages/ui/src/index.ts'),
      '@admin-runtime': resolve(adminRoot, 'src/runtime/community.tsx'),
      '@admin': resolve(adminRoot, 'src'),
      '@': resolve(adminRoot, 'src'),
    },
  },
})
