import type { PreviewMoment } from './sourceWorkspaceTypes'

export const previewMoments: PreviewMoment[] = [
  {
    id: 'm1',
    title: '雨夜电话打断告白',
    path: 'productions/pilot/segments/opening/scene_moments/rain_call',
    selectionState: 'selected',
    priority: '高优先级',
    production: '短剧试播集',
    segment: '开场钩子',
    settings: ['setting/rain_rooftop', 'asset/phone_screen', 'asset/wet_hair', 'setting/city_backlight'],
    shots: [
      {
        id: 'shot_phone_press',
        title: '女主手指停在拨号键上',
        camera: '特写 · 俯拍 · 静止',
        duration: '3s',
        expression: '迟疑、恐惧和最后一秒的决心同时出现，手机屏幕成为主要光源。',
        stillPosition: '0% 0%',
        path: '.../scene_moments/rain_call/shots/shot_phone_press',
        keyframes: ['kf_phone_hover', 'kf_rain_on_screen', 'kf_phone_press'],
        assets: [
          { title: 'asset/phone_screen', status: 'locked' },
          { title: 'asset/wet_hand_ref', status: 'ready' },
        ],
        storyboard: 'storyboard/phone_press_board',
        contentUnit: {
          id: 'cu_storyboard_phone_press',
          type: 'storyboard_ref',
          outputKind: 'video',
          path: 'content_units/cu_storyboard_phone_press/content_unit.json',
          editPrompt: '雨夜手机特写视频，使用 {{asset:phone_screen}} 作为上游参考输入。',
          sceneMomentRef: 'scene_moment/rain_call',
          shotId: 'shot_phone_press',
          storyboardRef: 'storyboard/phone_press_board',
          keyframeRefs: ['kf_phone_hover', 'kf_rain_on_screen', 'kf_phone_press'],
          acceptedInputHash: 'sha256:8b7f2a',
          selectionState: 'selected',
          candidates: [
            { id: 'cand_phone_a', title: '雨滴压暗屏幕', model: 'video-i2v', inputHash: 'sha256:8b7f2a', selected: true, note: '表演克制，手机光源最稳定。' },
            { id: 'cand_phone_b', title: '更强反光版本', model: 'video-i2v', inputHash: 'sha256:8b7f2a', note: '节奏更锋利，但屏幕信息过亮。' },
            { id: 'cand_phone_c', title: '手部动作慢版', model: 'video-i2v', inputHash: 'sha256:8b7f2a', note: '适合作为备选长镜。' },
          ],
        },
      },
      {
        id: 'shot_headlights_back',
        title: '男主背影被车灯切开',
        camera: '中景 · 背面 · 横移',
        duration: '4s',
        expression: '车灯扫过背影，制造误会与危险靠近的感觉。',
        stillPosition: '100% 0%',
        path: '.../scene_moments/rain_call/shots/shot_headlights_back',
        keyframes: ['kf_back_silhouette', 'kf_headlight_sweep'],
        assets: [
          { title: 'asset/headlight_beam', status: 'missing' },
          { title: 'asset/black_coat', status: 'locked' },
        ],
        storyboard: 'storyboard/headlights_back_board',
        contentUnit: {
          id: 'cu_video_headlights_back',
          type: 'shot_video',
          outputKind: 'video',
          path: 'content_units/cu_video_headlights_back/content_unit.json',
          editPrompt: '背影被车灯扫过的视频镜头，使用 {{asset:headlight_beam}} 控制压迫感。',
          sceneMomentRef: 'scene_moment/rain_call',
          shotId: 'shot_headlights_back',
          storyboardRef: 'storyboard/headlights_back_board',
          keyframeRefs: ['kf_back_silhouette', 'kf_headlight_sweep'],
          selectionState: 'needs_candidate',
          candidates: [
            { id: 'cand_headlights_a', title: '远车灯压迫', model: 'video-t2v', inputHash: 'sha256:22a901', note: '构图成立，人物轮廓还需更清楚。' },
            { id: 'cand_headlights_b', title: '湿街反射加强', model: 'video-t2v', inputHash: 'sha256:22a901', note: '环境更有张力，可作为候选。' },
          ],
        },
      },
    ],
  },
  {
    id: 'm2',
    title: '电梯门合上前的对视',
    path: 'productions/pilot/segments/escalation/scene_moments/elevator_look',
    selectionState: 'stale',
    priority: '中优先级',
    production: '短剧试播集',
    segment: '关系升级',
    settings: ['setting/hotel_elevator', 'asset/evening_dress', 'setting/warm_corridor', 'asset/metal_reflection'],
    shots: [
      {
        id: 'shot_elevator_gap',
        title: '电梯缝隙里的双人对视',
        camera: '近景 · 正反打 · 缓慢推进',
        duration: '5s',
        expression: '电梯门像剪辑线一样压缩两人的关系，最后只剩眼神。',
        stillPosition: '0% 100%',
        path: '.../scene_moments/elevator_look/shots/shot_elevator_gap',
        keyframes: ['kf_gap_wide', 'kf_eye_contact', 'kf_gap_close'],
        assets: [
          { title: 'asset/elevator_metal', status: 'ready' },
          { title: 'asset/evening_dress', status: 'missing' },
        ],
        storyboard: 'storyboard/elevator_gap_board',
        contentUnit: {
          id: 'cu_storyboard_elevator_gap',
          type: 'storyboard_ref',
          outputKind: 'video',
          path: 'content_units/cu_storyboard_elevator_gap/content_unit.json',
          editPrompt: '电梯门缝对视镜头，使用 {{asset:evening_dress}} 控制材质与光位。',
          sceneMomentRef: 'scene_moment/elevator_look',
          shotId: 'shot_elevator_gap',
          storyboardRef: 'storyboard/elevator_gap_board',
          keyframeRefs: ['kf_gap_wide', 'kf_eye_contact', 'kf_gap_close'],
          acceptedInputHash: 'sha256:4cf002',
          selectionState: 'stale',
          candidates: [
            { id: 'cand_elevator_a', title: '门缝压缩版', model: 'video-i2v', inputHash: 'sha256:4cf002', selected: true, note: '曾经选中，但 keyframe/kf_eye_contact 已更新。' },
            { id: 'cand_elevator_b', title: '暖光更强版本', model: 'video-i2v', inputHash: 'sha256:9c11aa', note: '匹配最新输入，可重新选择。' },
          ],
        },
      },
    ],
  },
  {
    id: 'm3',
    title: '清晨厨房里的假装平静',
    path: 'productions/pilot/segments/aftermath/scene_moments/morning_kitchen',
    selectionState: 'ready',
    priority: '高优先级',
    production: '短剧试播集',
    segment: '余波',
    settings: ['setting/morning_kitchen', 'asset/coffee_cup', 'asset/notes_stack', 'setting/window_backlight'],
    shots: [
      {
        id: 'shot_coffee_tremble',
        title: '咖啡杯边缘轻微颤动',
        camera: '特写 · 低机位 · 静止',
        duration: '2s',
        expression: '平静表面下的失控，通过杯子震动表现。',
        stillPosition: '100% 100%',
        path: '.../scene_moments/morning_kitchen/shots/shot_coffee_tremble',
        keyframes: ['kf_cup_still'],
        assets: [
          { title: 'asset/coffee_cup', status: 'ready' },
          { title: 'setting/window_backlight', status: 'ready' },
        ],
        storyboard: 'storyboard/coffee_tremble_board',
        contentUnit: {
          id: 'cu_keyframe_coffee_tremble',
          type: 'keyframe_ref',
          outputKind: 'image',
          path: 'content_units/cu_keyframe_coffee_tremble/content_unit.json',
          editPrompt: '清晨厨房咖啡杯关键帧，使用 {{asset:coffee_cup}} 表达表面平静。',
          sceneMomentRef: 'scene_moment/morning_kitchen',
          shotId: 'shot_coffee_tremble',
          storyboardRef: 'storyboard/coffee_tremble_board',
          keyframeRefs: ['kf_cup_still'],
          selectionState: 'ready',
          candidates: [
            { id: 'cand_coffee_a', title: '晨光安静版', model: 'image-t2i', inputHash: 'sha256:79b12f', note: '可作为 keyframe 首选。' },
            { id: 'cand_coffee_b', title: '杯面颤动预演', model: 'image-t2i', inputHash: 'sha256:79b12f', note: '更强调动作线索。' },
          ],
        },
      },
    ],
  },
]
