import React from 'react'

export const ProjectAgentContentPanel = React.lazy(() => import('@/features/agent/components/ProjectAgentModePage').then((module) => ({ default: module.ProjectAgentContentPanel })))
export const ProjectAgentModeSidebar = React.lazy(() => import('@/features/agent/components/ProjectAgentModePage').then((module) => ({ default: module.ProjectAgentModeSidebar })))
export const ProjectAIAssistantPanel = React.lazy(() => import('@/features/agent/components/ProjectAgentModePage').then((module) => ({ default: module.ProjectAIAssistantPanel })))
export const AgentTerminalPanel = React.lazy(() => import('@/features/agent/components/AgentTerminalPanel').then((module) => ({ default: module.AgentTerminalPanel })))

export const AuthPage = React.lazy(() => import('@/pages/AuthPage'))
export const AppSettingsPage = React.lazy(() => import('@/pages/app-settings/AppSettingsPage'))
export const CanvasListPage = React.lazy(() => import('@/pages/canvas/CanvasListPage'))
export const CanvasEditorPage = React.lazy(() => import('@/pages/canvas/CanvasEditorPage'))
export const ContentCanvasWorkspacePage = React.lazy(() => import('@/features/content/components/ContentCanvasWorkspacePage'))
export const RefImageGenPage = React.lazy(() => import('@/pages/tools/RefImageGenPage'))
export const RefVideoGenPage = React.lazy(() => import('@/pages/tools/RefVideoGenPage'))
export const AudioGenPage = React.lazy(() => import('@/pages/tools/AudioGenPage'))
export const MotionImitationPage = React.lazy(() => import('@/pages/tools/MotionImitationPage'))
export const StyleTransferPage = React.lazy(() => import('@/pages/tools/StyleTransferPage'))
export const MultiAnglePage = React.lazy(() => import('@/pages/tools/MultiAnglePage'))
export const OrgSelectPage = React.lazy(() => import('@/pages/org/OrgSelectPage'))
export const InvitePage = React.lazy(() => import('@/pages/auth/InvitePage'))
export const ResourcesPage = React.lazy(() => import('@/pages/resources/ResourcesPage'))
export const ExternalResourcesPage = React.lazy(() => import('@/pages/resources/ExternalResourcesPage'))
export const ShotLibraryPage = React.lazy(() => import('@/pages/shot-library/ShotLibraryPage'))
export const JobsPage = React.lazy(() => import('@/pages/jobs/JobsPage'))
export const PluginToolPage = React.lazy(() => import('@/pages/plugins/PluginToolPage'))
export const GlobalHomePage = React.lazy(() => import('@/pages/home/GlobalHomePage'))
export const EditingWorkspacePage = React.lazy(() => import('@/pages/editing/EditingWorkspacePage'))
export const ProjectOverviewPage = React.lazy(() => import('@/pages/project/ProjectOverviewPage'))
export const ProjectStandardsPage = React.lazy(() => import('@/pages/project/standards/ProjectStandardsPage'))
export const AgentModePage = React.lazy(() => import('@/pages/agent-mode/AgentModePage'))
export const AgentModeCanvasListPage = React.lazy(() => import('@/pages/agent-mode/AgentModeCanvasListPage'))
export const ScriptsPage = React.lazy(() => import('@/pages/scripts/ScriptsPage'))
export const AgentConnectionsPage = React.lazy(() => import('@/pages/agent/AgentConnectionsPage'))
export const MovScriptWorkspaceFilesPage = React.lazy(() => import('@/pages/agent/MovScriptWorkspaceFilesPage'))
export const MovScriptWorkspaceReviewPage = React.lazy(() => import('@/pages/agent/MovScriptWorkspaceReviewPage'))
export const ModelProvidersPage = React.lazy(() => import('@/pages/agent/ModelProvidersPage'))
export const AgentsPage = React.lazy(() => import('@/pages/agent/AgentsPage'))
export const AIAgentSettingsPage = React.lazy(() => import('@/pages/agent/AIAgentSettingsPage'))
export const ClientPluginsPage = React.lazy(() => import('@/pages/plugins/ClientPluginsPage'))
