package ai

import (
	"github.com/movscript/movscript/internal/domain/media"
	providercontract "github.com/movscript/movscript/internal/providers/contract"
)

var (
	_ providercontract.AIGatewayModelCatalog            = (*AIService)(nil)
	_ providercontract.AIGatewayRoutingPolicy           = (*AIService)(nil)
	_ providercontract.AIGatewayGovernancePolicy        = (*AIService)(nil)
	_ providercontract.AIGatewayUsageGovernor           = (*AIService)(nil)
	_ providercontract.AIGatewayCallAuditor             = (*AIService)(nil)
	_ providercontract.AIGatewayHealthProbe             = (*AIService)(nil)
	_ providercontract.AIGatewayProvider                = (*LocalAdapter)(nil)
	_ providercontract.AIGatewayTextStreamProvider      = (*LocalAdapter)(nil)
	_ providercontract.AIGatewayResponsesProvider       = (*LocalAdapter)(nil)
	_ media.AudioGenerationProvider                     = (*LocalAdapter)(nil)
	_ media.SpeechToSpeechProvider                      = (*LocalAdapter)(nil)
	_ media.SubtitleProvider                            = (*LocalAdapter)(nil)
	_ media.SpeechTranslateProvider                     = (*LocalAdapter)(nil)
	_ media.VoiceProfileProvider                        = (*LocalAdapter)(nil)
	_ media.DubbingProvider                             = (*LocalAdapter)(nil)
	_ providercontract.AIGatewayProvider                = (*OpenAIAdapter)(nil)
	_ providercontract.AIGatewayTextStreamProvider      = (*OpenAIAdapter)(nil)
	_ providercontract.AIGatewayResponsesProvider       = (*OpenAIAdapter)(nil)
	_ providercontract.AIGatewayVideoTaskProvider       = (*OpenAIAdapter)(nil)
	_ providercontract.AIGatewayVideoTaskCancelProvider = (*OpenAIAdapter)(nil)
	_ media.TTSProvider                                 = (*OpenAIAdapter)(nil)
	_ media.SubtitleProvider                            = (*OpenAIAdapter)(nil)
	_ media.SpeechTranslateProvider                     = (*OpenAIAdapter)(nil)
	_ media.SpeechToSpeechProvider                      = (*OpenAIAdapter)(nil)
	_ media.SpeechToSpeechProvider                      = (*DashScopeAdapter)(nil)
	_ media.SpeechToSpeechProvider                      = (*XiaomiMimoAdapter)(nil)
	_ media.SpeechToSpeechProvider                      = (*VolcenAdapter)(nil)
	_ media.AudioGenerationProvider                     = (*VolcenAdapter)(nil)
	_ media.VoiceProfileProvider                        = (*ElevenLabsAdapter)(nil)
	_ media.VoiceProfileProvider                        = (*VolcenAdapter)(nil)
	_ providercontract.AIGatewayVideoTaskCancelProvider = (*ViduAdapter)(nil)
	_ providercontract.AIGatewayVideoTaskCancelProvider = (*VolcenAdapter)(nil)
	_ providercontract.AIGatewayFileUploader            = (*OpenAIFileUploader)(nil)
	_ providercontract.AIGatewayFileUploader            = (*VolcenFileUploader)(nil)
	_ providercontract.AIGatewayTextStreamProvider      = (*AnthropicAdapter)(nil)
)
