import type { AgentRuntimeContract } from './runtimeContract.js'

export const SCRIPT_SPLIT_RUNTIME_CONTRACT_ID = 'script-split-agent'

export const SCRIPT_SPLIT_RUNTIME_CONTRACT: AgentRuntimeContract = {
  id: SCRIPT_SPLIT_RUNTIME_CONTRACT_ID,
  matches: (manifest) => manifest.id === SCRIPT_SPLIT_RUNTIME_CONTRACT_ID,
  structuredContract: [
    'Return only one valid JSON object matching schema movscript.script_split_analysis.v1.',
    'Do not wrap the JSON in markdown fences, prose, or code blocks.',
    'Output shape:',
    '{',
    '  "schema": "movscript.script_split_analysis.v1",',
    '  "source_title": string,',
    '  "source_summary": string,',
    '  "source_script": {',
    '    "title": string,',
    '    "summary": string,',
    '    "content": string,',
    '    "source_type": "raw"',
    '  },',
    '  "global_settings": {',
    '    "story_world": string,',
    '    "core_rules": string[],',
    '    "character_relationships": string[],',
    '    "key_characters": string[],',
    '    "key_locations": string[],',
    '    "key_props": string[],',
    '    "continuity_notes": string[]',
    '  },',
    '  "episode_drafts": [',
    '    {',
    '      "order": number,',
    '      "title": string,',
    '      "summary": string,',
    '      "content": string,',
    '      "global_context": {',
    '        "story_world": string,',
    '        "core_rules": string[],',
    '        "character_relationships": string[],',
    '        "key_characters": string[],',
    '        "key_locations": string[],',
    '        "key_props": string[],',
    '        "continuity_notes": string[],',
    '        "episode_relevance": string[]',
    '      },',
    '      "start": number,',
    '      "end": number,',
    '      "action": "create" | "update",',
    '      "existing_script_id": number | null,',
    '      "rationale": string',
    '    }',
    '  ],',
    '  "warnings": string[],',
    '  "confidence": number',
    '}',
    'Every episode_drafts item must carry global_context. Repeat the global story/world rules, character relationships, recurring locations/props, and continuity constraints that downstream production orchestration needs even when it only reads one episode.',
    'Do not put only episode-local facts in global_context. Include source-wide assumptions and explain episode_relevance for facts that matter in that episode.',
  ].join('\n'),
  requiresConfiguredModel: true,
  requiresStructuredJSON: true,
}
