import assert from 'node:assert/strict'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import test from 'node:test'
import {
  resolveAgentWorkspaceRuntimePaths,
  writeAgentWorkspaceConfig,
} from '@movscript/agent-runtime'
import {
  codexSpawnEnvironmentFromDistribution,
  distributeCodexConfigFromMovScriptWorkspace,
} from './codexConfigDistribution'

test('distributes MovScript Codex account config into Codex config files', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    modelConfig: {
      model: 'gpt-test-codex',
      apiKind: 'openai_responses',
      baseURL: 'https://gateway.example/v1/',
    },
    agents: {
      codex: {
        auth: {
          mode: 'apiKey',
          apiKey: 'sk-test-key',
        },
      },
    },
  })

  const distribution = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:03.000Z'),
  })

  assert.equal(distribution.ok, true)
  assert.equal(distribution.apiKeyConfigured, true)
  assert.equal(distribution.accountConfigured, true)
  assert.equal(distribution.accountSource, 'movscript-agent-account')
  assert.equal(distribution.baseURL, 'https://gateway.example/v1')
  assert.equal(distribution.sourceConfigPath, paths.configPath)
  assert.equal(distribution.configTomlPath, join(codexHome, 'config.toml'))
  assert.equal(distribution.authJsonPath, join(codexHome, 'auth.json'))

  const configToml = readFileSync(distribution.configTomlPath, 'utf8')
  assert.match(configToml, /Generated by MovScript/)
  assert.doesNotMatch(configToml, /^model = /m)
  assert.match(configToml, /model_provider = "movscript"/)
  assert.match(configToml, /base_url = "https:\/\/gateway\.example\/v1"/)
  assert.match(configToml, /env_key = "OPENAI_API_KEY"/)
  assert.match(configToml, /wire_api = "responses"/)
  assert.match(configToml, /requires_openai_auth = false/)

  const authJson = JSON.parse(readFileSync(distribution.authJsonPath, 'utf8'))
  assert.equal(authJson.auth_mode, 'apikey')
  assert.equal(authJson.OPENAI_API_KEY, 'sk-test-key')

  const env = codexSpawnEnvironmentFromDistribution(distribution, {})
  assert.equal(env.CODEX_HOME, codexHome)
  assert.equal(env.OPENAI_API_KEY, 'sk-test-key')
  assert.equal(env.MOVSCRIPT_CODEX_CONFIG_SOURCE, paths.configPath)
})

test('inherits existing MovScript-managed Codex auth when no explicit account is configured', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-no-key-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    modelConfig: {
      model: 'gpt-test-codex',
      apiKind: 'openai_responses',
      baseURL: 'https://gateway.example/v1',
    },
  })
  mkdirSync(codexHome, { recursive: true })
  writeFileSync(join(codexHome, 'auth.json'), '{"OPENAI_API_KEY":"managed-codex-home-key"}\n')

  const distribution = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:03.000Z'),
  })

  assert.equal(distribution.ok, true)
  assert.equal(distribution.apiKeyConfigured, true)
  assert.equal(distribution.accountConfigured, true)
  assert.equal(distribution.accountSource, 'codex-home')
  assert.equal(JSON.parse(readFileSync(distribution.authJsonPath, 'utf8')).OPENAI_API_KEY, 'managed-codex-home-key')
  const env = codexSpawnEnvironmentFromDistribution(distribution, { OPENAI_API_KEY: 'external-key' })
  assert.equal(env.OPENAI_API_KEY, 'managed-codex-home-key')
})

test('keeps Codex launch hash stable across distribution timestamps', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-stable-hash-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    modelConfig: {
      model: 'gpt-test-codex',
      apiKind: 'openai_responses',
      baseURL: 'https://gateway.example/v1',
    },
    agents: {
      codex: {
        auth: {
          mode: 'apiKey',
          apiKey: 'sk-test-key',
        },
      },
    },
  })

  const first = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:03.000Z'),
  })
  const second = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:04.000Z'),
  })

  assert.notEqual(first.distributedAt, second.distributedAt)
  assert.equal(first.hash, second.hash)
})

test('clears Codex auth only when MovScript explicitly disables the account', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-none-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    modelConfig: {
      model: 'gpt-test-codex',
      apiKind: 'openai_responses',
      baseURL: 'https://gateway.example/v1',
    },
    agents: {
      codex: {
        auth: { mode: 'none' },
      },
    },
  })
  mkdirSync(codexHome, { recursive: true })
  writeFileSync(join(codexHome, 'auth.json'), '{"OPENAI_API_KEY":"stale"}\n')

  const distribution = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:03.000Z'),
  })

  assert.equal(distribution.ok, false)
  assert.equal(distribution.apiKeyConfigured, false)
  assert.equal(distribution.accountConfigured, false)
  assert.equal(distribution.accountSource, 'none')
  assert.throws(() => readFileSync(distribution.authJsonPath, 'utf8'), /ENOENT/)
  assert.equal(codexSpawnEnvironmentFromDistribution(distribution, { OPENAI_API_KEY: 'external-key' }).OPENAI_API_KEY, undefined)
})

test('does not create CODEX_HOME when no Codex account can be projected', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-no-home-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    agents: {
      codex: {
        auth: { mode: 'none' },
      },
    },
  })

  const distribution = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:03.000Z'),
  })

  assert.equal(distribution.accountConfigured, false)
  assert.equal(existsSync(codexHome), false)
})

test('inherits managed Codex ChatGPT auth without forcing API key env', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-chatgpt-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    modelConfig: {
      model: 'gpt-test-codex',
      apiKind: 'openai_responses',
      baseURL: 'https://api.openai.com/v1',
    },
  })
  mkdirSync(codexHome, { recursive: true })
  writeFileSync(join(codexHome, 'auth.json'), JSON.stringify({
    auth_mode: 'chatgpt',
    tokens: {
      id_token: 'id-token',
      access_token: 'access-token',
      refresh_token: 'refresh-token',
    },
    last_refresh: '2026-06-04T00:00:00.000Z',
  }, null, 2))

  const distribution = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:03.000Z'),
  })

  assert.equal(distribution.ok, true)
  assert.equal(distribution.apiKeyConfigured, false)
  assert.equal(distribution.accountConfigured, true)
  assert.equal(distribution.accountSource, 'codex-home')
  assert.equal(codexSpawnEnvironmentFromDistribution(distribution, { OPENAI_API_KEY: 'external-key' }).OPENAI_API_KEY, undefined)
  const configToml = readFileSync(distribution.configTomlPath, 'utf8')
  assert.match(configToml, /model_provider = "openai"/)
  assert.doesNotMatch(configToml, /env_key = "OPENAI_API_KEY"/)
})

test('distributes user supplied Codex base URL and API key', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-custom-key-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    agents: {
      codex: {
        config: { mode: 'customApiKey' },
        auth: {
          mode: 'apiKey',
          apiKey: 'sk-user-key',
          baseURL: 'https://user-gateway.example/v1/',
        },
      },
    },
  })

  const distribution = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:03.000Z'),
  })

  assert.equal(distribution.ok, true)
  assert.equal(distribution.accountSource, 'movscript-agent-account')
  assert.equal(distribution.baseURL, 'https://user-gateway.example/v1')
  assert.equal(codexSpawnEnvironmentFromDistribution(distribution, {}).OPENAI_API_KEY, 'sk-user-key')
  assert.match(readFileSync(distribution.configTomlPath, 'utf8'), /base_url = "https:\/\/user-gateway\.example\/v1"/)
})

test('inherits local Codex home provider config and auth without copying a home-level model', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-local-'))
  const localCodexHome = mkdtempSync(join(tmpdir(), 'movscript-local-codex-home-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  writeFileSync(join(localCodexHome, 'config.toml'), 'model = "local-codex-model"\nmodel_provider = "openai"\n')
  writeFileSync(join(localCodexHome, 'auth.json'), JSON.stringify({
    auth_mode: 'chatgpt',
    tokens: { access_token: 'local-access-token' },
    last_refresh: '2026-06-04T00:00:00.000Z',
  }, null, 2))
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    agents: {
      codex: {
        config: { mode: 'localCodex', localCodexHome },
        auth: { mode: 'localCodex', localCodexHome },
      },
    },
  })

  const distribution = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:03.000Z'),
  })

  assert.equal(distribution.ok, true)
  assert.equal(distribution.accountSource, 'local-codex-home')
  const configToml = readFileSync(distribution.configTomlPath, 'utf8')
  assert.equal(configToml, 'model_provider = "openai"\n')
  assert.doesNotMatch(configToml, /^model = /m)
  assert.equal(JSON.parse(readFileSync(distribution.authJsonPath, 'utf8')).tokens.access_token, 'local-access-token')
  assert.equal(codexSpawnEnvironmentFromDistribution(distribution, { OPENAI_API_KEY: 'external-key' }).OPENAI_API_KEY, undefined)
})

test('custom Codex config mode does not overwrite user edited config files', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-manual-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  mkdirSync(codexHome, { recursive: true })
  writeFileSync(join(codexHome, 'config.toml'), 'model = "manual-model"\n')
  writeFileSync(join(codexHome, 'auth.json'), '{"OPENAI_API_KEY":"manual-key"}\n')
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    agents: {
      codex: {
        config: { mode: 'customConfig' },
        auth: { mode: 'customConfig' },
      },
    },
  })

  const distribution = distributeCodexConfigFromMovScriptWorkspace({
    workspaceDir,
    codexHome,
    now: new Date('2026-06-04T01:02:03.000Z'),
  })

  assert.equal(distribution.ok, true)
  assert.equal(distribution.accountSource, 'custom-config')
  assert.equal(readFileSync(distribution.configTomlPath, 'utf8'), 'model = "manual-model"\n')
  assert.equal(codexSpawnEnvironmentFromDistribution(distribution, {}).OPENAI_API_KEY, 'manual-key')
})

test('changes distribution hash when only API key changes', () => {
  const workspaceDir = mkdtempSync(join(tmpdir(), 'movscript-codex-config-key-change-'))
  const codexHome = join(workspaceDir, '.movscript', '.codex')
  const paths = resolveAgentWorkspaceRuntimePaths(workspaceDir)
  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:00.000Z',
    modelConfig: {
      model: 'gpt-test-codex',
      apiKind: 'openai_responses',
      baseURL: 'https://gateway.example/v1',
    },
    agents: { codex: { auth: { mode: 'apiKey', apiKey: 'sk-first' } } },
  })
  const first = distributeCodexConfigFromMovScriptWorkspace({ workspaceDir, codexHome, now: new Date('2026-06-04T01:02:03.000Z') })

  writeAgentWorkspaceConfig(paths.configPath, {
    schema: 'movscript.agent.workspace-config.v1',
    updatedAt: '2026-06-04T00:00:01.000Z',
    modelConfig: {
      model: 'gpt-test-codex',
      apiKind: 'openai_responses',
      baseURL: 'https://gateway.example/v1',
    },
    agents: { codex: { auth: { mode: 'apiKey', apiKey: 'sk-second' } } },
  })
  const second = distributeCodexConfigFromMovScriptWorkspace({ workspaceDir, codexHome, now: new Date('2026-06-04T01:02:03.000Z') })

  assert.notEqual(first.hash, second.hash)
  assert.equal(codexSpawnEnvironmentFromDistribution(second, {}).OPENAI_API_KEY, 'sk-second')
})
