export const MAX_CLIP_DURATION_MS = 10 * 60 * 1000
export const MAX_CLIP_SOURCE_BYTES = 1024 * 1024 * 1024
export const MAX_OUTPUT_BASENAME_LENGTH = 80
export const OUTPUT_SUFFIX = '_clip'
export const WINDOWS_RESERVED_BASENAME_PATTERN = /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])$/i
export const FFMPEG_TIMEOUT_MS = 20 * 60 * 1000
export const FFMPEG_STATUS_TIMEOUT_MS = 5000
export const FFMPEG_STDERR_LIMIT = 64 * 1024
export {
  MAX_TIMELINE_CAPTION_TEXT_LENGTH,
  MAX_TIMELINE_EXPORT_AUDIO_CLIPS,
  MAX_TIMELINE_EXPORT_CAPTIONS,
  MAX_TIMELINE_EXPORT_CLIPS,
  MAX_TIMELINE_EXPORT_DURATION_MS,
  MAX_TIMELINE_EXPORT_OVERLAYS,
} from '@movscript/core/resources'
