import react from '@vitejs/plugin-react'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'

const serviceRoot = __dirname

export default defineConfig({
  base: process.env.MOVSCRIPT_LOCAL_SURFACE_HOST_BASE ?? '/',
  plugins: [react()],
  resolve: {
    alias: {
      '@movscript/admin-surface/react': resolve(serviceRoot, '../../surface/admin/src/react.ts'),
      '@movscript/admin-surface': resolve(serviceRoot, '../../surface/admin/src/index.ts'),
      '@admin-runtime': resolve(serviceRoot, '../../surface/admin/src/runtime/community.tsx'),
      '@admin': resolve(serviceRoot, '../../surface/admin/src'),
      '@movscript/canvas-surface/i18n': resolve(serviceRoot, '../../surface/canvas/src/i18n.ts'),
      '@movscript/canvas-surface/data': resolve(serviceRoot, '../../surface/canvas/src/data.ts'),
      '@movscript/canvas-surface/layout': resolve(serviceRoot, '../../surface/canvas/src/layout.ts'),
      '@movscript/canvas-surface/pages': resolve(serviceRoot, '../../surface/canvas/src/pages/index.ts'),
      '@movscript/canvas-surface/shell': resolve(serviceRoot, '../../surface/canvas/src/shell.ts'),
      '@movscript/canvas-surface/workbench': resolve(serviceRoot, '../../surface/canvas/src/workbench.ts'),
      '@movscript/canvas-surface': resolve(serviceRoot, '../../surface/canvas/src/index.ts'),
      '@movscript/editing/browser': resolve(serviceRoot, '../../packages/editing/src/browser.ts'),
      '@movscript/editing': resolve(serviceRoot, '../../packages/editing/src/browser.ts'),
      '@movscript/editing-surface/app-events': resolve(serviceRoot, '../../surface/editing/src/app-events.ts'),
      '@movscript/editing-surface/browser-storage': resolve(serviceRoot, '../../surface/editing/src/browser-storage.ts'),
      '@movscript/editing-surface/contracts': resolve(serviceRoot, '../../surface/editing/src/contracts.ts'),
      '@movscript/editing-surface/host-api': resolve(serviceRoot, '../../surface/editing/src/host-api.ts'),
      '@movscript/editing-surface/media-probe': resolve(serviceRoot, '../../surface/editing/src/media-probe.ts'),
      '@movscript/editing-surface/navigation': resolve(serviceRoot, '../../surface/editing/src/navigation.ts'),
      '@movscript/editing-surface/pages': resolve(serviceRoot, '../../surface/editing/src/pages'),
      '@movscript/editing-surface/registry': resolve(serviceRoot, '../../surface/editing/src/registry.ts'),
      '@movscript/editing-surface/routes': resolve(serviceRoot, '../../surface/editing/src/routes.ts'),
      '@movscript/editing-surface/service-host-api': resolve(serviceRoot, '../../surface/editing/src/service-host-api.ts'),
      '@movscript/editing-surface/surface-routes': resolve(serviceRoot, '../../surface/editing/src/surface-routes.tsx'),
      '@movscript/editing-surface/toast': resolve(serviceRoot, '../../surface/editing/src/toast.ts'),
      '@movscript/editing-surface/window-events': resolve(serviceRoot, '../../surface/editing/src/window-events.ts'),
      '@movscript/editing-surface': resolve(serviceRoot, '../../surface/editing/src/index.ts'),
      '@movscript/project-surface/react': resolve(serviceRoot, '../../surface/project/src/react.ts'),
      '@movscript/project-surface/runtime': resolve(serviceRoot, '../../surface/project/src/runtime.ts'),
      '@movscript/project-surface/data': resolve(serviceRoot, '../../surface/project/src/data.ts'),
      '@movscript/project-surface/routes': resolve(serviceRoot, '../../surface/project/src/routes.ts'),
      '@movscript/project-surface/layout': resolve(serviceRoot, '../../surface/project/src/layout.ts'),
      '@movscript/project-surface/pages': resolve(serviceRoot, '../../surface/project/src/pages/index.ts'),
      '@movscript/project-surface': resolve(serviceRoot, '../../surface/project/src/index.ts'),
      '@movscript/resources': resolve(serviceRoot, '../../packages/resources/src/index.ts'),
      '@movscript/shared/browser': resolve(serviceRoot, '../../packages/shared/src/browser.ts'),
      '@movscript/shared/media-probe': resolve(serviceRoot, '../../packages/shared/src/mediaProbe.ts'),
      '@movscript/shared/surface-http': resolve(serviceRoot, '../../packages/shared/src/surfaceHttpClient.ts'),
      '@movscript/shared/surface-routes': resolve(serviceRoot, '../../packages/shared/src/surfaceRoutes.ts'),
      '@movscript/shared/semantic-entities': resolve(serviceRoot, '../../packages/shared/src/surfaceSemanticEntities.ts'),
      '@movscript/shared/workspace-candidates': resolve(serviceRoot, '../../packages/shared/src/workspaceCandidates.ts'),
      '@movscript/shared/app-events': resolve(serviceRoot, '../../packages/shared/src/appEvents.ts'),
      '@movscript/shared': resolve(serviceRoot, '../../packages/shared/src/index.ts'),
      '@movscript/resource-surface/data': resolve(serviceRoot, '../../surface/resource/src/data.ts'),
      '@movscript/resource-surface/routes': resolve(serviceRoot, '../../surface/resource/src/routes.ts'),
      '@movscript/resource-surface/resource-browser': resolve(serviceRoot, '../../surface/resource/src/resource-browser.ts'),
      '@movscript/resource-surface/resource-media': resolve(serviceRoot, '../../surface/resource/src/resourceMediaBrowser.ts'),
      '@movscript/resource-surface/resource-media-components': resolve(serviceRoot, '../../surface/resource/src/resourceMediaComponents.tsx'),
      '@movscript/resource-surface/resource-media-viewer': resolve(serviceRoot, '../../surface/resource/src/resourceMediaViewer.tsx'),
      '@movscript/resource-surface/resource-media-diagnostics': resolve(serviceRoot, '../../surface/resource/src/resourceMediaDiagnostics.ts'),
      '@movscript/resource-surface/resource-candidate-attach-panel': resolve(serviceRoot, '../../surface/resource/src/resourceCandidateAttachPanel.tsx'),
      '@movscript/resource-surface/resource-interaction': resolve(serviceRoot, '../../surface/resource/src/resourceInteraction.ts'),
      '@movscript/resource-surface/resource-library-picker': resolve(serviceRoot, '../../surface/resource/src/resourceLibraryPicker.tsx'),
      '@movscript/resource-surface/resource-library-picker-ui': resolve(serviceRoot, '../../surface/resource/src/resourceLibraryPickerUi.tsx'),
      '@movscript/resource-surface/i18n': resolve(serviceRoot, '../../surface/resource/src/i18n.ts'),
      '@movscript/resource-surface/pages': resolve(serviceRoot, '../../surface/resource/src/pages/index.ts'),
      '@movscript/resource-surface/react': resolve(serviceRoot, '../../surface/resource/src/react.ts'),
      '@movscript/resource-surface': resolve(serviceRoot, '../../surface/resource/src/index.ts'),
      '@movscript/core/agent': resolve(serviceRoot, '../../packages/core/src/agent/index.ts'),
      '@movscript/core/content': resolve(serviceRoot, '../../packages/core/src/content/index.ts'),
      '@movscript/core/generation': resolve(serviceRoot, '../../packages/core/src/generation/index.ts'),
      '@movscript/core/resources': resolve(serviceRoot, '../../packages/core/src/resources/index.ts'),
      '@movscript/workspace': resolve(serviceRoot, '../../packages/workspace/src/index.ts'),
      '@movscript/engine': resolve(serviceRoot, '../../packages/engine/src/index.ts'),
      '@movscript/theme/theme.css': resolve(serviceRoot, '../../packages/theme/src/theme.css'),
      '@movscript/theme': resolve(serviceRoot, '../../packages/theme/src/index.ts'),
      '@movscript/ui/styles/base.css': resolve(serviceRoot, '../../packages/ui/src/styles/base.css'),
      '@movscript/ui/styles/surface-host.css': resolve(serviceRoot, '../../packages/ui/src/styles/surface-host.css'),
      '@movscript/ui/styles/business/agent.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/agent.css'),
      '@movscript/ui/styles/business/app.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/app.css'),
      '@movscript/ui/styles/business/canvas.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/canvas.css'),
      '@movscript/ui/styles/business/generation.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/generation.css'),
      '@movscript/ui/styles/business/resource.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/resource.css'),
      '@movscript/ui/styles/business/review.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/review.css'),
      '@movscript/ui/styles/business/workbench.css': resolve(serviceRoot, '../../packages/ui/src/styles/business/workbench.css'),
      '@movscript/ui/styles/primitives.css': resolve(serviceRoot, '../../packages/ui/src/styles/primitives.css'),
      '@movscript/ui/styles/semantic.css': resolve(serviceRoot, '../../packages/ui/src/styles/semantic.css'),
      '@movscript/ui/styles/layout.css': resolve(serviceRoot, '../../packages/ui/src/styles/layout.css'),
      '@movscript/ui/style-system': resolve(serviceRoot, '../../packages/ui/src/style-system.ts'),
      '@movscript/ui/semantic': resolve(serviceRoot, '../../packages/ui/src/semantic.ts'),
      '@movscript/ui/primitives': resolve(serviceRoot, '../../packages/ui/src/primitives.ts'),
      '@movscript/ui/layout': resolve(serviceRoot, '../../packages/ui/src/layout.ts'),
      '@movscript/ui/debug': resolve(serviceRoot, '../../packages/ui/src/debug-entry.ts'),
      '@movscript/ui/toast': resolve(serviceRoot, '../../packages/ui/src/toast.ts'),
      '@movscript/ui/business/app': resolve(serviceRoot, '../../packages/ui/src/business/app.ts'),
      '@movscript/ui/business/canvas': resolve(serviceRoot, '../../packages/ui/src/business/canvas.ts'),
      '@movscript/ui/business/generation': resolve(serviceRoot, '../../packages/ui/src/business/generation.ts'),
      '@movscript/ui/business/resource': resolve(serviceRoot, '../../packages/ui/src/business/resource.ts'),
      '@movscript/ui/business/review': resolve(serviceRoot, '../../packages/ui/src/business/review.ts'),
      '@movscript/ui/business/workbench': resolve(serviceRoot, '../../packages/ui/src/business/workbench.ts'),
      '@movscript/ui': resolve(serviceRoot, '../../packages/ui/src/index.ts'),
      '@': resolve(serviceRoot, 'src'),
    },
  },
})
