import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

const appSource = readSource('apps/frontend/src/App.tsx')
const routerConfigSource = readSource('apps/frontend/src/features/app-shell/application/AppRouterConfig.tsx')
const backendBoundarySource = readSource('apps/frontend/src/features/app-shell/application/BackendBootBoundary.tsx')
const navigationEffectsSource = readSource('apps/frontend/src/features/app-shell/application/GlobalNavigationEffects.tsx')
const shellLayoutSource = readSource('apps/frontend/src/features/app-shell/application/AppShellLayout.tsx')
const shellLayoutHeadersSource = readSource('apps/frontend/src/features/app-shell/application/AppShellLayoutHeaders.tsx')
const shellLayoutControlsSource = readSource('apps/frontend/src/features/app-shell/application/AppShellLayoutControls.tsx')
const shellLayoutSlotsSource = readSource('apps/frontend/src/features/app-shell/application/AppShellLayoutSlots.ts')
const canvasShellRouteSource = readSource('apps/frontend/src/features/app-shell/application/AppCanvasEditorShellRoute.tsx')
const routeComponentsSource = readSource('apps/frontend/src/features/app-shell/application/appRouteComponents.tsx')
const routeBoundariesSource = readSource('apps/frontend/src/features/app-shell/application/AppRouteBoundaries.tsx')
const routeHeadersSource = readSource('apps/frontend/src/features/app-shell/application/appShellRouteHeaders.tsx')
const startupTasksSource = readSource('apps/frontend/src/features/app-shell/application/AppStartupTasks.tsx')
const projectRequiredDialogSource = readSource('apps/frontend/src/features/app-shell/components/ProjectRequiredDialog.tsx')
const headerSource = readSource('apps/frontend/src/features/app-shell/components/Header.tsx')
const appWindowControllerSource = readSource('apps/frontend/src/features/app-shell/application/useAppWindowController.ts')
const projectGitHeaderActionsSource = readSource('apps/frontend/src/features/app-shell/components/ProjectGitHeaderActions.tsx')
const projectGitWorkspaceSource = readSource('apps/frontend/src/features/project/application/projectGitWorkspace.ts')
const appSettingsStoreSource = readSource('apps/frontend/src/shared/infrastructure/appSettingsStore.ts')
const browserStorageSource = readSource('apps/frontend/src/shared/infrastructure/browserStorage.ts')

test('app shell delegates backend boot, project required flow, and global navigation effects', () => {
  assert.doesNotMatch(appSource, /function BackendBoot(?:Overlay|Boundary)\(/)
  assert.doesNotMatch(appSource, /function ProjectRequiredDialog\(/)
  assert.doesNotMatch(appSource, /function RedirectListener\(/)
  assert.doesNotMatch(appSource, /canManageLocalBackend|onBackendStatus|getBackendStatus|setAppSettings/)
  assert.doesNotMatch(appSource, /api\.post\('\/projects'/)
  assert.doesNotMatch(appSource, /\bRoutes\b|\bRoute\b|\bNavigate\b|runtimeRoutes|runtimeNavItems/)
  assert.doesNotMatch(appSource, /providerRoute|providerRouteForKey|useProviderConfigStore/)
  assert.doesNotMatch(appSource, /React\.lazy\(/)
  assert.doesNotMatch(appSource, /agentTelemetryReporter|builtinClientPlugins|scheduleIdleTask/)
  assert.doesNotMatch(appSource, /function (LoadingScreen|RouteSuspense|ProjectGuard|OrgAdminGuard|OrgGuard|RouteContentShell|RouteErrorBoundary)\(/)
  assert.doesNotMatch(appSource, /class ErrorBoundary extends/)
  assert.doesNotMatch(appSource, /function (projectRouteHeaderTitle|toolRouteHeaderTitle|accountSettingsTabForLocation|normalizeSettingsReturnPath|rememberSettingsReturnPath|readSettingsReturnPath|useRememberSettingsReturnPath|accountSettingsRouteHeaderTitle|AppRouteHeaderTitle)\(/)
  assert.doesNotMatch(appSource, /SETTINGS_RETURN_PATH_STORAGE_KEY/)
  assert.doesNotMatch(appSource, /BackendBootBoundary/)
  assert.doesNotMatch(appSource, /ProjectRequiredDialog/)
  assert.doesNotMatch(appSource, /function ShellLayout\(/)
  assert.doesNotMatch(appSource, /function Canvas(?:EditorShellRoute|HeaderLeft|HeaderTitle|HeaderActions)\(/)
  assert.doesNotMatch(appSource, /useCanvasHeaderStore|useInlineTitleEditor|canvasBackPath/)
  assert.doesNotMatch(appSource, /useRouteLayoutPaneController|useAgentPanelUiStore|APP_SHELL_/)
  assert.doesNotMatch(appSource, /GlobalNavigationEffects/)
  assert.match(appSource, /<AppStartupTasks settingsHydrated=\{settingsHydrated\} \/>/)
  assert.match(appSource, /<AuthenticatedAppRouter \/>/)
  assert.match(appSource, /<AnonymousAppRouter \/>/)
})

test('app shell boundary modules keep side-effect ownership explicit', () => {
  assert.match(backendBoundarySource, /canManageLocalBackend/)
  assert.match(backendBoundarySource, /readElectronApi\(\)\?\.onBackendStatus/)
  assert.doesNotMatch(backendBoundarySource, /window\.api/)
  assert.match(routerConfigSource, /export function AnonymousAppRouter/)
  assert.match(routerConfigSource, /export function AuthenticatedAppRouter/)
  assert.match(routerConfigSource, /<BackendBootBoundary \/>/)
  assert.match(routerConfigSource, /<ProjectRequiredDialog \/>/)
  assert.match(routerConfigSource, /runtimeRoutes\.map/)
  assert.match(routerConfigSource, /fallbackAgentProfileRoute/)
  assert.match(navigationEffectsSource, /subscribeApiRedirect/)
  assert.match(navigationEffectsSource, /subscribeWorkspaceChangeHandoff/)
  assert.match(shellLayoutSource, /export function ShellLayout/)
  assert.match(shellLayoutSource, /<GlobalNavigationEffects \/>/)
  assert.match(shellLayoutSource, /useRouteLayoutPaneController/)
  assert.match(shellLayoutSource, /AppShellLayoutHeaders/)
  assert.match(shellLayoutHeadersSource, /AppShellLayoutControls/)
  assert.match(shellLayoutSource, /AppShellLayoutSlots/)
  assert.doesNotMatch(shellLayoutSource, /AppWindowIconButton/)
  assert.doesNotMatch(shellLayoutSource, /openHomeWindow/)
  assert.doesNotMatch(shellLayoutSource, /window\.history/)
  assert.doesNotMatch(shellLayoutHeadersSource, /AppWindowIconButton/)
  assert.doesNotMatch(shellLayoutHeadersSource, /openHomeWindow/)
  assert.doesNotMatch(shellLayoutHeadersSource, /window\.history/)
  assert.match(shellLayoutControlsSource, /export function AppShellHomeControl/)
  assert.match(shellLayoutControlsSource, /openHomeWindow/)
  assert.match(shellLayoutControlsSource, /window\.history\.back/)
  assert.match(shellLayoutControlsSource, /window\.history\.forward/)
  assert.match(shellLayoutSlotsSource, /export function appShellHiddenSlotStyle/)
  assert.match(shellLayoutSlotsSource, /export function appShellCollapsedSlotStyle/)
  assert.doesNotMatch(shellLayoutSource, /useAgentPanelUiStore/)
  assert.match(canvasShellRouteSource, /export function CanvasEditorShellRoute/)
  assert.match(canvasShellRouteSource, /useCanvasHeaderStore/)
  assert.match(canvasShellRouteSource, /useInlineTitleEditor/)
  assert.match(routeComponentsSource, /React\.lazy\(\(\) => import/)
  assert.match(routeBoundariesSource, /export function ProjectGuard/)
  assert.match(routeBoundariesSource, /export function OrgGuard/)
  assert.match(routeBoundariesSource, /export class ErrorBoundary/)
  assert.match(routeBoundariesSource, /export function RouteSuspense/)
  assert.match(routeHeadersSource, /export function projectRouteHeaderTitle/)
  assert.match(routeHeadersSource, /export function toolRouteHeaderTitle/)
  assert.match(routeHeadersSource, /export function accountSettingsTabForLocation/)
  assert.match(routeHeadersSource, /SETTINGS_RETURN_PATH_STORAGE_KEY/)
  assert.match(routeHeadersSource, /readBrowserStorageItem\('session', SETTINGS_RETURN_PATH_STORAGE_KEY\)/)
  assert.match(routeHeadersSource, /writeBrowserStorageItem\('session', SETTINGS_RETURN_PATH_STORAGE_KEY/)
  assert.doesNotMatch(routeHeadersSource, /window\.sessionStorage/)
  assert.match(browserStorageSource, /window\.sessionStorage/)
  assert.match(startupTasksSource, /agentTelemetryReporter/)
  assert.match(startupTasksSource, /builtinClientPlugins/)
  assert.match(startupTasksSource, /scheduleIdleTask/)
  assert.match(projectRequiredDialogSource, /api\.post\('\/projects'/)
  assert.match(projectRequiredDialogSource, /initializeProjectGitWorkspace/)
})

test('app shell components delegate Electron API access to boundary modules', () => {
  assert.doesNotMatch(headerSource, /window\.api/)
  assert.match(headerSource, /useAppWindowController/)
  assert.match(appWindowControllerSource, /readElectronApi\(\)/)
  assert.doesNotMatch(appWindowControllerSource, /window\.api/)
  assert.match(appWindowControllerSource, /windowControl/)
  assert.match(appWindowControllerSource, /onWindowState/)

  assert.doesNotMatch(projectGitHeaderActionsSource, /window\.api/)
  assert.match(projectGitHeaderActionsSource, /runProjectGitWorkspaceAction/)
  assert.match(projectGitWorkspaceSource, /readElectronApi\(\)/)
  assert.doesNotMatch(projectGitWorkspaceSource, /window\.api/)
  assert.match(projectGitWorkspaceSource, /commitProjectGitWorkspace/)
  assert.match(projectGitWorkspaceSource, /pullProjectGitWorkspace/)
  assert.match(projectGitWorkspaceSource, /pushProjectGitWorkspace/)

  assert.match(appSettingsStoreSource, /export async function saveElectronAppSettings/)
  assert.match(appSettingsStoreSource, /readElectronApi\(\)\?\.setAppSettings/)
  assert.doesNotMatch(appSettingsStoreSource, /window\.api/)
})

function readSource(path) {
  return readFileSync(resolve(path), 'utf8')
}
