import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

const resourcesPageSource = readSource('apps/frontend/src/features/resources/components/ResourcesPage.tsx')
const resourcesPageControllerSource = readSource('apps/frontend/src/features/resources/components/useResourceLibraryController.ts')
const resourcesPageDialogsSource = readSource('apps/frontend/src/features/resources/components/ResourcesPageDialogs.tsx')
const resourcesPageItemsSource = readSource('apps/frontend/src/features/resources/components/ResourcesPageItems.tsx')
const externalSearchSource = readSource('apps/frontend/src/features/resources/components/ResourcesPageExternalSearch.tsx')
const externalSearchItemsSource = readSource('apps/frontend/src/features/resources/components/ResourcesPageExternalSearchItems.tsx')
const externalSearchControllerSource = readSource('apps/frontend/src/features/resources/application/useExternalResourceSearchController.ts')
const externalSearchModelSource = readSource('apps/frontend/src/features/resources/application/externalResourceSearchModel.ts')
const resourcePageUiSource = readSource('apps/frontend/src/features/resources/components/ResourcePageUi.tsx')
const resourcePageDialogUiSource = readSource('apps/frontend/src/features/resources/components/ResourcePageDialogUi.tsx')
const contextMenuDismissSource = readSource('apps/frontend/src/features/resources/application/useResourceContextMenuDismiss.ts')
const videoClipElectronSource = readSource('apps/frontend/src/features/resources/application/resourceVideoClipElectron.ts')
const videoClipSourceHookSource = readSource('apps/frontend/src/features/resources/application/useResourceVideoClipSource.ts')
const videoClipStatusHookSource = readSource('apps/frontend/src/features/resources/application/useResourceVideoClipStatus.ts')
const videoClipUploadHookSource = readSource('apps/frontend/src/features/resources/application/useResourceVideoClipUpload.ts')
const videoClipDialogSource = readSource('apps/frontend/src/features/resources/components/ResourcesPageVideoClipDialog.tsx')
const videoClipDialogControllerSource = readSource('apps/frontend/src/features/resources/components/useVideoClipDialogController.ts')
const genResultCardSource = readSource('apps/frontend/src/shared/ui/GenResultCard.tsx')
const resourceQueryCacheSource = readSource('apps/frontend/src/features/resources/application/resourceQueryCache.ts')

test('resources page delegates library state and mutations to controller hook', () => {
  assert.match(resourcesPageSource, /from '@\/features\/resources\/components\/useResourceLibraryController'/)
  assert.match(resourcesPageSource, /const controller = useResourceLibraryController\(\)/)
  assert.doesNotMatch(resourcesPageSource, /\buseMutation\(/)
  assert.doesNotMatch(resourcesPageSource, /\buseQuery\(/)
  assert.doesNotMatch(resourcesPageSource, /\buseProjectStore\b/)
  assert.doesNotMatch(resourcesPageSource, /\buseUserStore\b/)
  assert.match(resourcesPageControllerSource, /export function useResourceLibraryController/)
  assert.match(resourcesPageControllerSource, /resourceKeys\.libraryPage/)
  assert.match(resourcesPageControllerSource, /resourceBindingKeys\.projectLibraryScope/)
  assert.match(resourcesPageControllerSource, /resourceLibraryChangedResult/)
  assert.match(resourcesPageControllerSource, /resourceBindingChangedResult/)
})

test('resources page delegates context menu global dismiss listeners', () => {
  assert.match(resourcesPageSource, /from '@\/features\/resources\/components\/ResourcesPageItems'/)
  assert.doesNotMatch(resourcesPageSource, /from '@\/features\/resources\/application\/useResourceContextMenuDismiss'/)
  assert.doesNotMatch(resourcesPageSource, /window\.addEventListener/)
  assert.doesNotMatch(resourcesPageSource, /window\.removeEventListener/)
  assert.match(resourcesPageItemsSource, /from '@\/features\/resources\/application\/useResourceContextMenuDismiss'/)
  assert.match(resourcesPageItemsSource, /useResourceContextMenuDismiss\(onClose\)/)

  assert.match(contextMenuDismissSource, /export function useResourceContextMenuDismiss/)
  assert.match(contextMenuDismissSource, /from '@\/shared\/infrastructure\/windowEvents'/)
  assert.match(contextMenuDismissSource, /listenToWindowEvent\('click', close\)/)
  assert.match(contextMenuDismissSource, /listenToWindowEvent\('keydown', close\)/)
  assert.doesNotMatch(contextMenuDismissSource, /window\.addEventListener/)
  assert.doesNotMatch(contextMenuDismissSource, /window\.removeEventListener/)
})

test('resources page delegates resource trim Electron mediaPipeline access', () => {
  assert.match(resourcesPageSource, /from '@\/features\/resources\/components\/ResourcesPageVideoClipDialog'/)
  assert.doesNotMatch(resourcesPageSource, /from '@\/features\/resources\/application\/resourceVideoClipElectron'/)
  assert.match(videoClipDialogSource, /from '@\/features\/resources\/components\/useVideoClipDialogController'/)
  assert.doesNotMatch(videoClipDialogSource, /from '@\/features\/resources\/application\/useResourceVideoClipUpload'/)
  assert.match(videoClipDialogControllerSource, /from '@\/features\/resources\/application\/useResourceVideoClipUpload'/)
  assert.match(videoClipDialogControllerSource, /useResourceVideoClipUpload\(\{/)
  assert.match(videoClipUploadHookSource, /from '@\/features\/resources\/application\/resourceVideoClipElectron'/)
  assert.match(videoClipUploadHookSource, /trimResourceVideoSegment\(/)
  assert.doesNotMatch(videoClipDialogSource, /from '@\/features\/resources\/application\/useResourceVideoClipStatus'/)
  assert.match(videoClipDialogControllerSource, /from '@\/features\/resources\/application\/useResourceVideoClipStatus'/)
  assert.match(videoClipDialogControllerSource, /useResourceVideoClipStatus\(\)/)
  assert.doesNotMatch(videoClipDialogSource, /getResourceVideoClipStatus\(/)
  assert.doesNotMatch(videoClipDialogSource, /resourceVideoClipApiAvailable\(\)/)
  assert.doesNotMatch(videoClipDialogSource, /trimResourceVideoSegment\(/)
  assert.doesNotMatch(resourcesPageSource, /window\.api/)
  assert.doesNotMatch(videoClipDialogSource, /window\.api/)

  assert.match(videoClipStatusHookSource, /getResourceMediaPipelineTrimStatus\(\)/)
  assert.match(videoClipStatusHookSource, /resourceMediaPipelineTrimApiAvailable\(\)/)
  assert.match(videoClipElectronSource, /renderMediaPipelineSingleClip/)
  assert.match(videoClipElectronSource, /getMediaPipelineFFmpegStatus/)
  assert.doesNotMatch(videoClipElectronSource, /api\?\.clipVideo/)
  assert.doesNotMatch(videoClipElectronSource, /api\?\.getVideoClipStatus/)
  assert.doesNotMatch(videoClipElectronSource, /\?\?/)
  assert.doesNotMatch(videoClipElectronSource, /window\.api/)
  assert.match(videoClipElectronSource, /export function resourceMediaPipelineTrimApiAvailable/)
})

test('resources video clip dialog delegates source blob loading lifecycle', () => {
  assert.match(videoClipDialogSource, /from '@\/features\/resources\/components\/useVideoClipDialogController'/)
  assert.doesNotMatch(videoClipDialogSource, /from '@\/features\/resources\/application\/useResourceVideoClipSource'/)
  assert.match(videoClipDialogControllerSource, /from '@\/features\/resources\/application\/useResourceVideoClipSource'/)
  assert.match(videoClipDialogControllerSource, /useResourceVideoClipSource\(resource\)/)
  assert.doesNotMatch(videoClipDialogSource, /loadResourceBlob/)
  assert.doesNotMatch(videoClipDialogSource, /createObjectUrl/)
  assert.doesNotMatch(videoClipDialogSource, /revokeObjectUrl/)
  assert.doesNotMatch(videoClipDialogSource, /sourceLoadAttempt/)

  assert.match(videoClipSourceHookSource, /export function useResourceVideoClipSource/)
  assert.match(videoClipSourceHookSource, /loadResourceBlob\(resource/)
  assert.match(videoClipSourceHookSource, /createObjectUrl\(blob\)/)
  assert.match(videoClipSourceHookSource, /revokeObjectUrl\(objectUrl\)/)
  assert.match(videoClipSourceHookSource, /retrySourceLoad: \(\) => setSourceLoadAttempt/)
})

test('resources page delegates dialog implementations', () => {
  assert.match(resourcesPageSource, /from '@\/features\/resources\/components\/ResourcesPageDialogs'/)
  assert.match(resourcesPageDialogsSource, /export function MoveDialog/)
  assert.match(resourcesPageDialogsSource, /export function RenameResourceDialog/)
  assert.match(resourcesPageDialogsSource, /export function ShareToProjectDialog/)
  assert.doesNotMatch(resourcesPageSource, /function MoveDialog/)
  assert.doesNotMatch(resourcesPageSource, /function RenameResourceDialog/)
  assert.doesNotMatch(resourcesPageSource, /function ShareToProjectDialog/)
  assert.doesNotMatch(resourcesPageSource, /ResourceDialogContent/)
})

test('resource page dialog, clip, and permission primitives are split from the wrapper barrel', () => {
  assert.match(resourcePageUiSource, /export \* from '@\/features\/resources\/components\/ResourcePageDialogUi'/)
  assert.doesNotMatch(resourcePageUiSource, /export function ResourceDialogContent/)
  assert.doesNotMatch(resourcePageUiSource, /export function ResourceClipLayout/)
  assert.doesNotMatch(resourcePageUiSource, /export function ResourcePermissionSection/)

  assert.match(resourcePageDialogUiSource, /export function ResourceDialogContent/)
  assert.match(resourcePageDialogUiSource, /export function ResourceClipLayout/)
  assert.match(resourcePageDialogUiSource, /export function ResourcePermissionSection/)
})

test('resource cache reads are delegated to application helpers', () => {
  assert.match(genResultCardSource, /from '@\/features\/resources\/application\/resourceQueryCache'/)
  assert.match(genResultCardSource, /readCachedResourceById\(qc, id\)/)
  assert.doesNotMatch(genResultCardSource, /qc\.getQueryData/)
  assert.match(resourceQueryCacheSource, /export function readCachedResourceById/)
  assert.match(resourceQueryCacheSource, /resourceKeys\.all/)
  assert.match(resourceQueryCacheSource, /queryClient\.getQueryData<RawResource\[]>/)
})

test('external resource search delegates state, queries, and imports to controller', () => {
  assert.match(externalSearchSource, /from '@\/features\/resources\/application\/useExternalResourceSearchController'/)
  assert.match(externalSearchSource, /useExternalResourceSearchController\(\)/)
  assert.doesNotMatch(externalSearchSource, /\buseQuery\(/)
  assert.doesNotMatch(externalSearchSource, /\buseMutation\(/)
  assert.doesNotMatch(externalSearchSource, /loadExternalResourceSearchSnapshot\(\)/)
  assert.doesNotMatch(externalSearchSource, /subscribeExternalResourceSearchSnapshot/)
  assert.doesNotMatch(externalSearchSource, /saveExternalResourceSearchSnapshot\(/)
  assert.doesNotMatch(externalSearchSource, /uploadExternalResourceItem\(/)

  assert.match(externalSearchControllerSource, /export function useExternalResourceSearchController/)
  assert.match(externalSearchControllerSource, /externalResourceKeys\.sources/)
  assert.match(externalSearchControllerSource, /externalResourceKeys\.search/)
  assert.match(externalSearchControllerSource, /loadExternalResourceSearchSnapshot\(\)/)
  assert.match(externalSearchControllerSource, /subscribeExternalResourceSearchSnapshot/)
  assert.match(externalSearchControllerSource, /saveExternalResourceSearchSnapshot\(\{/)
  assert.match(externalSearchControllerSource, /uploadExternalResourceItem\(item\)/)
  assert.match(externalSearchControllerSource, /invalidateResourceMutationResult/)
  assert.match(externalSearchModelSource, /export function externalResourceKey/)
  assert.match(externalSearchModelSource, /EXTERNAL_RESOURCE_PAGE_SIZE = 24/)
  assert.match(externalSearchItemsSource, /from '@\/features\/resources\/application\/externalResourceSearchModel'/)
})

function readSource(path) {
  return readFileSync(resolve(path), 'utf8')
}
