import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('pre-production review only loads explicitly opened workspace artifacts', () => {
  const source = readFileSync(resolve('src/features/pre-production/components/PreProductionPage.tsx'), 'utf8')
  const launchSource = readFileSync(resolve('src/features/pre-production/application/preProductionAgentLaunch.ts'), 'utf8')
  const canvasLaunchSource = readFileSync(resolve('src/features/pre-production/application/preProductionCanvasLaunch.ts'), 'utf8')
  const dataControllerSource = readFileSync(resolve('src/features/pre-production/application/preProductionDataController.ts'), 'utf8')
  const workspaceRepositorySource = readFileSync(resolve('src/features/pre-production/application/preProductionWorkspaceRepository.ts'), 'utf8')
  const assetRowsSource = readFileSync(resolve('src/features/pre-production/domain/preProductionAssetRows.ts'), 'utf8')
  const assetWriteSource = readFileSync(resolve('src/features/pre-production/domain/preProductionAssetCandidateWrite.ts'), 'utf8')
  const candidateControllerSource = readFileSync(resolve('src/features/pre-production/application/preProductionAssetCandidateController.ts'), 'utf8')
  const assetWorkspaceControllerSource = readFileSync(resolve('src/features/pre-production/application/preProductionAssetWorkspaceController.ts'), 'utf8')
  const auditControllerSource = readFileSync(resolve('src/features/pre-production/application/preProductionAuditController.ts'), 'utf8')
  const mediaControllerSource = readFileSync(resolve('src/features/pre-production/application/preProductionMediaCandidateController.ts'), 'utf8')
  const pageControllerSource = readFileSync(resolve('src/features/pre-production/application/preProductionPageController.ts'), 'utf8')
  const resourceLibrarySource = readFileSync(resolve('src/features/pre-production/application/preProductionResourceLibrary.ts'), 'utf8')
  const refreshControllerSource = readFileSync(resolve('src/features/pre-production/application/preProductionRefreshController.ts'), 'utf8')
  const reviewControllerSource = readFileSync(resolve('src/features/pre-production/application/preProductionReviewController.ts'), 'utf8')
  const uploadInputSource = readFileSync(resolve('src/features/pre-production/application/preProductionUploadInput.ts'), 'utf8')
  const reviewWorkspaceSource = readFileSync(resolve('src/features/pre-production/components/PreProductionReviewWorkspace.tsx'), 'utf8')
  const assetBoardSource = readFileSync(resolve('src/features/pre-production/components/PreProductionAssetBoard.tsx'), 'utf8')
  const assetDetailSource = readFileSync(resolve('src/features/pre-production/components/PreProductionAssetDetail.tsx'), 'utf8')
  const resourceLibraryDialogSource = readFileSync(resolve('src/features/pre-production/components/PreProductionResourceLibraryDialog.tsx'), 'utf8')

  assert.match(source, /usePreProductionReviewController\(\{ projectId, searchParams, setSearchParams \}\)/)
  assert.match(reviewControllerSource, /export async function loadPreProductionReviewWorkspaces/)
  assert.match(reviewControllerSource, /providerSessionClient\.getWorkspaceArtifact\(workspaceId\)/)
  assert.match(reviewControllerSource, /openedSettingWorkspaceId/)
  assert.match(reviewControllerSource, /openedAssetWorkspaceArtifactId/)
  assert.match(reviewControllerSource, /searchParams\.get\('assetWorkspaceArtifactId'\)/)
  assert.match(reviewControllerSource, /searchParams\.get\('assetWorkspaceWorkspaceId'\)/)
  assert.match(reviewControllerSource, /queryKey: \['asset-workspace-workspaces', projectId, openedAssetWorkspaceArtifactId, openedWorkspaceId\]/)
  assert.match(reviewControllerSource, /queryKey: \['setting-workspace-workspaces', projectId, openedSettingWorkspaceId, openedWorkspaceId\]/)
  assert.doesNotMatch(source, /buildPreProductionAssetWorkspaceMutationOptions/)
  assert.doesNotMatch(source, /runPreProductionMediaCandidateGeneration/)
  assert.doesNotMatch(source, /runPreProductionAudit/)
  assert.doesNotMatch(source, /buildPreProductionAssetSlotCanvasMutationOptions/)
  assert.match(source, /refreshPreProductionWorkbenchContext/)
  assert.match(source, /usePreProductionWorkbenchData\(projectId\)/)
  assert.match(source, /buildUpdatePreProductionAssetSlotMutationOptions/)
  assert.match(source, /buildCreatePreProductionAssetSlotMutationOptions/)
  assert.match(source, /usePreProductionUploadInput/)
  assert.match(source, /<PreProductionReviewWorkspace/)
  assert.match(source, /buildPreProductionLockCandidateMutationOptions/)
  assert.match(source, /buildPreProductionRejectCandidateMutationOptions/)
  assert.doesNotMatch(source, /buildPreProductionAddCandidateMutationOptions/)
  assert.match(source, /buildPreProductionAttachLibraryCandidateMutationOptions/)
  assert.match(source, /buildPreProductionUploadCandidateMutationOptions/)
  assert.match(source, /usePreProductionPageController\(\{/)
  assert.match(source, /usePreProductionResourceLibrary\(\)/)
  assert.match(source, /ResourcePrepWorkbenchShell/)
  assert.match(source, /ResourcePrepWorkbenchLayout/)
  assert.match(source, /type PreProductionWorkbenchView = 'setting' \| 'asset'/)
  assert.match(source, /type PreProductionSettingDetailView = 'setting' \| 'assets'/)
  assert.doesNotMatch(source, /<PreProductionAssetBoard/)
  assert.doesNotMatch(source, /刷新上下文/)
  assert.doesNotMatch(source, /审阅工作区/)
  assert.doesNotMatch(source, /梳理设定\+素材/)
  assert.match(source, /<PreProductionResourceLibraryDialog/)
  assert.match(launchSource, /export function buildAssetCandidateWorkspaceReviewSearchParams/)
  assert.match(launchSource, /export function buildPreProductionAuditReviewSearchParams/)
  assert.match(launchSource, /export function buildMediaCandidateGenerationAgentPanelWorkspacePayload/)
  assert.match(launchSource, /export function getMediaCandidateGenerationResult/)
  assert.match(launchSource, /mergeProjectWorkbenchArtifactReviewSearchParams/)
  assert.match(canvasLaunchSource, /export function buildPreProductionAssetSlotCanvasPayload/)
  assert.match(canvasLaunchSource, /export async function createPreProductionAssetSlotCanvas/)
  assert.match(canvasLaunchSource, /export function preProductionCanvasRoute/)
  assert.match(canvasLaunchSource, /export function buildPreProductionAssetSlotCanvasMutationOptions/)
  assert.match(dataControllerSource, /export function usePreProductionWorkbenchData/)
  assert.match(dataControllerSource, /export function buildUpdatePreProductionAssetSlotMutationOptions/)
  assert.match(dataControllerSource, /export function buildCreatePreProductionAssetSlotMutationOptions/)
  assert.match(dataControllerSource, /loadPreProductionWorkspaceData\(projectId!\)/)
  assert.match(dataControllerSource, /buildPreProductionAssetRows/)
  assert.match(dataControllerSource, /buildReferenceAssetClusters/)
  assert.match(dataControllerSource, /buildPreProductionAssetSlotCreatePayload/)
  assert.match(dataControllerSource, /savePreProductionWorkspaceAssetSlot/)
  assert.doesNotMatch(dataControllerSource, /createSemanticEntity/)
  assert.doesNotMatch(dataControllerSource, /updateSemanticEntity/)
  assert.doesNotMatch(dataControllerSource, /listSemanticEntities/)
  assert.match(workspaceRepositorySource, /createElectronMovScriptWorkspaceService/)
  assert.match(workspaceRepositorySource, /service\.querySettings\(\)/)
  assert.match(workspaceRepositorySource, /service\.queryAssets\(\{ includeCandidates: true \}\)/)
  assert.match(workspaceRepositorySource, /service\.upsertSetting/)
  assert.match(workspaceRepositorySource, /service\.upsertAsset/)
  assert.doesNotMatch(workspaceRepositorySource, /readMovScriptWorkspaceFile/)
  assert.doesNotMatch(workspaceRepositorySource, /writeMovScriptWorkspaceFile/)
  assert.doesNotMatch(workspaceRepositorySource, /movscript\.setting\.v1/)
  assert.doesNotMatch(workspaceRepositorySource, /movscript\.asset(_slot)?\.v1/)
  assert.match(source, /reviewMovScriptWorkspace/)
  assert.match(source, /buildMovScriptWorkspace/)
  assert.match(source, /workspaceReviewReady\(workspaceBuildReview\)/)
  assert.doesNotMatch(source, /updateMovScriptWorkspaceProjection/)
  assert.doesNotMatch(source, /previewMovScriptWorkspaceApply/)
  assert.doesNotMatch(source, /applyMovScriptWorkspaceProjection/)
  assert.doesNotMatch(source, /workspaceActionNamespace/)
  assert.doesNotMatch(source, /namespace: workspaceActionNamespace/)
  assert.doesNotMatch(source, /workspaceReviewPath/)
  assert.match(dataControllerSource, /preProductionAssetSlotsQueryKey/)
  assert.match(assetRowsSource, /export function buildPreProductionAssetRows/)
  assert.match(assetRowsSource, /export function buildReferenceAssetClusters/)
  assert.match(assetRowsSource, /export function buildAssetCandidatePatchPayload/)
  assert.match(assetRowsSource, /export function assetSlotHasLoadedResource/)
  assert.match(assetRowsSource, /export function candidateReferenceResourceIds/)
  assert.match(assetWriteSource, /export function buildPreProductionAssetSlotCreatePayload/)
  assert.match(assetWriteSource, /export function buildPreProductionLibraryCandidatePayload/)
  assert.match(assetWriteSource, /export function buildPreProductionUploadCandidatePayload/)
  assert.match(assetWriteSource, /export function buildPreProductionGeneratedCandidatePayload/)
  assert.match(assetWriteSource, /export function preProductionResourceLibraryPageCount/)
  assert.match(assetWriteSource, /export const initialPreProductionResourceLibraryState/)
  assert.match(assetWriteSource, /export function openPreProductionResourceLibraryState/)
  assert.match(assetWriteSource, /export function setPreProductionResourceLibrarySearch/)
  assert.match(candidateControllerSource, /export function buildPreProductionLockCandidateMutationOptions/)
  assert.match(candidateControllerSource, /export function buildPreProductionRejectCandidateMutationOptions/)
  assert.match(candidateControllerSource, /export function buildPreProductionAddCandidateMutationOptions/)
  assert.match(candidateControllerSource, /export function buildPreProductionAttachLibraryCandidateMutationOptions/)
  assert.match(candidateControllerSource, /export function buildPreProductionUploadCandidateMutationOptions/)
  assert.match(candidateControllerSource, /invalidateAssetCandidateConsumers/)
  assert.match(candidateControllerSource, /savePreProductionWorkspaceAssetCandidate/)
  assert.match(candidateControllerSource, /createWorkspaceAssetSlotCandidate/)
  assert.doesNotMatch(candidateControllerSource, /api\.patch/)
  assert.match(candidateControllerSource, /api\.post/)
  assert.match(assetWorkspaceControllerSource, /export function buildPreProductionAssetWorkspaceMutationOptions/)
  assert.match(assetWorkspaceControllerSource, /createAssetCandidateWorkspaceArtifact/)
  assert.match(assetWorkspaceControllerSource, /launchAssetCandidateWorkspaceAgent/)
  assert.match(assetWorkspaceControllerSource, /candidateReferenceResourceIds/)
  assert.match(assetWorkspaceControllerSource, /buildAssetCandidateWorkspaceReviewSearchParams/)
  assert.match(auditControllerSource, /export function runPreProductionAudit/)
  assert.match(auditControllerSource, /launchPreProductionAuditAgent/)
  assert.match(auditControllerSource, /buildPreProductionAuditReviewSearchParams/)
  assert.match(auditControllerSource, /pre_production_audit/)
  assert.match(mediaControllerSource, /export function runPreProductionMediaCandidateGeneration/)
  assert.match(mediaControllerSource, /launchMediaCandidateGenerationAgent/)
  assert.match(mediaControllerSource, /buildPreProductionGeneratedCandidatePayload/)
  assert.match(pageControllerSource, /export function usePreProductionPageController/)
  assert.match(pageControllerSource, /export function resolvePreProductionPageSelection/)
  assert.match(pageControllerSource, /export function buildPreProductionFilterParams/)
  assert.match(pageControllerSource, /readNumberParam\(searchParams, 'asset_slot_id'\)/)
  assert.match(pageControllerSource, /setNewSlotEditId/)
  assert.match(pageControllerSource, /setNewReferenceEditKey/)
  assert.match(pageControllerSource, /updateContentFilterParams/)
  assert.match(resourceLibrarySource, /export function usePreProductionResourceLibrary/)
  assert.match(resourceLibrarySource, /export function buildPreProductionResourceLibraryQueryKey/)
  assert.match(resourceLibrarySource, /export function buildPreProductionResourceLibraryParams/)
  assert.match(resourceLibrarySource, /api\.get\('\/resources'/)
  assert.match(resourceLibrarySource, /preProductionResourceLibraryPageCount/)
  assert.match(resourceLibrarySource, /preProductionResourceLibraryTotal/)
  assert.match(resourceLibrarySource, /setPreProductionResourceLibrarySearch/)
  assert.match(resourceLibrarySource, /setPreProductionResourceLibraryType/)
  assert.match(refreshControllerSource, /export async function refreshPreProductionWorkbenchContext/)
  assert.match(refreshControllerSource, /'pre-production-settings'/)
  assert.match(refreshControllerSource, /'semantic-asset-slots-page'/)
  assert.match(refreshControllerSource, /'semantic-asset-slot-candidates-page'/)
  assert.match(uploadInputSource, /export function usePreProductionUploadInput/)
  assert.match(uploadInputSource, /triggerUpload/)
  assert.match(uploadInputSource, /resetUpload/)
  assert.match(reviewWorkspaceSource, /PreProductionWorkspaceReviewPanel/)
  assert.match(reviewWorkspaceSource, /kind="setting_workspace"/)
  assert.match(reviewWorkspaceSource, /kind="asset_workspace"/)
  assert.match(assetBoardSource, /export function PreProductionAssetBoard/)
  assert.match(assetBoardSource, /export function SlotThumb/)
  assert.match(assetBoardSource, /export function SlotStatusBadge/)
  assert.match(assetBoardSource, /WorkbenchEntityCard/)
  assert.match(assetBoardSource, /assetKindOrder/)
  assert.match(assetDetailSource, /export function AssetSlotDetail/)
  assert.match(assetDetailSource, /function CandidateRow/)
  assert.match(assetDetailSource, /assetSlotHasLoadedResource/)
  assert.match(assetDetailSource, /SlotThumb/)
  assert.match(resourceLibraryDialogSource, /export function PreProductionResourceLibraryDialog/)
  assert.match(resourceLibraryDialogSource, /ResourceLibraryPicker/)
  assert.match(resourceLibraryDialogSource, /assetKindLabel/)
  assert.doesNotMatch(source, /api\.post\('\/canvases'/)
  assert.doesNotMatch(source, /navigate\(`\/canvases\/\$\{canvas\.ID\}`\)/)
  assert.doesNotMatch(source, /createPreProductionAssetSlotCanvas/)
  assert.doesNotMatch(source, /preProductionCanvasRoute/)
  assert.doesNotMatch(source, /function buildRows/)
  assert.doesNotMatch(source, /listSemanticEntities\(projectId!/)
  assert.doesNotMatch(source, /createSemanticEntity\(projectId/)
  assert.doesNotMatch(source, /updateSemanticEntity\(projectId!/)
  assert.doesNotMatch(source, /buildPreProductionAssetSlotCreatePayload/)
  assert.doesNotMatch(source, /buildPreProductionAssetRows\(visibleSlots/)
  assert.doesNotMatch(source, /buildReferenceAssetClusters\(settings/)
  assert.doesNotMatch(source, /function candidatePatchPayload/)
  assert.doesNotMatch(source, /function buildReferenceAssetClusters/)
  assert.doesNotMatch(source, /function candidateReferenceResourceIds/)
  assert.doesNotMatch(source, /function assetSlotHasLoadedResource/)
  assert.doesNotMatch(source, /function defaultResourceTypeForAssetKind/)
  assert.doesNotMatch(source, /function runMediaCandidateGeneration/)
  assert.doesNotMatch(source, /function PreProductionAssetBoard/)
  assert.doesNotMatch(source, /function ReferenceClusterButton/)
  assert.doesNotMatch(source, /function ReferenceAssetTile/)
  assert.doesNotMatch(source, /function AssetSlotDetail/)
  assert.doesNotMatch(source, /function CandidateRow/)
  assert.doesNotMatch(source, /function AssetResourceLibraryDialog/)
  assert.doesNotMatch(source, /from '@\/components\/shared\/ResourceLibraryPicker'/)
  assert.doesNotMatch(source, /<ResourceLibraryPicker/)
  assert.doesNotMatch(source, /uploadInputRef/)
  assert.doesNotMatch(source, /const \[uploading, setUploading\]/)
  assert.doesNotMatch(source, /api\.(patch|post)\(/)
  assert.doesNotMatch(source, /api\.get\('\/resources'/)
  assert.doesNotMatch(source, /invalidateAssetCandidateConsumers/)
  assert.doesNotMatch(source, /preProductionResourceLibraryPageCount/)
  assert.doesNotMatch(source, /initialPreProductionResourceLibraryState/)
  assert.doesNotMatch(source, /setPreProductionResourceLibrarySearch/)
  assert.doesNotMatch(source, /setPreProductionResourceLibraryType/)
  assert.doesNotMatch(source, /readNumberParam\(searchParams, 'asset_slot_id'\)/)
  assert.doesNotMatch(source, /readStringParam\(searchParams, 'kind'\)/)
  assert.doesNotMatch(source, /updateContentFilterParams\(searchParams/)
  assert.doesNotMatch(source, /const \[newSlotEditId, setNewSlotEditId\]/)
  assert.doesNotMatch(source, /const \[newReferenceEditKey, setNewReferenceEditKey\]/)
  assert.doesNotMatch(source, /useState\(false\)[\s\S]{0,200}useState\(''\)[\s\S]{0,200}useState<ResourceTypeFilter>\('all'\)/)
  assert.doesNotMatch(source, /note: `从资源库选择/)
  assert.doesNotMatch(source, /note: `手动上传候选/)
  assert.doesNotMatch(source, /selectLatestWorkspaceArtifact/)
  assert.doesNotMatch(source, /selectLatestGeneratedResource/)
  assert.doesNotMatch(source, /buildEmptyAssetWorkspaceWorkspaceContent/)
  assert.doesNotMatch(source, /buildCommandFirstClientInput/)
  assert.doesNotMatch(source, /openAgentPanelWorkspace/)
  assert.doesNotMatch(source, /registerAgentPanelPageTool/)
  assert.doesNotMatch(source, /taskType: 'pre_production_audit'/)
  assert.doesNotMatch(source, /launchPreProductionAuditAgent/)
  assert.doesNotMatch(source, /buildPreProductionAuditReviewSearchParams/)
  assert.doesNotMatch(source, /taskType: 'asset_candidate_workspace'/)
  assert.doesNotMatch(source, /createAssetCandidateWorkspaceWorkspace/)
  assert.doesNotMatch(source, /launchAssetCandidateWorkspaceAgent/)
  assert.doesNotMatch(source, /buildAssetCandidateWorkspaceReviewSearchParams/)
  assert.doesNotMatch(source, /taskType: 'asset_candidate_generation'/)
  assert.doesNotMatch(source, /providerSessionClient\.listWorkspaces\(\{ projectId, kind: 'setting_workspace'/)
  assert.doesNotMatch(source, /providerSessionClient\.listWorkspaces\(\{ projectId, kind: 'asset_workspace'/)
  assert.doesNotMatch(source, /function loadPreProductionReviewWorkspaces/)
  assert.doesNotMatch(source, /providerSessionClient\.getWorkspace\(workspaceId\)/)
  assert.doesNotMatch(source, /openedSettingWorkspaceId/)
  assert.doesNotMatch(source, /openedAssetWorkspaceArtifactId/)
})

test('pre-production workspace panel does not link to historical workspace inventory', () => {
  const source = readFileSync(resolve('src/features/pre-production/components/workspaces/PreProductionWorkspaceReviewPanel.tsx'), 'utf8')

  assert.doesNotMatch(source, /查看全部 AI 草案/)
  assert.doesNotMatch(source, /href="\/agent\/workspaces"/)
  assert.doesNotMatch(source, /FileText/)
})

test('pre-production workbench uses head-level views and setting detail filters', () => {
  const source = readFileSync(resolve('src/features/pre-production/components/PreProductionPage.tsx'), 'utf8')
  const pageControllerSource = readFileSync(resolve('src/features/pre-production/application/preProductionPageController.ts'), 'utf8')
  const editorSource = readFileSync(resolve('src/shared/ui/SemanticEntityInlineEditor.tsx'), 'utf8')

  assert.match(editorSource, /hideHeaderActions\?: boolean/)
  assert.match(source, /type PreProductionWorkbenchView = 'setting' \| 'asset'/)
  assert.match(source, /type PreProductionSettingDetailView = 'setting' \| 'assets'/)
  assert.match(source, /readStringParam\(searchParams, 'prep_view'\)/)
  assert.match(pageControllerSource, /readStringParam\(nextParams, 'kind'\)/)
  assert.match(source, /setFilter\(\{ prep_view: view \}\)/)
  assert.match(source, /openWorkspaceSubmitPreview/)
  assert.match(source, /构建工作区/)
  assert.match(source, /构建生效/)
  assert.match(source, /setting_state_id: \[\]/)
  assert.match(editorSource, /hasExternalSettingOptions/)
  assert.match(editorSource, /hasExternalSettingStateOptions/)
  assert.match(source, /actions: \(\s*<div className="flex flex-wrap items-center gap-2">/)
  assert.match(source, /<ResourcePrepViewTabs>/)
  assert.match(source, /active=\{workbenchView === 'setting'\}/)
  assert.match(source, /active=\{workbenchView === 'asset'\}/)
  assert.doesNotMatch(source, /headerBody: \(\s*<ResourcePrepViewTabs>/)
  assert.match(source, /ResourcePrepWorkbenchShell/)
  assert.match(source, /ResourcePrepWorkbenchLayout/)
  assert.match(source, /ResourcePrepWorkbenchRail/)
  assert.match(source, /ResourcePrepWorkbenchMain/)
  assert.match(source, /workbenchView === 'setting' \? '设定视图' : '素材视图'/)
  assert.match(source, /workbenchView === 'setting' \? \(\s*<>/)
  assert.match(source, /rows\.map\(\(row\) => \(\s*<AssetSlotInlineCard/)
  assert.match(source, /function PreProductionSettingDetail/)
  assert.match(source, /function PreProductionAssetDetailPanel/)
  assert.match(source, /active=\{detailView === 'setting'\}/)
  assert.match(source, /setDetailView\('setting'\)/)
  assert.match(source, /active=\{detailView === 'assets'\}/)
  assert.match(source, /setDetailView\('assets'\)/)
  assert.match(source, /<SettingAssetList/)
  assert.match(source, /<AssetSlotDetail\s+row=\{selected\}/)
  assert.match(source, /hideHeaderActions/)
  assert.match(source, /hideDeleteAction/)
  assert.match(source, /hiddenFieldKeys=\{\['status'\]\}/)
  assert.match(source, /showAdvancedFields=\{false\}/)
  assert.match(source, /openAssetCreateDialog/)
  assert.match(source, /素材必须先归属到一个设定/)
  assert.doesNotMatch(source, /type InspectorMode = 'asset' \| 'reference'/)
  assert.doesNotMatch(source, /function PreProductionInspector/)
  assert.doesNotMatch(source, /onModeChange=\{setInspectorMode\}/)
  assert.doesNotMatch(source, /const detailRailCollapsed = referenceEditorCollapsed && assetEditorCollapsed/)
  assert.doesNotMatch(source, /data-detail-rail-collapsed/)
  assert.doesNotMatch(source, /collapsedMode="horizontal"/)
  assert.doesNotMatch(source, /fixed right-0 top-0/)
})
