import type { MCPTool } from '../../protocol/types'
import { objectSchema } from '../schema'

const projectLocator = {
  homeDir: { type: 'string', description: 'MovScript Home directory used to discover daemon-owned service endpoints.' },
  home_dir: { type: 'string', description: 'Alias for homeDir.' },
  workspaceDir: { type: 'string', description: 'Workspace root used for backend auth lookup.' },
  workspace_dir: { type: 'string', description: 'Alias for workspaceDir.' },
  projectDir: { type: 'string', description: 'MovScript project directory for Project Service-backed candidate and source actions.' },
  project_dir: { type: 'string', description: 'Alias for projectDir.' },
  backendBaseURL: { type: 'string', description: 'Daemon gateway or backend base URL.' },
  backend_base_url: { type: 'string', description: 'Alias for backendBaseURL.' },
  server: { type: 'string', description: 'Alias for daemon gateway/backend base URL.' },
  editingServiceURL: { type: 'string', description: 'Explicit Editing Service base URL.' },
  editing_service_url: { type: 'string', description: 'Alias for editingServiceURL.' },
  mediaPipelineServiceURL: { type: 'string', description: 'Explicit Media Pipeline Service base URL.' },
  media_pipeline_service_url: { type: 'string', description: 'Alias for mediaPipelineServiceURL.' },
  projectServiceURL: { type: 'string', description: 'Explicit Project Service base URL for candidate/source actions.' },
  project_service_url: { type: 'string', description: 'Alias for projectServiceURL.' },
  token: { type: 'string', description: 'Backend bearer token.' },
  mediaProjectId: { type: ['string', 'number'], description: 'MediaEditingProject project id used by editing workspaces and media task recovery.' },
  media_project_id: { type: ['string', 'number'], description: 'Alias for mediaProjectId.' },
  projectId: { type: ['string', 'number'], description: 'Deprecated alias for mediaProjectId. Do not use as a MovScript source project locator.' },
  project_id: { type: ['string', 'number'], description: 'Deprecated alias for mediaProjectId.' },
}

const editingProjectInput = {
  editingProject: { type: 'object', additionalProperties: true, description: 'MediaEditingProject object.' },
  editing_project: { type: 'object', additionalProperties: true, description: 'Alias for editingProject.' },
  project: { type: 'object', additionalProperties: true, description: 'Alias for editingProject.' },
}

export function editingTools(): MCPTool[] {
  return [
    {
      name: 'editing_project_create',
      description: 'Create and persist an empty MovScript media editing project through Editing Service. This does not render media or write content candidates.',
      inputSchema: objectSchema({
        ...projectLocator,
        title: { type: 'string' },
        width: { type: 'number' },
        height: { type: 'number' },
        fps: { type: 'number' },
        background: { type: 'string' },
      }),
    },
    {
      name: 'editing_project_get',
      description: 'Read a persisted MediaEditingProject by id from Editing Service.',
      inputSchema: objectSchema({ ...projectLocator, editingProjectId: { type: 'string' }, editing_project_id: { type: 'string' } }),
    },
    {
      name: 'editing_project_update_settings',
      description: 'Update MediaEditingProject settings such as title, fps, canvas size, background, and workspace binding. This mutates project data only.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        title: { type: 'string' },
        width: { type: 'number' },
        height: { type: 'number' },
        fps: { type: 'number' },
        background: { type: 'string' },
        workspace: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_project_add_asset',
      description: 'Add a RawResource, generated resource, local file, or bytes-backed source to a MediaEditingProject asset registry.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        asset: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_project_remove_asset',
      description: 'Remove an unused asset reference from a MediaEditingProject asset registry. Fails if any clip still references the asset.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        assetId: { type: 'string' },
        asset_id: { type: 'string' },
      }),
    },
    {
      name: 'editing_project_save',
      description: 'Persist a MediaEditingProject revision through Editing Service. Pass expectedRevision for optimistic locking against the last revision read.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        expectedRevision: { type: 'number', description: 'Last persisted revision observed before editing. Save returns conflict if the stored revision changed.' },
        expected_revision: { type: 'number', description: 'Alias for expectedRevision.' },
      }),
    },
    {
      name: 'editing_timeline_apply_commands',
      description: 'Apply MovScript media timeline commands to a MediaEditingProject. This modifies the editing project only; it does not render media or create candidates.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        commands: { type: 'array', items: { type: 'object', additionalProperties: true } },
        command: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_timeline_add_track',
      description: 'Add a video, image, audio, text, subtitle, or effect track to a MediaEditingProject timeline.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        track: { type: 'object', additionalProperties: true },
        trackId: { type: 'string' },
        track_id: { type: 'string' },
        type: { type: 'string' },
        trackType: { type: 'string' },
        track_type: { type: 'string' },
        name: { type: 'string' },
        zIndex: { type: 'number' },
        z_index: { type: 'number' },
      }),
    },
    {
      name: 'editing_timeline_remove_track',
      description: 'Remove an empty track from a MediaEditingProject timeline.',
      inputSchema: objectSchema({ ...editingProjectInput, trackId: { type: 'string' }, track_id: { type: 'string' } }),
    },
    {
      name: 'editing_timeline_add_clip',
      description: 'Place an asset-backed or text clip onto a timeline track.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        trackId: { type: 'string' },
        track_id: { type: 'string' },
        clip: { type: 'object', additionalProperties: true },
        assetId: { type: 'string' },
        asset_id: { type: 'string' },
        assetType: { type: 'string' },
        asset_type: { type: 'string' },
        timelineStartMs: { type: 'number' },
        timeline_start_ms: { type: 'number' },
        durationMs: { type: 'number' },
        duration_ms: { type: 'number' },
      }),
    },
    {
      name: 'editing_timeline_update_clip',
      description: 'Update trim, duration, placement, volume, fit, style, or metadata for an existing timeline clip.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        clipId: { type: 'string' },
        clip_id: { type: 'string' },
        patch: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_timeline_split_clip',
      description: 'Split a timeline clip at an absolute timeline timestamp.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        clipId: { type: 'string' },
        clip_id: { type: 'string' },
        splitTimeMs: { type: 'number' },
        split_time_ms: { type: 'number' },
        retainSide: { type: 'string' },
        retain_side: { type: 'string' },
      }),
    },
    {
      name: 'editing_timeline_move_clip',
      description: 'Move a timeline clip to a new timestamp and optionally to another compatible track.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        clipId: { type: 'string' },
        clip_id: { type: 'string' },
        targetTrackId: { type: 'string' },
        target_track_id: { type: 'string' },
        timelineStartMs: { type: 'number' },
        timeline_start_ms: { type: 'number' },
      }),
    },
    {
      name: 'editing_timeline_delete_clip',
      description: 'Delete a clip from a MediaEditingProject timeline.',
      inputSchema: objectSchema({ ...editingProjectInput, clipId: { type: 'string' }, clip_id: { type: 'string' } }),
    },
    {
      name: 'editing_timeline_validate',
      description: 'Validate a MediaEditingProject timeline for missing assets, invalid timing, track mismatch, and unsupported clip settings.',
      inputSchema: objectSchema({ ...editingProjectInput }),
    },
    {
      name: 'editing_runtime_capabilities_get',
      description: 'Read Electron mediaPipeline runtime capabilities such as FFmpeg availability, version, supported task types, project store, and local HLS preview support. This does not start a task.',
      inputSchema: objectSchema({}),
    },
    {
      name: 'editing_video_compose',
      description: 'MovScript video_compose entrypoint: validate an existing MediaEditingProject and create a Media Pipeline render/HLS task. It does not accept legacy handoff artifacts or create production editing workspaces; use production_editing_workspace_create/open for production-bound editing. Supports movscript_media_pipeline/ffmpeg only; Remotion, HyperFrames, and external NLE runtimes return explicit blockers instead of silent fallback.',
      inputSchema: objectSchema({
        ...projectLocator,
        ...editingProjectInput,
        editingProjectId: { type: 'string' },
        editing_project_id: { type: 'string' },
        renderRuntime: { type: 'string' },
        render_runtime: { type: 'string' },
        format: { type: 'string', description: 'mp4 or hls. Defaults to mp4.' },
        output: { type: 'object', additionalProperties: true },
        importToResource: { type: 'boolean' },
        import_to_resource: { type: 'boolean' },
      }),
    },
    {
      name: 'editing_task_render_create',
      description: 'Create an Electron mediaPipeline timeline_render task for a MediaEditingProject. Rendering runs in Electron, not in the backend.',
      inputSchema: objectSchema({ ...projectLocator, ...editingProjectInput, output: { type: 'object', additionalProperties: true } }),
    },
    {
      name: 'editing_task_hls_create',
      description: 'Create an Electron mediaPipeline timeline_hls task. HLS packaging, including optional output.hlsVariants adaptive renditions, runs in Electron; backend only hosts uploaded artifacts.',
      inputSchema: objectSchema({ ...projectLocator, ...editingProjectInput, output: { type: 'object', additionalProperties: true } }),
    },
    {
      name: 'editing_task_transcode_create',
      description: 'Create an Electron mediaPipeline media_transcode task. Pass mediaProjectId so the task is stored in the correct Electron media workspace.',
      inputSchema: objectSchema({ ...projectLocator, source: { type: 'object', additionalProperties: true }, output: { type: 'object', additionalProperties: true } }),
    },
    {
      name: 'editing_task_reframe_create',
      description: 'Create an Electron mediaPipeline media_reframe task for mechanical crop/contain/pad reframe. Pass mediaProjectId so the task is stored in the correct Electron media workspace.',
      inputSchema: objectSchema({ ...projectLocator, source: { type: 'object', additionalProperties: true }, output: { type: 'object', additionalProperties: true }, target: { type: 'string' }, mode: { type: 'string' } }),
    },
    {
      name: 'editing_task_get',
      description: 'Read an Electron mediaPipeline task state. Pass mediaProjectId with taskId for persisted workspace recovery after app restart.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        mediaProjectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task recovery.' },
        media_project_id: { type: 'string', description: 'Alias for mediaProjectId.' },
        projectId: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
        project_id: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
      }),
    },
    {
      name: 'editing_task_cancel',
      description: 'Cancel an Electron mediaPipeline task. Pass mediaProjectId with taskId so Electron can recover persisted task state and write a clear cancel diagnostic after app restart.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        mediaProjectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task recovery.' },
        media_project_id: { type: 'string', description: 'Alias for mediaProjectId.' },
        projectId: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
        project_id: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
      }),
    },
    {
      name: 'editing_task_logs_get',
      description: 'Read FFmpeg/task logs for an Electron mediaPipeline task. Pass mediaProjectId with taskId for persisted workspace log recovery after app restart.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        mediaProjectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task log recovery.' },
        media_project_id: { type: 'string', description: 'Alias for mediaProjectId.' },
        projectId: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
        project_id: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
      }),
    },
    {
      name: 'editing_result_register',
      description: 'Register a completed render/export artifact in Media Pipeline result registry. This records an observable result only; it does not upload, create candidates, adopt, or select.',
      inputSchema: objectSchema({
        ...projectLocator,
        result: { type: 'object', additionalProperties: true },
        resultId: { type: 'string' },
        result_id: { type: 'string' },
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        backend: { type: 'string' },
        kind: { type: 'string' },
        outputKind: { type: 'string' },
        output_kind: { type: 'string' },
        status: { type: 'string' },
        source: { type: 'string' },
        outputPath: { type: 'string' },
        output_path: { type: 'string' },
        outputName: { type: 'string' },
        output_name: { type: 'string' },
        manifestPath: { type: 'string' },
        manifest_path: { type: 'string' },
        hlsManifestPath: { type: 'string' },
        hls_manifest_path: { type: 'string' },
        hlsDirectory: { type: 'string' },
        hls_directory: { type: 'string' },
        segmentPaths: { type: 'array', items: { type: 'string' } },
        segment_paths: { type: 'array', items: { type: 'string' } },
        resourceId: { type: ['string', 'number'] },
        resource_id: { type: ['string', 'number'] },
        streamId: { type: ['string', 'number'] },
        stream_id: { type: ['string', 'number'] },
        candidateId: { type: ['string', 'number'] },
        candidate_id: { type: ['string', 'number'] },
        provenance: { type: 'object', additionalProperties: true },
        metadata: { type: 'object', additionalProperties: true },
        params: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_result_recover_external_nle',
      description: 'Detect a completed External NLE export from outputPath/manifestPath or an output directory, then register it in the Media Pipeline result registry. This is result recovery only; it does not upload, create candidates, adopt, or select.',
      inputSchema: objectSchema({
        ...projectLocator,
        resultId: { type: 'string' },
        result_id: { type: 'string' },
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        outputPath: { type: 'string', description: 'Explicit single-file video export path.' },
        output_path: { type: 'string', description: 'Alias for outputPath.' },
        outputDirectory: { type: 'string', description: 'Directory to scan recursively for External NLE video or HLS exports.' },
        output_directory: { type: 'string', description: 'Alias for outputDirectory.' },
        watchDirectory: { type: 'string', description: 'Alias for outputDirectory, used by future monitor flows.' },
        watch_directory: { type: 'string', description: 'Alias for watchDirectory.' },
        exportDirectory: { type: 'string', description: 'Alias for outputDirectory.' },
        export_directory: { type: 'string', description: 'Alias for exportDirectory.' },
        waitForMs: { type: 'number', description: 'Optional watch-once timeout in milliseconds. When set, the tool polls until a supported output appears or the timeout elapses.' },
        wait_for_ms: { type: 'number', description: 'Alias for waitForMs.' },
        pollIntervalMs: { type: 'number', description: 'Polling interval in milliseconds for waitForMs watch-once recovery.' },
        poll_interval_ms: { type: 'number', description: 'Alias for pollIntervalMs.' },
        manifestPath: { type: 'string', description: 'Explicit HLS manifest path.' },
        manifest_path: { type: 'string', description: 'Alias for manifestPath.' },
        hlsManifestPath: { type: 'string', description: 'Alias for manifestPath.' },
        hls_manifest_path: { type: 'string', description: 'Alias for hlsManifestPath.' },
        hlsDirectory: { type: 'string' },
        hls_directory: { type: 'string' },
        segmentPaths: { type: 'array', items: { type: 'string' } },
        segment_paths: { type: 'array', items: { type: 'string' } },
        outputName: { type: 'string' },
        output_name: { type: 'string' },
        filename: { type: 'string' },
        outputKind: { type: 'string' },
        output_kind: { type: 'string' },
        status: { type: 'string' },
        source: { type: 'string' },
        exchangeProjectPath: { type: 'string', description: 'External NLE exchange project file used for the handoff, such as FCPXML/OTIO/EDL.' },
        exchange_project_path: { type: 'string', description: 'Alias for exchangeProjectPath.' },
        externalApp: { type: 'string', description: 'External editor app, such as final_cut_pro, premiere, or davinci_resolve.' },
        external_app: { type: 'string', description: 'Alias for externalApp.' },
        externalNle: { type: 'string', description: 'Alias for externalApp.' },
        external_nle: { type: 'string', description: 'Alias for externalNle.' },
        reviewer: { type: 'string' },
        reviewStatus: { type: 'string' },
        review_status: { type: 'string' },
        provenance: { type: 'object', additionalProperties: true },
        metadata: { type: 'object', additionalProperties: true },
        params: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_result_watch_external_nle_create',
      description: 'Create a daemon-owned background watch for an External NLE export directory or explicit artifact path. When a supported output appears, Media Pipeline registers a resultId. This does not upload, create candidates, adopt, or select.',
      inputSchema: objectSchema({
        ...projectLocator,
        watchId: { type: 'string' },
        watch_id: { type: 'string' },
        resultId: { type: 'string' },
        result_id: { type: 'string' },
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        outputPath: { type: 'string', description: 'Explicit single-file video export path to wait for.' },
        output_path: { type: 'string', description: 'Alias for outputPath.' },
        outputDirectory: { type: 'string', description: 'Directory to watch recursively for External NLE video or HLS exports.' },
        output_directory: { type: 'string', description: 'Alias for outputDirectory.' },
        watchDirectory: { type: 'string', description: 'Alias for outputDirectory.' },
        watch_directory: { type: 'string', description: 'Alias for watchDirectory.' },
        exportDirectory: { type: 'string', description: 'Alias for outputDirectory.' },
        export_directory: { type: 'string', description: 'Alias for exportDirectory.' },
        timeoutMs: { type: 'number', description: 'Optional maximum watch lifetime in milliseconds. Omit to keep watching while the daemon is running.' },
        timeout_ms: { type: 'number', description: 'Alias for timeoutMs.' },
        pollIntervalMs: { type: 'number', description: 'Polling interval in milliseconds for the background watch.' },
        poll_interval_ms: { type: 'number', description: 'Alias for pollIntervalMs.' },
        manifestPath: { type: 'string', description: 'Explicit HLS manifest path to wait for.' },
        manifest_path: { type: 'string', description: 'Alias for manifestPath.' },
        hlsManifestPath: { type: 'string', description: 'Alias for manifestPath.' },
        hls_manifest_path: { type: 'string', description: 'Alias for hlsManifestPath.' },
        hlsDirectory: { type: 'string' },
        hls_directory: { type: 'string' },
        segmentPaths: { type: 'array', items: { type: 'string' } },
        segment_paths: { type: 'array', items: { type: 'string' } },
        outputKind: { type: 'string' },
        output_kind: { type: 'string' },
        exchangeProjectPath: { type: 'string', description: 'External NLE exchange project file used for handoff provenance.' },
        exchange_project_path: { type: 'string', description: 'Alias for exchangeProjectPath.' },
        externalApp: { type: 'string', description: 'External editor app, such as final_cut_pro, premiere, or davinci_resolve.' },
        external_app: { type: 'string', description: 'Alias for externalApp.' },
        externalNle: { type: 'string', description: 'Alias for externalApp.' },
        external_nle: { type: 'string', description: 'Alias for externalNle.' },
        reviewer: { type: 'string' },
        reviewStatus: { type: 'string' },
        review_status: { type: 'string' },
        provenance: { type: 'object', additionalProperties: true },
        metadata: { type: 'object', additionalProperties: true },
        params: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_result_watch_get',
      description: 'Read one Media Pipeline result watch by watchId.',
      inputSchema: objectSchema({
        ...projectLocator,
        watchId: { type: 'string' },
        watch_id: { type: 'string' },
      }),
    },
    {
      name: 'editing_result_watch_list',
      description: 'List Media Pipeline result watches by mediaProjectId, taskId, resultId, backend, or status.',
      inputSchema: objectSchema({
        ...projectLocator,
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        resultId: { type: 'string' },
        result_id: { type: 'string' },
        backend: { type: 'string' },
        status: { type: 'string' },
        limit: { type: 'number' },
      }),
    },
    {
      name: 'editing_result_watch_cancel',
      description: 'Cancel a daemon-owned Media Pipeline result watch. Canceling does not delete any already registered result.',
      inputSchema: objectSchema({
        ...projectLocator,
        watchId: { type: 'string' },
        watch_id: { type: 'string' },
      }),
    },
    {
      name: 'editing_external_nle_open',
      description: 'Open an External NLE exchange project file in the local OS or a named NLE application. This only launches the handoff for human editing; it does not watch results, upload artifacts, create candidates, adopt, or select.',
      inputSchema: objectSchema({
        ...projectLocator,
        exchangeProjectPath: { type: 'string', description: 'External NLE exchange project file to open, such as FCPXML, OTIO JSON, or EDL.' },
        exchange_project_path: { type: 'string', description: 'Alias for exchangeProjectPath.' },
        projectPath: { type: 'string', description: 'Alias for exchangeProjectPath.' },
        project_path: { type: 'string', description: 'Alias for projectPath.' },
        path: { type: 'string', description: 'Alias for exchangeProjectPath.' },
        externalApp: { type: 'string', description: 'External editor app id or display name, such as final_cut_pro, premiere, or davinci_resolve.' },
        external_app: { type: 'string', description: 'Alias for externalApp.' },
        externalNle: { type: 'string', description: 'Alias for externalApp.' },
        external_nle: { type: 'string', description: 'Alias for externalNle.' },
        appName: { type: 'string', description: 'Explicit local application display name, such as Final Cut Pro.' },
        app_name: { type: 'string', description: 'Alias for appName.' },
        application: { type: 'string', description: 'Alias for appName.' },
        applicationName: { type: 'string', description: 'Alias for appName.' },
        application_name: { type: 'string', description: 'Alias for applicationName.' },
        dryRun: { type: 'boolean', description: 'Return the opener command without launching the local application.' },
        dry_run: { type: 'boolean', description: 'Alias for dryRun.' },
        platform: { type: 'string', description: 'Optional platform override for diagnostics/tests.' },
      }),
    },
    {
      name: 'editing_result_get',
      description: 'Read one Media Pipeline render/export result by resultId. This is the CLI/MCP observation path after task completion or external backend import.',
      inputSchema: objectSchema({
        ...projectLocator,
        resultId: { type: 'string' },
        result_id: { type: 'string' },
      }),
    },
    {
      name: 'editing_result_list',
      description: 'List Media Pipeline render/export results by mediaProjectId, taskId, backend, kind, or status. This is used by render result recovery flows.',
      inputSchema: objectSchema({
        ...projectLocator,
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        backend: { type: 'string' },
        kind: { type: 'string' },
        outputKind: { type: 'string' },
        output_kind: { type: 'string' },
        status: { type: 'string' },
        limit: { type: 'number' },
      }),
    },
    {
      name: 'editing_export_import_resource',
      description: 'Upload a completed local editing export as a RawResource, optionally recording derivative provenance. This does not adopt or select the result. When resolving a completed Electron task by taskId, pass mediaProjectId for persisted workspace output recovery. HLS manifests must use editing_export_publish_hls so manifest and segment files are hosted as a MediaStreamArtifact instead of one RawResource.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        resultId: { type: 'string', description: 'Media Pipeline result registry id. When provided, output path and metadata are resolved from movscript.media.pipeline before the explicit import gate runs.' },
        result_id: { type: 'string', description: 'Alias for resultId.' },
        result: { type: 'object', additionalProperties: true, description: 'Inline Media Pipeline result object for offline/debug workflows.' },
        mediaProjectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task output recovery.' },
        media_project_id: { type: 'string', description: 'Alias for mediaProjectId.' },
        projectId: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
        project_id: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
        outputPath: { type: 'string' },
        output_path: { type: 'string' },
        filename: { type: 'string' },
        mimeType: { type: 'string' },
        mime_type: { type: 'string' },
        folderId: { type: ['string', 'number'] },
        folder_id: { type: ['string', 'number'] },
        derivative: { type: 'object', additionalProperties: true },
        operation: { type: 'string' },
        tool: { type: 'string' },
        inputResourceIds: { type: 'array', items: { type: ['string', 'number'] } },
        input_resource_ids: { type: 'array', items: { type: ['string', 'number'] } },
        sourceResourceId: { type: ['string', 'number'] },
        source_resource_id: { type: ['string', 'number'] },
        sourceResourceIds: { type: 'array', items: { type: ['string', 'number'] } },
        source_resource_ids: { type: 'array', items: { type: ['string', 'number'] } },
        params: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_export_save_local',
      description: 'Save a completed Electron editing export to an explicit local file path, save a complete HLS bundle to a local directory, or return/validate an existing local export path. When resolving by taskId, pass mediaProjectId for persisted workspace output recovery. This does not upload or create candidates.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        resultId: { type: 'string', description: 'Media Pipeline result registry id. When provided without savePath/saveDirectory, this returns a local result confirmation and does not require Electron runtime.' },
        result_id: { type: 'string', description: 'Alias for resultId.' },
        result: { type: 'object', additionalProperties: true, description: 'Inline Media Pipeline result object for offline/debug workflows.' },
        mediaProjectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task output recovery.' },
        media_project_id: { type: 'string', description: 'Alias for mediaProjectId.' },
        projectId: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
        project_id: { type: 'string', description: 'Deprecated alias for mediaProjectId.' },
        outputPath: { type: 'string' },
        output_path: { type: 'string' },
        savePath: { type: 'string' },
        save_path: { type: 'string' },
        saveDirectory: { type: 'string' },
        save_directory: { type: 'string' },
        hlsDirectory: { type: 'string' },
        hls_directory: { type: 'string' },
        segmentPaths: { type: 'array', items: { type: 'string' } },
        segment_paths: { type: 'array', items: { type: 'string' } },
        filename: { type: 'string' },
      }),
    },
    {
      name: 'editing_export_publish_hls',
      description: 'Upload completed HLS manifest/segments as a MediaStreamArtifact. When resolving a completed Electron HLS task by taskId, pass mediaProjectId for persisted workspace output recovery.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        resultId: { type: 'string', description: 'Media Pipeline result registry id. HLS manifest and segment fields are resolved before the explicit publish gate runs.' },
        result_id: { type: 'string', description: 'Alias for resultId.' },
        result: { type: 'object', additionalProperties: true, description: 'Inline Media Pipeline result object for offline/debug workflows.' },
        manifestPath: { type: 'string' },
        manifest_path: { type: 'string' },
        segmentPaths: { type: 'array', items: { type: 'string' } },
        segment_paths: { type: 'array', items: { type: 'string' } },
        title: { type: 'string' },
        mediaProjectId: { type: ['string', 'number'], description: 'Media workspace project id used with taskId for persisted task output recovery.' },
        media_project_id: { type: ['string', 'number'], description: 'Alias for mediaProjectId.' },
        projectId: { type: ['string', 'number'], description: 'Deprecated alias for mediaProjectId.' },
        project_id: { type: ['string', 'number'], description: 'Deprecated alias for mediaProjectId.' },
        sourceResourceId: { type: ['string', 'number'] },
        source_resource_id: { type: ['string', 'number'] },
        sourceDerivativeId: { type: ['string', 'number'] },
        source_derivative_id: { type: ['string', 'number'] },
        durationMs: { type: 'number' },
        duration_ms: { type: 'number' },
        width: { type: 'number' },
        height: { type: 'number' },
      }),
    },
    {
      name: 'editing_export_create_candidate',
      description: 'Explicitly write an exported editing result as a content candidate. RawResource outputs use resourceId/resource_id; HLS MediaStreamArtifact outputs use streamId/stream_id and become hls_stream candidate outputs. This is separate from render/export success and does not adopt/select the candidate.',
      inputSchema: objectSchema({
        ...projectLocator,
        contentUnitId: { type: ['string', 'number'] },
        content_unit_id: { type: ['string', 'number'] },
        resourceId: { type: ['string', 'number'] },
        resource_id: { type: ['string', 'number'] },
        streamId: { type: ['string', 'number'], description: 'HLS MediaStreamArtifact id for explicit hls_stream candidate creation.' },
        stream_id: { type: ['string', 'number'], description: 'Alias for streamId.' },
        candidateId: { type: ['string', 'number'] },
        candidate_id: { type: ['string', 'number'] },
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        resultId: { type: 'string', description: 'Media Pipeline result registry id. Result fields can populate output path, HLS stream/resource id, producer metadata, and prompt snapshot for the explicit candidate gate.' },
        result_id: { type: 'string', description: 'Alias for resultId.' },
        result: { type: 'object', additionalProperties: true, description: 'Inline Media Pipeline result object for offline/debug workflows.' },
        editingProjectId: { type: 'string' },
        editing_project_id: { type: 'string' },
        outputPath: { type: 'string' },
        output_path: { type: 'string' },
        manifestPath: { type: 'string' },
        manifest_path: { type: 'string' },
        hlsDirectory: { type: 'string' },
        hls_directory: { type: 'string' },
        segmentPaths: { type: 'array', items: { type: 'string' } },
        segment_paths: { type: 'array', items: { type: 'string' } },
        outputKind: { type: 'string' },
        output_kind: { type: 'string' },
        kind: { type: 'string' },
        mimeType: { type: 'string' },
        mime_type: { type: 'string' },
        durationMs: { type: 'number' },
        duration_ms: { type: 'number' },
        durationSec: { type: 'number' },
        duration_sec: { type: 'number' },
        width: { type: 'number' },
        height: { type: 'number' },
        source: { type: 'string' },
        status: { type: 'string' },
        params: { type: 'object', additionalProperties: true },
        producer: { type: 'object', additionalProperties: true },
        provenance: { type: 'object', additionalProperties: true },
        promptSnapshot: { type: 'object', additionalProperties: true },
        prompt_snapshot: { type: 'object', additionalProperties: true },
      }),
    },
  ]
}
