import type { MCPTool } from '../../protocol/types'
import { objectSchema } from '../schema'

const projectLocator = {
  projectId: { type: ['string', 'number'], description: 'MovScript project id.' },
  project_id: { type: ['string', 'number'], description: 'Alias for projectId.' },
}

const editingProjectInput = {
  editingProject: { type: 'object', additionalProperties: true, description: 'MediaEditingProject object.' },
  editing_project: { type: 'object', additionalProperties: true, description: 'Alias for editingProject.' },
  project: { type: 'object', additionalProperties: true, description: 'Alias for editingProject.' },
}

export function editingTools(): MCPTool[] {
  return [
    {
      name: 'editing_project_create',
      description: 'Create an empty MovScript media editing project. When an editing project store is available, the project is persisted immediately; otherwise the returned editing_project can be saved with editing_project_save. This does not render media or write content candidates.',
      inputSchema: objectSchema({
        title: { type: 'string' },
        width: { type: 'number' },
        height: { type: 'number' },
        fps: { type: 'number' },
        background: { type: 'string' },
      }),
    },
    {
      name: 'editing_project_create_from_edit_plan',
      description: 'Create a MediaEditingProject from a MovScript edit_plan. When an editing project store is available, the project is persisted immediately; otherwise the returned editing_project can be saved with editing_project_save. This is the main handoff from domain planning into the dedicated editing tool family.',
      inputSchema: objectSchema({
        editPlan: { type: 'object', additionalProperties: true, description: 'MovScript edit_plan artifact.' },
        edit_plan: { type: 'object', additionalProperties: true, description: 'Alias for editPlan.' },
        title: { type: 'string' },
        width: { type: 'number' },
        height: { type: 'number' },
        fps: { type: 'number' },
        background: { type: 'string' },
        defaultDurationMs: { type: 'number' },
        default_duration_ms: { type: 'number' },
      }),
    },
    {
      name: 'editing_project_get',
      description: 'Read a persisted MediaEditingProject by id. Editing projects are stored in the standalone editing project store. Requires the Electron editing runtime or a future backend project store.',
      inputSchema: objectSchema({ editingProjectId: { type: 'string' }, editing_project_id: { type: 'string' } }),
    },
    {
      name: 'editing_project_update_settings',
      description: 'Update MediaEditingProject settings such as title, fps, canvas size, background, and workspace binding. This mutates project data only.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        title: { type: 'string' },
        width: { type: 'number' },
        height: { type: 'number' },
        fps: { type: 'number' },
        background: { type: 'string' },
        workspace: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_project_add_asset',
      description: 'Add a RawResource, generated resource, local file, or bytes-backed source to a MediaEditingProject asset registry.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        asset: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_project_remove_asset',
      description: 'Remove an unused asset reference from a MediaEditingProject asset registry. Fails if any clip still references the asset.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        assetId: { type: 'string' },
        asset_id: { type: 'string' },
      }),
    },
    {
      name: 'editing_project_save',
      description: 'Persist a MediaEditingProject revision. Pass expectedRevision for optimistic locking against the last revision read. Requires the Electron editing runtime or a future backend project store.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        expectedRevision: { type: 'number', description: 'Last persisted revision observed before editing. Save returns conflict if the stored revision changed.' },
        expected_revision: { type: 'number', description: 'Alias for expectedRevision.' },
      }),
    },
    {
      name: 'editing_timeline_apply_commands',
      description: 'Apply MovScript media timeline commands to a MediaEditingProject. This modifies the editing project only; it does not render media or create candidates.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        commands: { type: 'array', items: { type: 'object', additionalProperties: true } },
        command: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_timeline_add_track',
      description: 'Add a video, image, audio, text, subtitle, or effect track to a MediaEditingProject timeline.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        track: { type: 'object', additionalProperties: true },
        trackId: { type: 'string' },
        track_id: { type: 'string' },
        type: { type: 'string' },
        trackType: { type: 'string' },
        track_type: { type: 'string' },
        name: { type: 'string' },
        zIndex: { type: 'number' },
        z_index: { type: 'number' },
      }),
    },
    {
      name: 'editing_timeline_remove_track',
      description: 'Remove an empty track from a MediaEditingProject timeline.',
      inputSchema: objectSchema({ ...editingProjectInput, trackId: { type: 'string' }, track_id: { type: 'string' } }),
    },
    {
      name: 'editing_timeline_add_clip',
      description: 'Place an asset-backed or text clip onto a timeline track.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        trackId: { type: 'string' },
        track_id: { type: 'string' },
        clip: { type: 'object', additionalProperties: true },
        assetId: { type: 'string' },
        asset_id: { type: 'string' },
        assetType: { type: 'string' },
        asset_type: { type: 'string' },
        timelineStartMs: { type: 'number' },
        timeline_start_ms: { type: 'number' },
        durationMs: { type: 'number' },
        duration_ms: { type: 'number' },
      }),
    },
    {
      name: 'editing_timeline_update_clip',
      description: 'Update trim, duration, placement, volume, fit, style, or metadata for an existing timeline clip.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        clipId: { type: 'string' },
        clip_id: { type: 'string' },
        patch: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_timeline_split_clip',
      description: 'Split a timeline clip at an absolute timeline timestamp.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        clipId: { type: 'string' },
        clip_id: { type: 'string' },
        splitTimeMs: { type: 'number' },
        split_time_ms: { type: 'number' },
        retainSide: { type: 'string' },
        retain_side: { type: 'string' },
      }),
    },
    {
      name: 'editing_timeline_move_clip',
      description: 'Move a timeline clip to a new timestamp and optionally to another compatible track.',
      inputSchema: objectSchema({
        ...editingProjectInput,
        clipId: { type: 'string' },
        clip_id: { type: 'string' },
        targetTrackId: { type: 'string' },
        target_track_id: { type: 'string' },
        timelineStartMs: { type: 'number' },
        timeline_start_ms: { type: 'number' },
      }),
    },
    {
      name: 'editing_timeline_delete_clip',
      description: 'Delete a clip from a MediaEditingProject timeline.',
      inputSchema: objectSchema({ ...editingProjectInput, clipId: { type: 'string' }, clip_id: { type: 'string' } }),
    },
    {
      name: 'editing_timeline_validate',
      description: 'Validate a MediaEditingProject timeline for missing assets, invalid timing, track mismatch, and unsupported clip settings.',
      inputSchema: objectSchema({ ...editingProjectInput }),
    },
    {
      name: 'editing_runtime_capabilities_get',
      description: 'Read Electron mediaPipeline runtime capabilities such as FFmpeg availability, version, supported task types, project store, and local HLS preview support. This does not start a task.',
      inputSchema: objectSchema({}),
    },
    {
      name: 'editing_task_render_create',
      description: 'Create an Electron mediaPipeline timeline_render task for a MediaEditingProject. Rendering runs in Electron, not in the backend.',
      inputSchema: objectSchema({ ...projectLocator, ...editingProjectInput, output: { type: 'object', additionalProperties: true } }),
    },
    {
      name: 'editing_task_hls_create',
      description: 'Create an Electron mediaPipeline timeline_hls task. HLS packaging, including optional output.hlsVariants adaptive renditions, runs in Electron; backend only hosts uploaded artifacts.',
      inputSchema: objectSchema({ ...projectLocator, ...editingProjectInput, output: { type: 'object', additionalProperties: true } }),
    },
    {
      name: 'editing_task_transcode_create',
      description: 'Create an Electron mediaPipeline media_transcode task. Pass projectId so the task is stored in the correct Electron media workspace.',
      inputSchema: objectSchema({ ...projectLocator, source: { type: 'object', additionalProperties: true }, output: { type: 'object', additionalProperties: true } }),
    },
    {
      name: 'editing_task_reframe_create',
      description: 'Create an Electron mediaPipeline media_reframe task for mechanical crop/contain/pad reframe. Pass projectId so the task is stored in the correct Electron media workspace.',
      inputSchema: objectSchema({ ...projectLocator, source: { type: 'object', additionalProperties: true }, output: { type: 'object', additionalProperties: true }, target: { type: 'string' }, mode: { type: 'string' } }),
    },
    {
      name: 'editing_task_get',
      description: 'Read an Electron mediaPipeline task state. Pass projectId with taskId for persisted workspace recovery after app restart.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        projectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task recovery.' },
        project_id: { type: 'string', description: 'Alias for projectId.' },
      }),
    },
    {
      name: 'editing_task_cancel',
      description: 'Cancel an Electron mediaPipeline task. Pass projectId with taskId so Electron can recover persisted task state and write a clear cancel diagnostic after app restart.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        projectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task recovery.' },
        project_id: { type: 'string', description: 'Alias for projectId.' },
      }),
    },
    {
      name: 'editing_task_logs_get',
      description: 'Read FFmpeg/task logs for an Electron mediaPipeline task. Pass projectId with taskId for persisted workspace log recovery after app restart.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        projectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task log recovery.' },
        project_id: { type: 'string', description: 'Alias for projectId.' },
      }),
    },
    {
      name: 'editing_export_import_resource',
      description: 'Upload a completed local editing export as a RawResource, optionally recording derivative provenance. This does not adopt or select the result. When resolving a completed Electron task by taskId, pass projectId for persisted workspace output recovery. HLS manifests must use editing_export_publish_hls so manifest and segment files are hosted as a MediaStreamArtifact instead of one RawResource.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        projectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task output recovery.' },
        project_id: { type: 'string', description: 'Alias for projectId.' },
        outputPath: { type: 'string' },
        output_path: { type: 'string' },
        filename: { type: 'string' },
        mimeType: { type: 'string' },
        mime_type: { type: 'string' },
        folderId: { type: ['string', 'number'] },
        folder_id: { type: ['string', 'number'] },
        derivative: { type: 'object', additionalProperties: true },
        operation: { type: 'string' },
        tool: { type: 'string' },
        inputResourceIds: { type: 'array', items: { type: ['string', 'number'] } },
        input_resource_ids: { type: 'array', items: { type: ['string', 'number'] } },
        sourceResourceId: { type: ['string', 'number'] },
        source_resource_id: { type: ['string', 'number'] },
        sourceResourceIds: { type: 'array', items: { type: ['string', 'number'] } },
        source_resource_ids: { type: 'array', items: { type: ['string', 'number'] } },
        params: { type: 'object', additionalProperties: true },
      }),
    },
    {
      name: 'editing_export_save_local',
      description: 'Save a completed Electron editing export to an explicit local file path, save a complete HLS bundle to a local directory, or return/validate an existing local export path. When resolving by taskId, pass projectId for persisted workspace output recovery. This does not upload or create candidates.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        projectId: { type: 'string', description: 'Media workspace project id used with taskId for persisted task output recovery.' },
        project_id: { type: 'string', description: 'Alias for projectId.' },
        outputPath: { type: 'string' },
        output_path: { type: 'string' },
        savePath: { type: 'string' },
        save_path: { type: 'string' },
        saveDirectory: { type: 'string' },
        save_directory: { type: 'string' },
        hlsDirectory: { type: 'string' },
        hls_directory: { type: 'string' },
        segmentPaths: { type: 'array', items: { type: 'string' } },
        segment_paths: { type: 'array', items: { type: 'string' } },
        filename: { type: 'string' },
      }),
    },
    {
      name: 'editing_export_publish_hls',
      description: 'Upload completed HLS manifest/segments as a MediaStreamArtifact. When resolving a completed Electron HLS task by taskId, pass projectId for persisted workspace output recovery.',
      inputSchema: objectSchema({
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        manifestPath: { type: 'string' },
        manifest_path: { type: 'string' },
        segmentPaths: { type: 'array', items: { type: 'string' } },
        segment_paths: { type: 'array', items: { type: 'string' } },
        title: { type: 'string' },
        projectId: { type: ['string', 'number'] },
        project_id: { type: ['string', 'number'] },
        sourceResourceId: { type: ['string', 'number'] },
        source_resource_id: { type: ['string', 'number'] },
        sourceDerivativeId: { type: ['string', 'number'] },
        source_derivative_id: { type: ['string', 'number'] },
        durationMs: { type: 'number' },
        duration_ms: { type: 'number' },
        width: { type: 'number' },
        height: { type: 'number' },
      }),
    },
    {
      name: 'editing_export_create_candidate',
      description: 'Explicitly write an exported RawResource-backed editing result as a content candidate. This is separate from render/export success. HLS MediaStreamArtifact outputs are hosted previews today; writing them as candidates requires a future domain candidate schema extension.',
      inputSchema: objectSchema({
        ...projectLocator,
        contentUnitId: { type: ['string', 'number'] },
        content_unit_id: { type: ['string', 'number'] },
        resourceId: { type: ['string', 'number'] },
        resource_id: { type: ['string', 'number'] },
        streamId: { type: ['string', 'number'], description: 'Known unsupported HLS MediaStreamArtifact ID. Current candidate outputs require resourceId/resource_id.' },
        stream_id: { type: ['string', 'number'], description: 'Alias for streamId.' },
        candidateId: { type: ['string', 'number'] },
        candidate_id: { type: ['string', 'number'] },
        taskId: { type: 'string' },
        task_id: { type: 'string' },
        editingProjectId: { type: 'string' },
        editing_project_id: { type: 'string' },
        outputPath: { type: 'string' },
        output_path: { type: 'string' },
        outputKind: { type: 'string' },
        output_kind: { type: 'string' },
        kind: { type: 'string' },
        mimeType: { type: 'string' },
        mime_type: { type: 'string' },
        durationMs: { type: 'number' },
        duration_ms: { type: 'number' },
        durationSec: { type: 'number' },
        duration_sec: { type: 'number' },
        width: { type: 'number' },
        height: { type: 'number' },
        source: { type: 'string' },
        status: { type: 'string' },
        producer: { type: 'object', additionalProperties: true },
        provenance: { type: 'object', additionalProperties: true },
        promptSnapshot: { type: 'object', additionalProperties: true },
        prompt_snapshot: { type: 'object', additionalProperties: true },
      }),
    },
  ]
}
