import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('agent chat UI owns a provider-neutral protocol and adapts Codex at the boundary', () => {
  const uiProtocol = readFileSync(resolve('src/features/agent/domain/agentChatProtocol.ts'), 'utf8')
  const dataSourceShell = readFileSync(resolve('src/features/agent/components/AgentChatDataSourceShell.tsx'), 'utf8')
  const unifiedShell = readFileSync(resolve('src/features/agent/components/AgentUnifiedChatShell.tsx'), 'utf8')
  const codexShell = readFileSync(resolve('src/features/agent/components/CodexThreadChatShell.tsx'), 'utf8')
  const movscriptShell = readFileSync(resolve('src/features/agent/components/MovScriptAgentChatShell.tsx'), 'utf8')
  const codexAdapter = readFileSync(resolve('src/shared/infrastructure/codex-app-server/codexAgentChatProtocolAdapter.ts'), 'utf8')
  const codexDataSource = readFileSync(resolve('src/shared/infrastructure/codex-app-server/codexAgentChatDataSource.ts'), 'utf8')
  const codexRpcClient = readFileSync(resolve('src/shared/infrastructure/codex-app-server/codexAppServerRpcClient.ts'), 'utf8')
  const codexAppServerIpc = readFileSync(resolve('electron/ipc/codexAppServerIpc.ts'), 'utf8')
  const agentConsolePage = readFileSync(resolve('src/features/agent/components/AgentConsolePage.tsx'), 'utf8')
  const agentProviderConfigStore = readFileSync(resolve('src/features/agent/state/agentProviderConfigStore.ts'), 'utf8')
  const capabilityProbe = readFileSync(resolve('src/features/agent/application/agentChatCapabilityProbe.ts'), 'utf8')
  const movscriptAdapter = readFileSync(resolve('src/shared/infrastructure/local-agent-client/movscriptAgentChatProtocolAdapter.ts'), 'utf8')
  const movscriptDataSource = readFileSync(resolve('src/shared/infrastructure/local-agent-client/movscriptAgentChatDataSource.ts'), 'utf8')
  const dataSourceFactory = readFileSync(resolve('src/features/agent/application/agentChatDataSourceFactory.ts'), 'utf8')

  assert.match(uiProtocol, /export interface AgentChatThread/)
  assert.match(uiProtocol, /export type AgentChatThreadItem/)
  assert.match(uiProtocol, /export interface AgentChatNotification/)
  assert.match(uiProtocol, /type: 'threadLifecycle'/)
  assert.match(uiProtocol, /type: 'serverRequestResolved'/)
  assert.match(uiProtocol, /type: 'realtime'/)
  assert.match(uiProtocol, /type: 'systemNotice'/)
  assert.match(uiProtocol, /export interface AgentChatServerRequest/)
  assert.match(uiProtocol, /export type AgentChatServerRequestResponse/)
  assert.match(uiProtocol, /export type AgentChatServerRequestHandler/)
  assert.match(uiProtocol, /export interface AgentChatDataSource/)
  assert.match(uiProtocol, /renameThread\?\(input: \{ threadId: string; name: string \}/)
  assert.match(uiProtocol, /archiveThread\?\(input: \{ threadId: string \}/)
  assert.match(uiProtocol, /unarchiveThread\?\(input: \{ threadId: string \}/)
  assert.match(uiProtocol, /deleteThread\?\(input: \{ threadId: string \}/)
  assert.match(uiProtocol, /startTurn\?\(input: \{ threadId: string; inputs: AgentChatInput\[\]/)
  assert.match(uiProtocol, /steerTurn\?\(input: \{ threadId: string; turnId: string; inputs: AgentChatInput\[\]/)
  assert.match(uiProtocol, /interruptTurn\?\(input: \{ threadId: string; turnId: string; reason\?: string/)
  assert.match(uiProtocol, /export interface AgentChatCapabilities/)
  assert.match(uiProtocol, /deltaBase64/)
  assert.match(uiProtocol, /sourcePath/)
  assert.match(uiProtocol, /destinationPath/)
  assert.match(uiProtocol, /interface AgentChatRealtimeCapability[\s\S]*listVoices\?/)
  assert.match(uiProtocol, /interface AgentChatRealtimeCapability[\s\S]*appendAudio/)
  assert.match(uiProtocol, /interface AgentChatRealtimeCapability[\s\S]*appendText/)
  assert.doesNotMatch(uiProtocol, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)

  assert.match(dataSourceShell, /type AgentChatThread/)
  assert.match(dataSourceShell, /type AgentChatThreadItem/)
  assert.match(dataSourceShell, /type AgentChatDataSource/)
  assert.match(dataSourceShell, /AgentConversationListPanel/)
  assert.match(dataSourceShell, /AgentConversationTabsPanel/)
  assert.match(dataSourceShell, /AgentChatMessage/)
  assert.match(dataSourceShell, /AgentComposerSection/)
  assert.match(dataSourceShell, /useAgentComposerController/)
  assert.match(dataSourceShell, /useAgentMentionEditorSync/)
  assert.match(dataSourceShell, /inputRef=\{composerInputRef\}/)
  assert.match(dataSourceShell, /onInputChange=\{\(nextInput\) => composer\.updateWorkspace\(\{ input: nextInput \}\)\}/)
  assert.match(dataSourceShell, /agentChatInputsFromComposer/)
  assert.match(dataSourceShell, /attachmentDisplayUrl/)
  assert.match(dataSourceShell, /dataSource\.startTurn/)
  assert.match(dataSourceShell, /dataSource\.steerTurn/)
  assert.match(dataSourceShell, /dataSource\.interruptTurn/)
  assert.match(dataSourceShell, /dataSource\?\.renameThread/)
  assert.match(dataSourceShell, /dataSource\?\.archiveThread/)
  assert.match(dataSourceShell, /onRename: \(name: string\) => void renameThread/)
  assert.match(dataSourceShell, /onArchive: \(\) => void archiveThread/)
  assert.match(dataSourceShell, /canStopLocalRun=\{canStopActiveTurn\}/)
  assert.match(dataSourceShell, /notification\.method === 'thread\/started'/)
  assert.match(dataSourceShell, /notification\.method === 'thread\/status\/changed'/)
  assert.match(dataSourceShell, /notification\.method === 'thread\/name\/updated'/)
  assert.match(dataSourceShell, /applyAgentChatNotificationEvent\(notification\.event/)
  assert.match(dataSourceShell, /event\.type === 'threadLifecycle'/)
  assert.match(dataSourceShell, /event\.type === 'serverRequestResolved'/)
  assert.match(dataSourceShell, /setPendingServerRequests/)
  assert.match(dataSourceShell, /notification\.method === 'item\/plan\/delta'/)
  assert.match(dataSourceShell, /item\/reasoning\/textDelta/)
  assert.match(dataSourceShell, /command\/exec\/outputDelta/)
  assert.match(dataSourceShell, /item\/fileChange\/outputDelta/)
  assert.match(dataSourceShell, /appendDeltaTurnItem/)
  assert.match(dataSourceShell, /showAttachmentTools/)
  assert.match(dataSourceShell, /showDebugPreview=\{false\}/)
  assert.match(dataSourceShell, /showMentionTools/)
  assert.match(dataSourceShell, /AgentThreadFill/)
  assert.match(dataSourceShell, /pendingServerRequests/)
  assert.match(dataSourceShell, /agentChatApproveResponse/)
  assert.match(dataSourceShell, /agentChatRejectResponse/)
  assert.match(dataSourceShell, /action: 'approve'/)
  assert.match(dataSourceShell, /action: 'reject'/)
  assert.doesNotMatch(dataSourceShell, /decision: 'accept'|decision: 'decline'/)
  assert.match(dataSourceShell, /item\.type === 'fileChange'/)
  assert.match(dataSourceShell, /item\.type === 'webSearch'/)
  assert.match(dataSourceShell, /item\.type === 'imageView'/)
  assert.match(dataSourceShell, /item\.type === 'reviewMode'/)
  assert.match(dataSourceShell, /item\.type === 'contextCompaction'/)
  assert.match(dataSourceShell, /item\.type === 'unknown'/)
  assert.doesNotMatch(dataSourceShell, /AgentComposerField|AgentChatDataSourceComposer/)
  assert.doesNotMatch(dataSourceShell, /grid-cols-\[240px/)
  assert.doesNotMatch(dataSourceShell, /rounded-md bg-primary/)
  assert.doesNotMatch(dataSourceShell, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)

  assert.match(codexShell, /<AgentChatDataSourceShell/)
  assert.doesNotMatch(codexShell, /codexAppServerProtocol/)
  assert.doesNotMatch(codexShell, /codexAgentChatProtocolAdapter/)
  assert.doesNotMatch(codexShell, /type CodexThread|type CodexTurn|type CodexThreadItem/)
  assert.match(movscriptShell, /<AgentChatDataSourceShell/)
  assert.doesNotMatch(unifiedShell, /AgentBuiltinChatShell/)

  assert.match(codexAdapter, /codexAppServerProtocol/)
  assert.match(codexAdapter, /agentChatThreadFromCodex/)
  assert.match(codexAdapter, /agentChatThreadItemFromCodex/)
  assert.match(codexAdapter, /thread\/started/)
  assert.match(codexAdapter, /thread\/status\/changed/)
  assert.match(codexAdapter, /thread\/archived/)
  assert.match(codexAdapter, /serverRequest\/resolved/)
  assert.match(codexAdapter, /thread\/realtime\//)
  assert.match(codexAdapter, /account\/updated/)
  assert.match(codexAdapter, /mcpServer\/startupStatus\/updated/)
  assert.match(codexAdapter, /configWarning/)
  assert.match(codexAdapter, /codexServerRequestResponseFromAgentChat/)
  assert.match(codexAdapter, /decision: response\.action === 'approve' \? 'accept' : 'decline'/)
  assert.match(codexDataSource, /command\/exec/)
  assert.match(codexDataSource, /codexUserInputFromAgentChat/)
  assert.match(codexDataSource, /client\.startTurn/)
  assert.match(codexDataSource, /client\.steerTurn/)
  assert.match(codexDataSource, /client\.interruptTurn/)
  assert.match(codexDataSource, /thread\/name\/set/)
  assert.match(codexDataSource, /thread\/archive/)
  assert.match(codexDataSource, /thread\/unarchive/)
  assert.match(codexDataSource, /fs\/readFile/)
  assert.match(codexDataSource, /mcpServer\/tool\/call/)
  assert.match(codexDataSource, /plugin\/list/)
  assert.match(codexDataSource, /skills\/list/)
  assert.match(codexDataSource, /model\/list/)
  assert.match(codexDataSource, /config\/read/)
  assert.match(codexDataSource, /account\/read/)
  assert.match(codexDataSource, /permissionProfile\/list/)
  assert.match(codexDataSource, /thread\/realtime\/start/)
  assert.match(codexDataSource, /thread\/realtime\/appendAudio/)
  assert.match(codexDataSource, /thread\/realtime\/appendText/)
  assert.match(codexDataSource, /thread\/realtime\/stop/)
  assert.match(codexDataSource, /thread\/realtime\/listVoices/)
  assert.match(codexDataSource, /Promise\.resolve\(onServerRequest\?\.\(nextRequest\)\)/)
  assert.match(codexDataSource, /codexServerRequestResponseFromAgentChat/)
  assert.doesNotMatch(codexRpcClient, /resolvedProvider\.[\s\S]{0,80}endpoint/)
  assert.match(codexAppServerIpc, /CODEX_AGENT_RUNTIME_DIR_NAME/)
  assert.match(codexAppServerIpc, /resolveAgentWorkspaceRuntimePaths/)
  assert.doesNotMatch(codexAppServerIpc, /lifecycle === 'attached'|profile\?\.endpoint/)
  assert.doesNotMatch(agentConsolePage, /只连接已有|已有服务 endpoint|endpoint 必须/)
  assert.match(agentConsolePage, /CODEX_HOME 由 MovScript 管理/)
  assert.doesNotMatch(agentConsolePage, /Profile ID/)
  assert.doesNotMatch(agentConsolePage, /~\/\.codex/)
  assert.match(agentProviderConfigStore, /MOVSCRIPT_MANAGED_CODEX_HOME = '\.movscript\/\.codex'/)
  assert.match(agentProviderConfigStore, /function normalizedCodexProfileId/)
  assert.match(agentProviderConfigStore, /return CODEX_MOVSCRIPT_HOME_PROFILE_ID/)
  assert.match(agentProviderConfigStore, /function managedCodexHome/)
  assert.match(agentProviderConfigStore, /trimmed === '~\/\.codex'/)
  assert.match(agentConsolePage, /AgentCapabilityProbePanel/)
  assert.match(agentConsolePage, /createAgentChatDataSourceForProvider\(provider\)/)
  assert.match(agentConsolePage, /probeAgentChatDataSourceCapabilities/)
  assert.doesNotMatch(agentConsolePage, /requestProtocol\(|codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.match(capabilityProbe, /AgentChatDataSource/)
  assert.match(capabilityProbe, /capabilities\?\.command\?\.exec/)
  assert.match(capabilityProbe, /capabilities\?\.fs\?\.readFile/)
  assert.match(capabilityProbe, /mcpServerStatus\/list/)
  assert.match(capabilityProbe, /thread\/realtime\/listVoices/)
  assert.doesNotMatch(capabilityProbe, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)

  assert.match(movscriptAdapter, /agentChatThreadFromMovScriptAgent/)
  assert.match(movscriptAdapter, /agentChatNotificationFromMovScriptRuntimeEvent/)
  assert.match(movscriptAdapter, /agentChatServerRequestsFromMovScriptRun/)
  assert.match(movscriptDataSource, /client\.listPlugins/)
  assert.match(movscriptDataSource, /client\.updateThread\(input\.threadId, \{ title: input\.name \}\)/)
  assert.match(movscriptDataSource, /client\.updateThread\(input\.threadId, \{ archived: true \}\)/)
  assert.match(movscriptDataSource, /client\.deleteThread\(input\.threadId\)/)
  assert.match(movscriptDataSource, /agentChatServerRequestsFromMovScriptRun/)
  assert.match(movscriptDataSource, /resolveMovScriptAgentChatServerRequest/)
  assert.match(movscriptDataSource, /client\.approveInteraction/)
  assert.match(movscriptDataSource, /client\.rejectInteraction/)
  assert.match(movscriptDataSource, /client\.answerRunInput/)
  assert.match(movscriptDataSource, /activeRunMode: 'runtime_input'/)
  assert.match(movscriptDataSource, /client\.cancelRun/)
  assert.match(movscriptDataSource, /client\.installPlugin/)
  assert.match(movscriptDataSource, /client\.getWorkspaceConfig/)
  assert.match(movscriptDataSource, /client\.getCapabilities/)
  assert.doesNotMatch(movscriptDataSource, /command\/exec|fs\/readFile|mcpServer\/tool\/call/)

  assert.match(dataSourceFactory, /createCodexAgentChatDataSource/)
  assert.match(dataSourceFactory, /createMovScriptAgentChatDataSource/)
})
