import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import test from 'node:test'

test('agent chat UI owns a provider-neutral protocol and adapts app-server providers at the boundary', () => {
  const coreAgentProtocol = readFileSync(resolve('../../packages/core/src/agent/protocol.ts'), 'utf8')
  const uiProtocol = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatProtocol.ts'), 'utf8')
  const frontendArchitecture = readFileSync(resolve('src/features/agent/ARCHITECTURE.md'), 'utf8')
  const neutralItemProtocol = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatThreadItems.ts'), 'utf8')
  const neutralThreadState = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatThreadState.ts'), 'utf8')
  const neutralNotificationDispatcher = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatNotificationDispatcher.ts'), 'utf8')
  const neutralRuntime = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatRuntime.ts'), 'utf8')
  const neutralNotificationDispatchCoverage = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatNotificationDispatchCoverage.ts'), 'utf8')
  const neutralPendingServerRequests = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatPendingServerRequests.ts'), 'utf8')
  const neutralMessageViews = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatMessageViews.ts'), 'utf8')
  const neutralProcessItemViews = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatProcessItemViews.ts'), 'utf8')
  const neutralDisplayPolicy = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatDisplayPolicy.ts'), 'utf8')
  const neutralRecentCapabilityEvents = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatRecentCapabilityEvents.ts'), 'utf8')
  const neutralSystemItemViews = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatSystemItemViews.ts'), 'utf8')
  const neutralServerRequests = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatServerRequests.ts'), 'utf8')
  const neutralServerRequestForms = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatServerRequestForms.ts'), 'utf8')
  const neutralToolResultViews = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatToolResultViews.ts'), 'utf8')
  const dataSourceShell = readFileSync(resolve('src/features/agent/components/AgentChatDataSourceShell.tsx'), 'utf8')
  const dataSourceShellView = readFileSync(resolve('src/features/agent/components/AgentChatShellView.tsx'), 'utf8')
  const dataSourceShellParts = readFileSync(resolve('src/features/agent/components/AgentChatDataSourceShellParts.tsx'), 'utf8')
  const dataSourceShellCoreState = readFileSync(resolve('src/features/agent/application/useAgentChatShellCoreState.ts'), 'utf8')
  const dataSourceRuntimeController = readFileSync(resolve('src/features/agent/application/useAgentChatRuntimeController.ts'), 'utf8')
  const dataSourceLoadEffect = readFileSync(resolve('src/features/agent/application/useAgentChatDataSourceLoadEffect.ts'), 'utf8')
  const dataSourceShellPresentationState = readFileSync(resolve('src/features/agent/presentation/useAgentChatShellPresentationState.ts'), 'utf8')
  const dataSourceThreadLifecycleEffects = readFileSync(resolve('src/features/agent/application/useAgentChatThreadLifecycleEffects.ts'), 'utf8')
  const dataSourceServerRequests = readFileSync(resolve('src/features/agent/application/useAgentChatServerRequests.ts'), 'utf8')
  const dataSourceThreadList = readFileSync(resolve('src/features/agent/application/useAgentChatThreadList.ts'), 'utf8')
  const dataSourceThreadTabs = readFileSync(resolve('src/features/agent/application/useAgentChatThreadTabs.ts'), 'utf8')
  const dataSourceThreadViewport = readFileSync(resolve('src/features/agent/application/useAgentChatThreadViewport.ts'), 'utf8')
  const dataSourceTurnControls = readFileSync(resolve('src/features/agent/application/useAgentChatTurnControls.ts'), 'utf8')
  const dataSourceThreadRuntimeEffects = readFileSync(resolve('src/features/agent/application/useAgentChatThreadRuntimeEffects.ts'), 'utf8')
  const dataSourceRecentCapabilityEventCard = readFileSync(resolve('src/features/agent/components/agent-chat-events/AgentChatRecentCapabilityEventCard.tsx'), 'utf8')
  const dataSourceServerRequestCard = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatServerRequestCard.tsx'), 'utf8')
  const dataSourceServerRequestForms = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatServerRequestForms.tsx'), 'utf8')
  const dataSourceItemView = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatThreadItemView.tsx'), 'utf8')
  const dataSourceNeutralItemRenderers = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatNeutralItemRenderers.tsx'), 'utf8')
  const dataSourceMessageItemRenderers = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatMessageItemRenderers.tsx'), 'utf8')
  const dataSourceProcessItemRenderers = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatProcessItemRenderers.tsx'), 'utf8')
  const dataSourceSystemItemRenderers = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatSystemItemRenderers.tsx'), 'utf8')
  const dataSourceToolItemRenderers = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatToolItemRenderers.tsx'), 'utf8')
  const dataSourceItemBlocks = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatThreadItemBlocks.tsx'), 'utf8')
  const unifiedShell = readFileSync(resolve('src/features/agent/components/AgentUnifiedChatShell.tsx'), 'utf8')
  const appServerShell = readFileSync(resolve('src/features/agent/components/AppServerChatShell.tsx'), 'utf8')
  const agentThreadRegistryHydration = readFileSync(resolve('src/features/agent/application/useAgentThreadRegistryHydration.ts'), 'utf8')
  const runProfilePreset = readFileSync(resolve('src/features/agent/domain/agentRunProfilePreset.ts'), 'utf8')
  const appServerDataSource = readFileSync(resolve('src/shared/infrastructure/app-server/appServerChatDataSource.ts'), 'utf8')
  const appServerChatCapabilities = readFileSync(resolve('src/shared/infrastructure/app-server/appServerChatCapabilities.ts'), 'utf8')
  const appServerProtocol = readFileSync(resolve('src/shared/infrastructure/app-server/appServerProtocol.ts'), 'utf8')
  const appServerThreadTurnItemAdapter = readFileSync(resolve('src/shared/infrastructure/app-server/appServerThreadTurnItemAdapter.ts'), 'utf8')
  const appServerThreadTurnItemProtocolAdapter = readFileSync(resolve('src/shared/infrastructure/app-server/appServerThreadTurnItemProtocolAdapter.ts'), 'utf8')
  const appServerThreadTurnItemNotificationEvents = readFileSync(resolve('src/shared/infrastructure/app-server/appServerThreadTurnItemNotificationEvents.ts'), 'utf8')
  const appServerThreadTurnItemProtocolEventAdapters = [
    appServerThreadTurnItemProtocolAdapter,
    appServerThreadTurnItemNotificationEvents,
  ].join('\n')
  const appServerThreadTurnItemMapper = readFileSync(resolve('src/shared/infrastructure/app-server/appServerThreadTurnItemItems.ts'), 'utf8')
  const appServerThreadTurnItemNotificationCoverage = readFileSync(resolve('src/shared/infrastructure/app-server/appServerThreadTurnItemNotificationCoverage.ts'), 'utf8')
  const appServerThreadTurnItemServerRequestCoverage = readFileSync(resolve('src/shared/infrastructure/app-server/appServerThreadTurnItemServerRequestCoverage.ts'), 'utf8')
  const appServerRpcClient = readFileSync(resolve('src/shared/infrastructure/app-server/appServerRpcClient.ts'), 'utf8')
  const appServerRpcClientConfig = readFileSync(resolve('src/shared/infrastructure/app-server/appServerRpcClientConfig.ts'), 'utf8')
  const appServerLifecycleClient = readFileSync(resolve('src/shared/infrastructure/app-server/appServerLifecycleClient.ts'), 'utf8')
  const appServerRpcClientBoundary = [
    appServerRpcClient,
    appServerRpcClientConfig,
    appServerLifecycleClient,
  ].join('\n')
  const appServerIpc = readFileSync(resolve('electron/ipc/appServerIpc.ts'), 'utf8')
  const appServerManager = readFileSync(resolve('electron/services/appServerManager.ts'), 'utf8')
  const appServerManagerTest = readFileSync(resolve('electron/services/appServerManager.test.ts'), 'utf8')
  const agentConsolePage = [
    readFileSync(resolve('src/features/agent/components/AgentConsolePage.tsx'), 'utf8'),
    readFileSync(resolve('src/features/agent/components/AgentConsolePageSections.tsx'), 'utf8'),
    readFileSync(resolve('src/features/agent/components/AgentConsoleSessionIntegrationPanel.tsx'), 'utf8'),
  ].join('\n')
  const agentConsoleCapabilityPanels = readFileSync(resolve('src/features/agent/components/AgentConsoleCapabilityPanels.tsx'), 'utf8')
  const projectAgentModePage = [
    readFileSync(resolve('src/features/agent/components/ProjectAgentModePage.tsx'), 'utf8'),
    readFileSync(resolve('src/features/agent/components/ProjectAgentModeSidebar.tsx'), 'utf8'),
    readFileSync(resolve('src/features/agent/components/ProjectAgentModeSidebarView.tsx'), 'utf8'),
  ].join('\n')
  const projectAgentContentPanel = readFileSync(resolve('src/features/agent/components/ProjectAgentContentPanel.tsx'), 'utf8')
  const agentsPage = [
    readFileSync(resolve('src/features/agent/components/AgentsPage.tsx'), 'utf8'),
    readFileSync(resolve('src/features/agent/components/AgentsPageAppServerPanel.tsx'), 'utf8'),
    readFileSync(resolve('src/features/agent/components/AgentsPageAppServerPanelModel.tsx'), 'utf8'),
  ].join('\n')
  const agentControlCenterHook = readFileSync(resolve('src/features/agent/presentation/useAgentControlCenter.ts'), 'utf8')
  const agentControlCenter = readFileSync(resolve('src/features/agent/application/agentControlCenter.ts'), 'utf8')
  const providerConfigStore = readFileSync(resolve('src/shared/infrastructure/providerConfigStore.ts'), 'utf8')
  const providerConfigDefaults = readFileSync(resolve('src/shared/infrastructure/providerConfigDefaults.ts'), 'utf8')
  const providerConfigAppServerProfile = readFileSync(resolve('src/shared/infrastructure/providerConfigAppServerProfile.ts'), 'utf8')
  const coreCapabilityProbe = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatCapabilityProbe.ts'), 'utf8')
  const dataSourceFactory = readFileSync(resolve('src/features/agent/application/agentChatDataSourceFactory.ts'), 'utf8')
  const coreModelCatalog = readFileSync(resolve('../../packages/core/src/agent/modelCatalog.ts'), 'utf8')
  const coreDefaultProvider = readFileSync(resolve('../../packages/core/src/agent/defaultProvider.ts'), 'utf8')
  const coreSensitiveData = readFileSync(resolve('../../packages/core/src/agent/sensitiveData.ts'), 'utf8')
  const coreSettingsSnapshot = readFileSync(resolve('../../packages/core/src/agent/settingsSnapshot.ts'), 'utf8')
  const coreTimelineState = readFileSync(resolve('../../packages/core/src/agent/timelineState.ts'), 'utf8')
  const coreRunProfilePreset = readFileSync(resolve('../../packages/core/src/agent/runProfilePreset.ts'), 'utf8')
  const coreProviderSessionStatusLight = readFileSync(resolve('../../packages/core/src/agent/providerSessionStatusLight.ts'), 'utf8')
  const agentChatDataSourceShellModel = [
    readFileSync(resolve('src/features/agent/presentation/agentChatDataSourceShellModel.ts'), 'utf8'),
    readFileSync(resolve('src/features/agent/presentation/agentChatThreadProjectionModel.ts'), 'utf8'),
  ].join('\n')
  const frontendAgentIndex = readFileSync(resolve('src/features/agent/index.ts'), 'utf8')
  const frontendModelCatalog = readFileSync(resolve('src/features/agent/domain/agentModelCatalog.ts'), 'utf8')
  const frontendModelCatalogApi = readFileSync(resolve('src/features/agent/application/agentModelCatalogApi.ts'), 'utf8')
  const frontendDefaultProvider = readFileSync(resolve('src/features/agent/application/defaultAgentProvider.ts'), 'utf8')
  const frontendUseAgentTimeline = readFileSync(resolve('src/features/agent/presentation/useAgentTimeline.ts'), 'utf8')
  const agentSettingsPage = readFileSync(resolve('src/features/agent/components/AIAgentSettingsPage.tsx'), 'utf8')
  const agentSettingsConfigFile = readFileSync(resolve('src/features/agent/application/agentSettingsConfigFile.ts'), 'utf8')
  const agentSettingsPageModel = readFileSync(resolve('src/features/agent/presentation/agentSettingsPageModel.ts'), 'utf8')
  const removedCoreChatCompatibilityModules = [
    'agentChatNotificationDispatchCoverage',
    'agentChatNotificationDispatcher',
    'agentChatPendingServerRequests',
    'agentChatProtocol',
    'agentChatRecentCapabilityEvents',
    'agentChatRuntime',
    'agentChatServerRequestForms',
    'agentChatServerRequests',
    'agentChatThreadItems',
    'agentChatThreadState',
    'agentChatToolResultViews',
  ]

  for (const moduleName of removedCoreChatCompatibilityModules) {
    assert.equal(
      existsSync(resolve(`src/features/agent/domain/${moduleName}.ts`)),
      false,
      `${moduleName}.ts should not reintroduce a frontend compatibility alias for core agent chat service logic`,
    )
    assert.equal(
      existsSync(resolve(`src/features/agent/domain/${moduleName}.test.ts`)),
      false,
      `${moduleName}.test.ts should not keep frontend-domain test shells for core agent chat service logic`,
    )
  }

  for (const filePath of [
    'src/features/agent/application/agentChatCapabilityProbe.test.ts',
    'src/features/agent/domain/agentSettingsSnapshot.test.ts',
    'src/features/agent/domain/agentTraceDebugData.test.ts',
  ]) {
    assert.equal(
      existsSync(resolve(filePath)),
      false,
      `${filePath} should not keep frontend test shells for service logic that lives in core`,
    )
  }

  assert.match(frontendArchitecture, /## Unified Agent Chat Contract/)
  assert.match(frontendArchitecture, /one UI over provider-specific protocols/)
  assert.match(frontendArchitecture, /Provider-session protocol types, schema constants, status helpers, telemetry payload helpers, media provider contracts, and run\/task graph data contracts live in `packages\/core\/src\/agent\/protocol\.ts`/)
  assert.match(frontendArchitecture, /must import these directly from `@movscript\/core\/agent\/protocol`/)
  assert.match(frontendArchitecture, /do not keep a frontend compatibility alias/)
  assert.match(frontendArchitecture, /Neutral chat protocol and runtime live under `packages\/core\/src\/agent\/chat`/)
  assert.match(frontendArchitecture, /Core owns that service logic/)
  assert.match(frontendArchitecture, /must import migrated service-level chat modules directly from `@movscript\/core\/agent\/chat`/)
  assert.match(frontendArchitecture, /do not keep frontend compatibility aliases/)
  assert.match(frontendArchitecture, /UI renderers live under `src\/features\/agent\/components\/agent-chat-\*`/)
  assert.match(frontendArchitecture, /Provider-neutral chat view-model helpers, copy, labels, collapse thresholds, and inspect-section grouping live in `packages\/core\/src\/agent\/chat`/)
  assert.match(frontendArchitecture, /frontend keeps component composition, orchestration, and product-specific display classifiers/)
  assert.match(frontendArchitecture, /App-server thread-turn-item mapping is reached through `src\/shared\/infrastructure\/app-server\/appServerThreadTurnItemAdapter\.ts`/)
  assert.match(frontendArchitecture, /Provider-specific compatibility aliases must not be reintroduced/)
  assert.match(frontendArchitecture, /Mova reuses the app-server protocol through provider configuration/)
  assert.match(frontendArchitecture, /Claude mapping is not implemented/)
  assert.match(frontendArchitecture, /Server-initiated requests are first-class chat state/)
  assert.match(frontendArchitecture, /adapter must recover them from authoritative pending state/)
  assert.match(frontendArchitecture, /Media inputs are neutral resources/)
  assert.match(frontendArchitecture, /Timeline pagination and stream-event merge rules are service-level state logic/)
  assert.match(frontendArchitecture, /Run profile presets are split by boundary/)
  assert.match(frontendArchitecture, /Agent backend model catalog and default-provider rules are service-level logic/)
  assert.match(frontendArchitecture, /Sensitive data detection and redaction are service-level safety rules/)
  assert.match(frontendArchitecture, /must import these helpers from `@movscript\/core\/agent` instead of keeping legacy trace helper aliases/)
  assert.match(frontendArchitecture, /Agent settings snapshot schema, parsing, export normalization, and reference validation are service-level portability rules/)
  assert.match(frontendArchitecture, /must import snapshot helpers from `@movscript\/core\/agent` instead of keeping compatibility re-exports/)
  assert.match(frontendArchitecture, /Do not remove old timeline components only because the unified chat exists/)

  assert.match(uiProtocol, /export interface AgentChatThread/)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentProtocol.ts')), false)
  assert.match(coreAgentProtocol, /export const AGENT_PROTOCOL_VERSION/)
  assert.match(coreAgentProtocol, /export const PROVIDER_SESSION_EVENT_V2_SCHEMA/)
  assert.match(coreAgentProtocol, /export interface ProviderSessionSnapshotV2/)
  assert.match(coreAgentProtocol, /export interface ProviderSessionEventV2/)
  assert.match(coreAgentProtocol, /export function isAgentRunTerminalStatus/)
  assert.match(coreAgentProtocol, /export function isAgentRunStoppableStatus/)
  assert.match(coreAgentProtocol, /export function providerSessionMessageRef/)
  assert.match(coreAgentProtocol, /export function providerSessionInputRef/)
  assert.match(coreAgentProtocol, /export function buildPendingActiveRunInputQueueItems/)
  assert.match(coreAgentProtocol, /export function activeRunInputDisplayDeliveryStatus/)
  assert.match(coreAgentProtocol, /export function activeRunInputIsWaitingForDelivery/)
  assert.match(coreAgentProtocol, /export function createAgentTelemetryMetricSample/)
  assert.doesNotMatch(coreAgentProtocol, /from ['"]@\/|from 'react'|@movscript\/ui|window\.|document\.|localStorage|sessionStorage|providerSessionClient|appServerRpcClient|i18n/)
  assert.equal(existsSync(resolve('src/features/agent/domain/providerSessionMessageRefs.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentActiveRunInputMessages.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentActiveRunInputMessages.test.ts')), false)
  assert.match(uiProtocol, /from '\.\/agentChatThreadItems\.js'/)
  assert.match(uiProtocol, /AgentChatThreadItem/)
  assert.match(neutralItemProtocol, /export type AgentChatThreadItem/)
  assert.match(neutralItemProtocol, /type: 'hookPrompt'/)
  assert.match(neutralItemProtocol, /export interface AgentChatPlanStep/)
  assert.match(neutralItemProtocol, /type: 'plan'[\s\S]*items\?: AgentChatPlanStep\[\]/)
  assert.match(neutralItemProtocol, /type: 'collabAgentToolCall'/)
  assert.match(neutralItemProtocol, /type: 'mcpToolCall'/)
  assert.match(neutralItemProtocol, /type: 'dynamicToolCall'/)
  assert.match(neutralItemProtocol, /type: 'systemNotice'/)
  assert.match(neutralItemProtocol, /threadId\?: string/)
  assert.match(neutralItemProtocol, /turnId\?: string/)
  assert.match(neutralItemProtocol, /type: 'approvalReview'/)
  assert.match(neutralItemProtocol, /terminalInteractions/)
  assert.match(neutralDisplayPolicy, /AGENT_CHAT_COLLAPSE_LIMITS/)
  assert.match(neutralDisplayPolicy, /agentChatContentDefaultOpen/)
  assert.match(neutralDisplayPolicy, /agentChatListDefaultOpen/)
  assert.doesNotMatch(neutralDisplayPolicy, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatDisplayPolicy.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatDisplayPolicy.test.ts')), false)
  assert.match(readFileSync(resolve('../../packages/core/src/agent/chat/index.ts'), 'utf8'), /export \* from '\.\/agentChatDisplayPolicy\.js'/)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatMessageViews.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatMessageViews.test.ts')), false)
  assert.match(readFileSync(resolve('../../packages/core/src/agent/chat/index.ts'), 'utf8'), /export \* from '\.\/agentChatMessageViews\.js'/)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatProcessItemViews.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatProcessItemViews.test.ts')), false)
  assert.match(readFileSync(resolve('../../packages/core/src/agent/chat/index.ts'), 'utf8'), /export \* from '\.\/agentChatProcessItemViews\.js'/)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatSystemItemViews.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatSystemItemViews.test.ts')), false)
  assert.match(readFileSync(resolve('../../packages/core/src/agent/chat/index.ts'), 'utf8'), /export \* from '\.\/agentChatSystemItemViews\.js'/)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatToolResultViews.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentChatToolResultViews.test.ts')), false)
  assert.match(readFileSync(resolve('../../packages/core/src/agent/chat/index.ts'), 'utf8'), /export \* from '\.\/agentChatToolResultViews\.js'/)
  assert.match(neutralPendingServerRequests, /export function agentChatThreadIdForServerRequest/)
  assert.match(neutralPendingServerRequests, /export function visibleAgentChatPendingServerRequests/)
  assert.match(neutralPendingServerRequests, /agentChatServerRequestsShareResolutionKey/)
  assert.doesNotMatch(neutralPendingServerRequests, /item\.request\.id === request\.id/)
  assert.doesNotMatch(neutralPendingServerRequests, /AgentChatDataSourceShell|AgentChatServerRequestCard|@movscript\/ui/)
  assert.match(neutralRuntime, /export function agentChatRuntimeReducer/)
  assert.match(neutralRuntime, /export function selectAgentChatRuntimeView/)
  assert.match(neutralRuntime, /threadReadRequests/)
  assert.doesNotMatch(neutralRuntime, /from 'react'|@movscript\/ui|AgentChatDataSourceShell|window\.|localStorage|useAgentSessionStore|@\/shared\/infrastructure\/api|appServerRpcClient/)
  assert.match(coreModelCatalog, /export const AGENT_BACKEND_MODEL_CAPABILITY_QUERY/)
  assert.match(coreModelCatalog, /export function mergeAgentBackendModels/)
  assert.match(coreModelCatalog, /export function publicAgentBackendModelId/)
  assert.doesNotMatch(coreModelCatalog, /@\/|from 'react'|@movscript\/ui|window\.|document\.|localStorage|sessionStorage|appServerRpcClient/)
  assert.match(coreDefaultProvider, /export function resolveDefaultAgentProviderFromBackend/)
  assert.match(coreDefaultProvider, /export function buildBackendDefaultAgentProviderConfig/)
  assert.match(coreDefaultProvider, /export function selectDefaultAgentProviderModel/)
  assert.match(coreDefaultProvider, /export function hasExplicitAgentProviderConfig/)
  assert.doesNotMatch(coreDefaultProvider, /@\/|from 'react'|@movscript\/ui|window\.|document\.|localStorage|sessionStorage|appServerRpcClient|ProviderSessionClient|getAPIBaseURL/)
  assert.match(coreSensitiveData, /export function hasSensitiveTextSecret/)
  assert.match(coreSensitiveData, /export function redactAgentTraceDebugText/)
  assert.match(coreSensitiveData, /PROVIDER_API_KEY_PATTERN/)
  assert.doesNotMatch(coreSensitiveData, /from ['"]@\/|from 'react'|@movscript\/ui|window\.|document\.|localStorage|sessionStorage|appServerRpcClient/)
  assert.match(coreSettingsSnapshot, /export function buildSettingsSnapshot/)
  assert.match(coreSettingsSnapshot, /export function parseSettingsSnapshot/)
  assert.match(coreSettingsSnapshot, /export function validateSettingsSnapshotReferences/)
  assert.match(coreSettingsSnapshot, /from '\.\/sensitiveData\.js'/)
  assert.match(coreSettingsSnapshot, /from '\.\/modelCatalog\.js'/)
  assert.doesNotMatch(coreSettingsSnapshot, /from ['"]@\/|from 'react'|@movscript\/ui|window\.|document\.|localStorage|sessionStorage|appServerRpcClient|ProviderSessionClient|getAPIBaseURL/)
  assert.match(coreTimelineState, /export function replaceTimelinePage/)
  assert.match(coreTimelineState, /export function mergeTimelinePage/)
  assert.match(coreTimelineState, /export function mergeTimelineResetPage/)
  assert.match(coreTimelineState, /export function applyTimelineEvent/)
  assert.match(coreTimelineState, /export function sortTimelineItems/)
  assert.doesNotMatch(coreTimelineState, /from ['"]@\/|from 'react'|@movscript\/ui|window\.|document\.|localStorage|sessionStorage|providerSessionClient|appServerRpcClient/)
  assert.match(coreRunProfilePreset, /export const AGENT_RUN_PROFILE_PRESETS/)
  assert.match(coreRunProfilePreset, /permissionProfileId: ':read-only'/)
  assert.match(coreRunProfilePreset, /approvalsReviewer: 'auto_review'/)
  assert.match(coreRunProfilePreset, /fallbackSandbox: 'danger-full-access'/)
  assert.doesNotMatch(coreRunProfilePreset, /label:|shortLabel:|description:|Read Only|Workspace|Auto Review|Full Access|from ['"]@\/|from 'react'|@movscript\/ui|window\.|document\./)
  assert.match(coreProviderSessionStatusLight, /export function providerSessionStatusLightFromStatusRecord/)
  assert.match(coreProviderSessionStatusLight, /export function providerSessionStatusLightForTargetKeys/)
  assert.doesNotMatch(coreProviderSessionStatusLight, /STOPPED_PROVIDER_SESSION_STATUS_LIGHT|停止|Runtime 会话当前不会自行触发新的 run|from ['"]@\/|from 'react'|@movscript\/ui|window\.|document\./)
  assert.equal(existsSync(resolve('src/features/agent/domain/providerSessionStatusLight.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/domain/providerSessionStatusLight.test.ts')), false)
  assert.doesNotMatch(frontendAgentIndex, /providerSessionStatusLight/)
  assert.match(frontendModelCatalog, /from '@movscript\/core\/agent'/)
  assert.doesNotMatch(frontendModelCatalog, /from '@\/shared\/infrastructure\/api'|client: AgentBackendModelCatalogClient<PublicModel> = api/)
  assert.match(frontendModelCatalogApi, /fetchAgentBackendModels as fetchAgentBackendModelsWithClient/)
  assert.match(frontendModelCatalogApi, /client: AgentBackendModelCatalogClient<PublicModel> = api/)
  assert.match(frontendDefaultProvider, /resolveDefaultAgentProviderFromBackend/)
  assert.match(frontendDefaultProvider, /new ProviderSessionClient/)
  assert.match(frontendDefaultProvider, /getAPIBaseURL\(\)/)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentTraceDebugData.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/domain/agentSettingsSnapshot.ts')), false)
  assert.match(agentSettingsConfigFile, /buildSettingsSnapshot/)
  assert.match(agentSettingsConfigFile, /from '@movscript\/core\/agent'/)
  assert.match(agentSettingsPageModel, /parseSettingsSnapshot/)
  assert.match(agentSettingsPageModel, /redactAgentTraceDebugText/)
  assert.match(agentSettingsPageModel, /from '@movscript\/core\/agent'/)
  assert.doesNotMatch(agentSettingsPage, /from '@movscript\/core\/agent'/)
  assert.doesNotMatch(agentSettingsPage, /redactAgentTraceDebugText/)
  assert.doesNotMatch(agentSettingsPage, /@\/features\/agent\/domain\/agent(?:TraceDebugData|SettingsSnapshot)/)
  assert.equal(existsSync(resolve('src/features/agent/application/agentTimelineState.ts')), false)
  assert.equal(existsSync(resolve('src/features/agent/application/agentTimelineState.test.ts')), false)
  assert.match(frontendUseAgentTimeline, /from '@movscript\/core\/agent'/)
  assert.match(frontendUseAgentTimeline, /CoreAgentTimelineState<AgentTimelineItem>/)
  assert.match(frontendUseAgentTimeline, /replaceTimelinePage/)
  assert.match(frontendUseAgentTimeline, /applyTimelineEvent/)
  assert.doesNotMatch(frontendUseAgentTimeline, /@\/features\/agent\/application\/agentTimelineState|function timelineItemTime|function dedupeTimelineItems|function uniqueStrings/)
  assert.match(runProfilePreset, /from '@movscript\/core\/agent'/)
  assert.match(runProfilePreset, /AGENT_RUN_PROFILE_COPY/)
  assert.match(runProfilePreset, /label: 'Read Only'/)
  assert.match(runProfilePreset, /description: 'Only read workspace files/)
  assert.match(runProfilePreset, /decorateRunProfilePreset/)
  assert.doesNotMatch(runProfilePreset, /import type \{ ApprovalsReviewer, AskForApproval, SandboxMode \}/)
  assert.match(neutralMessageViews, /export function agentChatUserMessageView/)
  assert.match(neutralMessageViews, /export function agentChatHookPromptView/)
  assert.match(neutralMessageViews, /export function agentChatAgentMessageView/)
  assert.match(neutralMessageViews, /Video resource/)
  assert.match(neutralMessageViews, /Audio resource/)
  assert.match(neutralMessageViews, /Image attachment/)
  assert.match(neutralMessageViews, /textElementDetails/)
  assert.match(neutralMessageViews, /agentChatMemoryCitationSummary/)
  assert.doesNotMatch(neutralMessageViews, /AgentChatUserMessageItem|AgentChatMediaPreviewGrid|AgentMessageSection|@movscript\/ui/)
  assert.match(dataSourceMessageItemRenderers, /from '@movscript\/core\/agent\/chat'/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /domain\/agentChatMessageViews/)
  assert.match(neutralProcessItemViews, /export function agentChatReasoningItemView/)
  assert.match(neutralProcessItemViews, /export function agentChatPlanItemView/)
  assert.match(neutralProcessItemViews, /export function agentChatPlanStatusIntent/)
  assert.match(neutralProcessItemViews, /summary part\(s\)/)
  assert.match(neutralProcessItemViews, /\^\s*\\\[\(\[\^\\\]\]\+\)\\\]\\s\+\(\.\+\)\$/)
  assert.doesNotMatch(neutralProcessItemViews, /<AgentChatReasoningItem|<AgentChatPlanItem|AgentPlanOverviewList|AgentMessageSection|@movscript\/ui/)
  assert.match(dataSourceProcessItemRenderers, /from '@movscript\/core\/agent\/chat'/)
  assert.doesNotMatch(dataSourceProcessItemRenderers, /domain\/agentChatProcessItemViews/)
  assert.match(neutralRecentCapabilityEvents, /export function agentChatRecentCapabilityEventView/)
  assert.match(neutralRecentCapabilityEvents, /type === 'fsChanged'/)
  assert.match(neutralRecentCapabilityEvents, /type === 'realtime'/)
  assert.match(neutralRecentCapabilityEvents, /type === 'account'/)
  assert.match(neutralRecentCapabilityEvents, /type === 'mcpStatus'/)
  assert.doesNotMatch(neutralRecentCapabilityEvents, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem|AgentRunStep|AgentMessage|anthropic_messages/)
  assert.match(neutralSystemItemViews, /export function agentChatSystemItemView/)
  assert.match(neutralSystemItemViews, /Approval review/)
  assert.match(neutralSystemItemViews, /requestPermissions/)
  assert.match(neutralSystemItemViews, /Context compacted/)
  assert.match(neutralSystemItemViews, /Unknown item/)
  assert.match(neutralSystemItemViews, /thread \$\{item\.threadId\}/)
  assert.match(neutralSystemItemViews, /turn \$\{item\.turnId\}/)
  assert.doesNotMatch(neutralSystemItemViews, /function AgentChatSystemItem|AgentMessageSection|AgentChatPreviewBlock|@movscript\/ui/)
  assert.match(dataSourceSystemItemRenderers, /from '@movscript\/core\/agent\/chat'/)
  assert.doesNotMatch(dataSourceSystemItemRenderers, /domain\/agentChatSystemItemViews/)
  assert.match(neutralServerRequests, /export function agentChatServerRequestTitle/)
  assert.match(neutralServerRequests, /export function agentChatServerRequestCanApprove/)
  assert.match(neutralServerRequests, /export function agentChatServerRequestCanApproveForSession/)
  assert.match(neutralServerRequests, /export function agentChatServerRequestCanApproveWithStrictAutoReview/)
  assert.match(neutralServerRequests, /export function agentChatServerRequestCanApproveWithExecPolicyAmendment/)
  assert.match(neutralServerRequests, /export function agentChatServerRequestNetworkPolicyAmendments/)
  assert.match(neutralServerRequests, /export function agentChatServerRequestCanCancel/)
  assert.match(neutralServerRequests, /export function agentChatServerRequestExternalUrl/)
  assert.match(neutralServerRequests, /export function agentChatApproveResponse/)
  assert.match(neutralServerRequests, /export function agentChatApproveForSessionResponse/)
  assert.match(neutralServerRequests, /export function agentChatApproveWithStrictAutoReviewResponse/)
  assert.match(neutralServerRequests, /export function agentChatApproveWithExecPolicyAmendmentResponse/)
  assert.match(neutralServerRequests, /export function agentChatApproveWithNetworkPolicyAmendmentResponse/)
  assert.match(neutralServerRequests, /export function agentChatCancelResponse/)
  assert.match(neutralServerRequests, /export function agentChatRejectResponse/)
  assert.match(neutralServerRequests, /export function agentChatServerRequestSummary/)
  assert.match(neutralServerRequests, /agentChatServerRequestArgumentSummaries\(params\.args\)/)
  assert.match(neutralServerRequests, /agentChatServerRequestPreviewSummaries\(params\.preview\)/)
  assert.match(neutralServerRequests, /request\.method === 'item\/permissions\/requestApproval'[\s\S]*return params\.args/)
  assert.match(neutralServerRequests, /ChatGPT token refresh required/)
  assert.match(neutralServerRequests, /Client attestation requested/)
  assert.match(neutralServerRequests, /applyPatchApproval/)
  assert.match(neutralServerRequests, /execCommandApproval/)
  assert.match(neutralServerRequests, /permissionApprovalRequestHasProfile/)
  assert.doesNotMatch(neutralServerRequests, /codexPermissionsRequestHasProfile/)
  assert.match(neutralServerRequests, /action: 'approve'/)
  assert.match(neutralServerRequests, /action: 'cancel'/)
  assert.match(neutralServerRequests, /action: 'reject'/)
  assert.match(neutralServerRequestForms, /export function agentChatInputRequestFormModel/)
  assert.match(neutralServerRequestForms, /export function agentChatInputRequestAnswerPayload/)
  assert.match(neutralServerRequestForms, /export function agentChatInputRequestFormCanSubmit/)
  assert.match(neutralServerRequestForms, /export function agentChatToolResultContentItems/)
  assert.match(neutralServerRequestForms, /export function agentChatElicitationFormModel/)
  assert.match(neutralServerRequestForms, /export function agentChatElicitationFieldValueIsValid/)
  assert.match(neutralServerRequestForms, /export function agentChatElicitationContent/)
  assert.match(neutralServerRequestForms, /kind: 'question-form'/)
  assert.match(neutralServerRequestForms, /kind: 'input-form'/)
  assert.doesNotMatch(neutralServerRequestForms, /codex-questions/)
  assert.doesNotMatch(neutralServerRequestForms, /agent-input/)
  assert.match(neutralServerRequestForms, /responseText: 'Confirmed\.'/)
  assert.match(neutralServerRequestForms, /type: 'inputVideo'/)
  assert.match(neutralServerRequestForms, /type: 'resource'/)
  assert.doesNotMatch(neutralServerRequestForms, /AgentChatServerRequestCard|AgentMessageSection|@movscript\/ui/)
  assert.match(dataSourceServerRequestForms, /agentChatToolResultContentItems/)
  assert.doesNotMatch(dataSourceServerRequestForms, /function toolResultContentItems/)
  assert.match(neutralToolResultViews, /export function agentChatDynamicToolOutputView/)
  assert.match(neutralToolResultViews, /export function agentChatMcpToolResultView/)
  assert.match(neutralToolResultViews, /export function agentChatMcpToolPendingSummary/)
  assert.match(neutralToolResultViews, /export function agentChatCommandExecutionView/)
  assert.match(neutralToolResultViews, /export function agentChatToolCallView/)
  assert.match(neutralToolResultViews, /export function agentChatFileChangeView/)
  assert.match(neutralToolResultViews, /export function agentChatCollabAgentToolCallView/)
  assert.match(neutralToolResultViews, /export function agentChatWebSearchView/)
  assert.match(neutralToolResultViews, /export function agentChatImageItemView/)
  assert.match(neutralToolResultViews, /revisedPrompt/)
  assert.match(neutralToolResultViews, /savedPath/)
  assert.match(neutralToolResultViews, /inputAudio|inputVideo|inputResource/)
  assert.match(neutralToolResultViews, /type === 'audio'/)
  assert.match(neutralToolResultViews, /type === 'video'/)
  assert.match(neutralToolResultViews, /agentChatToolRoundMeta/)
  assert.match(neutralToolResultViews, /terminalInteractions/)
  assert.match(neutralToolResultViews, /aggregatedOutput/)
  assert.match(neutralToolResultViews, /sandboxed/)
  assert.doesNotMatch(neutralToolResultViews, /AgentChatToolCallItem|AgentChatMediaPreviewGrid|AgentMessageSection|@movscript\/ui/)
  assert.match(uiProtocol, /export interface AgentChatNotification/)
  assert.match(uiProtocol, /type: 'threadLifecycle'/)
  assert.match(uiProtocol, /type: 'serverRequestResolved'/)
  assert.match(uiProtocol, /type: 'realtime'/)
  assert.match(uiProtocol, /type: 'systemNotice'/)
  assert.match(uiProtocol, /turnId\?: string/)
  assert.match(uiProtocol, /export interface AgentChatServerRequest/)
  assert.match(uiProtocol, /export type AgentChatServerRequestResponse/)
  assert.match(uiProtocol, /export type AgentChatServerRequestHandler/)
  assert.match(uiProtocol, /account\/chatgptAuthTokens\/refresh/)
  assert.match(uiProtocol, /attestation\/generate/)
  assert.match(uiProtocol, /applyPatchApproval/)
  assert.match(uiProtocol, /execCommandApproval/)
  assert.match(uiProtocol, /export interface AgentChatDataSource/)
  assert.match(uiProtocol, /serverRequestSubscriptionMode\?: 'global' \| 'globalWithThreadFallback'/)
  assert.match(uiProtocol, /renameThread\?\(input: \{ threadId: string; name: string \}/)
  assert.match(uiProtocol, /archiveThread\?\(input: \{ threadId: string \}/)
  assert.match(uiProtocol, /subscribeServerRequests\?\(input: \{/)
  assert.match(uiProtocol, /onNotification\?: \(notification: AgentChatNotification\) => void/)
  assert.match(uiProtocol, /unarchiveThread\?\(input: \{ threadId: string \}/)
  assert.match(uiProtocol, /deleteThread\?\(input: \{ threadId: string \}/)
  assert.match(uiProtocol, /startTurn\?\(input: \{ threadId: string; inputs: AgentChatInput\[\]/)
  assert.match(uiProtocol, /steerTurn\?\(input: \{ threadId: string; turnId: string; inputs: AgentChatInput\[\]/)
  assert.match(uiProtocol, /interruptTurn\?\(input: \{ threadId: string; turnId: string; reason\?: string/)
  assert.match(uiProtocol, /export interface AgentChatCapabilities/)
  assert.match(uiProtocol, /deltaBase64/)
  assert.match(uiProtocol, /sourcePath/)
  assert.match(uiProtocol, /destinationPath/)
  assert.match(uiProtocol, /interface AgentChatRealtimeCapability[\s\S]*listVoices\?/)
  assert.match(uiProtocol, /interface AgentChatRealtimeCapability[\s\S]*appendAudio/)
  assert.match(uiProtocol, /interface AgentChatRealtimeCapability[\s\S]*appendText/)
  assert.doesNotMatch(uiProtocol, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)

  assert.match(dataSourceRuntimeController, /type AgentChatThread/)
  assert.match(dataSourceShellCoreState, /type AgentChatDataSource/)
  assert.match(dataSourceShellParts, /type AgentChatThreadItem/)
  assert.match(dataSourceShellParts, /AgentChatThreadItemView/)
  assert.match(dataSourceShellParts, /AgentConversationItem/)
  assert.match(dataSourceShellParts, /AgentConversationTabsPanel/)
  assert.match(dataSourceShellParts, /function AgentChatDataSourcePanelCard/)
  assert.match(dataSourceShell, /<AgentChatShellView/)
  assert.match(dataSourceShellView, /<AgentChatDataSourcePanelCard/)
  assert.match(dataSourceShellParts, /function AgentChatDataSourcePageThreadShell/)
  assert.match(dataSourceShellView, /<AgentChatDataSourcePageThreadShell/)
  assert.doesNotMatch(dataSourceShell, /AgentConversationTabsPanel/)
  assert.doesNotMatch(dataSourceShell, /agent-page-chat-thread-shell/)
  assert.match(dataSourceShellParts, /AgentChatRecentCapabilityEventCard/)
  assert.match(dataSourceShellParts, /AgentComposerSection/)
  assert.match(dataSourceShellParts, /function AgentChatDataSourceComposerPanel/)
  assert.match(dataSourceShellView, /<AgentChatDataSourceComposerPanel/)
  assert.doesNotMatch(dataSourceShell, /AgentComposerSection/)
  assert.match(dataSourceShell, /from '@\/features\/agent\/application\/useAgentChatShellCoreState'/)
  assert.match(dataSourceShellCoreState, /useAgentComposerController/)
  assert.match(dataSourceShellCoreState, /useAgentMentionEditorSync/)
  assert.doesNotMatch(dataSourceShell, /features\/agent\/state\/agentStore/)
  assert.match(dataSourceShell, /composerInputRef=\{composerInputRef\}/)
  assert.match(dataSourceShellView, /onInputChange=\{composer\.updateInputDraft\}/)
  assert.match(dataSourceTurnControls, /agentChatInputsFromTextAndAttachments/)
  assert.match(dataSourceTurnControls, /dataSource\.startTurn/)
  assert.match(dataSourceTurnControls, /dataSource\.steerTurn/)
  assert.match(dataSourceTurnControls, /dataSource\.interruptTurn/)
  assert.match(dataSourceShell, /useAgentChatTurnControls\(\{[\s\S]*activeThread,[\s\S]*queuedInputs,[\s\S]*startThreadResult,[\s\S]*\}\)/)
  assert.doesNotMatch(dataSourceShell, /agentChatInputsFromTextAndAttachments/)
  assert.doesNotMatch(dataSourceShell, /await dataSource\.startTurn/)
  assert.doesNotMatch(dataSourceShell, /await dataSource\.steerTurn/)
  assert.doesNotMatch(dataSourceShell, /await dataSource\.interruptTurn/)
  assert.match(dataSourceThreadTabs, /dataSource\?\.renameThread/)
  assert.match(dataSourceThreadTabs, /onRename: \(name: string\) => void renameThread/)
  assert.match(dataSourceThreadTabs, /const closeThreadTab = useCallback/)
  assert.match(dataSourceThreadTabs, /resolveAgentChatNextThreadAfterClose\(\{[\s\S]*closingThreadId: threadId,[\s\S]*openThreadCandidates/)
  assert.match(dataSourceShell, /useAgentChatThreadTabs\(\{[\s\S]*readHistoryThread,[\s\S]*threadOrderIndex,[\s\S]*upsertThreadReadResult,[\s\S]*\}\)/)
  assert.doesNotMatch(dataSourceShell, /dataSource\?\.renameThread/)
  assert.doesNotMatch(dataSourceShell, /const closeThreadTab = useCallback/)
  assert.match(agentChatDataSourceShellModel, /export function resolveAgentChatNextThreadAfterClose/)
  assert.match(agentChatDataSourceShellModel, /const remainingThreads = input\.openThreadCandidates\.filter\(\(item\) => item\.id !== input\.closingThreadId\)/)
  assert.match(agentChatDataSourceShellModel, /return remainingThreads\[Math\.max\(0, closingIndex - 1\)\] \?\? remainingThreads\[0\]/)
  assert.match(dataSourceThreadTabs, /markThreadClosed\(threadId, !nextThread\)/)
  assert.doesNotMatch(dataSourceShell, /markThreadClosed\(threadId, !nextThread\)/)
  assert.match(dataSourceShell, /void closeThreadTab\(threadId\)/)
  assert.match(dataSourceShell, /canStopActiveTurn=\{canStopActiveTurn\}/)
  assert.match(dataSourceShellView, /canStopActiveRun=\{canStopActiveTurn\}/)
  assert.match(dataSourceShellCoreState, /agentChatRuntimeReducer/)
  assert.match(dataSourceServerRequests, /type: 'applyNotification'/)
  assert.match(dataSourceShell, /from '@\/features\/agent\/application\/useAgentChatRuntimeController'/)
  assert.match(dataSourceShell, /useAgentChatRuntimeController\(\{[\s\S]*activeThreadIdRef,[\s\S]*dispatchRuntime,[\s\S]*runtime,[\s\S]*\}\)/)
  assert.match(dataSourceRuntimeController, /selectAgentChatRuntimeView\(runtime\)/)
  assert.doesNotMatch(dataSourceShell, /buildAgentChatVisibleItems/)
  assert.match(dataSourceRuntimeController, /const runtimeView = useMemo\(\(\) => selectAgentChatRuntimeView\(runtime\), \[runtime\]\)/)
  assert.match(neutralRuntime, /buildAgentChatVisibleItems/)
  assert.match(neutralRuntime, /visibleAgentChatPendingServerRequests\(state\.pendingServerRequests, state\.activeThreadId\)/)
  assert.match(dataSourceShellParts, /agentChatPendingServerRequestEntryKey\(entry\)/)
  assert.match(dataSourceShellParts, /function AgentComposerActionLayer/)
  assert.match(dataSourceShellParts, /data-testid="agent-composer-action-layer"/)
  assert.match(dataSourceShellParts, /const pageCount = pendingServerRequests\.length/)
  assert.match(dataSourceShellParts, /const entry = pendingServerRequests\[safePage\]/)
  assert.match(dataSourceShellParts, /<ChevronLeft size=\{12\}/)
  assert.doesNotMatch(dataSourceShell, /pendingServerRequests\.map\(\(entry\)/)
  assert.match(dataSourceShell, /from '@\/features\/agent\/presentation\/useAgentChatShellPresentationState'/)
  assert.match(dataSourceShellPresentationState, /const hasThreadBodyContent = Boolean/)
  assert.match(dataSourceShellPresentationState, /const hasChatContent = hasThreadBodyContent \|\| hasComposerActionLayer/)
  assert.match(dataSourceShell, /<AgentChatShellView[\s\S]*visiblePendingServerRequests=\{visiblePendingServerRequests\}/)
  assert.match(dataSourceShellView, /<AgentChatDataSourceComposerPanel[\s\S]*pendingServerRequests=\{visiblePendingServerRequests\}/)
  assert.match(dataSourceShellParts, /<AgentComposerActionLayer[\s\S]*pendingServerRequests=\{pendingServerRequests\}/)
  assert.doesNotMatch(dataSourceShell, /<AgentChatDataSourceThreadBody[\s\S]{0,260}pendingServerRequests=\{visiblePendingServerRequests\}/)
  assert.match(dataSourceShellView, /!\{?hasChatContent/)
  assert.match(dataSourceShell, /from '@\/features\/agent\/application\/useAgentChatThreadLifecycleEffects'/)
  assert.match(dataSourceThreadLifecycleEffects, /visiblePendingServerRequests\.length === 0/)
  assert.match(dataSourceThreadLifecycleEffects, /type: 'requestThreadRead'/)
  assert.match(dataSourceShell, /from '@\/features\/agent\/application\/useAgentChatThreadViewport'/)
  assert.match(dataSourceShell, /useAgentChatThreadViewport\(\{[\s\S]*runtimeVisibleItems,[\s\S]*threadReadRequests,[\s\S]*threadReadStates,[\s\S]*\}\)/)
  assert.match(dataSourceThreadViewport, /AGENT_CHAT_OLDER_ITEMS_SCROLL_THRESHOLD_PX = 96/)
  assert.match(dataSourceThreadViewport, /buildAgentChatVisibleItemWindow\(/)
  assert.doesNotMatch(dataSourceShell, /AGENT_CHAT_OLDER_ITEMS_SCROLL_THRESHOLD_PX = 96/)
  assert.doesNotMatch(dataSourceShell, /buildAgentChatVisibleItemWindow\(/)
  assert.match(dataSourceShell, /from '@\/features\/agent\/application\/useAgentChatThreadList'/)
  assert.doesNotMatch(dataSourceShell, /AGENT_CHAT_THREAD_LIST_PAGE_SIZE = 20/)
  assert.match(dataSourceThreadList, /AGENT_CHAT_THREAD_LIST_PAGE_SIZE = 20/)
  assert.match(dataSourceThreadList, /dataSource\.listThreads\(\{ limit: AGENT_CHAT_THREAD_LIST_PAGE_SIZE \}\)/)
  assert.match(dataSourceThreadList, /cursor: threadListNextCursor/)
  assert.match(agentChatDataSourceShellModel, /function mergeAgentChatThreadListPage/)
  assert.match(dataSourceShell, /onLoadMoreThreads=\{loadMoreThreads\}/)
  assert.doesNotMatch(dataSourceShell, /listThreads\(\{ limit: 50/)
  assert.doesNotMatch(projectAgentModePage, /function AppServerSidebarActiveThread/)
  assert.match(projectAgentModePage, /const sortedChatConversations = chatConversations/)
  assert.match(agentThreadRegistryHydration, /AGENT_THREAD_REGISTRY_HYDRATION_PAGE_SIZE = 80/)
  assert.match(agentThreadRegistryHydration, /dataSource\.listThreads\(\{ limit: AGENT_THREAD_REGISTRY_HYDRATION_PAGE_SIZE \}\)/)
  assert.match(projectAgentModePage, /const appServerThreadHydration = useAgentThreadRegistryHydration/)
  assert.match(projectAgentModePage, /const sourceThreads = appServerMode \? appServerThreadHydration\.sourceThreads : providerSessionThreads/)
  assert.match(dataSourceThreadViewport, /const olderItemsScrollAnchorRef = useRef/)
  assert.match(dataSourceThreadViewport, /const handleThreadScroll = useCallback/)
  assert.match(dataSourceThreadViewport, /event\.currentTarget\.scrollTop > AGENT_CHAT_OLDER_ITEMS_SCROLL_THRESHOLD_PX/)
  assert.doesNotMatch(dataSourceShell, /const olderItemsScrollAnchorRef = useRef/)
  assert.doesNotMatch(dataSourceShell, /const handleThreadScroll = useCallback/)
  assert.match(dataSourceShellParts, /<AgentThreadFill[\s\S]*onScroll=\{onScroll\}/)
  assert.match(dataSourceThreadViewport, /suppressNextAutoScrollRef/)
  assert.doesNotMatch(dataSourceShell, /suppressNextAutoScrollRef/)
  assert.match(dataSourceShellView, /surface === 'panel' && historyOpen/)
  assert.doesNotMatch(dataSourceShell, /historyOpen && showThreadList/)
  assert.match(dataSourceShell, /from '@\/features\/agent\/application\/useAgentChatServerRequests'/)
  assert.match(dataSourceServerRequests, /agentChatThreadIdForServerRequest\(getActiveThreadId\(\), request\)/)
  assert.match(dataSourceServerRequests, /markThreadOpen\(requestThreadId\)/)
  assert.doesNotMatch(dataSourceShell, /if \(request\.threadId && request\.threadId !== currentThreadId\)/)
  assert.doesNotMatch(dataSourceShell, /writeStoredActiveThreadId|readStoredActiveThreadId/)
  assert.doesNotMatch(dataSourceShell, /request\.threadId && currentThreadId && request\.threadId !== currentThreadId\) return undefined/)
  assert.doesNotMatch(dataSourceShell, /request\.threadId && !currentThreadId\) return undefined/)
  assert.match(dataSourceShellCoreState, /selectAgentChatRuntimePendingThreadReadRequests/)
  assert.match(dataSourceShell, /from '@\/features\/agent\/application\/useAgentChatThreadRuntimeEffects'/)
  assert.match(dataSourceThreadRuntimeEffects, /type: 'beginThreadReadRequest'/)
  assert.match(dataSourceThreadRuntimeEffects, /type: 'completeThreadReadRequest'/)
  assert.match(dataSourceLoadEffect, /type: 'reset'/)
  assert.match(dataSourceServerRequests, /type: 'enqueueServerRequest'/)
  assert.match(dataSourceServerRequests, /type: 'resolveServerRequest'/)
  assert.match(dataSourceShell, /visibleStatusItems=\{visibleStatusItems\}/)
  assert.match(dataSourceShellView, /statusItems=\{visibleStatusItems\}/)
  assert.match(dataSourceShellParts, /AgentPinnedStatusShelf/)
  assert.doesNotMatch(dataSourceShell, /agentChatStatusSummaryEntryFromNotification/)
  assert.doesNotMatch(dataSourceShell, /agentChatNotificationEventIsStatusSummary/)
  assert.doesNotMatch(dataSourceShell, /updateStreamingAgentItems\(\(\) => \(\{\}\)\)/)
  assert.doesNotMatch(dataSourceShell, /streamingAgentItemsRef/)
  assert.doesNotMatch(dataSourceShell, /notification\.method === 'item\//)
  assert.doesNotMatch(dataSourceShell, /appendAgentChatDeltaTurnItem|appendAgentChatCommandTerminalInteraction|appendAgentChatMcpToolCallProgress|appendAgentChatTurnItem/)
  assert.doesNotMatch(dataSourceShell, /applyAgentChatNotificationEventToThread|ensureAgentChatReasoningSummaryPart|setAgentChatContextCompaction|setAgentChatFileChangePatch|setAgentChatTurnPlan|setAgentChatTurnDiff/)
  assert.doesNotMatch(dataSourceShell, /upsertAgentChatApprovalReview|upsertAgentChatSystemNotice|upsertAgentChatTurn/)
  assert.doesNotMatch(dataSourceShell, /function AgentChatCapabilityEventCard|function agentChatCapabilityEventTitle|function agentChatCapabilityEventDetail/)
  assert.doesNotMatch(dataSourceShell, /AgentMessageSection|agentChatContentDefaultOpen/)
  assert.match(dataSourceRecentCapabilityEventCard, /AgentChatRecentCapabilityEventCard/)
  assert.match(dataSourceRecentCapabilityEventCard, /agentChatRecentCapabilityEventView/)
  assert.match(dataSourceRecentCapabilityEventCard, /AgentChatThreadItemBlocks/)
  assert.match(dataSourceRecentCapabilityEventCard, /label="Details"/)
  assert.doesNotMatch(dataSourceRecentCapabilityEventCard, /label="Event details"/)
  assert.doesNotMatch(dataSourceRecentCapabilityEventCard, /event\.raw !== undefined/)
  assert.doesNotMatch(dataSourceRecentCapabilityEventCard, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem|AgentRunStep|anthropic_messages/)
  assert.match(neutralNotificationDispatcher, /export function dispatchAgentChatNotification/)
  assert.match(neutralNotificationDispatcher, /export function buildAgentChatVisibleItems/)
  assert.match(neutralNotificationDispatcher, /export function agentChatNotificationEventShouldDisplayAsRecent/)
  assert.match(neutralNotificationDispatchCoverage, /AGENT_CHAT_NOTIFICATION_METHOD_DISPATCH_COVERAGE/)
  assert.match(neutralNotificationDispatchCoverage, /AGENT_CHAT_NOTIFICATION_EVENT_DISPATCH_COVERAGE/)
  assert.match(neutralNotificationDispatchCoverage, /commandOutput[\s\S]*processId/)
  assert.match(neutralNotificationDispatcher, /notification\.method === 'thread\/started'/)
  assert.match(neutralNotificationDispatcher, /notification\.method === 'thread\/status\/changed'/)
  assert.match(neutralNotificationDispatcher, /notification\.method === 'thread\/name\/updated'/)
  assert.match(neutralNotificationDispatcher, /turn\/plan\/updated/)
  assert.match(neutralNotificationDispatcher, /turn\/diff\/updated/)
  assert.match(neutralNotificationDispatcher, /event\.type === 'threadLifecycle'/)
  assert.match(neutralNotificationDispatcher, /event\.type === 'serverRequestResolved'/)
  assert.match(neutralNotificationDispatcher, /agentChatPendingServerRequestMatchesResolvedEvent/)
  assert.doesNotMatch(neutralNotificationDispatcher, /item\.request\.id === event\.requestId/)
  assert.match(neutralNotificationDispatcher, /notification\.method === 'item\/plan\/delta'/)
  assert.match(neutralNotificationDispatcher, /item\/reasoning\/textDelta/)
  assert.match(neutralNotificationDispatcher, /item\/reasoning\/summaryPartAdded/)
  assert.match(neutralNotificationDispatcher, /item\/fileChange\/outputDelta/)
  assert.match(neutralNotificationDispatcher, /item\/fileChange\/patchUpdated/)
  assert.match(neutralNotificationDispatcher, /item\/mcpToolCall\/progress/)
  assert.match(neutralNotificationDispatcher, /item\/commandExecution\/terminalInteraction/)
  assert.match(neutralNotificationDispatcher, /item\/autoApprovalReview\/started/)
  assert.match(neutralNotificationDispatcher, /item\/autoApprovalReview\/completed/)
  assert.match(neutralNotificationDispatcher, /thread\/compacted/)
  assert.match(neutralNotificationDispatcher, /appendAgentChatDeltaTurnItem/)
  assert.match(neutralNotificationDispatcher, /appendAgentChatCommandTerminalInteraction/)
  assert.match(neutralNotificationDispatcher, /appendAgentChatMcpToolCallProgress/)
  assert.match(neutralNotificationDispatcher, /appendAgentChatTurnItem/)
  assert.match(neutralNotificationDispatcher, /applyAgentChatNotificationEventToThread/)
  assert.match(neutralNotificationDispatcher, /ensureAgentChatReasoningSummaryPart/)
  assert.match(neutralNotificationDispatcher, /setAgentChatContextCompaction/)
  assert.match(neutralNotificationDispatcher, /setAgentChatFileChangePatch/)
  assert.match(neutralNotificationDispatcher, /setAgentChatTurnPlan/)
  assert.match(neutralNotificationDispatcher, /setAgentChatTurnDiff/)
  assert.match(neutralNotificationDispatcher, /upsertAgentChatApprovalReview/)
  assert.match(neutralNotificationDispatcher, /upsertAgentChatSystemNotice/)
  assert.match(neutralNotificationDispatcher, /threadId: event\.threadId/)
  assert.match(neutralNotificationDispatcher, /turnId: event\.turnId/)
  assert.match(neutralNotificationDispatcher, /upsertAgentChatTurn/)
  assert.match(neutralThreadState, /event\.type === 'commandOutput'/)
  assert.doesNotMatch(neutralNotificationDispatcher, /CodexThread|CodexTurn|CodexThreadItem|AgentRunStep|AgentMessage/)
  assert.doesNotMatch(neutralNotificationDispatchCoverage, /CodexThread|CodexTurn|CodexThreadItem|AgentRunStep|AgentMessage/)
  assert.match(neutralThreadState, /export function upsertAgentChatTurn/)
  assert.match(neutralThreadState, /export function appendAgentChatTurnItem/)
  assert.match(neutralThreadState, /export function appendAgentChatDeltaTurnItem/)
  assert.match(neutralThreadState, /export function appendAgentChatCommandTerminalInteraction/)
  assert.match(neutralThreadState, /export function appendAgentChatMcpToolCallProgress/)
  assert.match(neutralThreadState, /export function upsertAgentChatApprovalReview/)
  assert.match(neutralThreadState, /export function upsertAgentChatSystemNotice/)
  assert.match(neutralThreadState, /export function setAgentChatContextCompaction/)
  assert.match(neutralThreadState, /export function setAgentChatFileChangePatch/)
  assert.match(neutralThreadState, /export function ensureAgentChatReasoningSummaryPart/)
  assert.match(neutralThreadState, /export function setAgentChatTurnPlan/)
  assert.match(neutralThreadState, /items,\s*raw: \{ explanation, plan \}/)
  assert.match(neutralThreadState, /export function setAgentChatTurnDiff/)
  assert.match(neutralThreadState, /export function applyAgentChatNotificationEventToThread/)
  assert.match(neutralThreadState, /event\.type === 'processOutput'/)
  assert.match(neutralThreadState, /event\.type === 'processExited'/)
  assert.doesNotMatch(neutralThreadState, /CodexThread|CodexTurn|CodexThreadItem|AgentRunStep|AgentMessage/)
  assert.match(neutralNotificationDispatcher, /function isAgentChatNotificationNeutralThreadItem/)
  assert.match(neutralNotificationDispatcher, /AGENT_CHAT_NEUTRAL_THREAD_ITEM_TYPES\.has\(providerType\) && isAgentChatNotificationNeutralThreadItem\(value\)/)
  assert.match(dataSourceShellView, /showAttachmentTools/)
  assert.match(dataSourceShellView, /showDebugPreview=\{false\}/)
  assert.match(dataSourceShellView, /showMentionTools/)
  assert.match(dataSourceShellParts, /AgentThreadFill/)
  assert.match(dataSourceShell, /visiblePendingServerRequests/)
  assert.match(dataSourceShellView, /pendingServerRequests/)
  assert.match(dataSourceThreadLifecycleEffects, /dataSource\.subscribeServerRequests/)
  assert.match(dataSourceThreadLifecycleEffects, /onNotification: handleNotification/)
  assert.match(dataSourceThreadLifecycleEffects, /serverRequestSubscriptionMode !== 'globalWithThreadFallback'/)
  assert.match(dataSourceThreadLifecycleEffects, /handleServerRequest/)
  assert.match(neutralRuntime, /resolveAgentChatPendingServerRequest/)
  assert.match(neutralRuntime, /resolveAgentChatPendingServerRequest\(state\.pendingServerRequests, action\.request, action\.response\)/)
  assert.doesNotMatch(dataSourceShell, /item\.request\.id === requestId/)
  assert.doesNotMatch(dataSourceShell, /resolveAgentChatPendingServerRequest\(current, requestId/)
  assert.match(dataSourceServerRequests, /agentChatServerRequestResponseForAction/)
  assert.doesNotMatch(dataSourceShell, /@\/features\/agent\/domain\/agentChat(?:Protocol|ThreadItems|Runtime|Notification|Pending|Server|Recent|ThreadState)/)
  assert.doesNotMatch(dataSourceShell, /agentChatApproveResponse/)
  assert.doesNotMatch(dataSourceShell, /agentChatApproveForSessionResponse/)
  assert.doesNotMatch(dataSourceShell, /agentChatApproveWithStrictAutoReviewResponse/)
  assert.doesNotMatch(dataSourceShell, /agentChatApproveWithExecPolicyAmendmentResponse/)
  assert.doesNotMatch(dataSourceShell, /agentChatApproveWithNetworkPolicyAmendmentResponse/)
  assert.doesNotMatch(dataSourceShell, /agentChatCancelResponse/)
  assert.doesNotMatch(dataSourceShell, /agentChatRejectResponse/)
  assert.match(dataSourceShell, /<AgentChatShellView[\s\S]*visiblePendingServerRequests=\{visiblePendingServerRequests\}/)
  assert.match(dataSourceShellView, /pendingServerRequests=\{visiblePendingServerRequests\}/)
  assert.match(dataSourceShellParts, /AgentChatServerRequestCard/)
  assert.doesNotMatch(dataSourceShell, /function AgentChatServerRequestCard|function agentChatServerRequestTitle|function agentChatServerRequestCanApprove/)
  assert.match(dataSourceServerRequestCard, /label="Summary"/)
  assert.match(dataSourceServerRequestCard, /label="Arguments"/)
  assert.match(dataSourceServerRequestCard, /AgentChatInspectBlock/)
  assert.doesNotMatch(dataSourceServerRequestCard, /label="Request details"/)
  assert.match(dataSourceServerRequestCard, /AgentChatServerRequestCard/)
  assert.match(dataSourceServerRequestCard, /AgentChatServerRequestForms/)
  assert.match(dataSourceServerRequestCard, /agentChatServerRequestView/)
  assert.match(dataSourceServerRequestForms, /export function AgentChatServerRequestAnswerForm/)
  assert.match(dataSourceServerRequestForms, /export function AgentChatServerRequestElicitationForm/)
  assert.match(dataSourceServerRequestForms, /export function AgentChatServerRequestToolResultForm/)
  assert.match(dataSourceServerRequestForms, /agentChatInputRequestFormModel/)
  assert.match(dataSourceServerRequestForms, /agentChatElicitationFormModel/)
  assert.match(dataSourceServerRequestForms, /agentChatToolResultContentItems/)
  assert.doesNotMatch(dataSourceServerRequestCard, /@\/features\/agent\/domain\/agentChat(?:Protocol|ThreadItems|Runtime|Notification|Pending|Server|Recent|ThreadState)/)
  assert.doesNotMatch(dataSourceServerRequestCard, /agentChatServerRequestSummary/)
  assert.doesNotMatch(dataSourceServerRequestCard, /agentChatServerRequestCanApprove/)
  assert.doesNotMatch(dataSourceServerRequestCard, /agentChatServerRequestCanApproveForSession/)
  assert.doesNotMatch(dataSourceServerRequestCard, /agentChatServerRequestCanApproveWithStrictAutoReview/)
  assert.doesNotMatch(dataSourceServerRequestCard, /agentChatServerRequestCanApproveWithExecPolicyAmendment/)
  assert.doesNotMatch(dataSourceServerRequestCard, /agentChatServerRequestNetworkPolicyAmendments/)
  assert.doesNotMatch(dataSourceServerRequestCard, /agentChatServerRequestCanCancel/)
  assert.doesNotMatch(dataSourceServerRequestCard, /agentChatServerRequestExternalUrl/)
  assert.doesNotMatch(dataSourceServerRequestCard, /request\.params/)
  assert.match(dataSourceServerRequestForms, /agentChatInputRequestFormModel/)
  assert.match(dataSourceServerRequestForms, /agentChatInputRequestAnswerPayload/)
  assert.match(dataSourceServerRequestForms, /agentChatInputRequestFormCanSubmit/)
  assert.match(dataSourceServerRequestForms, /agentChatElicitationFormModel/)
  assert.match(dataSourceServerRequestForms, /agentChatElicitationFieldValueIsValid/)
  assert.match(dataSourceServerRequestForms, /agentChatElicitationContent/)
  assert.doesNotMatch(dataSourceServerRequestForms, /hasQuestionAnswers|hasInputFormAnswer|selectedFallbackChoice/)
  assert.doesNotMatch(dataSourceServerRequestForms, /function inputRequestFormModel|function answerPayload|function agentInputChoicesForForm/)
  assert.doesNotMatch(dataSourceServerRequestForms, /function elicitationFormModel|function elicitationContent|function elicitationFieldValueIsValid|function singleSelectOptionsFromSchema|function multiSelectOptionsFromSchema/)
  assert.match(dataSourceServerRequestCard, /Open URL/)
  assert.match(dataSourceServerRequestCard, /AgentChatThreadItemBlocks/)
  assert.doesNotMatch(dataSourceServerRequestCard, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.doesNotMatch(appServerThreadTurnItemProtocolAdapter, /@\/features\/agent\/domain\/agentChat/)
  assert.doesNotMatch(appServerThreadTurnItemMapper, /@\/features\/agent\/domain\/agentChat/)
  assert.doesNotMatch(dataSourceShell, /action: 'approve'|action: 'reject'/)
  assert.doesNotMatch(dataSourceShell, /decision: 'accept'|decision: 'decline'/)
  assert.match(dataSourceItemView, /case 'hookPrompt'/)
  assert.match(dataSourceItemView, /case 'collabAgentToolCall'/)
  assert.match(dataSourceItemView, /case 'fileChange'/)
  assert.match(dataSourceItemView, /AgentChatNeutralItemRenderers/)
  assert.match(dataSourceItemView, /assertNeverAgentChatThreadItem/)
  assert.doesNotMatch(dataSourceItemView, /default:[\s\S]{0,80}return null/)
  assert.doesNotMatch(dataSourceItemView, /AgentMessageSection|AgentChatThreadItemBlocks/)
  assert.doesNotMatch(dataSourceItemView, /agentChatContentDefaultOpen|agentChatListDefaultOpen/)
  assert.match(dataSourceNeutralItemRenderers, /AgentChatMessageItemRenderers/)
  assert.match(dataSourceNeutralItemRenderers, /AgentChatProcessItemRenderers/)
  assert.match(dataSourceNeutralItemRenderers, /AgentChatSystemItemRenderers/)
  assert.match(dataSourceNeutralItemRenderers, /AgentChatToolItemRenderers/)
  assert.doesNotMatch(dataSourceNeutralItemRenderers, /AgentMessageSection|AgentPlanOverviewList|label="/)
  assert.match(dataSourceMessageItemRenderers, /AgentChatUserMessageItem/)
  assert.match(dataSourceMessageItemRenderers, /AgentChatHookPromptItem/)
  assert.match(dataSourceMessageItemRenderers, /AgentChatAgentMessageItem/)
  assert.match(dataSourceMessageItemRenderers, /agentChatUserMessageView/)
  assert.match(dataSourceMessageItemRenderers, /agentChatHookPromptView/)
  assert.match(dataSourceMessageItemRenderers, /agentChatAgentMessageView/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /item\.raw/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /item\.memoryCitation/)
  assert.match(dataSourceProcessItemRenderers, /AgentChatReasoningItem/)
  assert.match(dataSourceProcessItemRenderers, /AgentChatPlanItem/)
  assert.match(dataSourceProcessItemRenderers, /agentChatReasoningItemView/)
  assert.match(dataSourceProcessItemRenderers, /agentChatPlanItemView/)
  assert.match(dataSourceProcessItemRenderers, /agentChatPlanStatusIntent/)
  assert.doesNotMatch(dataSourceProcessItemRenderers, /function agentChatReasoningMeta|function agentChatPlanItems|function agentChatPlanIntro|function agentChatPlanDetails|function agentChatReasoningTone/)
  assert.match(dataSourceSystemItemRenderers, /AgentChatSystemItem/)
  assert.match(dataSourceSystemItemRenderers, /agentChatSystemItemView/)
  assert.match(dataSourceProcessItemRenderers, /AgentPlanOverviewList/)
  assert.match(dataSourceProcessItemRenderers, /AgentPlanOverviewTaskCard/)
  assert.doesNotMatch(dataSourceProcessItemRenderers, /item\.result/)
  assert.doesNotMatch(dataSourceProcessItemRenderers, /item\.error/)
  assert.doesNotMatch(dataSourceProcessItemRenderers, /item\.raw/)
  assert.doesNotMatch(dataSourceProcessItemRenderers, /item\.text/)
  assert.match(dataSourceToolItemRenderers, /AgentChatCommandExecutionItem/)
  assert.match(dataSourceToolItemRenderers, /AgentChatToolCallItem/)
  assert.match(dataSourceToolItemRenderers, /AgentChatFileChangeItem/)
  assert.match(dataSourceToolItemRenderers, /AgentChatCollabAgentToolCallItem/)
  assert.match(dataSourceToolItemRenderers, /AgentChatWebSearchItem/)
  assert.match(dataSourceToolItemRenderers, /AgentChatImageItem/)
  assert.match(dataSourceToolItemRenderers, /label="Result"/)
  assert.match(dataSourceToolItemRenderers, /label="Error"/)
  assert.match(dataSourceToolItemRenderers, /label="Pending"/)
  assert.match(dataSourceToolItemRenderers, /agentChatCommandExecutionView/)
  assert.match(dataSourceToolItemRenderers, /from '@movscript\/core\/agent\/chat'/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /domain\/agentChatToolResultViews/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.aggregatedOutput/)
  assert.match(dataSourceToolItemRenderers, /agentChatToolCallView/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.arguments/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.contentItems/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.progressMessages/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.raw/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.prompt/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.query/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.action/)
  assert.match(dataSourceToolItemRenderers, /agentChatFileChangeView/)
  assert.match(dataSourceToolItemRenderers, /agentChatCollabAgentToolCallView/)
  assert.match(dataSourceToolItemRenderers, /agentChatWebSearchView/)
  assert.match(dataSourceToolItemRenderers, /agentChatImageItemView/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.revisedPrompt/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /item\.savedPath/)
  assert.match(dataSourceToolItemRenderers, /AgentChatInspectBlock/)
  assert.match(dataSourceMessageItemRenderers, /AgentChatInspectBlock/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /label="Tool details"/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /label="Text elements"/)
  assert.match(dataSourceMessageItemRenderers, /label="Attachments"/)
  assert.match(dataSourceMessageItemRenderers, /label="Media attachments"/)
  assert.match(dataSourceMessageItemRenderers, /AgentChatMediaPreviewGrid/)
  assert.match(dataSourceMessageItemRenderers, /agentChatUserMessageView/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /label="Attachment details"/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /label="User message details"/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /label="Hook details"/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /label="Message details"/)
  assert.match(dataSourceToolItemRenderers, /label="Output"/)
  assert.match(dataSourceToolItemRenderers, /label="Terminal input"/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /label="Command details"/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /label="File change details"/)
  assert.match(dataSourceProcessItemRenderers, /label="Trace summary"/)
  assert.doesNotMatch(dataSourceProcessItemRenderers, /label="Reasoning details"/)
  assert.doesNotMatch(dataSourceProcessItemRenderers, /label="Plan details"/)
  assert.match(dataSourceSystemItemRenderers, /label="Details"/)
  assert.match(dataSourceSystemItemRenderers, /AgentChatInspectBlock/)
  assert.doesNotMatch(dataSourceSystemItemRenderers, /label="Review"/)
  assert.match(neutralSystemItemViews, /approvalReview/)
  assert.match(neutralSystemItemViews, /reviewMode/)
  assert.match(neutralSystemItemViews, /contextCompaction/)
  assert.match(neutralSystemItemViews, /rawDetailsLabel: 'unknown'/)
  assert.doesNotMatch(dataSourceSystemItemRenderers, /item\.type/)
  assert.doesNotMatch(dataSourceSystemItemRenderers, /item\.review/)
  assert.doesNotMatch(dataSourceSystemItemRenderers, /item\.raw/)
  assert.doesNotMatch(dataSourceSystemItemRenderers, /function agentChatSystemTone|function agentChatApprovalReviewDetail|function agentChatApprovalReviewActionContext|function agentChatContextCompactionDetail|function agentChatUnknownDetail/)
  assert.match(dataSourceMessageItemRenderers, /label="Hook runs"/)
  assert.match(dataSourceMessageItemRenderers, /label="Prompt"/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /function agentChatInputLabel|function agentChatMentionMediaPreviews|function agentChatTextElementLabel|function userMessageText|function agentChatMessagePhaseLabel|function agentChatMemoryCitationSummary|function agentChatMemoryCitationEntryLabel/)
  assert.match(dataSourceToolItemRenderers, /label="Query"/)
  assert.match(dataSourceToolItemRenderers, /label="Action"/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /label="Search details"/)
  assert.match(dataSourceToolItemRenderers, /label="Revised prompt"/)
  assert.match(dataSourceToolItemRenderers, /label="Saved path"/)
  assert.match(dataSourceToolItemRenderers, /label="Agents"/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /label="Collab details"/)
  assert.match(dataSourceToolItemRenderers, /label="Image preview"/)
  assert.match(dataSourceToolItemRenderers, /label="Content media previews"/)
  assert.match(dataSourceItemBlocks, /export function AgentChatMediaPreviewGrid/)
  assert.match(neutralToolResultViews, /progressMessages/)
  assert.match(dataSourceItemView, /case 'webSearch'/)
  assert.match(dataSourceItemView, /case 'imageView'/)
  assert.match(dataSourceItemView, /case 'reviewMode'/)
  assert.match(dataSourceItemView, /case 'systemNotice'/)
  assert.match(dataSourceItemView, /case 'approvalReview'/)
  assert.match(dataSourceItemView, /case 'contextCompaction'/)
  assert.match(dataSourceItemView, /case 'unknown'/)
  assert.match(dataSourceToolItemRenderers, /@movscript\/core\/agent\/chat/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /function agentChatDynamicOutputSummary|function agentChatMcpResultView|function agentChatMcpResultTexts|function agentChatMcpResultImages|function agentChatMcpResultMedia/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /function agentChatCommandMeta|function agentChatToolMeta|function agentChatToolRoundMeta|function agentChatFileChangeSummary|function agentChatWebSearchActionSummary|function agentChatImageTone|function agentChatCollabMeta/)
  assert.doesNotMatch(dataSourceItemView, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.doesNotMatch(dataSourceNeutralItemRenderers, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.doesNotMatch(dataSourceMessageItemRenderers, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.doesNotMatch(dataSourceProcessItemRenderers, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.doesNotMatch(dataSourceSystemItemRenderers, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.doesNotMatch(dataSourceToolItemRenderers, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.match(dataSourceItemBlocks, /AgentChatResultStack/)
  assert.match(dataSourceItemBlocks, /AgentChatTinyBadge/)
  assert.match(dataSourceItemBlocks, /AgentMessageSection/)
  assert.match(dataSourceItemBlocks, /agentChatContentDefaultOpen/)
  assert.match(dataSourceItemBlocks, /agentChatListDefaultOpen/)
  assert.match(dataSourceItemBlocks, /from '@movscript\/core\/agent\/chat'/)
  assert.doesNotMatch(dataSourceItemBlocks, /domain\/agentChatDisplayPolicy/)
  assert.match(dataSourceRecentCapabilityEventCard, /from '@movscript\/core\/agent\/chat'/)
  assert.doesNotMatch(dataSourceRecentCapabilityEventCard, /domain\/agentChatDisplayPolicy/)
  assert.match(dataSourceItemBlocks, /export function AgentChatSectionTitle/)
  assert.match(dataSourceItemBlocks, /export function AgentChatInlineList/)
  assert.match(dataSourceItemBlocks, /export function AgentChatPreviewBlock/)
  assert.match(dataSourceItemBlocks, /export function AgentChatTextBlock/)
  assert.match(dataSourceItemBlocks, /export function agentChatValuePreview/)
  assert.doesNotMatch(dataSourceItemBlocks, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem|AgentRunStep/)
  assert.doesNotMatch(dataSourceShell, /AgentComposerField/)
  assert.doesNotMatch(dataSourceShell, /function AgentChatDataSourceComposerPanel/)
  assert.doesNotMatch(dataSourceShell, /grid-cols-\[240px/)
  assert.doesNotMatch(dataSourceShell, /rounded-md bg-primary/)
  assert.doesNotMatch(dataSourceShell, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)

  assert.match(appServerShell, /<AgentChatDataSourceShell/)
  assert.match(appServerShell, /providerInstanceId\(provider\)/)
  assert.match(appServerShell, /providerId: input\.provider\.id, providerInstanceId: providerInstanceId\(input\.provider\)/)
  assert.match(dataSourceFactory, /providerId: provider\.id/)
  assert.match(dataSourceFactory, /providerInstanceId: providerInstanceId\(provider\)/)
  assert.match(appServerDataSource, /providerId\?: string/)
  assert.match(appServerDataSource, /providerInstanceId\?: string/)
  assert.match(uiProtocol, /providerId\?: string/)
  assert.match(uiProtocol, /providerInstanceId\?: string/)
  assert.match(appServerShell, /selectActiveAgentConversationRegistryRecord/)
  assert.match(appServerShell, /export function appServerThreadScopeKey\(provider\?: ProviderConfig\): string \{[\s\S]{0,160}return appServerProviderScopedKey\(provider, 'threadScope'\)[\s\S]{0,20}\}/)
  assert.doesNotMatch(appServerShell, /appServerActiveThreadCompatStorageKey|appServerActiveThreadStorageKey|ACTIVE_APP_SERVER_THREAD_STORAGE_KEY/)
  assert.doesNotMatch(appServerShell, /codexAppServerProtocol/)
  assert.doesNotMatch(appServerShell, /codexAgentChatProtocolAdapter/)
  assert.doesNotMatch(appServerShell, /type CodexThread|type CodexTurn|type CodexThreadItem/)
  assert.doesNotMatch(unifiedShell, /AgentBuiltinChatShell/)

  assert.match(appServerThreadTurnItemProtocolAdapter, /appServerProtocol/)
  assert.doesNotMatch(appServerThreadTurnItemProtocolEventAdapters, /agentChatDisplayPolicy|agentChatContentDefaultOpen|AgentChatThreadItemView/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /APP_SERVER_THREAD_TURN_ITEM_NOTIFICATION_COVERAGE/)
  assert.match(appServerThreadTurnItemServerRequestCoverage, /APP_SERVER_THREAD_TURN_ITEM_SERVER_REQUEST_COVERAGE/)
  assert.match(appServerThreadTurnItemServerRequestCoverage, /account\/chatgptAuthTokens\/refresh[\s\S]*credential-refresh/)
  assert.match(appServerThreadTurnItemServerRequestCoverage, /attestation\/generate[\s\S]*attestation/)
  assert.match(appServerThreadTurnItemServerRequestCoverage, /applyPatchApproval[\s\S]*compat-approval/)
  assert.match(appServerThreadTurnItemServerRequestCoverage, /execCommandApproval[\s\S]*compat-approval/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /rawResponseItem\/completed[\s\S]*thread-item-notice/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /rawResponseItem\/completed/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /Raw response item completed/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /thread\/settings\/updated[\s\S]*metadata-invalidation/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /skills\/changed[\s\S]*invalidationOwner: 'plugin-catalog'/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /thread\/settings\/updated[\s\S]*invalidationOwner: 'thread-settings'/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /app\/list\/updated[\s\S]*invalidationOwner: 'app-metadata'/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /fuzzyFileSearch\/sessionUpdated[\s\S]*intentional-ignore/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /fuzzyFileSearch\/sessionUpdated[\s\S]*ignoreOwner: 'composer-search'/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /command\/exec\/outputDelta[\s\S]*eventOwner: 'neutral-dispatcher'/)
  assert.match(appServerThreadTurnItemNotificationCoverage, /thread\/realtime\/started[\s\S]*eventOwner: 'recent-capability-events'/)
  assert.doesNotMatch(appServerThreadTurnItemNotificationCoverage, /AgentChatDataSourceShell|AgentChatThreadItemView|codexAppServerProtocol/)
  assert.match(appServerThreadTurnItemMapper, /export function agentChatThreadItemFromAppServerThreadTurnItem/)
  assert.match(appServerThreadTurnItemMapper, /case 'hookPrompt'/)
  assert.match(appServerThreadTurnItemMapper, /case 'collabAgentToolCall'/)
  assert.match(appServerThreadTurnItemMapper, /case 'commandExecution'/)
  assert.match(appServerThreadTurnItemMapper, /case 'mcpToolCall'/)
  assert.match(appServerThreadTurnItemMapper, /case 'dynamicToolCall'/)
  assert.match(appServerThreadTurnItemMapper, /@movscript\/core\/agent\/chat/)
  assert.doesNotMatch(appServerThreadTurnItemMapper, /codexAppServerProtocol|codexAgentChatThreadItems/)
  assert.match(appServerThreadTurnItemProtocolAdapter, /thread\/started/)
  assert.match(appServerThreadTurnItemProtocolAdapter, /thread\/status\/changed/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /thread\/archived/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /serverRequest\/resolved/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /thread\/realtime\//)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /account\/updated/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /mcpServer\/startupStatus\/updated/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /model\/rerouted/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /model\/verification/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /thread\/tokenUsage\/updated/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /thread\/goal\/updated/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /hook\/completed/)
  assert.match(appServerThreadTurnItemProtocolEventAdapters, /configWarning/)
  assert.match(appServerThreadTurnItemProtocolAdapter, /acceptForSession/)
  assert.match(appServerThreadTurnItemProtocolAdapter, /decision: 'cancel'/)
  assert.match(appServerThreadTurnItemProtocolAdapter, /acceptWithExecpolicyAmendment/)
  assert.match(appServerThreadTurnItemProtocolAdapter, /applyNetworkPolicyAmendment/)
  assert.match(appServerDataSource, /createAppServerChatCapabilities/)
  assert.match(appServerChatCapabilities, /command\/exec/)
  assert.match(appServerDataSource, /appServerThreadTurnItemAdapter/)
  assert.match(appServerDataSource, /appServerThreadTurnItemUserInputFromAgentChat/)
  assert.match(appServerChatCapabilities, /AppServerClient/)
  assert.match(appServerThreadTurnItemAdapter, /appServerThreadTurnItemProtocolAdapter/)
  assert.doesNotMatch(appServerThreadTurnItemAdapter, /codexAgentChatProtocolAdapter|agentChatThreadFromCodex/)
  assert.doesNotMatch(appServerDataSource, /codexAgentChatProtocolAdapter|agentChatThreadFromCodex|agentChatTurnFromCodex|codexUserInputFromAgentChat|codexServerRequestResponseFromAgentChat/)
  assert.match(appServerDataSource, /client\.startTurn/)
  assert.match(appServerDataSource, /client\.steerTurn/)
  assert.match(appServerDataSource, /client\.interruptTurn/)
  assert.match(appServerDataSource, /thread\/name\/set/)
  assert.match(appServerDataSource, /thread\/archive/)
  assert.match(appServerDataSource, /thread\/unarchive/)
  assert.match(appServerChatCapabilities, /fs\/readFile/)
  assert.match(appServerChatCapabilities, /mcpServer\/tool\/call/)
  assert.match(appServerChatCapabilities, /plugin\/list/)
  assert.match(appServerChatCapabilities, /skills\/list/)
  assert.match(appServerChatCapabilities, /model\/list/)
  assert.match(appServerChatCapabilities, /config\/read/)
  assert.match(appServerChatCapabilities, /account\/read/)
  assert.match(appServerChatCapabilities, /permissionProfile\/list/)
  assert.match(appServerChatCapabilities, /thread\/realtime\/start/)
  assert.match(appServerChatCapabilities, /thread\/realtime\/appendAudio/)
  assert.match(appServerChatCapabilities, /thread\/realtime\/appendText/)
  assert.match(appServerChatCapabilities, /thread\/realtime\/stop/)
  assert.match(appServerChatCapabilities, /thread\/realtime\/listVoices/)
  assert.match(appServerDataSource, /subscribeServerRequests/)
  assert.match(appServerDataSource, /serverRequestSubscriptionMode: 'global'/)
  assert.match(appServerDataSource, /serverRequest\/resolved/)
  assert.match(appServerDataSource, /onNotification\?/)
  assert.match(appServerDataSource, /Promise\.resolve\(onServerRequest\?\.\(nextRequest\)\)/)
  assert.match(appServerDataSource, /appServerThreadTurnItemServerRequestResponseFromAgentChat/)
  assert.match(appServerShell, /App-server Provider/)
  assert.doesNotMatch(appServerShell, /App-server Agent/)
  assert.doesNotMatch(appServerRpcClientBoundary, /resolvedProvider\.[\s\S]{0,80}endpoint/)
  assert.match(appServerRpcClientBoundary, /resolveDefaultProvider/)
  assert.doesNotMatch(appServerRpcClientBoundary, new RegExp(['resolve', 'Codex', 'AgentProvider'].join('')))
  assert.match(appServerRpcClientBoundary, /providerScopedEnvURL\(env, provider\)/)
  assert.match(appServerRpcClientBoundary, /export function appServerScopedEnvURLKeys\(provider: ProviderConfig\)/)
  assert.match(appServerRpcClientBoundary, /profile\?\.providerKey/)
  assert.match(appServerRpcClientBoundary, /profile\?\.id/)
  assert.match(appServerRpcClientBoundary, /provider\.id/)
  assert.match(appServerRpcClientBoundary, /unscopedEnvURL\(env\)/)
  assert.doesNotMatch(appServerRpcClientBoundary, /codexAppServerWsUrl|VITE_CODEX_APP_SERVER_WS_URL|VITE_MOVSCRIPT_CODEX_APP_SERVER_WS_URL|movscript\.codexAppServerWsUrl/)
  assert.match(appServerRpcClientBoundary, /export function appServerURL/)
  assert.match(appServerRpcClient, /export function appServerClientForURL/)
  assert.match(appServerRpcClient, /export async function ensureAppServerURL/)
  assert.match(appServerRpcClient, /export async function ensureAppServerClient/)
  assert.match(appServerRpcClient, /export class AppServerDirectRpcClient/)
  assert.doesNotMatch(appServerRpcClient, new RegExp(['app', 'Server', 'Rpc', 'Client', 'For', 'URL'].join('')))
  assert.doesNotMatch(appServerRpcClient, new RegExp(['ensure', 'App', 'Server', 'Rpc', 'Client'].join('')))
  assert.doesNotMatch(appServerRpcClient, new RegExp(['App', 'Server', 'Rpc', 'Client'].join('')))
  assert.doesNotMatch(appServerRpcClient, new RegExp([
    ['ensure', 'Codex', 'App', 'Server'].join(''),
    ['Codex', 'App', 'Server', 'Rpc', 'Client'].join(''),
    ['codex', 'App', 'Server', 'URL'].join(''),
  ].join('|')))
  assert.match(appServerRpcClientBoundary, /searchParams\.get\('appServerWsUrl'\)/)
  assert.match(appServerManager, /return `\.\$\{providerKey\}`/)
  assert.doesNotMatch(appServerManager, /DEFAULT_MANAGED_CODEX_HOME_PATH|DEFAULT_MANAGED_MOVA_HOME_PATH|isCodexManagedAppServerHome|isMovaManagedAppServerHome/)
  assert.match(appServerManager, /launch provider home=/)
  assert.doesNotMatch(appServerManager, /launch env CODEX_HOME=/)
  assert.match(appServerManager, /pendingEnsures/)
  assert.match(appServerManagerTest, /keeps multiple profiles for one provider key isolated by profile id/)
  assert.match(appServerIpc, /appServerManager\.ensure\(input\)/)
  assert.doesNotMatch(appServerIpc, /codex:app-server-/)
  assert.doesNotMatch(appServerIpc, new RegExp([
    'spawn\\(executablePath',
    'reserveLocalPort',
    ['wait', 'For', 'Codex', 'App', 'Server', 'Ready'].join(''),
    'managedServers',
  ].join('|')))
  assert.doesNotMatch(agentConsolePage, /只连接已有|已有服务 endpoint|endpoint 必须/)
  assert.match(agentConsolePage, /home path 由对应 runtime profile 投影给启动进程/)
  assert.doesNotMatch(agentsPage, /local-codex-home|managed-codex-home|buildCodexAgentRecord|codexAuthSourceFromRecord|Codex home auth/)
  assert.match(agentsPage, /type AppServerConfigSource = 'local-machine' \| 'custom-service' \| 'backend'/)
  assert.doesNotMatch(agentsPage, /type AgentAuthSource/)
  assert.match(agentsPage, /PROVIDER_LOCAL_HOME_COMPAT_MODE/)
  assert.doesNotMatch(agentsPage, /LEGACY_PROVIDER_LOCAL_HOME_MODE/)
  assert.doesNotMatch(agentsPage, /OLD_LOCAL_HOME_CONFIG_MODE/)
  assert.match(agentsPage, /config: \{ mode: 'local-home' \}/)
  assert.match(agentsPage, /configSource: draft\.source/)
  assert.match(agentsPage, /MovScript 托管的 \{profile\.home\}\/config\.toml 和 \{profile\.home\}\/auth\.json/)
  assert.doesNotMatch(agentsPage, /auth:managed-home|auth:custom-config|auth:none/)
  assert.doesNotMatch(agentsPage, new RegExp(`config: \\{ mode: '${['local', 'Codex'].join('')}' \\}`))
  assert.doesNotMatch(agentConsolePage, /Profile ID/)
  assert.match(agentConsolePage, /继承本机账号/)
  assert.match(providerConfigDefaults, /MOVSCRIPT_MANAGED_CODEX_HOME = '\.codex'/)
  assert.match(providerConfigDefaults, /MOVSCRIPT_MANAGED_MOVA_HOME = '\.mova'/)
  assert.doesNotMatch(providerConfigDefaults, /CODEX_SYSTEM_AGENT_PROVIDER_ID|CODEX_SYSTEM_HOME_PROFILE_ID|DEFAULT_CODEX_SYSTEM_HOME_PROFILE/)
  assert.match(providerConfigDefaults, /export const CODEX_PROVIDER_ID = 'codex'/)
  assert.match(providerConfigDefaults, /export const MOVA_PROVIDER_ID = 'mova'/)
  assert.match(providerConfigDefaults, /export const PROVIDER_CONFIG_STORAGE_KEY = 'movscript-provider-config'/)
  assert.match(providerConfigAppServerProfile, /function normalizedAppServerProfileId/)
  assert.doesNotMatch(providerConfigAppServerProfile, /if \(kind === 'mova'\) return MOVA_MOVSCRIPT_HOME_PROFILE_ID/)
  assert.doesNotMatch(providerConfigAppServerProfile, /if \(kind === 'codex'\) return CODEX_MOVSCRIPT_HOME_PROFILE_ID/)
  assert.match(providerConfigDefaults, /MOVA_MOVSCRIPT_HOME_PROFILE_ID/)
  assert.match(providerConfigDefaults, /CODEX_MOVSCRIPT_HOME_PROFILE_ID/)
  assert.match(providerConfigAppServerProfile, /function managedAppServerHome/)
  assert.match(providerConfigAppServerProfile, /function managedAppServerHomePath/)
  assert.doesNotMatch(providerConfigAppServerProfile, /if \(kind === 'mova'\)|if \(kind === 'codex'\)/)
  assert.doesNotMatch(providerConfigAppServerProfile, /trimmed === '~\/\.codex'/)
  assert.match(agentConsolePage, /AgentCapabilityProbePanel/)
  assert.match(agentConsolePage, /useAgentControlCenter\(\)/)
  const removedRuntimeApi = new RegExp([
    ['ensure', 'Agent', 'Runtime'].join(''),
    ['stop', 'Agent', 'Runtime'].join(''),
  ].join('|'))
  const directAppServerIpcApi = new RegExp([
    ['ensure', 'Codex', 'App', 'Server'].join(''),
    ['stop', 'Codex', 'App', 'Server'].join(''),
    ['get', 'Codex', 'App', 'Server', 'Status'].join(''),
  ].join('|'))
  assert.doesNotMatch(agentConsolePage, new RegExp(`${removedRuntimeApi.source}|${directAppServerIpcApi.source}`))
  assert.doesNotMatch(agentControlCenterHook, removedRuntimeApi)
  assert.match(agentControlCenterHook, /@\/shared\/infrastructure\/app-server\/appServerRpcClient/)
  assert.doesNotMatch(agentControlCenterHook, directAppServerIpcApi)
  assert.match(agentControlCenterHook, /inspectAgentControlProviderCapabilities/)
  assert.doesNotMatch(agentControlCenterHook, /available: 0,[\s\S]{0,80}blocked: 0,[\s\S]{0,80}discovered: 0/)
  assert.match(agentControlCenter, /mcpServerStatus\/list|listServers/)
  assert.match(agentControlCenter, /plugins\?\.installed/)
  assert.match(agentControlCenter, /plugin\/installed|inspectAgentControlInstalledPlugins/)
  assert.match(agentControlCenter, /skills\/list|skills\?\.list/)
  assert.match(agentControlCenter, /appServerPolicy: 'status-only'/)
  assert.doesNotMatch(projectAgentModePage, /appServerPolicy: 'status-only'/)
  assert.match(agentThreadRegistryHydration, /\['app-server-threads', provider\.id, providerInstanceId\(provider\), 'agent-thread-registry-hydration'\]/)
  assert.match(appServerShell, /useAgentThreadRegistryHydration\(\{[\s\S]*userId,[\s\S]*provider,[\s\S]*enabled: Boolean\(provider\),/)
  assert.match(projectAgentContentPanel, /selectActiveAgentConversationRegistryRecord/)
  assert.doesNotMatch(projectAgentModePage, /readAppServerActiveThreadId|appServerActiveThreadStorageKey/)
  assert.doesNotMatch(projectAgentModePage, /function AppServerSidebarActiveThread/)
  assert.match(projectAgentModePage, /const sortedChatConversations = chatConversations/)
  assert.match(agentConsolePage, /title="Capabilities"/)
  assert.match(agentConsolePage, /AgentCapabilityHealthPanel/)
  assert.match(agentConsoleCapabilityPanels, /运行中 Provider 能力健康/)
  assert.match(agentConsoleCapabilityPanels, /刷新 Provider 能力/)
  assert.match(agentConsolePage, /Runtime ThreadRef/)
  assert.doesNotMatch(agentConsolePage, /刷新 Agent 能力|每个已启用 Agent|后续 Agent|个 Agent 可探测|没有已启用 Agent|运行中 Agent 能力健康|Provider ThreadRef|Agent ThreadRef/)
  assert.doesNotMatch(agentControlCenterHook, /app-server Agent/)
  assert.match(agentControlCenterHook, /app-server provider/)
  assert.match(agentsPage, /function providerDisplayTitle/)
  assert.doesNotMatch(agentsPage, /function agentTitle/)
  assert.match(agentConsoleCapabilityPanels, /createAgentChatDataSourceForProvider\(provider\)/)
  assert.match(agentConsoleCapabilityPanels, /probeAgentChatDataSourceCapabilities/)
  assert.doesNotMatch(agentConsolePage, /requestProtocol\(|codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem/)
  assert.match(agentConsoleCapabilityPanels, /from '@movscript\/core\/agent\/chat'/)
  assert.equal(existsSync(resolve('src/features/agent/application/agentChatCapabilityProbe.ts')), false)
  assert.match(coreCapabilityProbe, /AgentChatDataSource/)
  assert.match(coreCapabilityProbe, /capabilities\?\.command\?\.exec/)
  assert.match(coreCapabilityProbe, /capabilities\?\.fs\?\.readFile/)
  assert.match(coreCapabilityProbe, /mcpServerStatus\/list/)
  assert.match(coreCapabilityProbe, /thread\/realtime\/listVoices/)
  assert.doesNotMatch(coreCapabilityProbe, /codexAppServerProtocol|CodexThread|CodexTurn|CodexThreadItem|from ['"]@\/|from 'react'|@movscript\/ui|window\.|document\.|localStorage|sessionStorage/)

  assert.equal(existsSync(resolve(['src/features/agent/components/', 'MovScript', 'Agent', 'Chat', 'Shell.tsx'].join(''))), false)
  assert.equal(existsSync(resolve("src/shared/infrastructure/provider-session-client/movscriptAgentChatDataSource.ts")), false)
  assert.equal(existsSync(resolve("src/shared/infrastructure/provider-session-client/movscriptAgentChatProtocolAdapter.ts")), false)

  assert.match(dataSourceFactory, /createAppServerChatDataSource/)
  assert.match(dataSourceFactory, /messageAdapter: provider\.messageAdapter/)
  assert.match(appServerShell, /messageAdapter: input\.provider\?\.messageAdapter/)
  assert.match(dataSourceFactory, /@\/shared\/infrastructure\/app-server\/appServerChatDataSource/)
  assert.match(dataSourceFactory, /ensureAppServerClient/)
  assert.match(dataSourceFactory, /appServerClientForURL/)
  assert.match(dataSourceFactory, /@\/shared\/infrastructure\/app-server\/appServerRpcClient/)
  assert.match(appServerDataSource, /messageAdapter\?: AppServerChatMessageAdapterKind/)
  assert.match(appServerDataSource, /function appServerMessageAdapter/)
  assert.match(appServerDataSource, /function appServerProviderTitle/)
  assert.doesNotMatch(appServerDataSource, /provider === 'mova' \?/)
  assert.match(appServerDataSource, /Unsupported app-server message adapter/)
  assert.match(appServerDataSource, /@\/shared\/infrastructure\/app-server\/appServerProtocol/)
  assert.match(coreRunProfilePreset, /export type AgentRunApprovalPolicy/)
  assert.match(coreRunProfilePreset, /export type AgentRunSandboxMode/)
  assert.doesNotMatch(runProfilePreset, /@\/shared\/infrastructure\/app-server\/appServerProtocol/)
  assert.match(appServerProtocol, /app-server\/app-server-protocol\/v2/)
  assert.doesNotMatch(runProfilePreset, new RegExp(`${['codex', 'app-server'].join('-')}\\/app-server-protocol`))
  assert.match(appServerRpcClient, /AppServerDirectRpcClient/)
  assert.doesNotMatch(appServerRpcClient, new RegExp(['App', 'Server', 'Rpc', 'Client'].join('')))
  assert.match(appServerRpcClientBoundary, /resolveDefaultProvider/)
  assert.match(appServerRpcClientBoundary, /useProviderConfigStore/)
  assert.doesNotMatch(appServerRpcClient, /resolveDefaultAgentProvider|useAgentProviderConfigStore|AgentProviderConfig/)
  assert.doesNotMatch(appServerRpcClient, new RegExp([
    `${['Codex', 'App', 'Server', 'Rpc', 'Client'].join('')} as ${['App', 'Server', 'Rpc', 'Client'].join('')}`,
    `${['ensure', 'Codex', 'App', 'Server', 'URL'].join('')} as ensureAppServerURL`,
  ].join('|')))
  assert.doesNotMatch(dataSourceFactory, new RegExp(`@\\/shared\\/infrastructure\\/${['codex', 'app-server'].join('-')}\\/codexAgentChatDataSource`))
  assert.doesNotMatch(dataSourceFactory, new RegExp(`@\\/shared\\/infrastructure\\/${['codex', 'app-server'].join('-')}\\/codexAppServerRpcClient`))
  assert.doesNotMatch(dataSourceFactory, /codexAgentChatProtocolAdapter|agentChatThreadFromCodex|agentChatTurnFromCodex/)
  assert.doesNotMatch(dataSourceFactory, new RegExp(['create', 'MovScript', 'Agent', 'Chat', 'Data', 'Source'].join('')))
  assert.match(uiProtocol, /export type AgentChatProviderKind = 'codex' \| 'mova' \| 'claude' \| \(string & \{\}\)/)
  assert.match(providerConfigStore, /export type BuiltInProviderKind = 'codex' \| 'mova' \| 'claude'/)
  assert.match(providerConfigStore, /export type ProviderKind = BuiltInProviderKind \| \(string & \{\}\)/)
  assert.match(providerConfigStore, /export type BuiltInProviderProtocol = 'app-server' \| 'claude-code'/)
  assert.match(providerConfigStore, /export type ProviderProtocol = BuiltInProviderProtocol \| \(string & \{\}\)/)
  assert.match(providerConfigStore, /export type BuiltInProviderMessageAdapterKind = 'thread-turn-item' \| 'claude-thread-message'/)
  assert.match(providerConfigStore, /export type ProviderMessageAdapterKind = BuiltInProviderMessageAdapterKind \| \(string & \{\}\)/)
  assert.match(providerConfigStore, /export interface ProviderThreadRef/)
  assert.match(providerConfigStore, /export function createProviderThreadRef/)
  assert.match(providerConfigStore, /export function providerThreadRefKey/)
  assert.doesNotMatch(providerConfigStore, /AgentProviderConfig|AgentProviderSettings|useAgentProviderConfigStore/)
  assert.equal(existsSync(resolve('src/features/agent/state/agentProviderConfigStore.ts')), false)
  assert.doesNotMatch(providerConfigStore, new RegExp([
    'codex-thread-turn-item',
    ['codex', 'Profile'].join(''),
    ['mova', 'Profile'].join(''),
    ['codex', 'Home'].join(''),
  ].join('|')))
  assert.match(providerConfigStore, /export function usesAppServerProtocol/)
  assert.doesNotMatch(dataSourceFactory, /Claude|claude|anthropic_messages/)
  assert.doesNotMatch(dataSourceShell, /Claude|claude|anthropic_messages/)
})

test('agent chat item mapping stays layered by provider boundary', () => {
  const neutralItemProtocol = readFileSync(resolve('../../packages/core/src/agent/chat/agentChatThreadItems.ts'), 'utf8')
  const neutralItemView = readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatThreadItemView.tsx'), 'utf8')
  const neutralItemRenderers = [
    readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatMessageItemRenderers.tsx'), 'utf8'),
    readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatProcessItemRenderers.tsx'), 'utf8'),
    readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatSystemItemRenderers.tsx'), 'utf8'),
    readFileSync(resolve('src/features/agent/components/agent-chat-items/AgentChatToolItemRenderers.tsx'), 'utf8'),
  ].join('\n')
  const appServerThreadTurnItemMapper = readFileSync(resolve('src/shared/infrastructure/app-server/appServerThreadTurnItemItems.ts'), 'utf8')

  assert.match(neutralItemProtocol, /export type AgentChatThreadItem/)
  assert.doesNotMatch(neutralItemProtocol, /CodexThread|CodexTurn|CodexThreadItem|AgentRunStep|AgentMessage|anthropic_messages/)
  assert.doesNotMatch(neutralItemView, new RegExp([
    'codexAgentChatThreadItems',
    ['agent', 'Runtime', 'Chat', 'Thread', 'Items'].join(''),
    'codexAppServerProtocol',
    ['@movscript', 'protocol'].join('/'),
  ].join('|')))
  assert.doesNotMatch(neutralItemRenderers, new RegExp([
    'codexAgentChatThreadItems',
    ['agent', 'Runtime', 'Chat', 'Thread', 'Items'].join(''),
    'codexAppServerProtocol',
    ['@movscript', 'protocol'].join('/'),
  ].join('|')))

  assert.match(appServerThreadTurnItemMapper, /from '@movscript\/core\/agent\/chat'/)
  assert.match(appServerThreadTurnItemMapper, /from '@\/shared\/infrastructure\/app-server\/appServerProtocol'/)
  assert.match(appServerThreadTurnItemMapper, /agentChatLocalPathPreviewUrl/)
  assert.doesNotMatch(appServerThreadTurnItemMapper, new RegExp([
    'AgentChatThreadItemView',
    'AgentChat.*Renderers',
    'AgentChatDataSourceShell',
    ['@movscript', 'protocol'].join('/'),
    'codexAppServerProtocol',
  ].join('|')))

  assert.equal(existsSync(resolve('src/shared/infrastructure/claude-agent-client/claudeAgentChatThreadItems.ts')), false)
})
