import {
  AGENT_CONNECTION_WORKSPACE_PANES,
  AGENT_SETTINGS_DOCUMENT_ROUTE,
  APP_SHELL_AGENT_PANES,
  APP_SHELL_PROJECT_PANES,
  APP_SHELL_REMOTION_STUDIO_SHELL_WORKBENCH_DOCK_PANE,
  APP_SHELL_TOOL_PANES,
  CANVAS_PANES,
  CONTENT_CANVAS_WORKBENCH_PANES,
  HOME_ROUTE,
  PLUGIN_TOOL_NATIVE_LAYOUT_NOTE,
  PLUGIN_TOOL_WORKBENCH_PANES,
  PROJECT_WORKSPACE_ROUTE,
  REDIRECT_ROUTE,
  SETTINGS_WORKSPACE_ROUTE,
  TOOL_DOCUMENT_ROUTE,
  TOOL_WORKSPACE_ROUTE,
  TOOL_WORKBENCH_PANES,
  WORKSPACE_CONFIG_PANES,
  WORKSPACE_REVIEW_PANES,
  withShellWorkbenchDock,
} from './routeLayoutPanes'
import { appRouteViewportScrollForMode as sharedAppRouteViewportScrollForMode } from '@movscript/ui/layout'
import type { RouteLayoutSpec, RouteLayoutViewportScroll, RouteScrollMode } from './routeLayoutTypes'

import { ROUTES } from './projectRoutes'

export type * from './routeLayoutTypes'
export {
  AGENT_CONNECTION_EVENTS_PANE_ID,
  AGENT_CONNECTION_RAW_PANE_ID,
  AGENT_CONNECTION_THREADS_PANE_ID,
  APP_SHELL_AGENT_CONTENT_PANE_ID,
  APP_SHELL_AGENT_SIDEBAR_PANE_ID,
  APP_SHELL_PROJECT_AGENT_PANE_ID,
  APP_SHELL_SETTINGS_SIDEBAR_PANE_ID,
  APP_SHELL_SETTINGS_SIDEBAR_WIDTH_STORAGE_KEY,
  APP_SHELL_SHELL_WORKBENCH_DOCK_DEFAULT_HEIGHT,
  APP_SHELL_SHELL_WORKBENCH_DOCK_HEIGHT_STORAGE_KEY,
  APP_SHELL_SHELL_WORKBENCH_DOCK_MAX_HEIGHT,
  APP_SHELL_SHELL_WORKBENCH_DOCK_MIN_HEIGHT,
  APP_SHELL_SHELL_WORKBENCH_DOCK_PANE_ID,
  APP_SHELL_SHELL_WORKBENCH_DOCK_STATE_STORAGE_KEY,
  APP_SHELL_TOOL_SIDEBAR_PANE_ID,
  CANVAS_PALETTE_PANE_ID,
  CANVAS_WORKFLOW_PANE_DEFAULT_WIDTH,
  CANVAS_WORKFLOW_PANE_ID,
  CANVAS_WORKFLOW_PANE_MAX_WIDTH,
  CANVAS_WORKFLOW_PANE_MIN_WIDTH,
  CANVAS_WORKFLOW_PANE_WIDTH_STORAGE_KEY,
  CONTENT_CANVAS_INSPECTOR_DEFAULT_WIDTH,
  CONTENT_CANVAS_INSPECTOR_MAX_WIDTH,
  CONTENT_CANVAS_INSPECTOR_MIN_WIDTH,
  CONTENT_CANVAS_INSPECTOR_PANE_ID,
  CONTENT_CANVAS_INSPECTOR_WIDTH_STORAGE_KEY,
  CONTENT_CANVAS_STRUCTURE_DEFAULT_WIDTH,
  CONTENT_CANVAS_STRUCTURE_MAX_WIDTH,
  CONTENT_CANVAS_STRUCTURE_MIN_WIDTH,
  CONTENT_CANVAS_STRUCTURE_PANE_ID,
  CONTENT_CANVAS_STRUCTURE_WIDTH_STORAGE_KEY,
  CONTENT_CANVAS_TIMELINE_DEFAULT_HEIGHT,
  CONTENT_CANVAS_TIMELINE_HEIGHT_STORAGE_KEY,
  CONTENT_CANVAS_TIMELINE_MAX_HEIGHT,
  CONTENT_CANVAS_TIMELINE_MIN_HEIGHT,
  CONTENT_CANVAS_TIMELINE_PANE_ID,
  WORKSPACE_CONFIG_EDITOR_PANE_ID,
  WORKSPACE_CONFIG_FILE_TREE_PANE_ID,
  WORKSPACE_REVIEW_RAW_PANE_ID,
  WORKSPACE_REVIEW_SUMMARY_PANE_ID,
} from './routeLayoutPanes'

interface RouteLayoutRegistryEntry extends RouteLayoutSpec {
  match: (pathname: string) => boolean
}

const routeLayoutRegistry: RouteLayoutRegistryEntry[] = [
  route({
    routeId: 'invite',
    pathnamePattern: ROUTES.invite,
    kind: 'page',
    surface: 'tool',
    scrollMode: 'document',
    shellLayout: 'flush',
    panes: [],
    notes: 'Standalone invite recovery surface; authenticated direct route also bypasses ShellLayout.',
  }, (pathname) => /^\/invite\/[^/]+\/?$/.test(pathname)),
  route({
    routeId: 'canvas.editor',
    pathnamePattern: ROUTES.canvasEditor,
    kind: 'page',
    surface: 'canvas',
    scrollMode: 'canvas',
    shellLayout: 'flush',
    panes: CANVAS_PANES,
  }, (pathname) => /^\/canvases\/[^/]+\/?$/.test(pathname)),
  route({
    routeId: 'editing.project',
    pathnamePattern: ROUTES.editingProject,
    kind: 'page',
    surface: 'tool',
    scrollMode: 'workspace',
    shellLayout: 'flush',
    panes: [],
    projectEntryId: undefined,
    notes: 'Standalone editing project workspace; it opens in its own editingProject window and is not tied to a business project.',
  }, (pathname) => /^\/editing\/[^/]+\/?$/.test(pathname)),
  route({
    routeId: 'project.agent',
    pathnamePattern: ROUTES.project.agent,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'workspace',
    shellLayout: 'stacked',
    projectEntryId: undefined,
    panes: withShellWorkbenchDock(APP_SHELL_AGENT_PANES),
  }, (pathname) => pathname === ROUTES.project.agent),
  route({
    routeId: 'project.agentCanvases',
    pathnamePattern: ROUTES.project.agentCanvases,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'document',
    shellLayout: 'stacked',
    panes: APP_SHELL_AGENT_PANES,
  }, exact(ROUTES.project.agentCanvases)),
  route({
    routeId: 'project.root.redirect',
    pathnamePattern: ROUTES.project.root,
    ...REDIRECT_ROUTE,
  }, exact(ROUTES.project.root)),
  route({
    routeId: 'project.home',
    pathnamePattern: ROUTES.project.home,
    kind: 'page',
    surface: 'project',
    scrollMode: 'document',
    shellLayout: 'stacked',
    panes: APP_SHELL_PROJECT_PANES,
  }, exact(ROUTES.project.home)),
  route({
    routeId: 'project.standards',
    pathnamePattern: ROUTES.project.standards,
    ...PROJECT_WORKSPACE_ROUTE,
    projectEntryId: 'project_standards',
  }, exact(ROUTES.project.standards)),
  route({
    routeId: 'project.settings',
    pathnamePattern: ROUTES.project.settings,
    kind: 'page',
    surface: 'project',
    scrollMode: 'document',
    shellLayout: 'stacked',
    panes: APP_SHELL_PROJECT_PANES,
  }, exact(ROUTES.project.settings)),
  route({
    routeId: 'project.scripts',
    pathnamePattern: ROUTES.project.scripts,
    ...PROJECT_WORKSPACE_ROUTE,
    projectEntryId: 'orchestration_production',
    panes: withShellWorkbenchDock(PROJECT_WORKSPACE_ROUTE.panes),
  }, exact(ROUTES.project.scripts)),
  route({
    routeId: 'project.content',
    pathnamePattern: ROUTES.project.content,
    kind: 'page',
    surface: 'project',
    scrollMode: 'canvas',
    shellLayout: 'stacked',
    projectEntryId: 'content_preview',
    panes: [...APP_SHELL_PROJECT_PANES, ...CONTENT_CANVAS_WORKBENCH_PANES],
    notes: 'Legacy content entry opens the preview-first production surface.',
  }, exact(ROUTES.project.content)),
  route({
    routeId: 'project.content.canvas',
    pathnamePattern: ROUTES.project.contentCanvas,
    kind: 'page',
    surface: 'project',
    scrollMode: 'canvas',
    shellLayout: 'stacked',
    projectEntryId: 'content_canvas',
    panes: APP_SHELL_PROJECT_PANES,
    notes: 'Content canvas is a dedicated creation surface without preview or inspector panes.',
  }, exact(ROUTES.project.contentCanvas)),
  route({
    routeId: 'project.content.preview',
    pathnamePattern: ROUTES.project.contentPreview,
    kind: 'page',
    surface: 'project',
    scrollMode: 'canvas',
    shellLayout: 'stacked',
    projectEntryId: 'content_preview',
    panes: [...APP_SHELL_PROJECT_PANES, ...CONTENT_CANVAS_WORKBENCH_PANES],
    notes: 'Content preview is a dedicated review surface with structure and preview-detail panes.',
  }, exact(ROUTES.project.contentPreview)),
  route({
    routeId: 'project.remotionStudio',
    pathnamePattern: ROUTES.project.remotionStudio,
    kind: 'page',
    surface: 'project',
    scrollMode: 'workspace',
    shellLayout: 'stacked',
    panes: [...APP_SHELL_PROJECT_PANES, APP_SHELL_REMOTION_STUDIO_SHELL_WORKBENCH_DOCK_PANE],
  }, exact(ROUTES.project.remotionStudio)),
  route({
    routeId: 'project.setting.preview',
    pathnamePattern: ROUTES.project.settingPreview,
    kind: 'page',
    surface: 'project',
    scrollMode: 'canvas',
    shellLayout: 'stacked',
    projectEntryId: 'setting_preview',
    panes: [...APP_SHELL_PROJECT_PANES, ...CONTENT_CANVAS_WORKBENCH_PANES],
    notes: 'Setting preview is a dedicated review surface for setting namespace assets, states, and slots.',
  }, exact(ROUTES.project.settingPreview)),
  route({
    routeId: 'project.contentLegacy',
    pathnamePattern: ROUTES.project.contentLegacy,
    ...REDIRECT_ROUTE,
  }, exact(ROUTES.project.contentLegacy)),
  route({
    routeId: 'project.contentLegacyNext',
    pathnamePattern: ROUTES.project.contentLegacyNext,
    ...REDIRECT_ROUTE,
  }, exact(ROUTES.project.contentLegacyNext)),
  route({
    routeId: 'tools.image',
    pathnamePattern: ROUTES.tools.image,
    ...TOOL_WORKSPACE_ROUTE,
    panes: [...TOOL_WORKSPACE_ROUTE.panes, ...TOOL_WORKBENCH_PANES],
  }, exact(ROUTES.tools.image)),
  route({
    routeId: 'tools.video',
    pathnamePattern: ROUTES.tools.video,
    ...TOOL_WORKSPACE_ROUTE,
    panes: [...TOOL_WORKSPACE_ROUTE.panes, ...TOOL_WORKBENCH_PANES],
  }, exact(ROUTES.tools.video)),
  route({
    routeId: 'tools.audio',
    pathnamePattern: ROUTES.tools.audio,
    ...TOOL_WORKSPACE_ROUTE,
  }, exact(ROUTES.tools.audio)),
  route({
    routeId: 'tools.text',
    pathnamePattern: ROUTES.tools.text,
    ...TOOL_WORKSPACE_ROUTE,
  }, exact(ROUTES.tools.text)),
  route({
    routeId: 'tools.privateAssets',
    pathnamePattern: ROUTES.tools.privateAssets,
    ...TOOL_WORKSPACE_ROUTE,
  }, exact(ROUTES.tools.privateAssets)),
  route({
    routeId: 'tools.plugin',
    pathnamePattern: ROUTES.tools.plugin,
    ...TOOL_WORKSPACE_ROUTE,
    panes: [...TOOL_WORKSPACE_ROUTE.panes, ...PLUGIN_TOOL_WORKBENCH_PANES],
    notes: PLUGIN_TOOL_NATIVE_LAYOUT_NOTE,
  }, (pathname) => /^\/tools\/plugin\/[^/]+\/?$/.test(pathname)),
  route({
    routeId: 'admin.redirect',
    pathnamePattern: '/admin/*',
    ...REDIRECT_ROUTE,
  }, (pathname) => pathname === '/admin' || pathname.startsWith('/admin/')),
  route({
    routeId: 'account.settings',
    pathnamePattern: ROUTES.appSettings,
    ...SETTINGS_WORKSPACE_ROUTE,
    notes: 'Account settings are a neutral settings surface with a route-specific settings sidebar.',
  }, exact(ROUTES.appSettings)),
  route({
    routeId: 'account.profile',
    pathnamePattern: ROUTES.user,
    ...SETTINGS_WORKSPACE_ROUTE,
    notes: 'Account profile is hosted inside the neutral settings shell.',
  }, exact(ROUTES.user)),
  route({
    routeId: 'account.workspace',
    pathnamePattern: ROUTES.orgSettings,
    ...SETTINGS_WORKSPACE_ROUTE,
    notes: 'Workspace settings reuse the neutral settings shell.',
  }, exact(ROUTES.orgSettings)),
  route({
    routeId: 'org.select',
    pathnamePattern: ROUTES.orgSelect,
    ...TOOL_DOCUMENT_ROUTE,
    contentWidth: 'wide',
  }, exact(ROUTES.orgSelect)),
  route({
    routeId: 'home',
    pathnamePattern: ROUTES.root,
    ...HOME_ROUTE,
  }, exact(ROUTES.root)),
  route({
    routeId: 'projects',
    pathnamePattern: ROUTES.projects,
    ...TOOL_DOCUMENT_ROUTE,
  }, exact(ROUTES.projects)),
  route({
    routeId: 'projectData',
    pathnamePattern: ROUTES.projectData,
    kind: 'page',
    surface: 'home',
    scrollMode: 'document',
    shellLayout: 'stacked',
    panes: [],
    notes: 'Standalone project data window for production memory and candidate decisions; intentionally outside tool navigation.',
    contentWidth: 'wide',
  }, exact(ROUTES.projectData)),
  route({
    routeId: 'canvases',
    pathnamePattern: ROUTES.canvases,
    kind: 'page',
    surface: 'canvas',
    scrollMode: 'document',
    shellLayout: 'flush',
    panes: [],
    notes: 'Canvas list is a standalone canvas management program and bypasses the main app shell.',
    contentWidth: 'normal',
  }, exact(ROUTES.canvases)),
  route({
    routeId: 'editing',
    pathnamePattern: ROUTES.editing,
    kind: 'page',
    surface: 'tool',
    scrollMode: 'document',
    shellLayout: 'flush',
    panes: [],
    projectEntryId: undefined,
    notes: 'Standalone editing project list backed by Electron mediaPipeline and MediaEditingProject.',
  }, exact(ROUTES.editing)),
  route({
    routeId: 'resources',
    pathnamePattern: ROUTES.resources,
    ...TOOL_DOCUMENT_ROUTE,
    notes: 'Resource page is owned by resource-surface; the host provides chrome and runtime adapters.',
  }, exact(ROUTES.resources)),
  route({
    routeId: 'agent.resources',
    pathnamePattern: ROUTES.agentResources,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'document',
    shellLayout: 'flush',
    panes: [],
    notes: 'Agent browser resource library surface opened from MovScript MCP tools.',
  }, exact(ROUTES.agentResources)),
  route({
    routeId: 'agent.resourceDetail',
    pathnamePattern: ROUTES.agentResourceDetail,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'document',
    shellLayout: 'flush',
    panes: [],
    notes: 'Agent browser RawResource detail surface opened from MovScript MCP tools.',
  }, (pathname) => /^\/agent\/resources\/[^/]+\/?$/.test(pathname)),
  route({
    routeId: 'agent.contentPrompt',
    pathnamePattern: ROUTES.agentContentPrompt,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'workspace',
    shellLayout: 'flush',
    panes: [],
    notes: 'Agent browser content-unit prompt workbench surface opened from MovScript MCP tools.',
  }, exact(ROUTES.agentContentPrompt)),
  route({
    routeId: 'agent.contentCandidates',
    pathnamePattern: ROUTES.agentContentCandidates,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'workspace',
    shellLayout: 'flush',
    panes: [],
    notes: 'Agent browser content-unit candidate review surface opened from MovScript MCP tools.',
  }, exact(ROUTES.agentContentCandidates)),
  route({
    routeId: 'agent.generationJob',
    pathnamePattern: ROUTES.agentGenerationJob,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'document',
    shellLayout: 'flush',
    panes: [],
    notes: 'Agent browser generation job monitor surface opened from MovScript MCP tools.',
  }, (pathname) => /^\/agent\/generation\/jobs\/[^/]+\/?$/.test(pathname)),
  route({
    routeId: 'agent.previewTimeline',
    pathnamePattern: ROUTES.agentPreviewTimeline,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'workspace',
    shellLayout: 'flush',
    panes: [],
    notes: 'Agent browser production preview timeline surface opened from MovScript MCP tools.',
  }, exact(ROUTES.agentPreviewTimeline)),
  route({
    routeId: 'agent.impact',
    pathnamePattern: ROUTES.agentImpact,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'workspace',
    shellLayout: 'flush',
    panes: [],
    notes: 'Agent browser regeneration impact review surface opened from MovScript MCP tools.',
  }, exact(ROUTES.agentImpact)),
  route({
    routeId: 'agent.projectStatus',
    pathnamePattern: ROUTES.agentProjectStatus,
    kind: 'page',
    surface: 'agent',
    scrollMode: 'document',
    shellLayout: 'flush',
    panes: [],
    notes: 'Agent browser project status surface opened from MovScript MCP tools.',
  }, exact(ROUTES.agentProjectStatus)),
  route({
    routeId: 'resources.external',
    pathnamePattern: ROUTES.externalResources,
    ...TOOL_DOCUMENT_ROUTE,
    notes: 'External resource page is owned by resource-surface; the host keeps it in the tool workspace.',
  }, exact(ROUTES.externalResources)),
  route({
    routeId: 'shotLibrary',
    pathnamePattern: ROUTES.shotLibrary,
    ...TOOL_DOCUMENT_ROUTE,
  }, exact(ROUTES.shotLibrary)),
  route({
    routeId: 'jobs',
    pathnamePattern: ROUTES.jobs,
    ...TOOL_DOCUMENT_ROUTE,
  }, exact(ROUTES.jobs)),
  route({
    routeId: 'plugins',
    pathnamePattern: ROUTES.plugins,
    ...AGENT_SETTINGS_DOCUMENT_ROUTE,
  }, exact(ROUTES.plugins)),
  route({
    routeId: 'agent.console',
    pathnamePattern: ROUTES.agentConsole,
    ...SETTINGS_WORKSPACE_ROUTE,
    notes: 'Agent console is a settings tab hosted inside the neutral settings shell.',
  }, exact(ROUTES.agentConsole)),
  route({
    routeId: 'agent.connections',
    pathnamePattern: ROUTES.agentConnections,
    ...TOOL_WORKSPACE_ROUTE,
    panes: [...TOOL_WORKSPACE_ROUTE.panes, ...AGENT_CONNECTION_WORKSPACE_PANES],
  }, exact(ROUTES.agentConnections)),
  route({
    routeId: 'modelProviders',
    pathnamePattern: ROUTES.modelProviders,
    ...TOOL_DOCUMENT_ROUTE,
  }, exact(ROUTES.modelProviders)),
  route({
    routeId: 'agents.redirect',
    pathnamePattern: ROUTES.agents,
    ...REDIRECT_ROUTE,
  }, exact(ROUTES.agents)),
  route({
    routeId: 'agents.provider',
    pathnamePattern: ROUTES.agentProvider,
    ...AGENT_SETTINGS_DOCUMENT_ROUTE,
    notes: 'Provider agent settings stay inside the neutral settings chrome so switching agent configuration never changes the active work mode.',
  }, (pathname) => /^\/agents\/[^/]+\/?$/.test(pathname)),
  route({
    routeId: 'workspace.config',
    pathnamePattern: ROUTES.workspaceConfig,
    ...SETTINGS_WORKSPACE_ROUTE,
    panes: [...SETTINGS_WORKSPACE_ROUTE.panes, ...WORKSPACE_CONFIG_PANES],
  }, exact(ROUTES.workspaceConfig)),
  route({
    routeId: 'workspace.review',
    pathnamePattern: ROUTES.workspaceReview,
    ...SETTINGS_WORKSPACE_ROUTE,
    panes: [...SETTINGS_WORKSPACE_ROUTE.panes, ...WORKSPACE_REVIEW_PANES],
  }, exact(ROUTES.workspaceReview)),
  route({
    routeId: 'agent.settings',
    pathnamePattern: ROUTES.agentSettings,
    ...AGENT_SETTINGS_DOCUMENT_ROUTE,
    notes: 'Agent Settings is a neutral settings surface; it must not enter Agent work mode.',
  }, exact(ROUTES.agentSettings)),
]

export const registeredRouteLayoutSpecs: readonly RouteLayoutSpec[] = routeLayoutRegistry.map(({ match: _match, ...spec }) => spec)

export const fallbackRouteLayoutSpec: RouteLayoutSpec = {
  routeId: 'fallback',
  pathnamePattern: '*',
  kind: 'runtime',
  surface: 'tool',
  chrome: 'tool',
  scrollMode: 'document',
  shellLayout: 'stacked',
  panes: APP_SHELL_TOOL_PANES,
}

export function routeLayoutSpecForPathname(pathname: string): RouteLayoutSpec {
  const normalizedPathname = normalizePathname(pathname)
  const match = routeLayoutRegistry.find((entry) => entry.match(normalizedPathname))
  if (!match) return fallbackRouteLayoutSpec
  const { match: _match, ...spec } = match
  return spec
}

export function appRouteViewportScrollForMode(scrollMode: RouteScrollMode): RouteLayoutViewportScroll {
  return sharedAppRouteViewportScrollForMode(scrollMode)
}

function route<TSpec extends RouteLayoutSpec>(spec: TSpec, match: (pathname: string) => boolean): RouteLayoutRegistryEntry {
  return { ...spec, match }
}

function exact(pathname: string): (value: string) => boolean {
  return (value) => normalizePathname(value) === pathname
}

function normalizePathname(pathname: string): string {
  if (!pathname || pathname === '/') return '/'
  return pathname.endsWith('/') ? pathname.slice(0, -1) : pathname
}
