import assert from 'node:assert/strict'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import test from 'node:test'
import { collectArtifacts } from '../../scripts/release/release-workflow.mjs'

const root = process.cwd()

function read(path) {
  return readFileSync(resolve(root, path), 'utf8')
}

function legacyToken(...parts) {
  return parts.join('_')
}

test('GitHub release publishes Agent Plugin and Desktop as the two public product tracks', () => {
  const releaseWorkflow = read('.github/workflows/release.yml')
  const releaseNotes = read('.github/release-workspace-notes.md')
  const scriptsReadme = read('scripts/README.md')
  const desktopSmoke = read('scripts/release/smoke-desktop-package.mjs')

  assert.match(releaseWorkflow, /package-plugin:/)
  assert.match(releaseWorkflow, /name: Package Agent Plugin/)
  assert.match(releaseWorkflow, /pnpm run release -- package --app plugin/)
  assert.match(releaseWorkflow, /name: movscript-agent-plugin/)
  assert.match(releaseWorkflow, /artifact: movscript-desktop-macos-arm64/)
  assert.match(releaseWorkflow, /artifact: movscript-desktop-macos-x64/)
  assert.match(releaseWorkflow, /artifact: movscript-desktop-windows-x64/)
  assert.match(releaseWorkflow, /artifact: movscript-desktop-linux-x64/)
  assert.match(releaseWorkflow, /package-platform: linux/)
  assert.match(releaseWorkflow, /Smoke test desktop package[\s\S]*smoke-desktop-package --platform=\$\{\{ matrix\.package-platform \}\} --arch=\$\{\{ matrix\.package-arch \}\}/)
  assert.match(releaseWorkflow, /needs: \[package, package-plugin\]/)

  assert.match(releaseNotes, /Movscript Agent Plugin And Desktop/)
  assert.match(releaseNotes, /Movscript Agent Plugin/)
  assert.match(releaseNotes, /Movscript Desktop/)
  assert.match(releaseNotes, /movscript-agent-plugin/)
  assert.match(releaseNotes, /movscript\.local-node` daemon/)
  assert.match(releaseNotes, /not a third public download choice/)
  assert.match(releaseNotes, /Linux x64/)
  assert.match(releaseNotes, /AppImage artifact/)
  assert.doesNotMatch(releaseNotes, /Linux desktop packages are not included yet/)

  assert.match(scriptsReadme, /Agent Plugin only/)
  assert.match(scriptsReadme, /Desktop App/)
  assert.match(scriptsReadme, /not a third public release track/)
  assert.match(scriptsReadme, /--previous-artifact <zip>/)
  assert.match(scriptsReadme, /MOVSCRIPT_PLUGIN_SMOKE_PREVIOUS_ARTIFACT/)
  assert.match(desktopSmoke, /assertDesktopSmokeHomeCurrent/, 'desktop package smoke must verify Desktop seeded Home current')
  assert.match(desktopSmoke, /current\.identity/, 'desktop package smoke must verify Home current.identity')
  assert.match(desktopSmoke, /assertRuntimeDescriptorMatchesHomeCurrent/, 'desktop package smoke must verify descriptor identity against Home current')
  assert.match(desktopSmoke, /assertDesktopSmokeCodexMarketplace/, 'desktop package smoke must verify Codex compatibility marketplace links Home current')
  assert.match(desktopSmoke, /Codex marketplace plugin link target/, 'desktop package smoke must verify the Codex marketplace symlink target')
  assert.match(desktopSmoke, /canonicalPrefix/, 'desktop package smoke must verify the canonical /v1 gateway contract')
  assert.match(desktopSmoke, /compatibility\?\.compatible/, 'desktop package smoke must verify runtime bundle compatibility')
  assert.match(desktopSmoke, /MOVSCRIPT_DESKTOP_HOME/, 'desktop package smoke must force Desktop identity to use the smoke Home')
  assert.match(desktopSmoke, /MOVSCRIPT_DESKTOP_USER_DATA_DIR/, 'desktop package smoke must force Electron userData to use the smoke directory')
  assert.match(desktopSmoke, /unwrapCommandResult/, 'desktop package smoke must unwrap shared CLI command result envelopes')
  assert.match(desktopSmoke, /--existing-home-current/, 'desktop package smoke must expose an existing Home current scenario')
  assert.match(desktopSmoke, /MOVSCRIPT_DESKTOP_SMOKE_EXISTING_HOME_CURRENT/, 'desktop package smoke must support CI-provided existing current scenarios')
  assert.match(desktopSmoke, /stageExistingNewerHomeCurrent/, 'desktop package smoke must stage a newer Agent Plugin current')
  assert.match(desktopSmoke, /stageExistingOlderHomeCurrent/, 'desktop package smoke must stage an older Agent Plugin current')
  assert.match(desktopSmoke, /assertStagedHomeCurrentWasNotDowngraded/, 'desktop package smoke must verify Desktop did not downgrade Home current')
  assert.match(desktopSmoke, /assertStagedHomeCurrentWasUpgraded/, 'desktop package smoke must verify Desktop upgrades older Home current')
})

test('release artifact collection rewrites updater metadata and writes checksums', () => {
  const tempDir = mkdtempSync(join(tmpdir(), 'movscript-release-collect-'))
  try {
    const sourceDir = join(tempDir, 'desktop-release')
    const outputDir = join(tempDir, 'release-artifacts')
    mkdirSync(sourceDir, { recursive: true })
    writeFileSync(join(sourceDir, 'Movscript-0.1.30-arm64.dmg'), 'fake dmg\n', 'utf8')
    writeFileSync(join(sourceDir, 'Movscript-0.1.30-arm64.dmg.blockmap'), 'fake blockmap\n', 'utf8')
    writeFileSync(join(sourceDir, 'latest-mac-arm64.yml'), [
      'path: Movscript-0.1.30-arm64.dmg',
      'files:',
      '  - url: Movscript-0.1.30-arm64.dmg',
      '  - url: Movscript-0.1.30-arm64.dmg.blockmap',
      '',
    ].join('\n'), 'utf8')

    collectArtifacts(root, {
      app: 'desktop',
      sources: [sourceDir],
      outputDir,
      artifactPrefix: 'movscript-desktop-macos-arm64',
      env: {
        MOVSCRIPT_APP_UPDATE_POLICY: 'required',
        MOVSCRIPT_APP_UPDATE_SEVERITY: 'security',
        MOVSCRIPT_APP_UPDATE_MIN_SUPPORTED_VERSION: '0.1.29',
      },
    })

    const artifactName = 'movscript-desktop-macos-arm64-Movscript-0.1.30-arm64.dmg'
    const blockmapName = `${artifactName}.blockmap`
    const metadata = readFileSync(join(outputDir, 'latest-mac-arm64.yml'), 'utf8')
    const checksums = readFileSync(join(outputDir, 'movscript-desktop-macos-arm64-SHA256SUMS.txt'), 'utf8')

    assert.equal(existsSync(join(outputDir, artifactName)), true)
    assert.equal(existsSync(join(outputDir, blockmapName)), true)
    assert.match(metadata, new RegExp(`path: ${artifactName}`))
    assert.match(metadata, new RegExp(`url: ${artifactName}`))
    assert.match(metadata, new RegExp(`url: ${blockmapName}`))
    assert.match(metadata, /policy: "required"/)
    assert.match(metadata, /severity: "security"/)
    assert.match(metadata, /minSupportedVersion: "0\.1\.29"/)
    assert.match(checksums, new RegExp(`  ${artifactName}`))
    assert.match(checksums, new RegExp(`  ${blockmapName}`))
    assert.match(checksums, /  latest-mac-arm64\.yml/)
  } finally {
    rmSync(tempDir, { recursive: true, force: true })
  }
})

test('GitHub Pages install surface keeps plugin-only and Desktop paths separate', () => {
  const installDoc = read('docs/install.md')
  const pagesWorkflow = read('.github/workflows/pages.yml')
  const page = read('site/index.html')
  const pageScript = read('site/app.js')

  assert.match(installDoc, /Movscript publishes two app releases/)
  assert.match(installDoc, /Agent Plugin only/)
  assert.match(installDoc, /Desktop App/)
  assert.match(installDoc, /install-plugin\.sh/)
  assert.match(installDoc, /install-desktop\.sh/)
  assert.match(installDoc, /Linux x64/)
  assert.match(installDoc, /movscript-desktop-linux-x64-\*/)
  assert.match(installDoc, /\.AppImage/)
  assert.match(installDoc, /MovScript Home And Distribution Profiles/)
  assert.match(installDoc, /%LOCALAPPDATA%\\MovScript\\Home/)
  assert.match(installDoc, /MovScript Self Hosted\\Home/)
  assert.match(installDoc, /Cloud Or External Runtime/)
  assert.match(installDoc, /runtime gateway configure/)
  assert.match(installDoc, /--gateway-kind external/)
  assert.match(installDoc, /plugin installer .* does not install or launch the Desktop app/s)

  assert.match(pagesWorkflow, /cp install-desktop\.sh public\/install-desktop\.sh/)
  assert.match(pagesWorkflow, /cp install-plugin\.sh public\/install-plugin\.sh/)

  assert.match(page, /Agent plugin only/)
  assert.match(page, /Desktop app/)
  assert.match(page, /data-release-asset="plugin"/)
  assert.match(page, /data-release-asset="macos-arm64"/)
  assert.match(page, /data-release-asset="macos-x64"/)
  assert.match(page, /data-release-asset="windows-x64"/)
  assert.match(page, /data-release-asset="linux-x64"/)
  assert.match(page, /Desktop reuses the same local runtime daemon/)
  assert.match(page, /Desktop 与 Agent 插件和 CLI 复用同一个本机 runtime daemon/)
  assert.doesNotMatch(page, /Desktop[^<。]*owner/)
  assert.match(pageScript, /movscript-desktop-linux-x64-/)
  assert.match(pageScript, /linux-x64/)
  assert.match(pageScript, /dataset\.platformPanel !== platform/)
})

test('README docs index points to existing product docs and current desktop platforms', () => {
  const readme = read('README.md')
  const readmeZh = read('README.zh-CN.md')

  assert.match(readme, /Linux x64 AppImage/)
  assert.match(readmeZh, /Linux x64 AppImage/)
  assert.match(readme, /Product runtime distribution standard/)
  assert.match(readme, /Movscript Agent runtime architecture/)
  assert.match(readmeZh, /docs\/product-runtime-distribution-standard\.zh-CN\.md/)
  assert.match(readmeZh, /docs\/movscript-agent-runtime-architecture\.zh-CN\.md/)
  assert.doesNotMatch(readme, /Linux desktop packages are not published yet/)
  assert.doesNotMatch(readmeZh, /Linux 桌面包暂未发布/)

  for (const markdown of [readme, readmeZh]) {
    for (const match of markdown.matchAll(/\]\((docs\/[^)]+\.md)\)/g)) {
      assert.equal(existsSync(resolve(root, match[1])), true, `${match[1]} should exist`)
    }
  }
})

test('product transformation plan tracks the implemented Home plugin store baseline', () => {
  const plan = read('docs/product-transformation-plan.zh-CN.md')
  const homeStore = read('packages/plugins/src/node/homePluginStore.ts')
  const codexInstaller = read('apps/desktop/electron/services/codexPluginInstaller.ts')
  const desktopRuntime = read('apps/desktop/runtime/desktopApplicationRuntime.ts')
  const desktopRuntimeTest = read('apps/desktop/runtime/desktopApplicationRuntime.test.ts')
  const desktopRuntimeConfig = read('apps/desktop/electron/services/runtimeConfig.ts')
  const desktopRuntimeBundleAction = read('apps/desktop/electron/services/runtimeBundleAction.ts')
  const desktopAppTray = read('apps/desktop/electron/services/appTray.ts')

  assert.match(plan, /状态：实施追踪/)
  assert.match(plan, /packages\/plugins\/src\/node\/homePluginStore\.ts/)
  assert.match(plan, /Codex marketplace 和其他 provider target projection 都通过 symlink 指向 Home current/)
  assert.match(plan, /Desktop-to-provider target link 指向同一个 Home current/)
  assert.match(plan, /runtimeBundleStatus/)
  assert.match(plan, /runtimeBundleAction\.ts/)
  assert.match(plan, /状态：Node installer library 已落地/)
  assert.match(homeStore, /export function installMovScriptHomePluginBundle/)
  assert.match(homeStore, /export function rollbackMovScriptHomePluginBundle/)
  assert.match(homeStore, /export function resolveMovScriptHomePreviousPluginRoot/)
  assert.match(homeStore, /mode\?: 'replace' \| 'seed-or-upgrade' \| 'repair'/)
  assert.match(homeStore, /current\.identity/)
  assert.match(codexInstaller, /export function installMovScriptAgentProviderTargets/)
  assert.match(codexInstaller, /registerMovScriptAgentProviderTargets/)
  assert.match(codexInstaller, /targets: options\.targets \?\? 'all'/)
  assert.match(codexInstaller, /provider: targets\.join\(','\)/)
  assert.match(codexInstaller, /symlinkSync\(installed\.paths\.currentLink, pluginRoot/)
  assert.match(desktopRuntime, /seedDesktopHomePluginCurrent\(homeDir\)/)
  assert.match(desktopRuntime, /installMovScriptHomePluginBundle\({[\s\S]*reason: 'desktop-runtime-start'[\s\S]*provider: 'desktop'/)
  assert.match(desktopRuntimeTest, /does not downgrade an existing newer Home current plugin/)
  assert.match(desktopRuntimeTest, /version: '999\.0\.0'/)
  assert.match(desktopRuntimeConfig, /runtimeBundleCompatibility/)
  assert.match(desktopRuntimeConfig, /runtimeBundleStatus/)
  assert.match(desktopRuntimeConfig, /return 'upgrade'/)
  assert.match(desktopRuntimeConfig, /return input\.previousRoot \? 'rollback' : 'repair'/)
  assert.match(desktopRuntimeBundleAction, /installMovScriptHomePluginBundle/)
  assert.match(desktopRuntimeBundleAction, /rollbackMovScriptHomePluginBundle/)
  assert.match(desktopRuntimeBundleAction, /prepareDaemonForDesktopUpdateInstall/)
  assert.match(desktopRuntimeBundleAction, /forceRestart: true/)
  assert.match(desktopAppTray, /runtimeDescriptorMenuModel\(\)/)
  assert.match(desktopAppTray, /getElectronRuntimeConfig\(\)/)
  assert.match(desktopAppTray, /Runtime owner/)
  assert.match(desktopAppTray, /Data plane/)
  assert.match(desktopAppTray, /Plugin current/)
  assert.match(desktopAppTray, /Daemon status/)
  assert.match(desktopAppTray, /Daemon gateway/)
  assert.match(desktopAppTray, /install-agent-provider-targets/)
  assert.match(desktopAppTray, /installMovScriptAgentProviderTargets/)
  assert.doesNotMatch(plan, /Community 可以默认提示确认/)
  assert.doesNotMatch(plan, /Desktop 的“安装 Codex 插件”路径当前复制到/)
  assert.doesNotMatch(plan, /还没有完全复用 Home 中的 `plugins\/movscript\/current`/)
})

test('Agent Plugin installer retains rollback bundles and prints bundle identity', () => {
  const installer = read('install-plugin.sh')
  const pluginAgentMcp = read('apps/plugin/src/agent-mcp.ts')
  const pluginSmoke = read('scripts/release/smoke-plugin-package.mjs')
  const releaseWorkflowScript = read('scripts/release/release-workflow.mjs')
  const verifyPackageResourcesScript = read('scripts/release/verify-package-resources.mjs')
  const packageResources = JSON.parse(read('package-resources.manifest.json'))
  const scriptsReadme = read('scripts/README.md')
  const installDoc = read('docs/install.md')
  const productStandard = read('docs/product-runtime-distribution-standard.zh-CN.md')
  const providerPluginResource = packageResources.resources.find((resource) => resource.id === 'provider-plugin')

  assert.match(installer, /PLUGIN_RETAIN="\$\{MOVSCRIPT_PLUGIN_RETAIN:-2\}"/)
  assert.match(installer, /--retain <count>/)
  assert.match(installer, /--rollback-version <ver>/)
  assert.match(installer, /codex,harness,openclaw,claude-code,all/, 'plugin installer must document non-Codex provider targets')
  assert.match(installer, /PROVIDER_TARGETS=\$\(provider_targets "\$PROVIDER"\)/, 'plugin installer must normalize provider targets')
  assert.match(installer, /xiaolongxia\) printf '%s\\n' "openclaw"/, 'plugin installer must keep the old Xiaolongxia alias pointed at OpenClaw')
  assert.match(installer, /provider\/\$target/, 'plugin installer must write provider-specific registration roots')
  assert.match(installer, /\.agent-package\/package\.json/, 'plugin installer must require the neutral Agent Package manifest')
  assert.match(installer, /previous_plugin_target\(\)/)
  assert.match(installer, /switch_plugin_pointer\(\)/)
  assert.match(installer, /write_bundle_identity\(\)/)
  assert.match(installer, /write_home_cli_shim\(\)/)
  assert.match(installer, /MOVSCRIPT_BIN="\$MOVSCRIPT_HOME\/bin"/)
  assert.match(installer, /plugins\/movscript\/current/)
  assert.match(installer, /pathToFileURL\(pluginEntry\)/)
  assert.match(installer, /current\.identity/)
  assert.match(installer, /runtime_manifest_field\(\)/)
  assert.match(installer, /bundleHash=%s/)
  assert.match(installer, /apiVersion=%s/)
  assert.match(installer, /minDaemonApiVersion=%s/)
  assert.match(installer, /perform_plugin_rollback\(\)/)
  assert.match(installer, /prune_plugin_versions "\$PLUGIN_RETAIN"/)
  assert.match(installer, /retain_count.*-le 1[\s\S]*rm -f "\$PLUGIN_STORE\/previous"/)
  assert.match(installer, /switch_plugin_pointer "\$PLUGIN_STORE\/previous" "\$PREVIOUS_CURRENT_TARGET"/)
  assert.match(pluginAgentMcp, /rollbackCurrentPluginForStartupFailure/, 'plugin ensure must attempt rollback when current daemon startup fails')
  assert.match(pluginAgentMcp, /plugins\/movscript/, 'plugin rollback must operate on the Home plugin store')
  assert.match(pluginAgentMcp, /current['"`]\)/, 'plugin rollback must switch the current pointer')
  assert.match(pluginAgentMcp, /previous['"`]\)/, 'plugin rollback must use the previous pointer')
  assert.match(pluginAgentMcp, /MOVSCRIPT_PLUGIN_ROLLBACK_ON_DAEMON_START_FAILURE/, 'plugin rollback must have an explicit diagnostic opt-out')
  assert.match(pluginAgentMcp, /previousEntrypoint/, 'plugin rollback must retry daemon ensure from the previous bundle entrypoint')
  assert.match(pluginAgentMcp, /auto-rollback-daemon-startup-failure/, 'plugin rollback must write bundle identity reason metadata')

  assert.match(pluginSmoke, /runInstaller\(root, artifact, homeDir, env, spawn\)/, 'plugin package smoke must exercise the public installer')
  assert.match(pluginSmoke, /const artifactVersion = pluginVersionFromArtifact\(artifact\)/, 'plugin package smoke must resolve the current artifact version once')
  assert.match(pluginSmoke, /locateInstalledPluginRoot\(homeDir, artifactVersion\)/, 'plugin package smoke must start from the installed current bundle and expected artifact version')
  assert.match(pluginSmoke, /validateInstalledHomeCliShim\(homeDir\)/, 'plugin package smoke must verify the public Home CLI shim')
  assert.match(pluginSmoke, /installed Home CLI shim/, 'plugin package smoke must start through the Home CLI shim after install')
  assert.match(pluginSmoke, /current\.identity/, 'plugin package smoke must verify bundle identity output')
  assert.match(pluginSmoke, /readBundleIdentity\(identityPath\)/, 'plugin package smoke must parse current.identity fields')
  assert.match(pluginSmoke, /identity\.version/, 'plugin package smoke must verify current.identity version')
  assert.match(pluginSmoke, /identity\.bundleHash/, 'plugin package smoke must verify current.identity bundle hash')
  assert.match(pluginSmoke, /provider\/codex\/plugins\/movscript/, 'plugin package smoke must verify the Codex marketplace plugin link')
  assert.match(pluginSmoke, /realpathSync\(codexPluginLink\)/, 'plugin package smoke must ensure Codex plugin link targets Home current')
  assert.match(pluginSmoke, /--previous-artifact/, 'plugin package smoke must expose a previous artifact rollback path')
  assert.match(pluginSmoke, /MOVSCRIPT_PLUGIN_SMOKE_PREVIOUS_ARTIFACT/, 'plugin package smoke must support CI-provided previous artifacts')
  assert.match(pluginSmoke, /validateInstalledPreviousBundle\(homeDir, previousInstalledRoot, previousArtifactVersion\)/, 'plugin package smoke must verify current install retained previous')
  assert.match(pluginSmoke, /runInstallerRollback\(root, homeDir, env, spawn\)/, 'plugin package smoke must exercise public installer rollback')
  assert.match(pluginSmoke, /locateInstalledPluginRoot\(homeDir, previousArtifactVersion, \{ expectedReason: 'rollback' \}\)/, 'plugin package smoke must verify rollback identity reason')
  assert.match(pluginSmoke, /expectedVersion: previousArtifactVersion/, 'plugin package smoke must recheck daemon descriptor after rollback')
  assert.match(pluginSmoke, /rollbackExercised/, 'plugin package smoke must report whether current\\/previous rollback ran')
  assert.match(pluginSmoke, /descriptor\.runtime\?\.identity\?\.pluginVersion/, 'plugin package smoke must verify runtime descriptor identity')
  assert.match(pluginSmoke, /descriptor\.apiVersion/, 'plugin package smoke must verify runtime descriptor API version')
  assert.match(pluginSmoke, /descriptor\.bundleHash/, 'plugin package smoke must verify runtime descriptor bundle hash')
  assert.match(pluginSmoke, /descriptor\.compatibility\?\.kind/, 'plugin package smoke must verify runtime descriptor bundle compatibility')
  assert.match(pluginSmoke, /pluginVersionFromArtifact\(artifact\)/, 'plugin package smoke must compare descriptor identity to the release artifact version')
  assert.match(pluginSmoke, /--no-install/, 'plugin package smoke may keep a direct extraction debug escape hatch')
  assert.match(pluginSmoke, /runtime manifest schema/, 'plugin package smoke must verify runtime bundle manifest schema')
  assert.match(pluginSmoke, /\.agent-package\/package\.json/, 'plugin package smoke must require the neutral Agent Package manifest')
  assert.match(pluginSmoke, /runtimeManifest\.bundleHash/, 'plugin package smoke must verify runtime bundle manifest hash')
  assert.match(releaseWorkflowScript, /\['@movscript\/local-daemon', 'build'\]/, 'plugin package must rebuild local daemon before bundling')
  assert.match(releaseWorkflowScript, /\['@movscript\/local-runtime', 'build'\]/, 'plugin package must rebuild local runtime before bundling')
  assert.match(releaseWorkflowScript, /schema: 'movscript\.runtime-bundle\.v1'/, 'release workflow must generate the runtime bundle manifest schema')
  assert.match(releaseWorkflowScript, /\.agent-package/, 'plugin package must include the neutral Agent Package manifest')
  assert.match(releaseWorkflowScript, /bundleHash: pluginBundleHash\(pluginDir\)/, 'release workflow must hash the plugin runtime bundle')
  assert.match(verifyPackageResourcesScript, /--plugin-zip/, 'package resource verifier must expose a plugin zip compatibility gate')
  assert.match(verifyPackageResourcesScript, /MOVSCRIPT_PACKAGE_RESOURCE_PLUGIN_ZIP/, 'package resource verifier must support CI-provided plugin zip artifacts')
  assert.match(verifyPackageResourcesScript, /validateProviderPluginZipCompatibility/, 'package resource verifier must compare Desktop provider plugin and Agent Plugin zip')
  assert.match(verifyPackageResourcesScript, /compareRuntimeManifests/, 'package resource verifier must compare runtime bundle manifest fields')
  assert.match(verifyPackageResourcesScript, /providerManifest\.bundleHash !== providerBundleHash/, 'package resource verifier must hash-check Desktop provider plugin files')
  assert.match(verifyPackageResourcesScript, /zipManifest\.bundleHash !== zipBundleHash/, 'package resource verifier must hash-check Agent Plugin zip files')
  assert.equal(providerPluginResource?.to, 'provider-plugins/movscript')
  assert.equal(providerPluginResource?.filter.includes('.agent-package/**'), true)
  assert.equal(providerPluginResource?.verification.includes('check-plugin-distribution --check'), true)
  assert.equal(providerPluginResource?.verification.includes('verify-package-resources --plugin-zip'), true)
  assert.match(scriptsReadme, /MOVSCRIPT_PACKAGE_RESOURCE_PLUGIN_ZIP/)

  assert.match(installDoc, /current\.identity/)
  assert.match(installDoc, /install-plugin\.sh --rollback/)
  assert.match(productStandard, /<home>\/plugins\/movscript\/previous/)
  assert.match(productStandard, /<home>\/bin/)
  assert.match(productStandard, /current\.identity/)
})

test('CLI package exposes movscript as the only product command', () => {
  const cliPackage = JSON.parse(read('apps/cli/package.json'))
  const cliIndex = read('apps/cli/src/index.ts')
  const movscriptBin = read('apps/cli/bin/movscript')
  const movscriptMjs = read('apps/cli/bin/movscript.mjs')

  assert.equal(cliPackage.bin.movscript, './bin/movscript')
  assert.equal(Object.hasOwn(cliPackage.bin, 'movcli'), false)
  assert.match(cliIndex, /registerDaemonCommands\(program\)/)
  assert.match(cliIndex, /registerContextCommands\(program\)/)
  assert.match(cliIndex, /registerProjectCommands\(program\)/)
  assert.match(cliIndex, /registerProductionCommands\(program\)/)
  assert.match(cliIndex, /registerResourceCommands\(program\)/)
  assert.match(cliIndex, /registerArtifactCommands\(program\)/)
  assert.match(cliIndex, /registerExternalResourceCommands\(program\)/)
  assert.match(cliIndex, /registerShotCommands\(program\)/)
  assert.match(cliIndex, /registerVideoCommands\(program\)/)
  assert.match(cliIndex, /registerDomainCommands\(program\)/)
  assert.match(cliIndex, /registerEditingCommands\(program\)/)
  assert.match(cliIndex, /movscript\.mjs/)
  assert.doesNotMatch(cliIndex, /movcli|Movcli|MOVCLI|__movscript_movcli/)
  assert.match(movscriptBin, /ENTRY="\$SCRIPT_DIR\/movscript\.mjs"/)
  assert.match(movscriptMjs, /movscript has not been built yet/)
})

test('media generation product capabilities stay CLI/MCP first and routeable', () => {
  const mediaDoc = read('docs/media-generation-capability-remodel.zh-CN.md')
  const generationSkill = read('apps/plugin/skills/generation/SKILL.md')
  const capabilityContract = read('packages/core/src/mcp/tools/model/contracts/capability.ts')
  const modelActions = read('packages/core/src/mcp/node/tools/model/actions.ts')
  const generationDefinitions = read('packages/core/src/mcp/tools/generation/definitions.ts')
  const generationActions = read('packages/core/src/mcp/node/tools/generation/actions.ts')

  assert.match(mediaDoc, /保留 3 个媒体生成 capability：[\s\S]*image_generation[\s\S]*video_generation[\s\S]*audio_generation/, 'media generation doc must define the three media capability families')
  assert.match(mediaDoc, /不做运行时兼容，不接受旧 capability 和旧 operation alias/, 'media generation doc must reject runtime compatibility aliases')
  assert.match(mediaDoc, /模型目录的主能力只能来自：[\s\S]*image_generation[\s\S]*video_generation[\s\S]*audio_generation/, 'media generation doc must keep model catalog capabilities canonical')
  assert.match(mediaDoc, /新任务 payload 使用粗粒度 `job_type`：[\s\S]*image[\s\S]*video[\s\S]*audio/, 'media generation doc must keep execution job types coarse')

  const legacySpeechConversationAlias = legacyToken('audio', 'chat')
  const legacyMusicAlias = legacyToken('audio', 'music')
  const legacySubtitleAlias = legacyToken('subtitle', 'translate')
  assert.equal(capabilityContract.includes(legacyToken('voice', 'chat')), false, 'model capability aliases must not revive voice chat aliases')
  assert.equal(capabilityContract.includes(legacySpeechConversationAlias), false, 'model capability aliases must not revive legacy speech conversation capabilities')
  assert.equal(capabilityContract.includes(legacyMusicAlias), false, 'model capability aliases must not revive fine-grained music capabilities')
  assert.equal(modelActions.includes(legacyMusicAlias), false, 'system model list defaults must not include fine-grained music capabilities')
  assert.equal(modelActions.includes(legacySpeechConversationAlias), false, 'system model list defaults must not include legacy speech conversation capabilities')
  assert.equal(modelActions.includes(legacySubtitleAlias), false, 'system model list defaults must not include fine-grained subtitle capabilities')
  assert.equal(generationDefinitions.includes(legacyMusicAlias), false, 'generation schema must not expose fine-grained music capabilities')
  assert.equal(generationDefinitions.includes(legacySpeechConversationAlias), false, 'generation schema must not expose legacy speech conversation capabilities')
  assert.equal(generationDefinitions.includes(legacySubtitleAlias), false, 'generation schema must not expose fine-grained subtitle capabilities')
  assert.doesNotMatch(generationActions, /audioJobTypeForOperation/, 'generation submit must not map operations back to product capabilities')
  assert.match(generationActions, /audioGenerationReferenceAssetsPayload/, 'generation submit must materialize audio reference assets for input resources')
  assert.match(generationSkill, /audio_generation/, 'generation skill should document the canonical audio generation family')
})

test('shared CLI/MCP command manifest exposes product contract metadata', () => {
  const cliCommands = read('packages/cli-commands/src/index.ts')
  const localDaemonMCP = read('packages/local-daemon/src/mcp.ts')
  const projectClient = read('packages/project/src/index.ts')
  const projectService = read('services/project-service/src/server.mjs')
  const projectProductionEditingService = `${projectService}\n${read('services/project-service/src/productionEditing.mjs')}`
  const mediaPipelineService = read('services/media-pipeline/src/server.mjs')
  const mediaPipelineServiceTests = read('services/media-pipeline/tests/server.test.mjs')
  const mediaPipelineResultRegistry = read('services/media-pipeline/src/resultRegistry.mjs')
  const mediaPipelineResultWatchRegistry = read('services/media-pipeline/src/resultWatchRegistry.mjs')
  const localDaemon = read('packages/local-daemon/src/index.ts')
  const domainActions = read('packages/core/src/mcp/node/tools/domain/actions.ts')
  const domainRuntime = read('packages/core/src/mcp/node/tools/domain/runtime.ts')
  const productionEditingActions = read('packages/core/src/mcp/node/tools/production-editing/actions.ts')
  const productionEditingDefinitions = read('packages/core/src/mcp/tools/production-editing/definitions.ts')
  const productionEditingCli = read('apps/cli/src/commands/production-editing.ts')
  const editingClient = read('packages/editing/src/index.ts')
  const editingRuntime = read('packages/editing/src/runtime.ts')
  const editingActions = read('packages/core/src/mcp/node/tools/editing/actions.ts')
  const editingDefinitions = read('packages/core/src/mcp/tools/editing/definitions.ts')
  const editingCli = read('apps/cli/src/commands/editing.ts')
  const artifactActions = read('packages/core/src/mcp/node/tools/artifact/actions.ts')
  const artifactDefinitions = read('packages/core/src/mcp/tools/artifact/definitions.ts')
  const projectServiceTests = read('services/project-service/tests/server.test.mjs')
  const systemCli = read('apps/cli/src/commands/system.ts')
  const adminCli = read('apps/cli/src/commands/admin.ts')
  const localDaemonPackage = JSON.parse(read('packages/local-daemon/package.json'))
  const mcpHostStdio = read('packages/mcp-host/src/stdio.ts')
  const mcpHostPackage = JSON.parse(read('packages/mcp-host/package.json'))
  const plan = read('docs/mcp-skill-tool-production-editing-refactor.zh-CN.md')

  for (const required of [
    'export interface MovScriptCommandContract',
    'ownerService: string',
    'requiredRuntime: string[]',
    'permissions: string[]',
    'outputSchema: JSONSchemaObject',
    'examples: MovScriptCommandExample[]',
    'function withCommandContract',
    'function commandExecutionContract',
  ]) {
    assert.match(cliCommands, new RegExp(required.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
  }

  assert.match(cliCommands, /contract: commandExecutionContract\(spec\)/, 'command execution result must carry the shared product contract')
  assert.match(cliCommands, /export const runtimeCommandSpecs/, 'runtime bootstrap/control must be part of the shared command manifest')
  assert.match(cliCommands, /runtime\.doctor/, 'runtime command manifest must expose top-level CLI doctor')
  assert.match(cliCommands, /runtime_doctor/, 'runtime command manifest must expose runtime doctor MCP tool')
  assert.match(cliCommands, /runtime\.gateway\.configure/, 'runtime command manifest must expose runtime gateway configure')
  assert.match(cliCommands, /runtime_gateway_configure/, 'runtime command manifest must expose runtime gateway configure MCP tool')
  assert.match(cliCommands, /writeRuntimeEndpointRecord/, 'runtime gateway configure must write runtime endpoint records')
  assert.match(cliCommands, /movscript\.cloud-runtime\.gateway/, 'runtime gateway configure/discover must understand cloud runtime gateway records')
  assert.match(cliCommands, /export const contextCommandSpecs/, 'context/session hints must be part of the shared command manifest')
  assert.match(cliCommands, /system\.production\.workflow/, 'system command manifest must expose the CLI-only production workflow contract')
  assert.match(cliCommands, /system_production_workflow/, 'system command manifest must expose production workflow MCP tool')
  assert.match(cliCommands, /commandId: 'system\.production\.workflow'[\s\S]*productCliPath: \['production', 'workflow'\]/, 'production workflow must be a top-level product CLI backed by the system command manifest')
  assert.match(cliCommands, /commandId: 'system\.project\.create'[\s\S]*productCliPath: \['project', 'create'\]/, 'project create must be a top-level product CLI backed by the system command manifest')
  assert.match(cliCommands, /commandId: 'system\.resource\.library\.open'[\s\S]*productCliPath: \['resource', 'library', 'open'\]/, 'resource library open must be a top-level product CLI backed by the system command manifest')
  assert.match(cliCommands, /commandId: 'system\.artifact\.upload_export'[\s\S]*productCliPath: \['artifact', 'upload-export'\]/, 'artifact upload-export must be a top-level product CLI backed by the system command manifest')
  assert.match(cliCommands, /commandId: 'system\.external_resource\.search'[\s\S]*productCliPath: \['external-resource', 'search'\]/, 'external-resource search must be a top-level product CLI backed by the system command manifest')
  assert.match(cliCommands, /commandId: 'system\.shot\.group\.create'[\s\S]*productCliPath: \['shot', 'group', 'create'\]/, 'shot group create must be a top-level product CLI backed by the system command manifest')
  assert.match(cliCommands, /commandId: 'system\.video\.shot_cuts\.analyze'[\s\S]*productCliPath: \['video', 'shot-cuts', 'analyze'\]/, 'video shot-cuts analyze must be a top-level product CLI backed by the system command manifest')
  assert.match(cliCommands, /admin\.provider\.connection_test/, 'admin command manifest must expose provider connection test')
  assert.match(cliCommands, /admin_provider_connection_test/, 'admin command manifest must expose provider connection test MCP tool')
  assert.match(cliCommands, /admin\.provider_instance\.config\.get/, 'admin command manifest must expose provider instance config get')
  assert.match(cliCommands, /admin_provider_instance_config_update/, 'admin command manifest must expose provider instance config update')
  assert.match(cliCommands, /admin_provider_instance_config_apply/, 'admin command manifest must expose provider instance config apply')
  assert.match(cliCommands, /admin_provider_instance_config_activate/, 'admin command manifest must expose provider instance config activate')
  assert.match(cliCommands, /admin\.generation_tools\.call_test/, 'admin command manifest must expose generation tool call test')
  assert.match(cliCommands, /admin_generation_tool_call_test/, 'admin command manifest must expose generation tool call test MCP tool')
  assert.match(cliCommands, /admin\.cloud_file_config\.list/, 'admin command manifest must expose cloud file config list')
  assert.match(cliCommands, /admin_cloud_file_config_create/, 'admin command manifest must expose cloud file config create')
  assert.match(cliCommands, /admin_cloud_file_config_update/, 'admin command manifest must expose cloud file config update')
  assert.match(cliCommands, /admin_cloud_file_config_test/, 'admin command manifest must expose cloud file config test')
  assert.match(cliCommands, /admin_cloud_file_config_delete/, 'admin command manifest must expose cloud file config delete')
  assert.match(cliCommands, /admin\.usage_policy\.get/, 'admin command manifest must expose usage policy get')
  assert.match(cliCommands, /admin_usage_policy_update/, 'admin command manifest must expose usage policy update')
  assert.match(cliCommands, /admin_usage_policy_diagnose/, 'admin command manifest must expose usage policy diagnose')
  assert.match(cliCommands, /admin\.resource_access\.profile\.list/, 'admin command manifest must expose resource access profile list')
  assert.match(cliCommands, /admin_resource_access_profile_upsert/, 'admin command manifest must expose resource access profile upsert MCP tool')
  assert.match(cliCommands, /admin_resource_access_profile_delete/, 'admin command manifest must expose resource access profile delete MCP tool')
  assert.match(cliCommands, /admin_resource_access_profile_test/, 'admin command manifest must expose resource access profile test MCP tool')
  assert.match(cliCommands, /admin_resource_access_route_diagnose/, 'admin command manifest must expose resource access route diagnose MCP tool')
  assert.match(adminCli, /--provider-instance-id <id>/, 'admin CLI must expose provider instance id for connection diagnostics')
  assert.match(adminCli, /--tool-type <type>/, 'admin CLI must expose generation tool type for call-test diagnostics')
  assert.match(adminCli, /--operation <operation>/, 'admin CLI must expose generation tool operation for call-test diagnostics')
  assert.match(adminCli, /--cloud-file-config-id <id>/, 'admin CLI must expose cloud file config id')
  assert.match(adminCli, /--profile-id <id>/, 'admin CLI must expose resource access profile id')
  assert.match(adminCli, /--route-id <id>/, 'admin CLI must expose resource access route diagnostic id')
  assert.match(cliCommands, /export const domainCommandSpecs/, 'domain read/query/status/source writes and candidate gates must be part of the shared command manifest')
  assert.match(cliCommands, /export const editingCommandSpecs/, 'editing backend diagnostics must be part of the shared command manifest')
  assert.match(cliCommands, /export async function runMovScriptRuntimeCommand/, 'runtime CLI/MCP calls must share the command runner')
  assert.match(cliCommands, /export async function runMovScriptContextCommand/, 'context CLI/MCP calls must share the command runner')
  assert.match(cliCommands, /export async function runMovScriptDomainCommand/, 'domain CLI/MCP calls must share the command runner')
  assert.match(cliCommands, /export async function runMovScriptEditingCommand/, 'editing CLI/MCP calls must share the command runner')
  assert.match(cliCommands, /export function isRuntimeMCPToolName/, 'daemon MCP executor must be able to route runtime tools through the shared manifest')
  assert.match(cliCommands, /export function isContextMCPToolName/, 'daemon MCP executor must be able to route context tools through the shared manifest')
  assert.match(cliCommands, /export function isDomainMCPToolName/, 'daemon MCP executor must be able to route domain tools through the shared manifest')
  assert.match(cliCommands, /export function isEditingMCPToolName/, 'daemon MCP executor must be able to route editing tools through the shared manifest')
  assert.match(localDaemonMCP, /export async function handleDaemonMCPJSONRPC/, 'daemon must own the MCP JSON-RPC executor')
  assert.match(localDaemonMCP, /outputSchema: tool\.outputSchema/, 'daemon MCP tool adapter must expose command output schema')
  assert.match(localDaemonMCP, /runMovScriptRuntimeCommand\(name!, args\)/, 'daemon MCP runtime tools must call the shared runtime command runner')
  assert.match(localDaemonMCP, /runMovScriptContextCommand\(name!, args\)/, 'daemon MCP context tools must call the shared context command runner')
  assert.match(localDaemonMCP, /runMovScriptDomainCommand\(name!, args\)/, 'daemon MCP domain tools must call the shared domain command runner')
  assert.match(localDaemonMCP, /runMovScriptEditingCommand\(name!, args\)/, 'daemon MCP editing tools must call the shared editing command runner')
  assert.match(localDaemonMCP, /runMovScriptProductionEditingCommand\(name!, args\)/, 'daemon MCP production editing tools must call the shared production editing command runner')
  assert.doesNotMatch(localDaemonMCP, /runMovScriptTimelineCommand/, 'daemon MCP must not route removed timeline tools')
  assert.match(localDaemonMCP, /export const daemonMCPRuntimeBootstrapToolNames = new Set\(runtimeTools\.map/, 'daemon MCP bootstrap allowlist must come from runtimeCommandSpecs')
  assert.match(localDaemonMCP, /return \[\.\.\.daemonMCPCommandTools\]/, 'daemon tools/list must expose command-manifest tools only')
  assert.match(localDaemonMCP, /unknown daemon MCP tool/, 'daemon MCP unknown tools must fail instead of falling back to core direct execution')
  assert.doesNotMatch(localDaemonMCP, /\bcallTool\b/, 'daemon MCP must not keep direct core tool execution fallback')
  assert.doesNotMatch(localDaemonMCP, /\blistTools\b/, 'daemon MCP must not merge the core tool registry into tools/list')
  assert.doesNotMatch(localDaemonMCP, /\bhandleJSONRPC\b/, 'daemon MCP must not delegate unknown JSON-RPC methods to the core MCP handler')
  assert.match(mcpHostStdio, /handleDaemonMCPJSONRPC\(req/, 'MCP host local fallback must delegate to daemon MCP executor')
  assert.match(mcpHostStdio, /daemonMCPRuntimeBootstrapToolNames/, 'MCP host bootstrap proxy allowlist must come from daemon MCP runtime tools')
  assert.match(mcpHostStdio, /MOVSCRIPT_RUNTIME_MCP_ENDPOINT/, 'MCP host must discover explicit runtime MCP endpoints for cloud/external gateways')
  assert.match(mcpHostStdio, /MOVSCRIPT_RUNTIME_GATEWAY_URL/, 'MCP host must discover explicit runtime gateway URLs')
  assert.match(mcpHostStdio, /movscript\.runtime\.gateway/, 'MCP host must discover generic runtime gateway endpoint records')
  assert.match(mcpHostStdio, /movscript\.cloud-runtime\.gateway/, 'MCP host must discover cloud runtime gateway endpoint records')
  assert.match(mcpHostStdio, /movscript\.external-runtime\.gateway/, 'MCP host must discover external runtime gateway endpoint records')
  assert.doesNotMatch(mcpHostStdio, /runMovScriptRuntimeCommand/, 'MCP host must not call command runners directly')
  assert.doesNotMatch(mcpHostStdio, /\bcallTool\(/, 'MCP host must not own direct core tool execution')
  assert.doesNotMatch(mcpHostStdio, /if \(name === 'runtime_daemon_/, 'MCP host must not keep direct runtime fallback branches')
  assert.doesNotMatch(mcpHostStdio, /function runtimeReadinessSchema/, 'MCP host must not keep copied runtime schemas')
  assert.doesNotMatch(mcpHostStdio, /ensureLocalRuntimeDaemon/, 'MCP host must not own daemon startup implementation directly')
  assert.equal(localDaemonPackage.dependencies['@movscript/mcp-host'], undefined, 'local-daemon must not depend on mcp-host')
  assert.equal(localDaemonPackage.dependencies['@movscript/cli-commands'], 'workspace:*', 'local-daemon MCP executor must depend on shared CLI commands')
  assert.equal(mcpHostPackage.dependencies['@movscript/local-daemon'], 'workspace:*', 'mcp-host must depend on daemon MCP executor instead of owning it')
  assert.match(read('apps/plugin/skills/runtime/SKILL.md'), /mcp__movscript__runtime_gateway_configure/, 'runtime skill must grant runtime gateway configure')
  assert.match(projectClient, /PROJECT_SERVICE_SOURCE_PRODUCTION_WORK_PLAN_ENDPOINT = ['"`]\/v1\/project\/source\/production-work-plan['"`]/, 'Project client must expose typed production work plan endpoint')
  assert.match(projectService, /movscript\.project-source-production-work-plan\.v1/, 'Project Service must serve typed production work plan endpoint')
  assert.match(localDaemon, /\['\/v1\/project\/source\/production-work-plan', '\/v1\/project\/source\/production-work-plan'\]/, 'daemon gateway must proxy production work plan endpoint')
  assert.match(projectClient, /PROJECT_SERVICE_ASSET_PROVIDER_CERTIFICATION_PATCH_ENDPOINT = ['"`]\/v1\/project\/assets\/provider-certification\/patch['"`]/, 'Project client must expose typed asset provider certification patch endpoint')
  assert.match(projectClient, /patchAssetProviderCertification\(/, 'Project client must expose an asset provider certification patch method')
  assert.match(projectService, /movscript\.project-asset-provider-certification-patch\.v1/, 'Project Service must serve typed asset provider certification patch endpoint')
  assert.match(localDaemon, /\['\/v1\/project\/assets\/provider-certification\/patch', '\/v1\/project\/assets\/provider-certification\/patch'\]/, 'daemon gateway must proxy asset provider certification patch endpoint')
  assert.match(projectService, /patchProjectAssetProviderCertification/, 'Project Service must own asset provider certification source patching')
  assert.match(domainRuntime, /PROJECT_SERVICE_ASSET_PROVIDER_CERTIFICATION_PATCH_ENDPOINT/, 'domain runtime must call Project Service for provider certification source patches')
  assert.match(domainActions, /patchAssetProviderCertification\(\{/, 'domain provider certification action must patch source through the domain runtime')
  assert.equal(existsSync(resolve(root, 'packages/core/src/mcp/tools/timeline/definitions.ts')), false, 'removed timeline MCP definitions must not be kept as public surface')
  assert.equal(existsSync(resolve(root, 'packages/core/src/mcp/node/tools/timeline/actions.ts')), false, 'removed timeline MCP actions must not be kept as public surface')
  assert.equal(existsSync(resolve(root, 'apps/cli/src/commands/timeline.ts')), false, 'removed timeline CLI command must not be kept as public surface')
  for (const endpoint of [
    ['PROJECT_SERVICE_PRODUCTION_EDITING_RESOURCES_REFRESH_ENDPOINT', '/v1/project/productions/editing-resources/refresh'],
    ['PROJECT_SERVICE_PRODUCTION_EDITING_WORKSPACES_LIST_ENDPOINT', '/v1/project/productions/editing-workspaces/list'],
    ['PROJECT_SERVICE_PRODUCTION_EDITING_WORKSPACES_CREATE_ENDPOINT', '/v1/project/productions/editing-workspaces/create'],
    ['PROJECT_SERVICE_PRODUCTION_EDITING_WORKSPACES_OPEN_ENDPOINT', '/v1/project/productions/editing-workspaces/open'],
    ['PROJECT_SERVICE_PRODUCTION_EDITING_WORKSPACES_DELETE_ENDPOINT', '/v1/project/productions/editing-workspaces/delete'],
  ]) {
    assert.match(projectClient, new RegExp(`${endpoint[0]} = ['"\`]${endpoint[1].replace(/\//g, '\\/')}['"\`]`), `Project client must expose ${endpoint[0]}`)
    assert.match(localDaemon, new RegExp(`\\['${endpoint[1].replace(/\//g, '\\/')}', '${endpoint[1].replace(/\//g, '\\/')}'\\]`), `daemon gateway must proxy ${endpoint[1]}`)
  }
  assert.match(projectProductionEditingService, /movscript\.production_editing_workspace_create\.v1/, 'Project Service must serve production editing workspace creation')
  assert.match(projectProductionEditingService, /movscript\.production_editing_resources_refresh\.v1/, 'Project Service must serve production editing resource refresh')
  assert.match(projectProductionEditingService, /productionEditingWorkspaceHandoffEnvelope/, 'Project Service must own production editing handoff/preflight output')
  assert.match(projectProductionEditingService, /movscript\.production_editing_handoff_preflight\.v1/, 'Project Service must return production editing handoff preflight')
  assert.match(projectProductionEditingService, /REMOTION_PROJECT_FILES_MISSING/, 'Project Service Remotion open preflight must return explicit missing-project-file blockers')
  assert.match(projectProductionEditingService, /productionEditingEnsureCodexSkill/, 'Project Service Remotion preflight must auto-install bundled Codex skills when missing')
  assert.match(projectProductionEditingService, /installed_restart_required/, 'Project Service Remotion skill install must report restart/reindex status')
  assert.match(projectProductionEditingService, /codex_skill_install/, 'Project Service Remotion skill install must expose a Codex install action')
  assert.match(projectClient, /createProductionEditingWorkspace\(/, 'Project client must expose production editing workspace creation')
  assert.match(projectClient, /openProductionEditingWorkspace\(/, 'Project client must expose production editing workspace open')
  assert.doesNotMatch(projectClient, /createTimelineBackendProject\(/, 'Project client must not expose TimelineAssembly backend project materialization')
  assert.doesNotMatch(projectProductionEditingService, /compileTimelineAssemblyToFinishingProject/, 'Project Service must not compile TimelineAssembly as a project editing middle layer')
  assert.match(productionEditingDefinitions, /production_editing_resources_refresh/, 'production editing MCP schema must expose resource refresh')
  assert.match(productionEditingDefinitions, /production_editing_workspace_list/, 'production editing MCP schema must expose workspace list')
  assert.match(productionEditingDefinitions, /production_editing_workspace_create/, 'production editing MCP schema must expose workspace create')
  assert.match(productionEditingDefinitions, /production_editing_workspace_get/, 'production editing MCP schema must expose workspace get')
  assert.match(productionEditingDefinitions, /production_editing_workspace_open/, 'production editing MCP schema must expose workspace open')
  assert.match(productionEditingDefinitions, /production_editing_workspace_delete/, 'production editing MCP schema must expose workspace delete')
  assert.match(productionEditingDefinitions, /Workspace kind: system_editing or remotion/, 'production editing workspace kind must be the only public selector')
  assert.match(productionEditingActions, /toSkill: kind === 'remotion' \? 'remotion' : 'system_edit'/, 'production editing open/create must return backend-specific skill handoff')
  assert.match(productionEditingActions, /responseHandoffPreflight/, 'production editing MCP/CLI action must preserve Project Service handoff preflight')
  assert.match(productionEditingActions, /workspace kind must be system_editing or remotion/, 'production editing actions must reject unsupported workspace kinds')
  assert.match(productionEditingActions, /agentSkill[\s\S]*skillName: 'remotion'/, 'Remotion workspace handoff preflight must report Remotion skill status')
  assert.match(productionEditingActions, /agentSkill[\s\S]*skillName: 'system_edit'/, 'system_editing workspace handoff preflight must report system_edit skill status')
  assert.match(productionEditingCli, /registerProductionEditingCommands/, 'CLI must register production editing commands')
  assert.match(productionEditingCli, /--kind <kind>[\s\S]*system_editing or remotion/, 'CLI must expose only workspace kind selection')
  assert.match(cliCommands, /export const productionEditingCommandSpecs/, 'shared command manifest must expose production editing command specs')
  assert.match(cliCommands, /export async function runMovScriptProductionEditingCommand/, 'shared command manifest must expose production editing runner')
  assert.match(cliCommands, /production_editing\.workspace\.open/, 'shared command manifest must expose production editing workspace open')
  assert.match(cliCommands, /production_editing_workspace_open/, 'shared command manifest must route production_editing_workspace_open')
  assert.match(cliCommands, /\['movscript', 'production', 'editing', 'workspace', 'list', '--json'\]/, 'production workflow preflight must use production editing, not timeline backend conformance')
  assert.equal(existsSync(resolve(root, 'packages/editing/src/compile-manifest.ts')), false, 'TimelineAssembly compile manifest source must be deleted')
  assert.match(editingRuntime, /'backend_project_render'/, 'Editing runtime task type must include backend_project_render')
  assert.match(editingRuntime, /'backend_project_preview'/, 'Editing runtime task type must include backend_project_preview')
  assert.match(mediaPipelineService, /'backend_project_render'/, 'Media Pipeline Service must advertise backend_project_render')
  assert.match(mediaPipelineService, /'backend_project_preview'/, 'Media Pipeline Service must advertise backend_project_preview')
  assert.match(mediaPipelineService, /backendProjectRender/, 'Media Pipeline probe must expose backend project render capability')
  assert.match(mediaPipelineService, /backendProjectPreview/, 'Media Pipeline probe must expose backend project preview capability')
  assert.match(mediaPipelineServiceTests, /backend project render commands/, 'Media Pipeline tests must cover backend project render commands')
  assert.match(mediaPipelineServiceTests, /backend project preview commands/, 'Media Pipeline tests must cover backend project preview commands')
  assert.match(projectServiceTests, /REMOTION_PROJECT_FILES_MISSING/, 'Project Service tests must cover Remotion missing-file preflight blockers')
  assert.match(projectServiceTests, /REMOTION_SKILL_INSTALL_RESTART_REQUIRED/, 'Project Service tests must cover Remotion skill install restart blockers')
  assert.match(projectServiceTests, /movscript_movscript-bundled/, 'Project Service tests must cover project-local Codex skill materialization')
  for (const source of [cliCommands, localDaemonMCP, productionEditingDefinitions, productionEditingActions, productionEditingCli]) {
    assert.doesNotMatch(source, /timeline_backend_/, 'public production editing surface must not expose removed timeline backend tools')
    assert.doesNotMatch(source, /timelineCommandSpecs|runMovScriptTimelineCommand|registerTimelineCommands/, 'public production editing surface must not keep removed timeline CLI runners')
    assert.doesNotMatch(source, /production_editing_backend_/, 'production editing must not add backend sub-tools')
    assert.doesNotMatch(source, /production_editing_workspace_reseed/, 'production editing must not expose reseed as a separate public tool')
    assert.doesNotMatch(source, /preferredRuntime|installPolicy/, 'production editing must not expose backend runtime/install policy knobs')
  }
  assert.match(plan, /新增 production editing command family/, 'production editing plan must record the new CLI/MCP command family')
  assert.match(plan, /只保留 `production_editing_resources_refresh`、`production_editing_workspace_list`、`production_editing_workspace_create`、`production_editing_workspace_get`、`production_editing_workspace_open`、`production_editing_workspace_delete`/, 'production editing plan must record the minimal public tool set')
  assert.match(plan, /不保留 `backend\.preferredRuntime` \/ `backend\.installPolicy`/, 'production editing plan must reject backend policy knobs')
  assert.match(plan, /后端动作交给 `system_edit` \/ `remotion`/, 'production editing plan must route concrete backend actions to handoff skills')
  assert.match(cliCommands, /domain\.candidate\.legacy\.append[\s\S]*stability: 'temporary_fallback'/, 'legacy inline candidate append must be a temporary fallback')
  assert.match(cliCommands, /domain\.candidate\.legacy\.unlock[\s\S]*stability: 'temporary_fallback'/, 'legacy inline candidate unlock must be a temporary fallback')
  assert.match(cliCommands, /migration-only temporary MovScript CLI fallback contract/, 'legacy inline candidate CLI examples must not be described as stable contracts')
  assert.match(localDaemonMCP, /Temporary fallback \(migration-only\)/, 'daemon MCP tools/list must visibly mark temporary fallback tools')
  const domainSkill = read('apps/plugin/skills/domain/SKILL.md')
  assert.doesNotMatch(domainSkill, /mcp__movscript__domain_append_candidate/, 'default domain skill must not grant legacy inline candidate append')
  assert.doesNotMatch(domainSkill, /mcp__movscript__domain_create_asset_slot_candidate/, 'default domain skill must not grant legacy inline asset-slot candidate creation')
  assert.doesNotMatch(domainSkill, /mcp__movscript__domain_create_keyframe_candidate/, 'default domain skill must not grant legacy inline keyframe candidate creation')
  assert.doesNotMatch(domainSkill, /mcp__movscript__domain_select_candidate/, 'default domain skill must not grant legacy inline candidate selection')
  assert.doesNotMatch(domainSkill, /mcp__movscript__domain_update_candidate/, 'default domain skill must not grant legacy inline candidate update')
  assert.doesNotMatch(domainSkill, /mcp__movscript__domain_unlock_candidate/, 'default domain skill must not grant legacy inline candidate unlock')
  const generationSkill = read('apps/plugin/skills/generation/SKILL.md')
  assert.doesNotMatch(generationSkill, /mcp__movscript__domain_append_candidate/, 'default generation skill must not grant legacy inline candidate append')
  assert.doesNotMatch(generationSkill, /mcp__movscript__domain_create_asset_slot_candidate/, 'default generation skill must not grant legacy inline asset-slot candidate creation')
  assert.doesNotMatch(generationSkill, /mcp__movscript__domain_create_keyframe_candidate/, 'default generation skill must not grant legacy inline keyframe candidate creation')
  assert.doesNotMatch(generationSkill, /mcp__movscript__domain_select_candidate/, 'default generation skill must not grant legacy inline candidate selection')
  assert.doesNotMatch(generationSkill, /mcp__movscript__domain_update_candidate/, 'default generation skill must not grant legacy inline candidate update')
  assert.doesNotMatch(generationSkill, /mcp__movscript__domain_unlock_candidate/, 'default generation skill must not grant legacy inline candidate unlock')
  assert.match(editingClient, /MEDIA_PIPELINE_RESULT_REGISTER_ENDPOINT = ['"`]\/v1\/media-pipeline\/results\/register['"`]/, 'Editing SDK must expose Media Pipeline result register endpoint')
  assert.match(editingClient, /MEDIA_PIPELINE_RESULT_GET_ENDPOINT = ['"`]\/v1\/media-pipeline\/results\/get['"`]/, 'Editing SDK must expose Media Pipeline result get endpoint')
  assert.match(editingClient, /MEDIA_PIPELINE_RESULT_LIST_ENDPOINT = ['"`]\/v1\/media-pipeline\/results\/list['"`]/, 'Editing SDK must expose Media Pipeline result list endpoint')
  assert.match(editingClient, /MEDIA_PIPELINE_RESULT_WATCH_CREATE_ENDPOINT = ['"`]\/v1\/media-pipeline\/results\/watch\/create['"`]/, 'Editing SDK must expose Media Pipeline result watch create endpoint')
  assert.match(editingClient, /createResultWatch/, 'Editing SDK client must expose result watch create')
  assert.match(editingClient, /cancelResultWatch/, 'Editing SDK client must expose result watch cancel')
  assert.match(mediaPipelineService, /result-registry/, 'Media Pipeline Service must advertise result-registry capability')
  assert.match(mediaPipelineService, /result-watch/, 'Media Pipeline Service must advertise result-watch capability')
  assert.match(mediaPipelineService, /MEDIA_PIPELINE_RESULT_REGISTER_ENDPOINT/, 'Media Pipeline Service must serve result register endpoint')
  assert.match(mediaPipelineService, /MEDIA_PIPELINE_RESULT_GET_ENDPOINT/, 'Media Pipeline Service must serve result get endpoint')
  assert.match(mediaPipelineService, /MEDIA_PIPELINE_RESULT_LIST_ENDPOINT/, 'Media Pipeline Service must serve result list endpoint')
  assert.match(mediaPipelineService, /MEDIA_PIPELINE_RESULT_WATCH_CREATE_ENDPOINT/, 'Media Pipeline Service must serve result watch create endpoint')
  assert.match(mediaPipelineService, /MEDIA_PIPELINE_RESULT_WATCH_CANCEL_ENDPOINT/, 'Media Pipeline Service must serve result watch cancel endpoint')
  assert.match(mediaPipelineResultRegistry, /createFileMediaPipelineResultRegistry/, 'Media Pipeline result registry must have a file-backed implementation')
  assert.match(mediaPipelineResultRegistry, /movscript\.media-pipeline-result-registry\.v1/, 'Media Pipeline result registry file snapshot must be versioned')
  assert.match(mediaPipelineResultRegistry, /MOVSCRIPT_MEDIA_PIPELINE_RESULT_REGISTRY_PATH/, 'Media Pipeline result registry must expose an explicit persistence path override')
  assert.match(mediaPipelineResultWatchRegistry, /createFileMediaPipelineResultWatchRegistry/, 'Media Pipeline result watch registry must have a file-backed implementation')
  assert.match(mediaPipelineResultWatchRegistry, /movscript\.media-pipeline-result-watch-registry\.v1/, 'Media Pipeline result watch snapshots must be versioned')
  assert.match(mediaPipelineResultWatchRegistry, /MOVSCRIPT_MEDIA_PIPELINE_RESULT_WATCH_REGISTRY_PATH/, 'Media Pipeline result watch registry must expose an explicit persistence path override')
  assert.match(mediaPipelineResultWatchRegistry, /external_nle_background_watch/, 'Media Pipeline result watch must register external NLE background watch results')
  assert.match(mediaPipelineService, /createFileMediaPipelineResultRegistry\(\{ env \}\)/, 'Media Pipeline service CLI must use the file-backed result registry')
  assert.match(mediaPipelineService, /createFileMediaPipelineResultWatchRegistry\(\{ env, resultRegistry \}\)/, 'Media Pipeline service CLI must use the file-backed result watch registry')
  assert.match(cliCommands, /editing\.result\.register/, 'shared command manifest must expose editing result register')
  assert.match(cliCommands, /editing\.result\.recover_external_nle/, 'shared command manifest must expose external NLE result recovery')
  assert.match(cliCommands, /editing\.result\.watch_external_nle_create/, 'shared command manifest must expose external NLE background result watch creation')
  assert.match(cliCommands, /editing\.result\.watch_get/, 'shared command manifest must expose result watch get')
  assert.match(cliCommands, /editing\.result\.watch_list/, 'shared command manifest must expose result watch list')
  assert.match(cliCommands, /editing\.result\.watch_cancel/, 'shared command manifest must expose result watch cancel')
  assert.match(cliCommands, /editing\.external_nle\.open/, 'shared command manifest must expose External NLE open')
  assert.match(cliCommands, /editing\.result\.get/, 'shared command manifest must expose editing result get')
  assert.match(cliCommands, /editing\.result\.list/, 'shared command manifest must expose editing result list')
  assert.match(editingDefinitions, /editing_result_register/, 'editing MCP schema must expose result register')
  assert.match(editingDefinitions, /editing_result_recover_external_nle/, 'editing MCP schema must expose external NLE result recovery')
  assert.match(editingDefinitions, /editing_result_watch_external_nle_create/, 'editing MCP schema must expose external NLE background result watch')
  assert.match(editingDefinitions, /name: 'editing_result_watch_external_nle_create'[\s\S]*timeoutMs: \{ type: 'number'/, 'editing background watch schema must expose timeout')
  assert.match(editingDefinitions, /editing_result_watch_cancel/, 'editing MCP schema must expose result watch cancellation')
  assert.match(editingDefinitions, /editing_external_nle_open/, 'editing MCP schema must expose External NLE open')
  assert.match(editingDefinitions, /name: 'editing_external_nle_open'[\s\S]*dryRun: \{ type: 'boolean'/, 'editing External NLE open schema must expose dry-run')
  assert.match(editingDefinitions, /editing_result_get/, 'editing MCP schema must expose result get')
  assert.match(editingDefinitions, /editing_result_list/, 'editing MCP schema must expose result list')
  assert.match(editingActions, /registerResult\(\{ result: mediaPipelineResultInput\(args\) \}\)/, 'editing result register must call Media Pipeline Service client')
  assert.match(editingActions, /detectExternalNleResult/, 'editing result recovery must detect External NLE output artifacts')
  assert.match(editingActions, /editingResultWatchExternalNleCreate/, 'editing actions must expose External NLE background result watch creation')
  assert.match(editingActions, /editingExternalNleOpen/, 'editing actions must expose External NLE open')
  assert.match(editingActions, /externalNleOpenCommand/, 'editing External NLE open must build a platform opener command')
  assert.match(editingActions, /createResultWatch\(\{ watch: externalNleResultWatchInput\(args\) \}\)/, 'editing result watch must call Media Pipeline Service client')
  assert.match(editingActions, /external_nle_result_recovery/, 'editing result recovery must record external NLE provenance source')
  assert.match(editingActions, /resolveArgsWithMediaPipelineResult/, 'editing export gates must resolve resultId/result through Media Pipeline result registry')
  assert.match(editingDefinitions, /name: 'editing_export_save_local'[\s\S]*resultId: \{ type: 'string'/, 'editing save-local schema must accept resultId')
  assert.match(editingDefinitions, /name: 'editing_export_import_resource'[\s\S]*resultId: \{ type: 'string'/, 'editing import-resource schema must accept resultId')
  assert.match(editingDefinitions, /name: 'editing_export_publish_hls'[\s\S]*resultId: \{ type: 'string'/, 'editing publish-hls schema must accept resultId')
  assert.match(editingDefinitions, /name: 'editing_export_create_candidate'[\s\S]*resultId: \{ type: 'string'/, 'editing create-candidate schema must accept resultId')
  assert.match(artifactActions, /resolveArtifactArgsWithMediaPipelineResult/, 'system artifact gates must resolve resultId/result through Media Pipeline result registry')
  assert.match(artifactDefinitions, /name: 'system_artifact_upload_export'[\s\S]*resultId: \{ type: 'string'/, 'system artifact upload-export schema must accept resultId')
  assert.match(artifactDefinitions, /name: 'system_artifact_upload_hls_stream'[\s\S]*resultId: \{ type: 'string'/, 'system artifact upload-hls-stream schema must accept resultId')
  assert.match(systemCli, /\.option\('--media-pipeline-service-url <url>'/, 'system CLI must expose explicit Media Pipeline Service URL')
  assert.match(systemCli, /\.option\('--result-id <id>'/, 'system CLI must expose result id')
  assert.match(read('apps/cli/src/commands/runtime.ts'), /runtime_gateway_configure/, 'runtime CLI must route gateway configure through shared command runner')
  assert.match(read('apps/cli/src/commands/runtime.ts'), /\.option\('--gateway-base-url <url>'/, 'runtime CLI must expose gateway base URL configuration')
  assert.match(cliCommands, /appendPathArg\(argv, args, \['result_id', 'resultId'\], '--result-id'\)/, 'system debug argv must include result-id')
  assert.match(editingCli, /\.option\('--media-pipeline-service-url <url>'/, 'editing CLI must expose explicit Media Pipeline Service URL')
  assert.match(editingCli, /\.option\('--result-id <id>'/, 'editing CLI must expose result id')
  assert.match(editingCli, /\.option\('--watch-id <id>'/, 'editing CLI must expose result watch id')
  assert.match(editingCli, /\.option\('--output-directory <dir>'/, 'editing CLI must expose output directory scanning')
  assert.match(editingCli, /\.option\('--wait-for-ms <ms>'/, 'editing CLI must expose watch-once timeout')
  assert.match(editingCli, /\.option\('--timeout-ms <ms>'/, 'editing CLI must expose background watch timeout')
  assert.match(editingCli, /\.option\('--poll-interval-ms <ms>'/, 'editing CLI must expose watch-once poll interval')
  assert.match(editingCli, /\.option\('--exchange-project-path <path>'/, 'editing CLI must expose exchange project provenance')
  assert.match(editingCli, /\.option\('--app-name <name>'/, 'editing CLI must expose local app name for External NLE open')
  assert.match(editingCli, /\.option\('--dry-run'/, 'editing CLI must expose External NLE open dry-run')
  assert.match(cliCommands, /appendPathArg\(argv, args, \['outputDirectory', 'output_directory', 'watchDirectory', 'watch_directory', 'exportDirectory', 'export_directory'\], '--output-directory'\)/, 'editing debug argv must include output directory')
  assert.match(cliCommands, /appendPathArg\(argv, args, \['waitForMs', 'wait_for_ms'\], '--wait-for-ms'\)/, 'editing debug argv must include watch-once timeout')
  assert.match(cliCommands, /appendPathArg\(argv, args, \['watchId', 'watch_id'\], '--watch-id'\)/, 'editing debug argv must include watch id')
  assert.match(cliCommands, /appendPathArg\(argv, args, \['timeoutMs', 'timeout_ms'\], '--timeout-ms'\)/, 'editing debug argv must include background watch timeout')
  assert.match(cliCommands, /appendPathArg\(argv, args, \['appName', 'app_name', 'application', 'applicationName', 'application_name'\], '--app-name'\)/, 'editing debug argv must include External NLE app name')
  assert.match(cliCommands, /args\.dryRun === true \|\| args\.dry_run === true/, 'editing debug argv must include External NLE dry-run')
  assert.match(editingCli, /\.option\('--provenance <json>'/, 'editing CLI must expose result provenance for external backend recovery')
  assert.match(cliCommands, /appendJSONArg\(argv, args, \['provenance'\], '--provenance'\)/, 'editing debug argv must include result provenance')
})

test('MovScript plugin skills explain production contract, systems, blockers, review, and output', () => {
  const skillRoot = resolve(root, 'apps/plugin/skills')
  const skillNames = readdirSync(skillRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  assert.deepEqual(skillNames, [
    'admin',
    'domain',
    'editing',
    'generation',
    'planning',
    'production-editing',
    'project',
    'remotion',
    'review',
    'runtime',
    'system-edit',
    'workspace',
  ])

  for (const skillName of skillNames) {
    const source = read(`apps/plugin/skills/${skillName}/SKILL.md`)
    assert.match(source, /## Production Contract/, `${skillName} must have a production contract section`)
    for (const required of [
      'Production step:',
      'Systems/config:',
      'Blockers:',
      'Human review:',
      'Output:',
    ]) {
      assert.match(source, new RegExp(required.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')), `${skillName} production contract must include ${required}`)
    }
    assert.match(source, /runtime|daemon|Project Service|Data Service|Editing Service|Media Pipeline|Admin Service/i, `${skillName} must name the relevant system/runtime dependency`)
  }
})

test('MovScript creative skills describe MCP host only as a thin adapter', () => {
  for (const skillName of ['domain', 'generation', 'planning', 'review', 'editing', 'project', 'workspace', 'production-editing', 'remotion', 'system-edit']) {
    const source = read(`apps/plugin/skills/${skillName}/SKILL.md`)
    assert.doesNotMatch(source, /MCP host may run/i, `${skillName} must not describe MCP host as a runtime mode`)
    assert.doesNotMatch(source, /MCP host must be running/i, `${skillName} must not make MCP host the business prerequisite`)
    assert.doesNotMatch(source, /MCP host .*Project Service|MCP host .*Data Service|MCP host .*Editing Service|MCP host .*Media Pipeline/i, `${skillName} must not imply MCP host owns business services`)
  }

  const domain = read('apps/plugin/skills/domain/SKILL.md')
  const generation = read('apps/plugin/skills/generation/SKILL.md')
  assert.match(domain, /thin adapter over the daemon MCP endpoint or a cloud\/external runtime gateway/)
  assert.match(generation, /daemon MCP endpoint or a cloud\/external runtime gateway/)
})

test('Desktop package staging uses pnpm 10 injected deploy without legacy mode', () => {
  const releaseWorkflow = read('scripts/release/release-workflow.mjs')

  assert.match(
    releaseWorkflow,
    /spawn\(pnpm, \[\s*'--config\.inject-workspace-packages=true',\s*'--filter',\s*'@movscript\/desktop',\s*'deploy',\s*'--prod',\s*stageDir\s*\]/,
  )
  assert.doesNotMatch(releaseWorkflow, /'deploy',\s*'--legacy'/)
})

test('Local macOS DMG packaged app smoke is opt-in', () => {
  const localDmgPackage = read('scripts/release/package-macos-local-dmg.mjs')

  assert.match(localDmgPackage, /const smokeRequested = args\.includes\('--smoke'\) \|\| env\.MOVSCRIPT_PACKAGE_MAC_DMG_SMOKE\?\.trim\(\) === '1'/)
  assert.match(localDmgPackage, /const runSmoke = smokeRequested && !args\.includes\('--skip-smoke'\)/)
  assert.match(localDmgPackage, /Smoke test skipped by default; pass --smoke or set MOVSCRIPT_PACKAGE_MAC_DMG_SMOKE=1 to run it/)
  assert.doesNotMatch(localDmgPackage, /if \(!skipSmoke\)/)
})
